LEGACY_BROWSER_SCENARIO_COUNT = 40


def _scenario(key, prompt, expected_category, expected_sources, expected_terms, forbidden_terms):
    return {
        "key": key,
        "prompt": prompt,
        "expected_category": expected_category,
        "expected_sources": expected_sources,
        "expected_terms": expected_terms,
        "forbidden_terms": forbidden_terms,
    }


NEW_AGENT_BUILDER_SCENARIOS = [
    _scenario(
        "browser_competitor_site_to_telegram",
        "Каждое утро открывай сайт конкурента, проверяй изменения в акциях и присылай короткий отчёт в Telegram владельцу.",
        "custom",
        ["browser_use", "competitor_websites", "telegram"],
        ["изменения", "сайт", "telegram"],
        ["где искать клиентов"],
    ),
    _scenario(
        "browser_competitor_menu_prices",
        "Раз в день открывай сайты конкурентов, сравнивай меню и цены с нашими услугами и присылай отличия в Telegram.",
        "custom",
        ["browser_use", "competitor_websites", "services", "telegram"],
        ["меню", "цен", "telegram"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "browser_landing_changes_to_whatsapp",
        "Мониторь лендинг конкурента, находи новые блоки и отправляй черновик уведомления ответственному в WhatsApp.",
        "custom",
        ["browser_use", "competitor_websites", "whatsapp"],
        ["изменения", "сайт"],
        ["prospectingleads", "финансы localos"],
    ),
    _scenario(
        "browser_promo_page_digest",
        "Открывай страницу акций конкурента каждую пятницу, собирай новые офферы и готовь дайджест для руководителя.",
        "custom",
        ["browser_use", "competitor_websites"],
        ["изменения", "сайт"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "browser_product_stock_watch",
        "Проверяй сайт конкурента с товарами, находи новые позиции и исчезнувшие товары, присылай список менеджеру.",
        "custom",
        ["browser_use", "competitor_websites"],
        ["изменения", "сайт"],
        ["prospectingleads", "отзывы"],
    ),
    _scenario(
        "sheets_new_orders_to_telegram",
        "Каждый час бери новые строки из Google Sheets с заказами и отправляй краткий статус в Telegram.",
        "custom",
        ["google_sheets", "telegram"],
        ["google sheets", "telegram"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "sheets_event_signups_to_telegram",
        "Раз в день проверяй Google-таблицу регистраций на мероприятия и присылай список новых заявок в Telegram.",
        "custom",
        ["google_sheets", "telegram"],
        ["таблиц", "telegram"],
        ["prospectingleads", "финансы localos"],
    ),
    _scenario(
        "telegram_messages_to_sheets",
        "Когда клиент пишет в Telegram-бот, сохраняй имя, username и текст сообщения в Google Sheets после подтверждения.",
        "custom",
        ["telegram", "google_sheets"],
        ["telegram", "google sheets"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "telegram_support_to_sheets",
        "Новые сообщения из Telegram складывай в Google Sheets: дата, username, текст сообщения, статус обработки.",
        "custom",
        ["telegram", "google_sheets"],
        ["telegram", "google sheets"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "sheets_expenses_to_finance",
        "Каждый вечер читай Google Sheets с расходами, нормализуй категории и готовь добавление в финансы LocalOS после approval.",
        "custom",
        ["google_sheets", "localos_finance"],
        ["расход", "категор"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "whatsapp_questions_to_faq",
        "Каждую неделю собирай вопросы клиентов из WhatsApp, группируй их и предлагай новые пункты FAQ.",
        "custom",
        ["customer_questions"],
        ["пункты faq"],
        ["prospectingleads", "финансы"],
    ),
    _scenario(
        "telegram_whatsapp_questions_digest",
        "Собирай вопросы клиентов из Telegram и WhatsApp, группируй по темам и предлагай ответы для базы знаний.",
        "custom",
        ["telegram", "whatsapp", "customer_questions"],
        ["вопросов клиентов", "базы знаний"],
        ["prospectingleads", "подозрительных расходов"],
    ),
    _scenario(
        "reviews_negative_to_telegram",
        "Если появляется новый негативный отзыв, подготовь ответ и пришли отзыв с черновиком в Telegram без публикации.",
        "custom",
        ["external_reviews", "business_profile", "telegram"],
        ["черновик ответа"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "reviews_network_weekly_report",
        "Раз в неделю сравни отзывы по точкам сети, найди филиалы с падением рейтинга и отправь короткий отчёт.",
        "reviews",
        ["external_reviews", "locations"],
        ["филиалам", "рейтинг"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "reviews_positive_content",
        "Бери новые положительные отзывы и предлагай 3 идеи публикаций для карточек на картах.",
        "custom",
        ["external_reviews", "services"],
        ["3 идеи", "положительных отзывов"],
        ["prospectingleads", "проверка услуг"],
    ),
    _scenario(
        "services_empty_descriptions",
        "Раз в неделю проверяй услуги: пустые описания, слабые названия, отсутствующие цены и дубли.",
        "services",
        ["services"],
        ["Проверка услуг"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "services_seasonal_update",
        "Раз в месяц проверяй сезонные услуги, что пора добавить, скрыть или обновить в карточках и прайсе.",
        "services",
        ["services", "seasonality", "business_cards", "price_list"],
        ["сезонных услуг", "добавить, скрыть или обновить"],
        ["prospectingleads", "готовый результат по задаче"],
    ),
    _scenario(
        "bookings_tomorrow_no_prepay",
        "Каждое утро проверяй записи на завтра, находи клиентов без предоплаты и готовь напоминание администратору.",
        "communications",
        ["appointments"],
        ["Черновики сообщений"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "bookings_cancellation_risk",
        "Каждое утро находи записи клиентов, которые часто отменяют визиты, и готовь список для администратора.",
        "communications",
        ["appointments"],
        ["риском отмены", "администратор"],
        ["prospectingleads", "статусы реакции"],
    ),
    _scenario(
        "clients_reactivation_90_days",
        "Каждый понедельник находи клиентов, которые не записывались больше 90 дней, и готовь мягкое сообщение для возврата.",
        "communications",
        ["appointments"],
        ["клиентов"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "finance_unpaid_invoices",
        "Каждый день проверяй неоплаченные счета, находи просрочку больше 5 дней и присылай владельцу список в Telegram.",
        "custom",
        ["localos_finance", "telegram"],
        ["просроченных", "счет"],
        ["prospectingleads", "формат поста"],
    ),
    _scenario(
        "finance_revenue_anomaly_telegram",
        "Каждое утро сравнивай вчерашнюю выручку с обычным уровнем и присылай резкие отклонения в Telegram.",
        "custom",
        ["localos_finance", "revenue", "telegram"],
        ["отклонений выручки", "обычный уровень"],
        ["prospectingleads", "подозрительных расходов"],
    ),
    _scenario(
        "finance_large_expenses_review",
        "Проверяй новые расходы LocalOS, выделяй крупные траты и проси владельца подтвердить категорию.",
        "custom",
        ["localos_finance"],
        ["подозрительных расходов", "категор"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "inventory_low_supplies",
        "Каждый вечер проверяй остатки расходников и товаров, находи позиции ниже минимума и готовь список закупки.",
        "custom",
        ["inventory", "products", "supplies"],
        ["список для закупки", "сколько заказать"],
        ["prospectingleads", "финансы localos"],
    ),
    _scenario(
        "staff_schedule_conflicts",
        "Раз в неделю проверяй расписание смен, находи пересечения, пустые окна и перегрузки по сотрудникам.",
        "custom",
        ["staff_schedule", "team"],
        ["расписании смен", "перегруз"],
        ["prospectingleads", "готовый результат по задаче"],
    ),
    _scenario(
        "tasks_overdue_digest",
        "Каждое утро находи просроченные задачи сотрудников и присылай владельцу список: задача, ответственный, срок.",
        "custom",
        ["localos_tasks", "team"],
        ["просроченных задач", "ответственный"],
        ["prospectingleads", "финансы localos"],
    ),
    _scenario(
        "admin_response_lag",
        "Каждый день проверяй клиентские чаты и находи диалоги, где администратор долго не ответил.",
        "custom",
        ["customer_chats", "team"],
        ["администратор", "долго не ответил"],
        ["prospectingleads", "готовый результат по задаче"],
    ),
    _scenario(
        "faq_from_chats",
        "Раз в неделю бери повторяющиеся вопросы из клиентских переписок и предлагай новые пункты FAQ.",
        "custom",
        ["customer_chats", "customer_questions", "business_cards"],
        ["пункты faq", "клиентских переписок"],
        ["prospectingleads", "telegram"],
    ),
    _scenario(
        "photo_quality_locations",
        "Раз в неделю проверяй фотографии в карточках филиалов, находи устаревшие, тёмные или нерелевантные фото.",
        "custom",
        ["business_cards", "photos", "locations"],
        ["фото", "замен"],
        ["prospectingleads", "подозрительных расходов"],
    ),
    _scenario(
        "map_questions_answers",
        "Каждый день проверяй новые вопросы пользователей в Яндекс/Google-карточках и готовь ответы для подтверждения.",
        "custom",
        ["business_cards", "map_questions"],
        ["ответов на вопросы", "яндекс/google-карточках"],
        ["prospectingleads", "черновики ответов и причины ручной проверки"],
    ),
    _scenario(
        "location_description_quality",
        "Проверяй описания всех филиалов, находи устаревшую информацию, одинаковые тексты и слабые формулировки.",
        "custom",
        ["locations", "business_cards", "location_descriptions"],
        ["описаниях филиалов", "слабые формулировки"],
        ["prospectingleads", "какой результат"],
    ),
    _scenario(
        "new_employee_profile",
        "Когда добавляется новый сотрудник, проверяй фото, описание, услуги, график и привязку к филиалу.",
        "custom",
        ["team", "staff_profiles", "services", "schedule", "locations"],
        ["нового сотрудника", "график"],
        ["prospectingleads", "проблемных фото"],
    ),
    _scenario(
        "holiday_readiness_checklist",
        "За две недели до праздников проверяй карточки, услуги, посты и расписание, готовь чеклист подготовки.",
        "custom",
        ["business_cards", "services", "posts", "schedule"],
        ["чеклист подготовки", "праздникам"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "manager_friday_report",
        "Каждую пятницу собирай отчёт по филиалам: отзывы, записи, выручка, расходы, проблемы и рекомендации.",
        "custom",
        ["external_reviews", "appointments", "localos_finance", "locations"],
        ["отчёт по филиалам", "рекомендации"],
        ["prospectingleads", "проверка услуг"],
    ),
    _scenario(
        "problem_digest_telegram",
        "Каждое утро собирай дайджест: негативные отзывы, отменённые записи, просроченные задачи и необычные расходы. Присылай в Telegram.",
        "custom",
        ["localos_digest", "telegram"],
        ["ежедневный дайджест", "проблем"],
        ["prospectingleads", "формат поста"],
    ),
    _scenario(
        "partner_replies_classify",
        "Каждый день проверяй ответы потенциальных партнёров, классифицируй интересно / отказ / нужен ручной ответ.",
        "partnerships",
        ["prospectingleads", "outreach_drafts"],
        ["ответов партнёров", "следующий шаг"],
        ["google", "таблиц", "агент отзывов"],
    ),
    _scenario(
        "partner_shortlist_email",
        "Найди потенциальных партнёров в городе, собери shortlist, подготовь первое письмо и жди подтверждения.",
        "partnerships",
        ["prospectingleads", "services"],
        ["Shortlist", "черновики"],
        ["где искать клиентов", "какие лиды"],
    ),
    _scenario(
        "email_partner_proposal",
        "Подготовь письмо партнёру на основе профиля бизнеса и заметок, но не отправляй без проверки.",
        "partnerships",
        ["prospectingleads", "services", "business_profile"],
        ["черновики сообщений"],
        ["где искать клиентов"],
    ),
    _scenario(
        "document_contract_risks",
        "Разбери загруженный договор, найди сроки, суммы, риски и вопросы для юриста.",
        "documents",
        ["uploaded_documents"],
        ["summary", "risks"],
        ["prospectingleads", "telegram"],
    ),
    _scenario(
        "document_invoice_fields",
        "Извлеки из загруженных PDF-счетов номер, сумму, дату, контрагента и строки с отсутствующими полями.",
        "documents",
        ["uploaded_documents"],
        ["facts", "fields"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "uploaded_table_duplicates",
        "Проверь загруженную CSV таблицу клиентов, найди дубли, пустые телефоны и строки без источника.",
        "tables",
        ["uploaded_tables"],
        ["пустые поля", "дубликаты"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "uploaded_table_status_errors",
        "Проверь XLSX таблицу заказов, найди строки без статуса, суммы или ответственного.",
        "tables",
        ["uploaded_tables"],
        ["пустые поля", "статусы"],
        ["prospectingleads", "telegram"],
    ),
    _scenario(
        "no_discount_promo_ideas",
        "Раз в неделю предлагай 3 идеи продвижения без скидок на основе сезонности, услуг и отзывов.",
        "custom",
        ["services", "external_reviews", "seasonality"],
        ["без скидок", "3 идеи"],
        ["prospectingleads", "проверка услуг"],
    ),
    _scenario(
        "repeated_complaints_service_change",
        "Если в отзывах и сообщениях повторяется одна проблема, собери примеры и предложи, что изменить в сервисе.",
        "custom",
        ["external_reviews", "customer_messages", "services"],
        ["повторяющиеся жалобы", "изменить в сервисе"],
        ["prospectingleads", "черновики ответов"],
    ),
    _scenario(
        "content_plan_from_services",
        "Раз в неделю готовь 3 темы постов для карточек на картах на основе услуг, сезона и отзывов.",
        "custom",
        ["services", "external_reviews", "business_profile"],
        ["3 темы", "карточек на картах"],
        ["prospectingleads", "какие лиды"],
    ),
    _scenario(
        "telegram_content_reactions",
        "После публикации поста в Telegram проверяй реакции и комментарии через API и предлагай, что изменить в контент-плане.",
        "custom",
        ["telegram", "business_profile", "services", "external_reviews"],
        ["контент-план", "реакц"],
        ["prospectingleads", "финансы"],
    ),
    _scenario(
        "map_activity_calendar",
        "Каждый понедельник проверяй новости в карточках на картах и предлагай календарь публикаций на неделю.",
        "custom",
        ["services", "external_reviews", "business_profile"],
        ["3 темы", "карточек на картах"],
        ["prospectingleads", "подозрительных расходов"],
    ),
    _scenario(
        "booking_package_upsell",
        "Перед визитом клиента проверяй услугу и историю записей, предлагай администратору пакет или допродажу.",
        "communications",
        ["appointments"],
        ["Черновики сообщений"],
        ["prospectingleads", "где искать клиентов"],
    ),
    _scenario(
        "client_missing_contacts",
        "Раз в неделю находи клиентов без телефона, email или источника прихода и готовь список для менеджера.",
        "custom",
        ["clients"],
        ["пустыми полями", "телефон"],
        ["prospectingleads", "google"],
    ),
    _scenario(
        "openclaw_browser_then_telegram_owner",
        "Через browser use открой сайт конкурента, проверь изменения цен и подготовь сообщение владельцу в Telegram.",
        "custom",
        ["browser_use", "competitor_websites", "services", "telegram"],
        ["изменения", "сайт", "telegram"],
        ["prospectingleads", "где искать клиентов"],
    ),
]


MIXED_AGENT_BUILDER_COMBINATIONS = [
    ("browser_to_telegram", ["browser_competitor_site_to_telegram", "openclaw_browser_then_telegram_owner"]),
    ("browser_to_whatsapp", ["browser_landing_changes_to_whatsapp"]),
    ("sheets_to_telegram", ["sheets_new_orders_to_telegram", "sheets_event_signups_to_telegram"]),
    ("telegram_to_sheets", ["telegram_messages_to_sheets", "telegram_support_to_sheets"]),
    ("reviews_to_telegram", ["reviews_negative_to_telegram", "reviews_network_weekly_report"]),
    ("finance_to_telegram", ["finance_unpaid_invoices", "finance_revenue_anomaly_telegram"]),
    ("whatsapp_and_telegram_questions", ["whatsapp_questions_to_faq", "telegram_whatsapp_questions_digest"]),
    ("maps_and_content", ["content_plan_from_services", "map_activity_calendar", "telegram_content_reactions"]),
    ("operations_and_staff", ["inventory_low_supplies", "staff_schedule_conflicts", "tasks_overdue_digest"]),
    ("documents_and_tables", ["document_contract_risks", "uploaded_table_duplicates"]),
]
