import type { Language } from '@/i18n/LanguageContext.logic';
import type { ManagedCardGrowthCopy, ManagedCardGrowthActionCode, ManagedCardGrowthActionCopy } from './managedCardGrowthCopy';
import { managedCardGrowthCopyEuropean } from './managedCardGrowthCopyEuropean';

type ActionLabels = Record<ManagedCardGrowthActionCode, [string, string, string]>;

export function actionMessages(
  locale: string,
  labels: ActionLabels,
  outcomes: Record<string, string>,
  refreshOutcome: string,
  addOutcome: string,
  medianLabel: string,
): Record<ManagedCardGrowthActionCode, ManagedCardGrowthActionCopy> {
  const item = (code: ManagedCardGrowthActionCode): ManagedCardGrowthActionCopy => ({
    title: (provider) => labels[code][0].replace('{provider}', provider),
    reason: (_provider, { benchmarkMedian }) => labels[code][1] + (
      typeof benchmarkMedian === 'number' && Number.isFinite(benchmarkMedian)
        ? ` ${medianLabel}: ${new Intl.NumberFormat(locale).format(benchmarkMedian)}.` : ''
    ),
    cta: labels[code][2],
    outcome: (goal) => code === 'add_provider' ? addOutcome
      : code === 'refresh' || code === 'restore' ? refreshOutcome
        : Object.prototype.hasOwnProperty.call(outcomes, goal) ? outcomes[goal] : refreshOutcome,
  });
  return {
    refresh: item('refresh'), restore: item('restore'), add_provider: item('add_provider'),
    blocked: item('blocked'), access: item('access'), verified: item('verified'),
    duplicate: item('duplicate'), category: item('category'), contacts: item('contacts'),
    schedule: item('schedule'), action_path: item('action_path'), services: item('services'),
    prices: item('prices'), reviews: item('reviews'), review_responses: item('review_responses'),
    photos: item('photos'), publications: item('publications'),
  };
}

const el: ManagedCardGrowthCopy = {
  eyebrow: 'Διαχείριση καταχώρισης', title: 'Στόχος και κατάσταση καταχωρίσεων',
  description: 'Το LocalOS ελέγχει πρώτα την πρόσβαση και την ορθότητα της καταχώρισης, έπειτα την επικοινωνία, την προσφορά, την εμπιστοσύνη, τις φωτογραφίες και τους επίκαιρους λόγους επίσκεψης.',
  goal: 'Στόχος', chooseGoal: 'Επιλέξτε στόχο', saving: 'Αποθήκευση…', confirmGoal: 'Επιβεβαίωση στόχου',
  goalConfirmed: 'Ο στόχος επιβεβαιώθηκε. Το επόμενο βήμα επιλέγεται βάσει αυτού.',
  networkGoal: 'Επιβεβαιώστε τον στόχο ξεχωριστά για κάθε σημείο του δικτύου.', saveError: 'Δεν ήταν δυνατή η αποθήκευση του στόχου',
  waitingUntil: (date) => `Αναμονή δεδομένων έως ${date}`,
  waitingDescription: 'Η αλλαγή έχει ήδη γίνει. Στην ημερομηνία ελέγχου θα συγκρίνουμε τις ενέργειες στην καταχώριση με τις αρχικές 28 ημέρες.',
  baseline: 'Περίοδος αναφοράς: 28 ημέρες', views: 'Προβολές', clicks: 'Κλικ', actions: 'Ενέργειες',
  baselineDisclaimer: 'Οι προβολές και τα κλικ δεν είναι επιβεβαιωμένοι πελάτες ή πωλήσεις.',
  resultDisclaimer: 'Οι ενέργειες στις πλατφόρμες δεν είναι επιβεβαιωμένοι πελάτες, παραγγελίες ή πωλήσεις.', result: 'Αποτέλεσμα ελέγχου',
  critical: 'Υπάρχει κρίσιμο εμπόδιο', noCritical: 'Δεν εντοπίστηκαν κρίσιμα εμπόδια', needsAttention: 'Χρειάζεται προσοχή',
  snapshot: (date) => `Στιγμιότυπο: ${date}`, sourceObserved: 'Λήφθηκαν δεδομένα', sourceBlocked: 'Η πηγή δεν είναι διαθέσιμη', sourceUnknown: 'Χρειάζεται νέο στιγμιότυπο',
  benchmark: (count, days) => `Σύγκριση: ${new Intl.NumberFormat('el-GR').format(count)} παρόμοιες επιχειρήσεις, δεδομένα έως ${new Intl.NumberFormat('el-GR').format(days)} ημερών.`,
  smallSample: ' Το δείγμα είναι μικρότερο από το ελάχιστο των 10 επιχειρήσεων.', median: 'διάμεσος', upperQuartile: 'άνω τεταρτημόριο',
  benchmarkDisclaimer: 'Η σύγκριση είναι σημείο αναφοράς, όχι απόδειξη της αιτίας ενός αποτελέσματος.',
  noProviders: 'Δεν έχει προστεθεί πλατφόρμα. Συνδέστε πρώτα Google, Яндекс ή 2ГИС και λάβετε νέο στιγμιότυπο.',
  noCardState: 'Δεν έχει ληφθεί ακόμη η κατάσταση των καταχωρίσεων.', nextSteps: 'Επόμενα βήματα',
  nextStepsDescription: 'Θα γίνουν προτεραιότητα μετά την ολοκλήρωση του τρέχοντος βήματος και τον έλεγχο των δεδομένων.',
  policyVersion: 'Έκδοση κανόνων', policyUnknown: 'δεν έχει οριστεί', openEvidence: 'Άνοιγμα τεκμηρίων ελέγχου', dateUnknown: 'μη διαθέσιμη ημερομηνία',
  actionHeading: 'Κύρια ενέργεια', actionDescription: 'Ολοκληρώστε πρώτα αυτό το βήμα. Μετά το LocalOS θα περιμένει την ημερομηνία ελέγχου και θα συγκρίνει το αποτέλεσμα.',
  expectedOutcome: 'Αναμενόμενο αποτέλεσμα', continue: 'Συνέχεια', auditState: 'Κατάσταση ανά πλατφόρμα',
  auditDescription: 'Κάθε συμπέρασμα συνδέεται με πηγή και ημερομηνία στιγμιότυπου. Τα άγνωστα δεδομένα δεν θεωρούνται απόντα.',
  source: 'Πηγή', snapshotMissing: 'δεν έχει ληφθεί', safeFallback: 'Ανοίξτε την καταχώριση για να ελέγξετε το επόμενο βήμα.',
  goals: { inquiries: 'Περισσότερα αιτήματα', bookings: 'Περισσότερες κρατήσεις', orders: 'Περισσότερες παραγγελίες', directions: 'Περισσότερα αιτήματα διαδρομής', website_visits: 'Περισσότερες επισκέψεις στον ιστότοπο' },
  gates: { 0: 'Διαθέσιμα δεδομένα', 1: 'Σωστή καταχώριση', 2: 'Δυνατότητα επικοινωνίας', 3: 'Σαφής προσφορά', 4: 'Υπάρχει εμπιστοσύνη', 5: 'Υπάρχουν τεκμήρια', 6: 'Υπάρχει λόγος επιστροφής' },
  facts: { access: 'Πρόσβαση', verified: 'Επαλήθευση', duplicate: 'Διπλότυπα', category: 'Κατηγορία', contacts: 'Στοιχεία επικοινωνίας', schedule: 'Ωράριο', action_path: 'Κράτηση ή παραγγελία', services: 'Υπηρεσίες', prices: 'Τιμές', reviews: 'Κριτικές', review_responses: 'Απαντήσεις σε κριτικές', photos: 'Φωτογραφίες', publications: 'Δημοσιεύσεις' },
  states: { observed: 'Ελέγχθηκε', missing: 'Χρειάζεται συμπλήρωση', unknown: 'Δεν υπάρχουν δεδομένα', not_applicable: 'Δεν εφαρμόζεται', blocked: 'Μη διαθέσιμη πηγή' },
  evidence: {
    connected: 'Η καταχώριση συνδέθηκε', link_missing: 'Δεν έχει προστεθεί σύνδεσμος πλατφόρμας', no_duplicates: 'Δεν εντοπίστηκαν διπλότυπα',
    duplicate_unverified: 'Η πλατφόρμα δεν παρείχε αξιόπιστη ένδειξη διπλότυπου',
    internal_contacts: 'Τα εσωτερικά στοιχεία επικοινωνίας δεν αποδεικνύουν ότι δημοσιεύτηκαν στην πλατφόρμα',
    internal_schedule: 'Το εσωτερικό ωράριο δεν αποδεικνύει ότι ενημερώθηκε στην πλατφόρμα',
    internal_services: 'Οι εσωτερικές υπηρεσίες δεν αποδεικνύουν δημοσίευσή τους στην πλατφόρμα',
    internal_prices: 'Υπάρχουν εσωτερικές τιμές, αλλά χρειάζεται έλεγχος της πλατφόρμας',
    no_organic_news: 'Το 2GIS δεν διαθέτει οργανικό κανάλι ειδήσεων',
    conversion_content: 'Οι δημοσιεύσεις αξιολογούνται ως περιεχόμενο μετατροπής, όχι ως υποχρεωτικός παράγοντας κατάταξης',
    source_error: 'Η τελευταία ενημέρωση της πλατφόρμας απέτυχε',
  },
  decisions: {
    insufficient_data: 'Δεν υπάρχουν αρκετά συγκρίσιμα δεδομένα πλατφορμών για συμπέρασμα.',
    continue: 'Οι επιβεβαιωμένες ενέργειες στις καταχωρίσεις αυξήθηκαν σε σχέση με την περίοδο αναφοράς.',
    adjust: 'Στον πρώτο έλεγχο δεν υπάρχει ακόμη αύξηση ενεργειών· θα ελέγξουμε την επόμενη περίοδο.',
    replace: 'Δεν καταγράφηκε αύξηση ενεργειών στην περίοδο ελέγχου· χρειάζεται διαφορετική υπόθεση.',
  },
  actionMessages: actionMessages('el-GR', {
    refresh: ['Ενημερώστε τα δεδομένα στο {provider}', 'Χρειάζεται νέο στιγμιότυπο της καταχώρισης για να επιλεγεί η πρώτη διόρθωση.', 'Ενημέρωση δεδομένων'],
    restore: ['Αποκαταστήστε την ενημέρωση στο {provider}', 'Η τελευταία ενημέρωση απέτυχε.', 'Έλεγχος σύνδεσης'],
    add_provider: ['Προσθέστε πλατφόρμα για έλεγχο', 'Το LocalOS δεν γνωρίζει ακόμη ποιες καταχωρίσεις ανήκουν σε αυτό το σημείο. Προσθέστε Google, Яндекс ή 2ГИС για το πρώτο στιγμιότυπο.', 'Προσθήκη πλατφόρμας'],
    blocked: ['Αποκαταστήστε την ενημέρωση στο {provider}', 'Η πλατφόρμα προσωρινά δεν παρέχει αξιόπιστα δεδομένα. Αποκαταστήστε πρώτα την πηγή.', 'Έλεγχος σύνδεσης'],
    access: ['Συνδέστε την καταχώριση στο {provider}', 'Χωρίς σύνδεση το LocalOS δεν μπορεί να ελέγξει την καταχώριση και να παρακολουθήσει το αποτέλεσμα.', 'Προσθήκη πλατφόρμας'],
    verified: ['Ελέγξτε τη διαχείριση της καταχώρισης στο {provider}', 'Η πλατφόρμα δεν επιβεβαιώνει ότι η επιχείρηση διαχειρίζεται την καταχώριση.', 'Άνοιγμα καταχώρισης'],
    duplicate: ['Ελέγξτε για διπλότυπα στο {provider}', 'Ένα διπλότυπο μπορεί να διασπά τις κριτικές και να μπερδεύει τους πελάτες.', 'Έλεγχος καταχώρισης'],
    category: ['Διευκρινίστε την κύρια κατηγορία στο {provider}', 'Η κατηγορία πρέπει να περιγράφει με ακρίβεια την κύρια δραστηριότητα αυτού του σημείου.', 'Έλεγχος κατηγορίας'],
    contacts: ['Συμπληρώστε τα στοιχεία επικοινωνίας στο {provider}', 'Ο πελάτης πρέπει να καταλαβαίνει αμέσως πώς να επικοινωνήσει με αυτό το σημείο.', 'Έλεγχος στοιχείων επικοινωνίας'],
    schedule: ['Διευκρινίστε το ωράριο στο {provider}', 'Το ενημερωμένο ωράριο μειώνει τον κίνδυνο μιας χαμένης επίσκεψης.', 'Έλεγχος ωραρίου'],
    action_path: ['Προσθέστε σαφή τρόπο επικοινωνίας στο {provider}', 'Το τηλέφωνο, ο ιστότοπος ή η κράτηση πρέπει να οδηγούν στο συγκεκριμένο σημείο χωρίς περιττά βήματα.', 'Έλεγχος κράτησης'],
    services: ['Δημοσιεύστε τις κύριες υπηρεσίες στο {provider}', 'Η καταχώριση δεν δείχνει ακόμη με σαφήνεια τι προσφέρει η επιχείρηση.', 'Άνοιγμα υπηρεσιών'],
    prices: ['Προσθέστε τιμές στο {provider}', 'Μια τιμή ή σαφής ένδειξη κόστους βοηθά την απόφαση πριν από την επικοινωνία.', 'Άνοιγμα υπηρεσιών'],
    reviews: ['Ξεκινήστε συστηματική συλλογή κριτικών στο {provider}', 'Η εμπιστοσύνη σε αυτή την καταχώριση τεκμηριώνεται λιγότερο από ό,τι σε παρόμοιες επιχειρήσεις.', 'Άνοιγμα κριτικών'],
    review_responses: ['Απαντήστε στις κριτικές στο {provider}', 'Η καταχώριση έχει αναπάντητες κριτικές.', 'Άνοιγμα κριτικών'],
    photos: ['Προσθέστε χρήσιμες φωτογραφίες στο {provider}', 'Δείξτε είσοδο, χώρο, ομάδα, διαδικασία και αποτέλεσμα για ευκολότερη επιλογή.', 'Άνοιγμα φωτογραφιών'],
    publications: ['Ετοιμάστε επίκαιρη δημοσίευση για το {provider}', 'Η δημοσίευση πρέπει να δίνει συγκεκριμένο λόγο επικοινωνίας τώρα· δεν αντικαθιστά τη συμπλήρωση της καταχώρισης.', 'Άνοιγμα περιεχομένου'],
  }, {
    inquiries: 'Διευκολύνετε την επικοινωνία και ελέγξτε τη μεταβολή των επιβεβαιωμένων ενεργειών στην καταχώριση.',
    bookings: 'Διευκολύνετε την κράτηση και ελέγξτε τη μεταβολή κρατήσεων ή αιτημάτων.',
    orders: 'Διευκολύνετε την παραγγελία και ελέγξτε τη μεταβολή παραγγελιών ή αιτημάτων.',
    directions: 'Κάντε την επίσκεψη πιο κατανοητή και ελέγξτε τη μεταβολή των αιτημάτων διαδρομής.',
    website_visits: 'Κάντε τον σύνδεσμο του ιστοτόπου πιο εμφανή και ελέγξτε τη μεταβολή των κλικ.',
  }, 'Λάβετε αξιόπιστη εικόνα της καταχώρισης και επιλέξτε την πρώτη διόρθωση.', 'Λάβετε νέα δεδομένα καταχώρισης και εντοπίστε την πρώτη διόρθωση.', 'Διάμεσος παρόμοιων καταχωρίσεων'),
};

const th: ManagedCardGrowthCopy = {
  eyebrow: 'การจัดการข้อมูลร้าน', title: 'เป้าหมายและสถานะข้อมูลร้าน',
  description: 'LocalOS ตรวจสอบสิทธิ์เข้าถึงและความถูกต้องของข้อมูลก่อน แล้วจึงตรวจสอบช่องทางติดต่อ ข้อเสนอ ความน่าเชื่อถือ รูปภาพ และเหตุผลที่ควรมาใช้บริการในช่วงนี้',
  goal: 'เป้าหมาย', chooseGoal: 'เลือกเป้าหมาย', saving: 'กำลังบันทึก…', confirmGoal: 'ยืนยันเป้าหมาย',
  goalConfirmed: 'ยืนยันเป้าหมายแล้ว ขั้นตอนถัดไปจะเลือกตามเป้าหมายนี้', networkGoal: 'ยืนยันเป้าหมายแยกสำหรับแต่ละสาขาในเครือข่าย', saveError: 'บันทึกเป้าหมายไม่สำเร็จ',
  waitingUntil: (date) => `รอข้อมูลจนถึง ${date}`,
  waitingDescription: 'แก้ไขแล้ว เมื่อถึงวันตรวจสอบจะเปรียบเทียบการดำเนินการบนข้อมูลร้านกับช่วงอ้างอิง 28 วัน',
  baseline: 'ช่วงอ้างอิง 28 วัน', views: 'การดู', clicks: 'การคลิก', actions: 'การดำเนินการ',
  baselineDisclaimer: 'การดูและการคลิกไม่ใช่ลูกค้าหรือยอดขายที่ยืนยันแล้ว',
  resultDisclaimer: 'การดำเนินการบนแพลตฟอร์มไม่ใช่ลูกค้า คำสั่งซื้อ หรือยอดขายที่ยืนยันแล้ว', result: 'ผลการตรวจสอบ',
  critical: 'มีอุปสรรคสำคัญ', noCritical: 'ไม่พบอุปสรรคสำคัญ', needsAttention: 'ต้องตรวจสอบ',
  snapshot: (date) => `ข้อมูล ณ วันที่: ${date}`, sourceObserved: 'ได้รับข้อมูลแล้ว', sourceBlocked: 'แหล่งข้อมูลไม่พร้อมใช้งาน', sourceUnknown: 'ต้องใช้ข้อมูลชุดใหม่',
  benchmark: (count, days) => `ข้อมูลอ้างอิง: ธุรกิจที่เทียบเคียงได้ ${new Intl.NumberFormat('th-TH').format(count)} แห่ง ข้อมูลย้อนหลังไม่เกิน ${new Intl.NumberFormat('th-TH').format(days)} วัน`,
  smallSample: ' กลุ่มตัวอย่างน้อยกว่าขั้นต่ำ 10 ธุรกิจ', median: 'มัธยฐาน', upperQuartile: 'ควอไทล์บน',
  benchmarkDisclaimer: 'การเปรียบเทียบเป็นข้อมูลอ้างอิง ไม่ใช่หลักฐานยืนยันสาเหตุของผลลัพธ์',
  noProviders: 'ยังไม่ได้เพิ่มแพลตฟอร์ม เชื่อมต่อ Google, Яндекс หรือ 2ГИС ก่อน แล้วรับข้อมูลชุดใหม่',
  noCardState: 'ยังไม่ได้รับสถานะข้อมูลร้าน', nextSteps: 'ขั้นตอนถัดไป',
  nextStepsDescription: 'ขั้นตอนเหล่านี้จะเป็นงานหลักหลังจากทำขั้นตอนปัจจุบันเสร็จและตรวจสอบข้อมูลแล้ว',
  policyVersion: 'เวอร์ชันกฎ', policyUnknown: 'ยังไม่ระบุ', openEvidence: 'เปิดหลักฐานการตรวจสอบ', dateUnknown: 'ไม่มีข้อมูลวันที่',
  actionHeading: 'การดำเนินการหลัก', actionDescription: 'ทำขั้นตอนนี้ก่อน จากนั้น LocalOS จะรอวันตรวจสอบและเปรียบเทียบผลลัพธ์',
  expectedOutcome: 'ผลลัพธ์ที่คาดหวัง', continue: 'ดำเนินการต่อ', auditState: 'สถานะแยกตามแพลตฟอร์ม',
  auditDescription: 'ทุกข้อสรุปเชื่อมโยงกับแหล่งข้อมูลและวันที่เก็บข้อมูล ข้อมูลที่ยังไม่ทราบไม่ได้หมายความว่าไม่มี',
  source: 'แหล่งข้อมูล', snapshotMissing: 'ยังไม่ได้รับ', safeFallback: 'เปิดข้อมูลร้านเพื่อตรวจสอบขั้นตอนถัดไป',
  goals: { inquiries: 'เพิ่มการติดต่อ', bookings: 'เพิ่มการจอง', orders: 'เพิ่มคำสั่งซื้อ', directions: 'เพิ่มการขอเส้นทาง', website_visits: 'เพิ่มการเข้าชมเว็บไซต์' },
  gates: { 0: 'เข้าถึงข้อมูลได้', 1: 'ข้อมูลร้านถูกต้อง', 2: 'ติดต่อได้', 3: 'ข้อเสนอชัดเจน', 4: 'มีความน่าเชื่อถือ', 5: 'มีหลักฐาน', 6: 'มีเหตุผลให้กลับมา' },
  facts: { access: 'สิทธิ์เข้าถึง', verified: 'การยืนยัน', duplicate: 'ข้อมูลซ้ำ', category: 'หมวดหมู่', contacts: 'ข้อมูลติดต่อ', schedule: 'เวลาทำการ', action_path: 'การจองหรือสั่งซื้อ', services: 'บริการ', prices: 'ราคา', reviews: 'รีวิว', review_responses: 'คำตอบรีวิว', photos: 'รูปภาพ', publications: 'โพสต์' },
  states: { observed: 'ตรวจสอบแล้ว', missing: 'ต้องกรอกข้อมูล', unknown: 'ไม่มีข้อมูล', not_applicable: 'ไม่เกี่ยวข้อง', blocked: 'แหล่งข้อมูลไม่พร้อมใช้งาน' },
  evidence: {
    connected: 'เชื่อมต่อข้อมูลร้านแล้ว', link_missing: 'ยังไม่ได้เพิ่มลิงก์แพลตฟอร์ม', no_duplicates: 'ไม่พบข้อมูลซ้ำ',
    duplicate_unverified: 'แพลตฟอร์มไม่ได้ให้ข้อมูลที่น่าเชื่อถือว่ามีข้อมูลซ้ำหรือไม่',
    internal_contacts: 'ข้อมูลติดต่อภายในธุรกิจไม่ยืนยันว่าเผยแพร่บนแพลตฟอร์มแล้ว',
    internal_schedule: 'เวลาทำการภายในไม่ยืนยันว่าเวลาบนแพลตฟอร์มเป็นปัจจุบัน',
    internal_services: 'บริการในระบบภายในไม่ยืนยันว่าเผยแพร่บนแพลตฟอร์มแล้ว',
    internal_prices: 'มีราคาในระบบภายใน แต่ยังต้องตรวจสอบแพลตฟอร์ม',
    no_organic_news: '2GIS ไม่มีช่องทางข่าวแบบออร์แกนิก',
    conversion_content: 'โพสต์เป็นเนื้อหาที่ช่วยให้ลูกค้าตัดสินใจ ไม่ใช่ปัจจัยจัดอันดับที่จำเป็น',
    source_error: 'การอัปเดตแพลตฟอร์มครั้งล่าสุดล้มเหลว',
  },
  decisions: {
    insufficient_data: 'ข้อมูลแพลตฟอร์มที่เปรียบเทียบได้ยังไม่เพียงพอสำหรับสรุปผล',
    continue: 'การดำเนินการที่ยืนยันแล้วบนข้อมูลร้านเพิ่มขึ้นจากช่วงอ้างอิง',
    adjust: 'ยังไม่พบการเพิ่มขึ้นในจุดตรวจสอบแรก จะตรวจสอบช่วงถัดไป',
    replace: 'ไม่พบการเพิ่มขึ้นในช่วงตรวจสอบ ต้องเปลี่ยนสมมติฐาน',
  },
  actionMessages: actionMessages('th-TH', {
    refresh: ['อัปเดตข้อมูลบน {provider}', 'ต้องใช้ข้อมูลร้านชุดใหม่เพื่อเลือกสิ่งแรกที่ควรแก้ไข', 'อัปเดตข้อมูล'],
    restore: ['กู้คืนการอัปเดตบน {provider}', 'การอัปเดตครั้งล่าสุดล้มเหลว', 'ตรวจสอบการเชื่อมต่อ'],
    add_provider: ['เพิ่มแพลตฟอร์มสำหรับตรวจสอบ', 'LocalOS ยังไม่ทราบว่าข้อมูลร้านใดเป็นของสาขานี้ เพิ่ม Google, Яндекс หรือ 2ГИС เพื่อรับข้อมูลชุดแรก', 'เพิ่มแพลตฟอร์ม'],
    blocked: ['กู้คืนการอัปเดตบน {provider}', 'แพลตฟอร์มไม่ส่งข้อมูลที่น่าเชื่อถือชั่วคราว ต้องกู้คืนแหล่งข้อมูลก่อน', 'ตรวจสอบการเชื่อมต่อ'],
    access: ['เชื่อมต่อข้อมูลร้านบน {provider}', 'หากไม่เชื่อมต่อ LocalOS จะตรวจสอบข้อมูลร้านและติดตามผลไม่ได้', 'เพิ่มแพลตฟอร์ม'],
    verified: ['ตรวจสอบสิทธิ์จัดการข้อมูลร้านบน {provider}', 'แพลตฟอร์มไม่ยืนยันว่าธุรกิจเป็นผู้จัดการข้อมูลร้านนี้', 'เปิดข้อมูลร้าน'],
    duplicate: ['ตรวจสอบข้อมูลซ้ำบน {provider}', 'ข้อมูลซ้ำอาจทำให้รีวิวแยกกันและลูกค้าสับสน', 'ตรวจสอบข้อมูลร้าน'],
    category: ['ระบุหมวดหมู่หลักบน {provider} ให้ชัดเจน', 'หมวดหมู่ควรอธิบายกิจกรรมหลักของสาขานี้อย่างถูกต้อง', 'ตรวจสอบหมวดหมู่'],
    contacts: ['กรอกข้อมูลติดต่อบน {provider}', 'ลูกค้าควรเข้าใจทันทีว่าจะติดต่อสาขานี้ได้อย่างไร', 'ตรวจสอบข้อมูลติดต่อ'],
    schedule: ['ระบุเวลาทำการบน {provider} ให้ชัดเจน', 'เวลาทำการที่เป็นปัจจุบันช่วยลดโอกาสที่ลูกค้าจะมาเสียเที่ยว', 'ตรวจสอบเวลาทำการ'],
    action_path: ['เพิ่มช่องทางติดต่อที่ชัดเจนบน {provider}', 'โทรศัพท์ เว็บไซต์ หรือการจองต้องเชื่อมไปยังสาขาที่ถูกต้องและใช้งานได้โดยไม่มีขั้นตอนเกินจำเป็น', 'ตรวจสอบการจอง'],
    services: ['เผยแพร่บริการหลักบน {provider}', 'ข้อมูลร้านยังไม่ชัดเจนว่าธุรกิจให้บริการอะไร', 'เปิดบริการ'],
    prices: ['เพิ่มราคาบน {provider}', 'ราคาหรือช่วงราคาที่ชัดเจนช่วยให้ลูกค้าตัดสินใจก่อนติดต่อ', 'เปิดบริการ'],
    reviews: ['เริ่มรวบรวมรีวิวอย่างเป็นระบบบน {provider}', 'ความน่าเชื่อถือของข้อมูลร้านนี้ยังมีหลักฐานน้อยกว่าธุรกิจที่เทียบเคียงได้', 'เปิดรีวิว'],
    review_responses: ['ตอบรีวิวบน {provider}', 'ข้อมูลร้านมีรีวิวที่ยังไม่ได้ตอบ', 'เปิดรีวิว'],
    photos: ['เพิ่มรูปภาพที่เป็นประโยชน์บน {provider}', 'แสดงทางเข้า พื้นที่ ทีมงาน กระบวนการ และผลลัพธ์ เพื่อช่วยให้ลูกค้าเลือกได้ง่ายขึ้น', 'เปิดรูปภาพ'],
    publications: ['เตรียมโพสต์ที่เป็นปัจจุบันสำหรับ {provider}', 'โพสต์ควรให้เหตุผลที่ชัดเจนในการติดต่อขณะนี้ และไม่ทดแทนการกรอกข้อมูลร้านให้ครบ', 'เปิดเนื้อหา'],
  }, {
    inquiries: 'ทำให้ติดต่อได้ง่ายขึ้นและตรวจสอบการเปลี่ยนแปลงของการดำเนินการที่ยืนยันแล้วบนข้อมูลร้าน',
    bookings: 'ทำให้จองได้ง่ายขึ้นและตรวจสอบการเปลี่ยนแปลงของการจองหรือการติดต่อ',
    orders: 'ทำให้สั่งซื้อได้ง่ายขึ้นและตรวจสอบการเปลี่ยนแปลงของคำสั่งซื้อหรือการติดต่อ',
    directions: 'ทำให้การมาใช้บริการชัดเจนขึ้นและตรวจสอบการเปลี่ยนแปลงของการขอเส้นทาง',
    website_visits: 'ทำให้ลิงก์เว็บไซต์เด่นขึ้นและตรวจสอบการเปลี่ยนแปลงของการคลิก',
  }, 'รับสถานะข้อมูลร้านที่น่าเชื่อถือและเลือกสิ่งแรกที่ควรแก้ไข', 'รับข้อมูลร้านชุดใหม่และระบุสิ่งแรกที่ควรแก้ไข', 'มัธยฐานของข้อมูลร้านที่เทียบเคียงได้'),
};

const ar: ManagedCardGrowthCopy = {
  eyebrow: 'إدارة الملف التجاري', title: 'هدف وحالة الملفات التجارية',
  description: 'يتحقق LocalOS أولًا من الوصول إلى الملف ودقته، ثم من مسار التواصل والعرض والثقة والصور والأسباب الحالية للزيارة.',
  goal: 'الهدف', chooseGoal: 'اختر هدفًا', saving: 'جارٍ الحفظ…', confirmGoal: 'تأكيد الهدف',
  goalConfirmed: 'تم تأكيد الهدف. تُختار الخطوة التالية بناءً عليه.', networkGoal: 'أكّد الهدف لكل موقع في الشبكة على حدة.', saveError: 'تعذر حفظ الهدف',
  waitingUntil: (date) => `ننتظر البيانات حتى ${date}`,
  waitingDescription: 'تم إجراء التعديل. في موعد التحقق سنقارن إجراءات الملف بفترة الأساس البالغة 28 يومًا.',
  baseline: 'فترة الأساس: 28 يومًا', views: 'المشاهدات', clicks: 'النقرات', actions: 'الإجراءات',
  baselineDisclaimer: 'المشاهدات والنقرات ليست عملاء أو مبيعات مؤكدة.',
  resultDisclaimer: 'إجراءات المنصات ليست عملاء أو طلبات أو مبيعات مؤكدة.', result: 'نتيجة التحقق',
  critical: 'يوجد عائق حرج', noCritical: 'لم تُكتشف عوائق حرجة', needsAttention: 'يحتاج إلى انتباه',
  snapshot: (date) => `لقطة البيانات: ${date}`, sourceObserved: 'تم استلام البيانات', sourceBlocked: 'المصدر غير متاح', sourceUnknown: 'نحتاج إلى لقطة بيانات جديدة',
  benchmark: (count, days) => `مرجع المقارنة: ${new Intl.NumberFormat('ar').format(count)} أنشطة مشابهة، ببيانات لا تتجاوز ${new Intl.NumberFormat('ar').format(days)} يومًا.`,
  smallSample: ' العينة أقل من الحد الأدنى البالغ 10 أنشطة.', median: 'الوسيط', upperQuartile: 'الربيع الأعلى',
  benchmarkDisclaimer: 'المقارنة مرجع استرشادي وليست دليلًا على سبب النتيجة.',
  noProviders: 'لم تُضف أي منصة بعد. اربط Google أو Яндекс أو 2ГИС أولًا للحصول على لقطة بيانات حديثة.',
  noCardState: 'لم يتم استلام حالة الملفات بعد.', nextSteps: 'الخطوات التالية',
  nextStepsDescription: 'تصبح أولوية بعد إكمال الخطوة الحالية والتحقق من البيانات.',
  policyVersion: 'إصدار القواعد', policyUnknown: 'غير محدد', openEvidence: 'فتح أدلة التدقيق', dateUnknown: 'التاريخ غير متاح',
  actionHeading: 'الإجراء الرئيسي', actionDescription: 'أكمل هذه الخطوة أولًا. بعدها ينتظر LocalOS موعد التحقق ويقارن النتيجة.',
  expectedOutcome: 'النتيجة المتوقعة', continue: 'متابعة', auditState: 'الحالة حسب المنصة',
  auditDescription: 'يرتبط كل استنتاج بمصدر وتاريخ للبيانات. البيانات غير المعروفة لا تُعد مفقودة.',
  source: 'المصدر', snapshotMissing: 'لم تُستلم', safeFallback: 'افتح الملف لمراجعة الخطوة التالية.',
  goals: { inquiries: 'مزيد من الاستفسارات', bookings: 'مزيد من الحجوزات', orders: 'مزيد من الطلبات', directions: 'مزيد من طلبات الاتجاهات', website_visits: 'مزيد من زيارات الموقع' },
  gates: { 0: 'البيانات متاحة', 1: 'الملف صحيح', 2: 'يمكن التواصل', 3: 'العرض واضح', 4: 'توجد ثقة', 5: 'توجد أدلة', 6: 'يوجد سبب للعودة' },
  facts: { access: 'الوصول', verified: 'التحقق', duplicate: 'التكرارات', category: 'الفئة', contacts: 'بيانات التواصل', schedule: 'ساعات العمل', action_path: 'الحجز أو الطلب', services: 'الخدمات', prices: 'الأسعار', reviews: 'التقييمات', review_responses: 'الردود على التقييمات', photos: 'الصور', publications: 'المنشورات' },
  states: { observed: 'تم التحقق', missing: 'يحتاج إلى إكمال', unknown: 'لا توجد بيانات', not_applicable: 'لا ينطبق', blocked: 'المصدر غير متاح' },
  evidence: {
    connected: 'تم ربط الملف', link_missing: 'لم يُضف رابط المنصة', no_duplicates: 'لم تُكتشف تكرارات',
    duplicate_unverified: 'لم توفر المنصة مؤشرًا موثوقًا على التكرار',
    internal_contacts: 'بيانات التواصل الداخلية لا تثبت نشرها على المنصة',
    internal_schedule: 'ساعات العمل الداخلية لا تثبت تحديث الساعات على المنصة',
    internal_services: 'الخدمات الداخلية لا تثبت نشرها على المنصة',
    internal_prices: 'الأسعار موجودة داخليًا، لكن المنصة تحتاج إلى تحقق',
    no_organic_news: 'لا تتوفر في 2GIS قناة أخبار عضوية',
    conversion_content: 'تُقيّم المنشورات كمحتوى يساعد على التواصل، لا كعامل ترتيب إلزامي',
    source_error: 'فشل آخر تحديث للمنصة',
  },
  decisions: {
    insufficient_data: 'لا توجد بيانات منصات قابلة للمقارنة تكفي لتقييم النتيجة.',
    continue: 'زادت الإجراءات المؤكدة في الملفات مقارنة بفترة الأساس.',
    adjust: 'لم تظهر زيادة في الإجراءات عند أول نقطة تحقق؛ سنراجع الفترة التالية.',
    replace: 'لم تُسجل زيادة في الإجراءات خلال فترة التحقق؛ نحتاج إلى فرضية مختلفة.',
  },
  actionMessages: actionMessages('ar', {
    refresh: ['حدّث البيانات في {provider}', 'نحتاج إلى لقطة حديثة للملف لاختيار التصحيح الأول.', 'تحديث البيانات'],
    restore: ['استعد التحديث في {provider}', 'فشل التحديث الأخير.', 'فحص الاتصال'],
    add_provider: ['أضف منصة للتحقق', 'لا يعرف LocalOS بعد الملفات التابعة لهذا الموقع. أضف Google أو Яндекс أو 2ГИС للحصول على أول لقطة بيانات.', 'إضافة منصة'],
    blocked: ['استعد التحديث في {provider}', 'لا توفر المنصة بيانات موثوقة مؤقتًا. استعد المصدر أولًا.', 'فحص الاتصال'],
    access: ['اربط الملف في {provider}', 'بدون الربط لا يستطيع LocalOS فحص الملف ومتابعة النتيجة.', 'إضافة منصة'],
    verified: ['تحقق من إدارة الملف في {provider}', 'لا تؤكد المنصة أن النشاط التجاري يدير الملف.', 'فتح الملف'],
    duplicate: ['تحقق من التكرارات في {provider}', 'قد يؤدي الملف المكرر إلى تقسيم التقييمات وإرباك العملاء.', 'فحص الملف'],
    category: ['حدّد الفئة الرئيسية بدقة في {provider}', 'يجب أن تصف الفئة النشاط الرئيسي لهذا الموقع بدقة.', 'فحص الفئة'],
    contacts: ['أكمل بيانات التواصل في {provider}', 'يجب أن يفهم العميل فورًا كيفية التواصل مع هذا الموقع.', 'فحص بيانات التواصل'],
    schedule: ['وضّح ساعات العمل في {provider}', 'تقلل الساعات المحدثة من احتمال ضياع زيارة العميل.', 'فحص ساعات العمل'],
    action_path: ['أضف مسار تواصل واضحًا في {provider}', 'يجب أن يقود الهاتف أو الموقع أو الحجز إلى الموقع التجاري المحدد دون خطوات غير ضرورية.', 'فحص الحجز'],
    services: ['انشر الخدمات الرئيسية في {provider}', 'لا يوضح الملف بعد ما يقدمه النشاط التجاري بشكل موثوق.', 'فتح الخدمات'],
    prices: ['أضف الأسعار في {provider}', 'يساعد السعر أو التقدير الواضح على اتخاذ القرار قبل التواصل.', 'فتح الخدمات'],
    reviews: ['ابدأ بجمع التقييمات بانتظام في {provider}', 'الثقة في هذا الملف مدعومة بأدلة أقل من الأنشطة المشابهة.', 'فتح التقييمات'],
    review_responses: ['رُدّ على التقييمات في {provider}', 'توجد تقييمات بلا رد في الملف.', 'فتح التقييمات'],
    photos: ['أضف صورًا مفيدة في {provider}', 'اعرض المدخل والمكان والفريق وطريقة العمل والنتيجة لتسهيل اختيار العميل.', 'فتح الصور'],
    publications: ['حضّر منشورًا حديثًا لـ {provider}', 'يجب أن يقدم المنشور سببًا محددًا للتواصل الآن؛ ولا يغني عن إكمال الملف.', 'فتح المحتوى'],
  }, {
    inquiries: 'سهّل التواصل وتحقق من تغير الإجراءات المؤكدة في الملف.',
    bookings: 'سهّل الحجز وتحقق من تغير الحجوزات أو الاستفسارات.',
    orders: 'سهّل الطلب وتحقق من تغير الطلبات أو الاستفسارات.',
    directions: 'وضّح طريقة الزيارة وتحقق من تغير طلبات الاتجاهات.',
    website_visits: 'أبرز رابط الموقع وتحقق من تغير النقرات.',
  }, 'احصل على حالة موثوقة للملف واختر التصحيح الأول.', 'احصل على بيانات حديثة للملف وحدّد التصحيح الأول.', 'وسيط الملفات المشابهة'),
};

const ha: ManagedCardGrowthCopy = {
  eyebrow: 'Gudanar da bayanan kasuwanci', title: 'Manufa da matsayin bayanan kasuwanci',
  description: 'LocalOS yana duba damar shiga da daidaiton bayanan kasuwanci da farko, sannan hanyar tuntuɓa, abin da ake bayarwa, amincewa, hotuna da dalilan ziyara a yanzu.',
  goal: 'Manufa', chooseGoal: 'Zaɓi manufa', saving: 'Ana adanawa…', confirmGoal: 'Tabbatar da manufa',
  goalConfirmed: 'An tabbatar da manufa. Za a zaɓi mataki na gaba bisa wannan manufa.',
  networkGoal: 'Tabbatar da manufar kowane reshe na cibiyar dabam.', saveError: 'An kasa adana manufa',
  waitingUntil: (date) => `Ana jiran bayanai har zuwa ${date}`,
  waitingDescription: 'An riga an yi gyaran. A ranar dubawa za a kwatanta ayyukan da aka yi a shafin kasuwanci da kwanaki 28 na tushe.',
  baseline: 'Kwanaki 28 na tushe', views: 'Kallo', clicks: 'Dannawa', actions: 'Ayyuka',
  baselineDisclaimer: 'Kallo da dannawa ba abokan ciniki ko tallace-tallace da aka tabbatar ba ne.',
  resultDisclaimer: 'Ayyukan dandamali ba abokan ciniki, oda ko tallace-tallace da aka tabbatar ba ne.', result: 'Sakamakon dubawa',
  critical: 'Akwai babban cikas', noCritical: 'Ba a gano babban cikas ba', needsAttention: 'Yana buƙatar kulawa',
  snapshot: (date) => `Bayanan ranar: ${date}`, sourceObserved: 'An karɓi bayanai', sourceBlocked: 'Ba a samun tushen bayanai', sourceUnknown: 'Ana buƙatar sabbin bayanai',
  benchmark: (count, days) => `Ma’aunin kwatantawa: kasuwanci ${new Intl.NumberFormat('ha-NG').format(count)} masu kama, bayanan da ba su wuce kwanaki ${new Intl.NumberFormat('ha-NG').format(days)} ba.`,
  smallSample: ' Samfurin bai kai mafi ƙarancin kasuwanci 10 ba.', median: 'ƙimar tsakiya', upperQuartile: 'iyakar kashi 75 cikin 100',
  benchmarkDisclaimer: 'Kwatantawa jagora ce, ba hujjar abin da ya haifar da sakamako ba.',
  noProviders: 'Ba a ƙara dandamali ba tukuna. Haɗa Google, Яндекс ko 2ГИС da farko don samun sabbin bayanai.',
  noCardState: 'Ba a karɓi matsayin bayanan kasuwanci ba tukuna.', nextSteps: 'Matakai na gaba',
  nextStepsDescription: 'Za su zama manyan ayyuka bayan kammala matakin yanzu da duba bayanai.',
  policyVersion: 'Sigar ƙa’idoji', policyUnknown: 'ba a bayyana ba', openEvidence: 'Buɗe hujjojin bincike', dateUnknown: 'ba a samu kwanan wata ba',
  actionHeading: 'Babban aiki', actionDescription: 'Kammala wannan mataki da farko. Sannan LocalOS zai jira ranar dubawa ya kwatanta sakamakon.',
  expectedOutcome: 'Sakamakon da ake tsammani', continue: 'Ci gaba', auditState: 'Matsayi bisa dandamali',
  auditDescription: 'Kowane sakamako yana da tushen bayanai da kwanan wata. Bayanai da ba a sani ba ba su nufin babu su.',
  source: 'Tushen bayanai', snapshotMissing: 'ba a karɓa ba', safeFallback: 'Buɗe bayanan kasuwanci don duba mataki na gaba.',
  goals: { inquiries: 'Ƙarin tambayoyi', bookings: 'Ƙarin ajiyar lokaci', orders: 'Ƙarin oda', directions: 'Ƙarin neman hanya', website_visits: 'Ƙarin ziyartar shafin yanar gizo' },
  gates: { 0: 'Ana samun bayanai', 1: 'Bayanan kasuwanci daidai ne', 2: 'Ana iya tuntuɓa', 3: 'Abin da ake bayarwa a bayyane yake', 4: 'Akwai amincewa', 5: 'Akwai hujjoji', 6: 'Akwai dalilin dawowa' },
  facts: { access: 'Damar shiga', verified: 'Tabbatarwa', duplicate: 'Maimaitattun bayanai', category: 'Rukuni', contacts: 'Bayanan tuntuɓa', schedule: 'Lokutan aiki', action_path: 'Ajiyar lokaci ko oda', services: 'Ayyukan kasuwanci', prices: 'Farashi', reviews: 'Ra’ayoyi', review_responses: 'Amsoshin ra’ayoyi', photos: 'Hotuna', publications: 'Wallafe-wallafe' },
  states: { observed: 'An duba', missing: 'Ana buƙatar cika bayanai', unknown: 'Babu bayanai', not_applicable: 'Bai shafi wannan ba', blocked: 'Ba a samun tushen bayanai' },
  evidence: {
    connected: 'An haɗa bayanan kasuwanci', link_missing: 'Ba a ƙara hanyar haɗin dandamali ba', no_duplicates: 'Ba a gano maimaitattun bayanai ba',
    duplicate_unverified: 'Dandamalin bai ba da sahihiyar alamar maimaita bayanai ba',
    internal_contacts: 'Bayanan tuntuɓa na ciki ba su tabbatar da cewa an wallafa su a dandamali ba',
    internal_schedule: 'Lokutan aiki na ciki ba su tabbatar da sabunta lokutan dandamali ba',
    internal_services: 'Ayyukan da ke cikin tsarin ciki ba su tabbatar da wallafa su a dandamali ba',
    internal_prices: 'Akwai farashi a ciki, amma har yanzu ana buƙatar duba dandamali',
    no_organic_news: '2GIS ba shi da tashar labarai ta halitta',
    conversion_content: 'Ana duba wallafe-wallafe don taimaka wa tuntuɓa, ba a matsayin dole don matsayi a bincike ba',
    source_error: 'Sabuntawar dandamali ta ƙarshe ta gaza',
  },
  decisions: {
    insufficient_data: 'Babu isassun bayanan dandamali da za a kwatanta don yanke hukunci kan sakamako.',
    continue: 'Ayyukan da aka tabbatar a shafukan kasuwanci sun ƙaru idan aka kwatanta da lokacin tushe.',
    adjust: 'Har yanzu babu ƙaruwa a dubawar farko; za a duba lokaci na gaba.',
    replace: 'Ba a samu ƙarin ayyuka a lokacin dubawa ba; ana buƙatar wata hasashe dabam.',
  },
  actionMessages: actionMessages('ha-NG', {
    refresh: ['Sabunta bayanai a {provider}', 'Ana buƙatar sabbin bayanan kasuwanci don zaɓar gyaran farko.', 'Sabunta bayanai'],
    restore: ['Maido da sabuntawa a {provider}', 'Sabuntawar ƙarshe ta gaza.', 'Duba haɗi'],
    add_provider: ['Ƙara dandamali don dubawa', 'LocalOS bai san bayanan kasuwancin da suka shafi wannan reshe ba tukuna. Ƙara Google, Яндекс ko 2ГИС don samun bayanan farko.', 'Ƙara dandamali'],
    blocked: ['Maido da sabuntawa a {provider}', 'Dandamalin ba ya ba da sahihan bayanai na ɗan lokaci. Maido da tushen bayanai da farko.', 'Duba haɗi'],
    access: ['Haɗa bayanan kasuwanci a {provider}', 'Ba tare da haɗi ba, LocalOS ba zai iya duba bayanan kasuwanci ko bin sakamako ba.', 'Ƙara dandamali'],
    verified: ['Duba ikon kula da bayanan kasuwanci a {provider}', 'Dandamalin bai tabbatar da cewa kasuwancin ne ke kula da bayanan ba.', 'Buɗe bayanan kasuwanci'],
    duplicate: ['Duba maimaitattun bayanai a {provider}', 'Maimaita bayanai na iya raba ra’ayoyin abokan ciniki kuma ya ruɗe su.', 'Duba bayanan kasuwanci'],
    category: ['Fayyace babban rukuni a {provider}', 'Rukuni ya kamata ya bayyana babban aikin wannan reshe daidai.', 'Duba rukuni'],
    contacts: ['Cika bayanan tuntuɓa a {provider}', 'Ya kamata abokin ciniki ya fahimci yadda zai tuntuɓi wannan reshe nan take.', 'Duba bayanan tuntuɓa'],
    schedule: ['Fayyace lokutan aiki a {provider}', 'Lokutan aiki na yanzu suna rage haɗarin ziyarar banza.', 'Duba lokutan aiki'],
    action_path: ['Ƙara bayyananniyar hanyar tuntuɓa a {provider}', 'Waya, shafin yanar gizo ko ajiyar lokaci su kai ga reshen da ya dace ba tare da matakai marasa amfani ba.', 'Duba ajiyar lokaci'],
    services: ['Wallafa manyan ayyukan kasuwanci a {provider}', 'Bayanan kasuwanci ba su bayyana abin da kasuwancin yake bayarwa da tabbaci ba tukuna.', 'Buɗe ayyukan kasuwanci'],
    prices: ['Ƙara farashi a {provider}', 'Farashi ko bayyanannen kiyasi yana taimakawa yanke shawara kafin tuntuɓa.', 'Buɗe ayyukan kasuwanci'],
    reviews: ['Fara tattara ra’ayoyi cikin tsari a {provider}', 'Hujjojin amincewa da wannan shafin kasuwanci sun yi ƙasa da na kasuwanci masu kama.', 'Buɗe ra’ayoyi'],
    review_responses: ['Amsa ra’ayoyi a {provider}', 'Akwai ra’ayoyin da ba a amsa ba a shafin kasuwanci.', 'Buɗe ra’ayoyi'],
    photos: ['Ƙara hotuna masu amfani a {provider}', 'Nuna ƙofar shiga, wurin, ma’aikata, yadda ake aiki da sakamako don sauƙaƙa zaɓin abokin ciniki.', 'Buɗe hotuna'],
    publications: ['Shirya wallafar da ta dace da yanzu don {provider}', 'Wallafar ta ba da takamaiman dalilin tuntuɓa yanzu; ba ta maye gurbin cika bayanan kasuwanci ba.', 'Buɗe abubuwan wallafawa'],
  }, {
    inquiries: 'Sauƙaƙa tuntuɓa kuma duba canjin ayyukan da aka tabbatar a shafin kasuwanci.',
    bookings: 'Sauƙaƙa ajiyar lokaci kuma duba canjin ajiyar lokaci ko tambayoyi.',
    orders: 'Sauƙaƙa oda kuma duba canjin oda ko tambayoyi.',
    directions: 'Fayyace yadda ake ziyara kuma duba canjin neman hanyoyi.',
    website_visits: 'Sa hanyar shafin yanar gizo ta fi bayyana kuma duba canjin dannawa.',
  }, 'Samu sahihin matsayin bayanan kasuwanci kuma zaɓi gyaran farko.', 'Samu sabbin bayanan kasuwanci kuma gano gyaran farko.', 'Ƙimar tsakiya ta shafukan kasuwanci masu kama'),
};

export const managedCardGrowthCopyAdditional: Record<Exclude<Language, 'ru' | 'en' | 'es'>, ManagedCardGrowthCopy> = {
  fr: managedCardGrowthCopyEuropean.fr,
  de: managedCardGrowthCopyEuropean.de,
  tr: managedCardGrowthCopyEuropean.tr,
  el, th, ar, ha,
};
