import { useEffect, useState } from 'react';
import { CalendarDays, Check, ChevronRight, FileText, ShieldCheck, Sparkles } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useLanguage, type Language } from '@/i18n/LanguageContext';
import { cn } from '@/lib/utils';

type Copy = {
  eyebrow: string; title: string; description: string; create: string; setup: string; setupHint: string; goal: string; goalValue: string;
  period: string; periodValue: string; frequency: string; frequencyValue: string; channels: string; generate: string; preview: string; previewHint: string;
  theme: string; themeValue: string; draft: string; draftValue: string; editHint: string; save: string; saved: string; calendar: string;
  calendarHint: string; review: string; safety: string; startOver: string;
};

const copy: Record<Language, Copy> = {
  ru: { eyebrow: 'LOCALOS CONTENT', title: 'Контент‑план', description: 'От цели и каналов — к готовому черновику в календаре. Демо сохраняет изменения только в этой вкладке.', create: 'Создать план', setup: 'Настройте план', setupHint: 'Выберите цель, темп и каналы. Наружу ничего не отправляется.', goal: 'Цель', goalValue: 'Получать больше записей на услуги', period: 'Период', periodValue: '14 дней', frequency: 'Темп', frequencyValue: '3 публикации в неделю', channels: 'Каналы', generate: 'Показать предварительный план', preview: 'Предварительный план', previewHint: 'LocalOS собрал темы и адаптировал формат под выбранные каналы.', theme: 'Тема', themeValue: 'Как подобрать уход между визитами', draft: 'Черновик', draftValue: 'Простой домашний уход помогает сохранить результат между визитами. Мы собрали три коротких совета.', editHint: 'Измените текст перед сохранением.', save: 'Сохранить в план', saved: 'Черновик сохранён в демо‑календаре.', calendar: 'Календарь', calendarHint: 'Материал готов к проверке.', review: 'Перейти к проверке', safety: 'Публикация остаётся ручным решением. Демо ничего не отправляет во внешние каналы.', startOver: 'Начать заново' },
  en: { eyebrow: 'LOCALOS CONTENT', title: 'Content plan', description: 'Move from a goal and channels to an editable draft in the calendar. Demo changes stay in this browser tab.', create: 'Create plan', setup: 'Set up the plan', setupHint: 'Choose a goal, pace, and channels. Nothing is sent outside LocalOS.', goal: 'Goal', goalValue: 'Get more service bookings', period: 'Period', periodValue: '14 days', frequency: 'Pace', frequencyValue: '3 posts per week', channels: 'Channels', generate: 'Show preview plan', preview: 'Preview plan', previewHint: 'LocalOS assembled topics and adapted the format to the selected channels.', theme: 'Topic', themeValue: 'How to choose care between appointments', draft: 'Draft', draftValue: 'Simple home care helps preserve the result between appointments. We collected three short tips.', editHint: 'Edit the text before saving.', save: 'Save to plan', saved: 'The draft was saved to the demo calendar.', calendar: 'Calendar', calendarHint: 'The material is ready for review.', review: 'Continue to review', safety: 'Publishing remains a manual decision. The demo never sends anything to external channels.', startOver: 'Start over' },
  fr: { eyebrow: 'CONTENU LOCALOS', title: 'Plan de contenu', description: 'Passez de l’objectif et des canaux à un brouillon modifiable dans le calendrier. Les changements restent dans cet onglet.', create: 'Créer un plan', setup: 'Configurer le plan', setupHint: 'Choisissez un objectif, un rythme et des canaux. Rien n’est envoyé hors de LocalOS.', goal: 'Objectif', goalValue: 'Obtenir plus de réservations', period: 'Période', periodValue: '14 jours', frequency: 'Rythme', frequencyValue: '3 publications par semaine', channels: 'Canaux', generate: 'Afficher l’aperçu', preview: 'Aperçu du plan', previewHint: 'LocalOS a assemblé les sujets et adapté le format aux canaux choisis.', theme: 'Sujet', themeValue: 'Comment choisir les soins entre deux rendez-vous', draft: 'Brouillon', draftValue: 'Des soins simples à domicile aident à conserver le résultat entre les rendez-vous. Voici trois conseils courts.', editHint: 'Modifiez le texte avant de l’enregistrer.', save: 'Enregistrer dans le plan', saved: 'Le brouillon est enregistré dans le calendrier de démonstration.', calendar: 'Calendrier', calendarHint: 'Le contenu est prêt à être vérifié.', review: 'Passer à la vérification', safety: 'La publication reste une décision manuelle. La démo n’envoie rien vers des canaux externes.', startOver: 'Recommencer' },
  es: { eyebrow: 'CONTENIDO LOCALOS', title: 'Plan de contenido', description: 'Pasa del objetivo y los canales a un borrador editable en el calendario. Los cambios de la demo quedan en esta pestaña.', create: 'Crear plan', setup: 'Configurar el plan', setupHint: 'Elige objetivo, ritmo y canales. No se envía nada fuera de LocalOS.', goal: 'Objetivo', goalValue: 'Conseguir más reservas', period: 'Periodo', periodValue: '14 días', frequency: 'Ritmo', frequencyValue: '3 publicaciones por semana', channels: 'Canales', generate: 'Mostrar vista previa', preview: 'Vista previa del plan', previewHint: 'LocalOS reunió temas y adaptó el formato a los canales elegidos.', theme: 'Tema', themeValue: 'Cómo elegir cuidados entre citas', draft: 'Borrador', draftValue: 'Un cuidado sencillo en casa ayuda a conservar el resultado entre citas. Reunimos tres consejos breves.', editHint: 'Edita el texto antes de guardarlo.', save: 'Guardar en el plan', saved: 'El borrador se guardó en el calendario de demostración.', calendar: 'Calendario', calendarHint: 'El material está listo para revisar.', review: 'Continuar a revisión', safety: 'Publicar sigue siendo una decisión manual. La demo no envía nada a canales externos.', startOver: 'Empezar de nuevo' },
  el: { eyebrow: 'ΠΕΡΙΕΧΟΜΕΝΟ LOCALOS', title: 'Πλάνο περιεχομένου', description: 'Από τον στόχο και τα κανάλια σε επεξεργάσιμο προσχέδιο στο ημερολόγιο. Οι αλλαγές μένουν σε αυτή την καρτέλα.', create: 'Δημιουργία πλάνου', setup: 'Ρύθμιση πλάνου', setupHint: 'Επιλέξτε στόχο, ρυθμό και κανάλια. Δεν αποστέλλεται τίποτα.', goal: 'Στόχος', goalValue: 'Περισσότερες κρατήσεις', period: 'Περίοδος', periodValue: '14 ημέρες', frequency: 'Ρυθμός', frequencyValue: '3 δημοσιεύσεις την εβδομάδα', channels: 'Κανάλια', generate: 'Προβολή προεπισκόπησης', preview: 'Προεπισκόπηση πλάνου', previewHint: 'Το LocalOS συγκέντρωσε θέματα και προσάρμοσε το υλικό στα κανάλια.', theme: 'Θέμα', themeValue: 'Φροντίδα μεταξύ ραντεβού', draft: 'Προσχέδιο', draftValue: 'Η απλή φροντίδα στο σπίτι διατηρεί το αποτέλεσμα μεταξύ των ραντεβού. Συγκεντρώσαμε τρεις σύντομες συμβουλές.', editHint: 'Επεξεργαστείτε το κείμενο πριν την αποθήκευση.', save: 'Αποθήκευση στο πλάνο', saved: 'Το προσχέδιο αποθηκεύτηκε στο ημερολόγιο demo.', calendar: 'Ημερολόγιο', calendarHint: 'Το υλικό είναι έτοιμο για έλεγχο.', review: 'Συνέχεια στον έλεγχο', safety: 'Η δημοσίευση απαιτεί δική σας απόφαση. Το demo δεν στέλνει τίποτα εκτός LocalOS.', startOver: 'Από την αρχή' },
  de: { eyebrow: 'LOCALOS CONTENT', title: 'Content-Plan', description: 'Vom Ziel und den Kanälen zum bearbeitbaren Entwurf im Kalender. Demo-Änderungen bleiben in diesem Tab.', create: 'Plan erstellen', setup: 'Plan einrichten', setupHint: 'Ziel, Rhythmus und Kanäle wählen. Nichts wird extern gesendet.', goal: 'Ziel', goalValue: 'Mehr Buchungen erhalten', period: 'Zeitraum', periodValue: '14 Tage', frequency: 'Rhythmus', frequencyValue: '3 Beiträge pro Woche', channels: 'Kanäle', generate: 'Vorschau anzeigen', preview: 'Planvorschau', previewHint: 'LocalOS hat Themen zusammengestellt und an die Kanäle angepasst.', theme: 'Thema', themeValue: 'Pflege zwischen zwei Terminen', draft: 'Entwurf', draftValue: 'Einfache Pflege zu Hause erhält das Ergebnis zwischen den Terminen. Wir haben drei kurze Tipps zusammengestellt.', editHint: 'Text vor dem Speichern bearbeiten.', save: 'Im Plan speichern', saved: 'Der Entwurf wurde im Demo-Kalender gespeichert.', calendar: 'Kalender', calendarHint: 'Der Inhalt ist zur Prüfung bereit.', review: 'Zur Prüfung', safety: 'Veröffentlichen bleibt eine manuelle Entscheidung. Die Demo sendet nichts an externe Kanäle.', startOver: 'Neu beginnen' },
  tr: { eyebrow: 'LOCALOS İÇERİK', title: 'İçerik planı', description: 'Hedef ve kanallardan takvimde düzenlenebilir bir taslağa ilerleyin. Demo değişiklikleri bu sekmede kalır.', create: 'Plan oluştur', setup: 'Planı ayarla', setupHint: 'Hedefi, tempoyu ve kanalları seçin. LocalOS dışına hiçbir şey gönderilmez.', goal: 'Hedef', goalValue: 'Daha fazla hizmet randevusu almak', period: 'Dönem', periodValue: '14 gün', frequency: 'Tempo', frequencyValue: 'Haftada 3 yayın', channels: 'Kanallar', generate: 'Ön planı göster', preview: 'Plan önizlemesi', previewHint: 'LocalOS konuları topladı ve biçimi seçilen kanallara uyarladı.', theme: 'Konu', themeValue: 'Randevular arasında bakım nasıl seçilir', draft: 'Taslak', draftValue: 'Basit ev bakımı randevular arasında sonucu korumaya yardımcı olur. Üç kısa ipucu hazırladık.', editHint: 'Kaydetmeden önce metni düzenleyin.', save: 'Plana kaydet', saved: 'Taslak demo takvimine kaydedildi.', calendar: 'Takvim', calendarHint: 'İçerik incelemeye hazır.', review: 'İncelemeye geç', safety: 'Yayınlama manuel bir karardır. Demo haricî kanallara hiçbir şey göndermez.', startOver: 'Baştan başla' },
  th: { eyebrow: 'เนื้อหา LOCALOS', title: 'แผนเนื้อหา', description: 'จากเป้าหมายและช่องทางสู่ร่างที่แก้ไขได้ในปฏิทิน การเปลี่ยนแปลงจะอยู่ในแท็บนี้', create: 'สร้างแผน', setup: 'ตั้งค่าแผน', setupHint: 'เลือกเป้าหมาย จังหวะ และช่องทาง จะไม่มีการส่งออก', goal: 'เป้าหมาย', goalValue: 'รับการจองมากขึ้น', period: 'ระยะเวลา', periodValue: '14 วัน', frequency: 'จังหวะ', frequencyValue: '3 โพสต์ต่อสัปดาห์', channels: 'ช่องทาง', generate: 'แสดงตัวอย่าง', preview: 'ตัวอย่างแผน', previewHint: 'LocalOS รวบรวมหัวข้อและปรับให้เหมาะกับช่องทาง', theme: 'หัวข้อ', themeValue: 'การดูแลระหว่างนัด', draft: 'ร่าง', draftValue: 'การดูแลง่ายๆ ที่บ้านช่วยรักษาผลลัพธ์ระหว่างนัด เรารวบรวมเคล็ดลับสั้นๆ สามข้อ', editHint: 'แก้ไขข้อความก่อนบันทึก', save: 'บันทึกในแผน', saved: 'บันทึกร่างในปฏิทินสาธิตแล้ว', calendar: 'ปฏิทิน', calendarHint: 'เนื้อหาพร้อมตรวจ', review: 'ไปที่การตรวจ', safety: 'การเผยแพร่เป็นการตัดสินใจด้วยตนเอง เดโมไม่ส่งออก', startOver: 'เริ่มใหม่' },
  ar: { eyebrow: 'محتوى LOCALOS', title: 'خطة المحتوى', description: 'انتقل من الهدف والقنوات إلى مسودة قابلة للتعديل في التقويم. تبقى التغييرات في هذه العلامة.', create: 'إنشاء خطة', setup: 'إعداد الخطة', setupHint: 'اختر الهدف والوتيرة والقنوات. لا يتم إرسال شيء.', goal: 'الهدف', goalValue: 'الحصول على حجوزات أكثر', period: 'المدة', periodValue: '14 يومًا', frequency: 'الوتيرة', frequencyValue: '3 منشورات أسبوعيًا', channels: 'القنوات', generate: 'عرض المعاينة', preview: 'معاينة الخطة', previewHint: 'جمع LocalOS الموضوعات وكيّفها للقنوات.', theme: 'الموضوع', themeValue: 'العناية بين المواعيد', draft: 'المسودة', draftValue: 'تساعد العناية المنزلية البسيطة في الحفاظ على النتيجة بين المواعيد. جمعنا ثلاث نصائح قصيرة.', editHint: 'عدّل النص قبل الحفظ.', save: 'حفظ في الخطة', saved: 'حُفظت المسودة في تقويم العرض.', calendar: 'التقويم', calendarHint: 'المحتوى جاهز للمراجعة.', review: 'المتابعة إلى المراجعة', safety: 'يبقى النشر قرارًا يدويًا. لا يرسل العرض شيئًا إلى قنوات خارجية.', startOver: 'البدء من جديد' },
  ha: { eyebrow: 'ABUN CIKI NA LOCALOS', title: 'Shirin abun ciki', description: 'Daga manufa da tashoshi zuwa daftari da za a gyara a kalanda. Canjin demo yana nan a wannan shafin.', create: 'Ƙirƙiri shiri', setup: 'Saita shirin', setupHint: 'Zaɓi manufa, sauri da tashoshi. Ba a aika komai waje.', goal: 'Manufa', goalValue: 'Samun ƙarin ajiyar sabis', period: 'Lokaci', periodValue: 'Kwana 14', frequency: 'Sauri', frequencyValue: 'Wallafa 3 a mako', channels: 'Tashoshi', generate: 'Nuna samfuri', preview: 'Samfurin shiri', previewHint: 'LocalOS ya tattara jigogi ya daidaita su da tashoshi.', theme: 'Jigo', themeValue: 'Kulawa tsakanin alƙawura', draft: 'Daftari', draftValue: 'Kulawa mai sauƙi a gida tana taimaka wa sakamako ya dawwama tsakanin alƙawura. Mun tattara shawarwari uku.', editHint: 'Gyara rubutu kafin ajiye shi.', save: 'Ajiye a shiri', saved: 'An ajiye daftarin a kalandar demo.', calendar: 'Kalanda', calendarHint: 'Abun ciki yana shirye don dubawa.', review: 'Ci gaba zuwa dubawa', safety: 'Wallafawa hukuncin hannu ne. Demo ba ya aika komai zuwa tashoshin waje.', startOver: 'Sake farawa' },
};

type Stage = 'intro' | 'setup' | 'preview' | 'saved' | 'review';
const STORAGE_KEY = 'localos:demo-content-plan:v1';

export function DemoContentPlanPage() {
  const { language } = useLanguage();
  const [searchParams] = useSearchParams();
  const t = copy[language];
  const [stage, setStage] = useState<Stage>(() => {
    const saved = window.sessionStorage.getItem(STORAGE_KEY);
    return saved === 'setup' || saved === 'preview' || saved === 'saved' || saved === 'review' ? saved : 'intro';
  });
  const [draft, setDraft] = useState(t.draftValue);

  useEffect(() => { window.sessionStorage.setItem(STORAGE_KEY, stage); }, [stage]);
  useEffect(() => { setDraft(t.draftValue); }, [t.draftValue]);
  useEffect(() => {
    const requestedStage = searchParams.get('demo_stage');
    if (requestedStage === 'setup' || requestedStage === 'preview' || requestedStage === 'saved' || requestedStage === 'review') setStage(requestedStage);
  }, [searchParams]);

  const reset = () => { window.sessionStorage.removeItem(STORAGE_KEY); setStage('intro'); setDraft(t.draftValue); };

  return <div className="space-y-5 pb-16" data-tour-target="content-calendar">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">{t.eyebrow}</div><h1 className="mt-1 text-balance text-3xl font-semibold text-slate-950">{t.title}</h1><p className="mt-2 max-w-3xl text-pretty text-sm leading-6 text-slate-600">{t.description}</p></div>{stage === 'intro' ? <Button type="button" onClick={() => setStage('setup')} className="min-h-11 gap-2 transition-transform active:scale-[0.96]"><Sparkles className="h-4 w-4" />{t.create}</Button> : <Button type="button" variant="outline" onClick={reset} className="min-h-11 transition-transform active:scale-[0.96]">{t.startOver}</Button>}</header>
    <div className="grid grid-cols-4 gap-2" aria-label={t.title}>{(['setup', 'preview', 'saved', 'review'] satisfies Stage[]).map((value, index) => <div key={value} className={cn('h-1.5 rounded-full', ['setup', 'preview', 'saved', 'review'].indexOf(stage) >= index ? 'bg-orange-500' : 'bg-slate-200')} />)}</div>
    {stage === 'intro' ? <section className="rounded-2xl bg-white p-8 text-center shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><CalendarDays className="mx-auto h-9 w-9 text-slate-400" /><h2 className="mt-4 text-balance text-xl font-semibold text-slate-950">{t.create}</h2><p className="mx-auto mt-2 max-w-xl text-pretty text-sm leading-6 text-slate-600">{t.setupHint}</p></section> : null}
    {stage === 'setup' ? <section data-tour-target="content-plan-setup" className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><h2 className="text-balance text-xl font-semibold text-slate-950">{t.setup}</h2><p className="mt-1 text-pretty text-sm text-slate-500">{t.setupHint}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label={t.goal} value={t.goalValue} /><Field label={t.period} value={t.periodValue} /><Field label={t.frequency} value={t.frequencyValue} /><Field label={t.channels} value="Telegram · VK · Google" /></div><Button type="button" onClick={() => setStage('preview')} className="mt-5 min-h-11 gap-2 transition-transform active:scale-[0.96]">{t.generate}<ChevronRight className="h-4 w-4" /></Button></section> : null}
    {stage === 'preview' ? <section data-tour-target="content-plan-preview" className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><h2 className="text-balance text-xl font-semibold text-slate-950">{t.preview}</h2><p className="mt-1 text-pretty text-sm text-slate-500">{t.previewHint}</p><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.theme}</div><div className="mt-1 font-semibold text-slate-950">{t.themeValue}</div><div className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">{t.draft}</div><Textarea value={draft} onChange={(event) => setDraft(event.target.value)} className="mt-2 min-h-32 bg-white" /><p className="mt-2 text-xs text-slate-500">{t.editHint}</p></div><Button type="button" onClick={() => setStage('saved')} className="mt-5 min-h-11 gap-2 transition-transform active:scale-[0.96]"><Check className="h-4 w-4" />{t.save}</Button></section> : null}
    {stage === 'saved' || stage === 'review' ? <section data-tour-target="content-plan-save" className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Check className="h-5 w-5" /></div><div><h2 className="text-balance text-xl font-semibold text-slate-950">{t.saved}</h2><p className="mt-1 text-sm text-slate-600">{t.calendarHint}</p></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.calendar}</div><div className="mt-1 font-semibold text-slate-950">{t.themeValue}</div></div><span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800">{t.review}</span></div><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{draft}</p></div>{stage === 'saved' ? <Button type="button" onClick={() => setStage('review')} className="mt-5 min-h-11 gap-2 transition-transform active:scale-[0.96]">{t.review}<ChevronRight className="h-4 w-4" /></Button> : null}</section> : null}
    {stage === 'review' ? <section data-tour-target="content-plan-review" className="rounded-2xl bg-amber-50 p-5 shadow-[inset_0_0_0_1px_rgba(245,158,11,0.24)]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-amber-700" /><div><h2 className="font-semibold text-slate-950">{t.review}</h2><p className="mt-1 text-pretty text-sm leading-6 text-slate-700">{t.safety}</p></div></div></section> : null}
  </div>;
}

function Field({ label, value }: { label: string; value: string }) {
  return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-sm font-medium text-slate-950">{value}</div></div>;
}
