import { type ReactNode, useMemo, useState } from 'react';
import { Bot, CheckCircle2, Clock3, FileCheck2, MapPinned, MessageCircle, Newspaper, Play, ShieldCheck } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { useLanguage, type Language } from '@/i18n/LanguageContext';
import { cn } from '@/lib/utils';

type DemoAgentCopy = {
  eyebrow: string; title: string; description: string; flow: string; today: string; completed: string; prepared: string; decisions: string;
  employees: string; employeesHint: string; overview: string; history: string; scenario: string; settings: string; sources: string;
  input: string; schedule: string; result: string; safety: string; run: string; running: string; review: string; approved: string;
  resultTitle: string; resultBody: string; approvalTitle: string; approvalBody: string; historyTitle: string; historyBody: string;
  cards: { name: string; job: string; status: string; sources: string; schedule: string }[];
};

const copy: Record<Language, DemoAgentCopy> = {
  ru: { eyebrow: 'ЦИФРОВЫЕ СОТРУДНИКИ', title: 'Агенты', description: 'LocalOS получает новые отзывы, изменения в карточках, темы из Telegram и новости. Агент проверяет их по расписанию и готовит черновик или список действий. Владелец решает, что применять.', flow: 'Новый отзыв или тема → задача агенту → готовый черновик → проверка владельца → запись в истории', today: 'Сегодня', completed: 'задач завершено', prepared: 'результата готовы к проверке', decisions: 'результат ждёт решения', employees: 'Мои сотрудники', employeesHint: 'Выберите агента, чтобы увидеть его источники, расписание и последний результат.', overview: 'Обзор', history: 'История', scenario: 'Сценарий', settings: 'Настройки', sources: 'Источники', input: 'Какие данные проверяет', schedule: 'Когда запускается', result: 'Что подготовил в последний раз', safety: 'Агент ничего не публикует и не отправляет без вашего подтверждения.', run: 'Запустить на примере', running: 'Агент ищет отзывы без ответа и готовит черновики…', review: 'Проверить черновики', approved: 'Черновики проверены. Решение записано в историю.', resultTitle: 'Готовы четыре черновика', resultBody: 'Агент нашёл 4 отзыва без ответа и подготовил отдельный текст для каждого.', approvalTitle: 'Перед публикацией проверьте текст', approvalBody: 'Пока вы не подтвердите результат, ответы останутся черновиками.', historyTitle: 'Что агент сделал раньше', historyBody: 'Для каждого запуска указаны дата, источники, подготовленный результат и кто его подтвердил.', cards: [{ name: 'Агент по отзывам', job: 'Находит отзывы без ответа и готовит отдельный черновик для каждого.', status: 'Ждёт проверки', sources: 'Карты и отзывы', schedule: 'Каждое утро' }, { name: 'Контент-агент', job: 'Собирает повторяющиеся вопросы и предлагает темы для публикаций.', status: 'Готовит темы', sources: 'Telegram и новости', schedule: 'Каждый понедельник' }, { name: 'Telegram-радар', job: 'Находит сообщения по заданным словам и раскладывает их по действиям.', status: 'Проверка завершена', sources: 'Выбранные Telegram-каналы', schedule: 'Каждые 3 часа' }] },
  en: { eyebrow: 'DIGITAL TEAM MEMBERS', title: 'Agents', description: 'Signals from maps, reviews, social networks, and news become clear tasks. Agents handle the repetitive part while the owner makes the decision.', flow: 'Signal → task → agent work → owner review → result history', today: 'Today', completed: 'completed', prepared: 'results ready', decisions: 'decision pending', employees: 'My team members', employeesHint: 'Choose a team member to see the task and next action.', overview: 'Overview', history: 'History', scenario: 'Scenario', settings: 'Settings', sources: 'Sources', input: 'What it receives', schedule: 'Work mode', result: 'Latest result', safety: 'External publishing and sending only happen after your approval.', run: 'Run an example', running: 'The agent is preparing a result…', review: 'Review and approve', approved: 'The result was approved and saved to history.', resultTitle: 'Draft prepared', resultBody: 'Four unanswered reviews were found and personal reply drafts were prepared.', approvalTitle: 'You keep the final decision', approvalBody: 'The agent never publishes replies without a manual review.', historyTitle: 'History keeps the facts', historyBody: 'See when a task ran, what it prepared, and who approved it.', cards: [{ name: 'Reputation agent', job: 'Finds unanswered reviews and prepares reply drafts.', status: 'Waiting for a decision', sources: 'Maps and reviews', schedule: 'Every morning' }, { name: 'Content agent', job: 'Turns audience signals into publication ideas.', status: 'Working', sources: 'Social networks and news', schedule: 'On schedule' }, { name: 'Telegram radar', job: 'Highlights important messages and topics.', status: 'Task completed', sources: 'Telegram', schedule: 'Every 3 hours' }] },
  fr: { eyebrow: 'COLLABORATEURS NUMÉRIQUES', title: 'Agents', description: 'Les signaux des cartes, avis, réseaux sociaux et actualités deviennent des tâches claires. Les agents traitent la partie répétitive et le propriétaire décide.', flow: 'Signal → tâche → travail de l’agent → validation → historique', today: 'Aujourd’hui', completed: 'terminées', prepared: 'résultats prêts', decisions: 'décision en attente', employees: 'Mes collaborateurs', employeesHint: 'Choisissez un collaborateur pour voir sa mission et l’action suivante.', overview: 'Aperçu', history: 'Historique', scenario: 'Scénario', settings: 'Paramètres', sources: 'Sources', input: 'Données reçues', schedule: 'Mode de travail', result: 'Dernier résultat', safety: 'Toute publication ou tout envoi externe exige votre validation.', run: 'Lancer un exemple', running: 'L’agent prépare le résultat…', review: 'Vérifier et approuver', approved: 'Le résultat a été approuvé et ajouté à l’historique.', resultTitle: 'Brouillon préparé', resultBody: 'Quatre avis sans réponse ont été trouvés et des réponses personnalisées ont été préparées.', approvalTitle: 'Vous gardez la décision finale', approvalBody: 'L’agent ne publie jamais de réponse sans validation manuelle.', historyTitle: 'L’historique conserve les faits', historyBody: 'Voyez quand la tâche a été exécutée, le résultat produit et la personne qui l’a approuvé.', cards: [{ name: 'Agent de réputation', job: 'Repère les avis sans réponse et prépare des brouillons.', status: 'En attente de décision', sources: 'Cartes et avis', schedule: 'Chaque matin' }, { name: 'Agent de contenu', job: 'Transforme les signaux du public en idées de publication.', status: 'En cours', sources: 'Réseaux sociaux et actualités', schedule: 'Selon le calendrier' }, { name: 'Radar Telegram', job: 'Met en évidence les messages et sujets importants.', status: 'Tâche terminée', sources: 'Telegram', schedule: 'Toutes les 3 heures' }] },
  es: { eyebrow: 'COLABORADORES DIGITALES', title: 'Agentes', description: 'Las señales de mapas, reseñas, redes sociales y noticias se convierten en tareas claras. Los agentes hacen la parte repetitiva y el propietario decide.', flow: 'Señal → tarea → trabajo del agente → revisión → historial', today: 'Hoy', completed: 'completadas', prepared: 'resultados listos', decisions: 'decisión pendiente', employees: 'Mis colaboradores', employeesHint: 'Elige un colaborador para ver su tarea y siguiente acción.', overview: 'Resumen', history: 'Historial', scenario: 'Escenario', settings: 'Ajustes', sources: 'Fuentes', input: 'Qué recibe', schedule: 'Modo de trabajo', result: 'Último resultado', safety: 'Las publicaciones y envíos externos solo ocurren tras tu aprobación.', run: 'Ejecutar ejemplo', running: 'El agente está preparando el resultado…', review: 'Revisar y aprobar', approved: 'El resultado fue aprobado y guardado en el historial.', resultTitle: 'Borrador preparado', resultBody: 'Se encontraron cuatro reseñas sin respuesta y se prepararon borradores personalizados.', approvalTitle: 'Tú tomas la decisión final', approvalBody: 'El agente nunca publica respuestas sin revisión manual.', historyTitle: 'El historial conserva los hechos', historyBody: 'Consulta cuándo se ejecutó la tarea, qué preparó y quién lo aprobó.', cards: [{ name: 'Agente de reputación', job: 'Encuentra reseñas sin respuesta y prepara borradores.', status: 'Espera una decisión', sources: 'Mapas y reseñas', schedule: 'Cada mañana' }, { name: 'Agente de contenido', job: 'Convierte señales del público en ideas de publicación.', status: 'Trabajando', sources: 'Redes sociales y noticias', schedule: 'Según calendario' }, { name: 'Radar de Telegram', job: 'Destaca mensajes y temas importantes.', status: 'Tarea completada', sources: 'Telegram', schedule: 'Cada 3 horas' }] },
  el: { eyebrow: 'ΨΗΦΙΑΚΟΙ ΣΥΝΕΡΓΑΤΕΣ', title: 'Πράκτορες', description: 'Τα σήματα από χάρτες, κριτικές, κοινωνικά δίκτυα και νέα γίνονται σαφείς εργασίες. Οι πράκτορες εκτελούν το επαναλαμβανόμενο μέρος και ο ιδιοκτήτης αποφασίζει.', flow: 'Σήμα → εργασία → πράκτορας → έλεγχος → ιστορικό', today: 'Σήμερα', completed: 'ολοκληρώθηκαν', prepared: 'αποτελέσματα έτοιμα', decisions: 'απόφαση σε αναμονή', employees: 'Οι συνεργάτες μου', employeesHint: 'Επιλέξτε συνεργάτη για να δείτε την εργασία και το επόμενο βήμα.', overview: 'Επισκόπηση', history: 'Ιστορικό', scenario: 'Σενάριο', settings: 'Ρυθμίσεις', sources: 'Πηγές', input: 'Τι λαμβάνει', schedule: 'Τρόπος εργασίας', result: 'Τελευταίο αποτέλεσμα', safety: 'Εξωτερικές δημοσιεύσεις και αποστολές μόνο μετά την έγκρισή σας.', run: 'Εκτέλεση παραδείγματος', running: 'Ο πράκτορας ετοιμάζει το αποτέλεσμα…', review: 'Έλεγχος και έγκριση', approved: 'Το αποτέλεσμα εγκρίθηκε και αποθηκεύτηκε στο ιστορικό.', resultTitle: 'Έτοιμο προσχέδιο', resultBody: 'Βρέθηκαν τέσσερις κριτικές χωρίς απάντηση και ετοιμάστηκαν προσωπικά προσχέδια.', approvalTitle: 'Η τελική απόφαση είναι δική σας', approvalBody: 'Ο πράκτορας δεν δημοσιεύει απαντήσεις χωρίς χειροκίνητο έλεγχο.', historyTitle: 'Το ιστορικό διατηρεί τα γεγονότα', historyBody: 'Δείτε πότε εκτελέστηκε η εργασία, τι ετοίμασε και ποιος την ενέκρινε.', cards: [{ name: 'Πράκτορας φήμης', job: 'Βρίσκει κριτικές χωρίς απάντηση και ετοιμάζει προσχέδια.', status: 'Αναμονή απόφασης', sources: 'Χάρτες και κριτικές', schedule: 'Κάθε πρωί' }, { name: 'Πράκτορας περιεχομένου', job: 'Μετατρέπει σήματα κοινού σε ιδέες δημοσίευσης.', status: 'Εργάζεται', sources: 'Κοινωνικά δίκτυα και νέα', schedule: 'Σύμφωνα με το πρόγραμμα' }, { name: 'Ραντάρ Telegram', job: 'Επισημαίνει σημαντικά μηνύματα και θέματα.', status: 'Η εργασία ολοκληρώθηκε', sources: 'Telegram', schedule: 'Κάθε 3 ώρες' }] },
  de: { eyebrow: 'DIGITALE MITARBEITENDE', title: 'Agenten', description: 'Signale aus Karten, Bewertungen, sozialen Netzwerken und Nachrichten werden zu klaren Aufgaben. Agenten erledigen den wiederkehrenden Teil, die Entscheidung bleibt beim Inhaber.', flow: 'Signal → Aufgabe → Agentenarbeit → Prüfung → Verlauf', today: 'Heute', completed: 'erledigt', prepared: 'Ergebnisse bereit', decisions: 'Entscheidung offen', employees: 'Meine Mitarbeitenden', employeesHint: 'Wählen Sie einen Mitarbeitenden, um Aufgabe und nächsten Schritt zu sehen.', overview: 'Übersicht', history: 'Verlauf', scenario: 'Szenario', settings: 'Einstellungen', sources: 'Quellen', input: 'Eingaben', schedule: 'Arbeitsweise', result: 'Letztes Ergebnis', safety: 'Externe Veröffentlichungen und Sendungen erfolgen nur nach Ihrer Freigabe.', run: 'Beispiel starten', running: 'Der Agent bereitet ein Ergebnis vor…', review: 'Prüfen und freigeben', approved: 'Das Ergebnis wurde freigegeben und im Verlauf gespeichert.', resultTitle: 'Entwurf vorbereitet', resultBody: 'Vier unbeantwortete Bewertungen wurden gefunden und persönliche Antwortentwürfe vorbereitet.', approvalTitle: 'Sie treffen die letzte Entscheidung', approvalBody: 'Der Agent veröffentlicht keine Antworten ohne manuelle Prüfung.', historyTitle: 'Der Verlauf bewahrt die Fakten', historyBody: 'Sehen Sie Zeitpunkt, Ergebnis und Freigabe jeder Aufgabe.', cards: [{ name: 'Reputationsagent', job: 'Findet unbeantwortete Bewertungen und erstellt Entwürfe.', status: 'Wartet auf Entscheidung', sources: 'Karten und Bewertungen', schedule: 'Jeden Morgen' }, { name: 'Content-Agent', job: 'Macht aus Zielgruppensignalen Publikationsideen.', status: 'Arbeitet', sources: 'Soziale Netzwerke und Nachrichten', schedule: 'Nach Zeitplan' }, { name: 'Telegram-Radar', job: 'Hebt wichtige Nachrichten und Themen hervor.', status: 'Aufgabe erledigt', sources: 'Telegram', schedule: 'Alle 3 Stunden' }] },
  tr: { eyebrow: 'DİJİTAL ÇALIŞANLAR', title: 'Ajanlar', description: 'Haritalar, yorumlar, sosyal ağlar ve haberlerden gelen sinyaller net görevlere dönüşür. Ajanlar tekrarlanan kısmı yapar, karar işletme sahibinde kalır.', flow: 'Sinyal → görev → ajan çalışması → sahip kontrolü → sonuç geçmişi', today: 'Bugün', completed: 'tamamlandı', prepared: 'sonuç hazır', decisions: 'karar bekliyor', employees: 'Çalışanlarım', employeesHint: 'Görevi ve sonraki adımı görmek için bir çalışan seçin.', overview: 'Genel bakış', history: 'Geçmiş', scenario: 'Senaryo', settings: 'Ayarlar', sources: 'Kaynaklar', input: 'Aldığı veriler', schedule: 'Çalışma modu', result: 'Son sonuç', safety: 'Haricî yayın ve gönderimler yalnızca onayınızdan sonra yapılır.', run: 'Örnek çalıştır', running: 'Ajan sonucu hazırlıyor…', review: 'İncele ve onayla', approved: 'Sonuç onaylandı ve geçmişe kaydedildi.', resultTitle: 'Taslak hazırlandı', resultBody: 'Dört yanıtsız yorum bulundu ve kişisel yanıt taslakları hazırlandı.', approvalTitle: 'Son karar sizde', approvalBody: 'Ajan, elle kontrol olmadan yanıt yayınlamaz.', historyTitle: 'Geçmiş gerçekleri saklar', historyBody: 'Görevin ne zaman yapıldığını, ne hazırlandığını ve kimin onayladığını görün.', cards: [{ name: 'İtibar ajanı', job: 'Yanıtsız yorumları bulur ve yanıt taslağı hazırlar.', status: 'Karar bekliyor', sources: 'Haritalar ve yorumlar', schedule: 'Her sabah' }, { name: 'İçerik ajanı', job: 'Kitle sinyallerini yayın fikirlerine dönüştürür.', status: 'Çalışıyor', sources: 'Sosyal ağlar ve haberler', schedule: 'Programa göre' }, { name: 'Telegram radarı', job: 'Önemli mesaj ve konuları vurgular.', status: 'Görev tamamlandı', sources: 'Telegram', schedule: 'Her 3 saatte' }] },
  th: { eyebrow: 'พนักงานดิจิทัล', title: 'เอเจนต์', description: 'สัญญาณจากแผนที่ รีวิว โซเชียลและข่าวกลายเป็นงานที่ชัดเจน เอเจนต์ทำงานซ้ำ ส่วนเจ้าของเป็นผู้ตัดสินใจ', flow: 'สัญญาณ → งาน → เอเจนต์ → เจ้าของตรวจ → ประวัติ', today: 'วันนี้', completed: 'เสร็จ', prepared: 'ผลลัพธ์พร้อม', decisions: 'รอตัดสินใจ', employees: 'พนักงานของฉัน', employeesHint: 'เลือกพนักงานเพื่อดูงานและขั้นต่อไป', overview: 'ภาพรวม', history: 'ประวัติ', scenario: 'สถานการณ์', settings: 'ตั้งค่า', sources: 'แหล่งข้อมูล', input: 'ข้อมูลที่ได้รับ', schedule: 'โหมดทำงาน', result: 'ผลลัพธ์ล่าสุด', safety: 'การเผยแพร่และส่งออกต้องได้รับอนุมัติจากคุณ', run: 'รันตัวอย่าง', running: 'เอเจนต์กำลังเตรียมผลลัพธ์…', review: 'ตรวจและอนุมัติ', approved: 'อนุมัติและบันทึกผลลัพธ์แล้ว', resultTitle: 'เตรียมร่างแล้ว', resultBody: 'พบรีวิวที่ไม่มีคำตอบ 4 รีวิวและเตรียมร่างส่วนบุคคล', approvalTitle: 'คุณเป็นผู้ตัดสินใจสุดท้าย', approvalBody: 'เอเจนต์ไม่เผยแพร่โดยไม่ผ่านการตรวจด้วยตนเอง', historyTitle: 'ประวัติเก็บข้อเท็จจริง', historyBody: 'ดูเวลา ผลลัพธ์ และผู้อนุมัติของแต่ละงาน', cards: [{ name: 'เอเจนต์ชื่อเสียง', job: 'ค้นหารีวิวที่ไม่มีคำตอบและเตรียมร่าง', status: 'รอการตัดสินใจ', sources: 'แผนที่และรีวิว', schedule: 'ทุกเช้า' }, { name: 'เอเจนต์เนื้อหา', job: 'เปลี่ยนสัญญาณผู้ชมเป็นไอเดียโพสต์', status: 'กำลังทำงาน', sources: 'โซเชียลและข่าว', schedule: 'ตามกำหนดการ' }, { name: 'เรดาร์ Telegram', job: 'เน้นข้อความและหัวข้อสำคัญ', status: 'งานเสร็จ', sources: 'Telegram', schedule: 'ทุก 3 ชั่วโมง' }] },
  ar: { eyebrow: 'موظفون رقميون', title: 'الوكلاء', description: 'تتحول إشارات الخرائط والمراجعات والشبكات الاجتماعية والأخبار إلى مهام واضحة. ينفذ الوكلاء العمل المتكرر ويتخذ المالك القرار.', flow: 'إشارة → مهمة → عمل الوكيل → مراجعة المالك → السجل', today: 'اليوم', completed: 'مكتملة', prepared: 'نتائج جاهزة', decisions: 'قرار معلق', employees: 'موظفي', employeesHint: 'اختر موظفًا لرؤية مهمته والخطوة التالية.', overview: 'نظرة عامة', history: 'السجل', scenario: 'السيناريو', settings: 'الإعدادات', sources: 'المصادر', input: 'ما يستلمه', schedule: 'نمط العمل', result: 'آخر نتيجة', safety: 'لا يتم النشر أو الإرسال الخارجي إلا بعد موافقتك.', run: 'تشغيل مثال', running: 'يحضّر الوكيل النتيجة…', review: 'مراجعة وموافقة', approved: 'تمت الموافقة على النتيجة وحفظها في السجل.', resultTitle: 'تم إعداد المسودة', resultBody: 'تم العثور على أربع مراجعات بلا رد وإعداد مسودات شخصية.', approvalTitle: 'القرار النهائي لك', approvalBody: 'لا ينشر الوكيل الردود بدون مراجعة يدوية.', historyTitle: 'السجل يحفظ الحقائق', historyBody: 'شاهد وقت التنفيذ والنتيجة ومن وافق عليها.', cards: [{ name: 'وكيل السمعة', job: 'يجد المراجعات بلا رد ويعد المسودات.', status: 'ينتظر قرارًا', sources: 'الخرائط والمراجعات', schedule: 'كل صباح' }, { name: 'وكيل المحتوى', job: 'يحول إشارات الجمهور إلى أفكار نشر.', status: 'يعمل', sources: 'الشبكات والأخبار', schedule: 'حسب الجدول' }, { name: 'رادار Telegram', job: 'يبرز الرسائل والموضوعات المهمة.', status: 'اكتملت المهمة', sources: 'Telegram', schedule: 'كل 3 ساعات' }] },
  ha: { eyebrow: 'MA’AIKATAN DIJITAL', title: 'Wakilai', description: 'Alamomi daga taswira, bita, kafafen sada zumunta da labarai suna zama ayyuka masu haske. Wakilai suna yin aikin maimaitawa, mai kasuwanci yana yanke hukunci.', flow: 'Alama → aiki → wakili → dubawar mai kasuwanci → tarihi', today: 'Yau', completed: 'an gama', prepared: 'sakamako a shirye', decisions: 'hukunci yana jira', employees: 'Ma’aikatana', employeesHint: 'Zaɓi ma’aikaci don ganin aikinsa da mataki na gaba.', overview: 'Bayani', history: 'Tarihi', scenario: 'Tsari', settings: 'Saituna', sources: 'Tushe', input: 'Abin da yake karɓa', schedule: 'Yanayin aiki', result: 'Sakamako na ƙarshe', safety: 'Bugawa da aika saƙo a waje sai bayan amincewarka.', run: 'Gudanar da misali', running: 'Wakili yana shirya sakamako…', review: 'Duba ka amince', approved: 'An amince da sakamakon kuma an ajiye shi a tarihi.', resultTitle: 'An shirya daftari', resultBody: 'An sami bita huɗu marasa amsa kuma an shirya daftarin amsa.', approvalTitle: 'Hukunci na ƙarshe naka ne', approvalBody: 'Wakili ba ya wallafa amsa ba tare da dubawar hannu ba.', historyTitle: 'Tarihi yana riƙe gaskiya', historyBody: 'Duba lokacin aiki, abin da aka shirya da wanda ya amince.', cards: [{ name: 'Wakilin suna', job: 'Yana nemo bita marasa amsa ya shirya daftari.', status: 'Yana jiran hukunci', sources: 'Taswira da bita', schedule: 'Kowace safiya' }, { name: 'Wakilin abun ciki', job: 'Yana juya alamomin masu sauraro zuwa ra’ayoyin wallafa.', status: 'Yana aiki', sources: 'Kafafen sada zumunta da labarai', schedule: 'Bisa jadawali' }, { name: 'Radar na Telegram', job: 'Yana nuna muhimman saƙonni da jigogi.', status: 'An gama aiki', sources: 'Telegram', schedule: 'Kowane awa 3' }] },
};

export function DemoAgentsPage() {
  const { language } = useLanguage();
  const t = copy[language];
  const [selected, setSelected] = useState(0);
  const [stage, setStage] = useState<'idle' | 'running' | 'review' | 'approved'>('idle');
  const agent = t.cards[selected];
  const tabs = useMemo(() => [t.overview, t.history, t.scenario, t.settings], [t]);

  const run = () => {
    setStage('running');
    window.setTimeout(() => setStage('review'), 650);
  };

  return <div className="space-y-5 pb-16" data-tour-target="agents-workspace">
    <section className="rounded-2xl bg-gradient-to-br from-orange-50 to-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(249,115,22,0.16)]">
      <div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-white"><Bot className="h-6 w-6" /></div><div><div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">{t.eyebrow}</div><h1 className="mt-1 text-balance text-3xl font-semibold text-slate-950">{t.title}</h1><p className="mt-2 max-w-4xl text-pretty text-sm leading-6 text-slate-600">{t.description}</p></div></div>
      <div className="mt-4 rounded-xl bg-white/80 px-4 py-3 text-sm font-semibold text-slate-700 shadow-[inset_0_0_0_1px_rgba(15,23,42,0.07)]">{t.flow}</div>
    </section>
    <section data-tour-target="agents-today" className="rounded-2xl bg-white px-5 py-4 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><strong className="text-slate-950">{t.today}</strong><span><b className="tabular-nums text-slate-950">7</b> {t.completed}</span><span><b className="tabular-nums text-slate-950">3</b> {t.prepared}</span><span className="text-amber-800"><b className="tabular-nums">1</b> {t.decisions}</span></div></section>
    <div className="grid gap-5 lg:grid-cols-[22rem_minmax(0,1fr)]">
      <section data-tour-target="agents-employees" className="rounded-2xl bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><h2 className="text-balance text-lg font-semibold text-slate-950">{t.employees}</h2><p className="mt-1 text-pretty text-sm text-slate-500">{t.employeesHint}</p><div className="mt-4 space-y-2">{t.cards.map((card, index) => <button key={card.name} type="button" onClick={() => { setSelected(index); setStage('idle'); }} className={cn('min-h-20 w-full rounded-xl px-3 py-3 text-start transition-[background-color,box-shadow,scale] active:scale-[0.96]', selected === index ? 'bg-orange-50 shadow-[inset_0_0_0_1px_rgba(249,115,22,0.35)]' : 'bg-slate-50 hover:bg-slate-100')}><span className="block text-sm font-semibold text-slate-950">{card.name}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{card.job}</span><span className="mt-2 inline-flex rounded-full bg-white px-2 py-1 text-[11px] font-semibold text-slate-700">{card.status}</span></button>)}</div></section>
      <main data-tour-target="agents-control" className="min-w-0 space-y-4">
        <nav className="flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1" aria-label={t.title}>{tabs.map((tab, index) => <button key={tab} type="button" className={cn('min-h-10 shrink-0 rounded-lg px-4 text-sm font-semibold transition-[background-color,color,scale] active:scale-[0.96]', index === 0 ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-600')}>{tab}</button>)}</nav>
        <section className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-balance text-xl font-semibold text-slate-950">{agent.name}</h2><p className="mt-1 text-pretty text-sm leading-6 text-slate-600">{agent.job}</p></div><span className="inline-flex w-fit rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800">{agent.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info icon={<MapPinned />} label={t.input} value={agent.sources} /><Info icon={<Clock3 />} label={t.schedule} value={agent.schedule} /></div></section>
        <section data-tour-target="agents-run" className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><div className="flex items-start gap-3"><Play className="mt-0.5 h-5 w-5 text-orange-600" /><div className="flex-1"><h3 className="font-semibold text-slate-950">{t.result}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{stage === 'running' ? t.running : t.resultBody}</p><Button type="button" onClick={run} disabled={stage === 'running'} className="mt-4 min-h-10 transition-transform active:scale-[0.96]">{t.run}</Button></div></div></section>
        <section data-tour-target="agents-review" className="rounded-2xl bg-amber-50 p-5 shadow-[inset_0_0_0_1px_rgba(245,158,11,0.25)]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-amber-700" /><div className="flex-1"><h3 className="font-semibold text-slate-950">{t.approvalTitle}</h3><p className="mt-1 text-sm leading-6 text-slate-700">{stage === 'approved' ? t.approved : t.approvalBody}</p>{stage === 'review' ? <Button type="button" onClick={() => setStage('approved')} className="mt-4 min-h-10 transition-transform active:scale-[0.96]">{t.review}</Button> : null}</div></div></section>
        <section data-tour-target="agents-history" className="rounded-2xl bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.06),0_0_0_1px_rgba(15,23,42,0.08)]"><div className="flex items-start gap-3"><FileCheck2 className="mt-0.5 h-5 w-5 text-emerald-600" /><div><h3 className="font-semibold text-slate-950">{t.historyTitle}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{t.historyBody}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-medium text-slate-600"><span className="rounded-full bg-slate-100 px-3 py-1.5"><CheckCircle2 className="me-1 inline h-3.5 w-3.5 text-emerald-600" />{t.resultTitle}</span><span className="rounded-full bg-slate-100 px-3 py-1.5"><Newspaper className="me-1 inline h-3.5 w-3.5" />4</span><span className="rounded-full bg-slate-100 px-3 py-1.5"><MessageCircle className="me-1 inline h-3.5 w-3.5" />{t.sources}</span></div></div></div></section>
      </main>
    </div>
  </div>;
}

function Info({ icon, label, value }: { icon: ReactNode; label: string; value: string }) {
  return <div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{label}</div><div className="mt-2 text-sm font-medium text-slate-900">{value}</div></div>;
}
