export type PublicAuditLanguage = 'ru' | 'en' | 'fr' | 'es' | 'el' | 'de' | 'th' | 'ar' | 'ha' | 'tr' | 'hy';

export const supportedPublicAuditLanguages: PublicAuditLanguage[] = ['ru', 'en', 'fr', 'es', 'el', 'de', 'th', 'ar', 'ha', 'tr', 'hy'];

const publicAuditCopy = {
  ru: {
    auditScore: 'Оценка',
    auditFixYourself: 'Исправить самостоятельно',
    auditPrepareWithLocalOS: 'Подготовить исправления с LocalOS',
    auditFixToday: 'Что исправить сегодня',
    auditFixTodayHint: 'Начните с этих точек: они сильнее всего влияют на понятность и доверие.',
    auditWhyImportant: 'Почему важно',
    auditActions: 'Что сделать',
    auditDetails: 'Подробнее',
    auditHideDetails: 'Скрыть детали',
    auditStrengths: 'Что уже хорошо',
    auditNoStrengths: 'Пока нет достаточно данных, чтобы подтвердить сильные стороны.',
    auditCustomerUnderstanding: 'Как клиент понимает карточку',
    auditStrongAnswers: 'Хорошо отвечает',
    auditWeakAnswers: 'Не хватает информации',
    auditMissingPhotos: 'Какие фото добавить',
    auditNeedPhoto: 'Нужно добавить',
    auditCardData: 'Что видно в карточке',
    auditShowMore: 'Показать ещё',
    auditShowLess: 'Скрыть',
    auditNoReply: 'Ответа нет',
    auditHasReply: 'Есть ответ',
    auditShowFull: 'Показать полностью',
    auditHideFull: 'Свернуть',
    auditFullPlan: 'Полный план и методика',
    auditFullPlanHint: 'Дополнительные проблемы, план на 7 дней, сравнение карт и источники.',
    auditHidePlan: 'Скрыть полный план',
  },
  en: {
    auditScore: 'Score',
    auditFixYourself: 'Fix it yourself',
    auditPrepareWithLocalOS: 'Prepare improvements with LocalOS',
    auditFixToday: 'What to fix today',
    auditFixTodayHint: 'Start with these priorities: they have the strongest effect on clarity and trust.',
    auditWhyImportant: 'Why it matters',
    auditActions: 'What to do',
    auditDetails: 'Details',
    auditHideDetails: 'Hide details',
    auditStrengths: 'What is already working well',
    auditNoStrengths: 'There is not enough verified data yet to confirm strong points.',
    auditCustomerUnderstanding: 'How customers understand the listing',
    auditStrongAnswers: 'Answers well',
    auditWeakAnswers: 'Missing information',
    auditMissingPhotos: 'Photos to add',
    auditNeedPhoto: 'Needs a photo',
    auditCardData: 'What customers can see',
    auditShowMore: 'Show more',
    auditShowLess: 'Show less',
    auditNoReply: 'No reply',
    auditHasReply: 'Reply present',
    auditShowFull: 'Show full text',
    auditHideFull: 'Collapse',
    auditFullPlan: 'Full plan and methodology',
    auditFullPlanHint: 'Additional issues, the 7-day plan, listing comparison, and sources.',
    auditHidePlan: 'Hide full plan',
  },

  hy: {
    auditScore: "Միավոր",
    auditFixYourself: "Ինքներդ շտկեք",
    auditPrepareWithLocalOS: "Պատրաստեք բարելավումներ LocalOS-ի հետ",
    auditFixToday: "Ինչ շտկել այսօր",
    auditFixTodayHint: "Սկսեք այս առաջնահերթություններից. դրանք ամենաուժեղ ազդեցությունն ունեն հստակության և վստահության վրա:",
    auditWhyImportant: "Ինչու է դա կարևոր",
    auditActions: "Ինչ անել",
    auditDetails: "Մանրամասներ",
    auditHideDetails: "Թաքցնել մանրամասները",
    auditStrengths: "Ինչն արդեն լավ է աշխատում",
    auditNoStrengths: "Առայժմ բավարար ստուգված տվյալներ չկան ուժեղ կողմերը հաստատելու համար:",
    auditCustomerUnderstanding: "Ինչպես են հաճախորդները հասկանում ցուցակը",
    auditStrongAnswers: "Լավ է պատասխանում",
    auditWeakAnswers: "Տեղեկություններ բացակայում են",
    auditMissingPhotos: "Լուսանկարներ ավելացնելու համար",
    auditNeedPhoto: "Պահանջվում է լուսանկար",
    auditCardData: "Ինչ կարող են տեսնել հաճախորդները",
    auditShowMore: "Ցույց տալ ավելին",
    auditShowLess: "Ցույց տալ ավելի քիչ",
    auditNoReply: "Ոչ մի պատասխան",
    auditHasReply: "Պատասխանել ներկա",
    auditShowFull: "Ցույց տալ ամբողջական տեքստը",
    auditHideFull: "Փլուզում",
    auditFullPlan: "Ամբողջական պլան և մեթոդաբանություն",
    auditFullPlanHint: "Լրացուցիչ խնդիրներ, 7-օրյա պլան, ցուցակման համեմատություն և աղբյուրներ:",
    auditHidePlan: "Թաքցնել ամբողջական պլանը",
  },};

export const publicAuditUiTextForLanguage = (lang: PublicAuditLanguage) => (
  lang === 'ru' ? publicAuditCopy.ru : lang === 'hy' ? publicAuditCopy.hy : publicAuditCopy.en
);
