import type { Language } from "@/i18n/LanguageContext";

export type AboutStoryCopy = {
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  intro: string;
  workdayValue: string;
  workdayText: string;
  workdayNote: string;
  storyEyebrow: string;
  storyTitle: string;
  storyIntro: string;
  chapterOneTitle: string;
  chapterOneText: string;
  chapterTwoTitle: string;
  chapterTwoText: string;
  chapterThreeTitle: string;
  chapterThreeText: string;
  industries: string[];
  channelEyebrow: string;
  channelTitle: string;
  channelText: string;
  channelButton: string;
  popular: string;
};

export const aboutStoryCopy: Record<Language, AboutStoryCopy> = {
  ru: {
    metaTitle: "О команде LocalOS — 15 лет автоматизации бизнеса",
    metaDescription: "История команды LocalOS: 15 лет в бизнесе и автоматизации транспорта, ритейла, производства, логистики и услуг.",
    eyebrow: "Команда LocalOS",
    title: "Мы начинали бизнес, чтобы стать свободнее",
    intro: "Но по мере роста свободы становилось меньше. Утром — цифры и сотрудники. Днём — клиенты и срочные вопросы. Вечером — то, что не успели. Выключить телефон или уехать на неделю казалось рискованным.",
    workdayValue: "14 часов",
    workdayText: "может длиться день владельца, когда всё важное проходит через него",
    workdayNote: "Нам знаком этот режим изнутри.",
    storyEyebrow: "Почему мы сделали LocalOS",
    storyTitle: "15 лет в бизнесе и автоматизации",
    storyIntro: "Мы работали в транспорте, ритейле, производстве, логистике и услугах.",
    chapterOneTitle: "Мы знаем эту проблему изнутри",
    chapterOneText: "15 лет мы строили и автоматизировали бизнес в транспорте, ритейле, производстве, логистике и услугах. Работали и с небольшими компаниями, и с крупными предприятиями. Один из транспортных проектов вырос с нуля до работы в 40 странах. Для крупной компании мы внедрили схему, которая экономила несколько миллионов долларов в год.\n\nНо по мере роста собственных проектов каждый из нас столкнулся с одной и той же проблемой: всё больше работы возвращалось к владельцу. Клиенты, сотрудники, цифры, срочные вопросы. Проще было сделать самому, чем объяснить, передать и потом проверить.",
    chapterTwoTitle: "Сначала мы решили эту проблему для себя",
    chapterTwoText: "Научились собирать удалённые команды, описывать процессы и автоматизировать повторяющуюся работу. За 15 лет мы не раз встречали одни и те же задачи в компаниях разных отраслей — и находили способы их решать. Этот опыт лёг в основу LocalOS.",
    chapterThreeTitle: "Так появился LocalOS",
    chapterThreeText: "Мы превратили накопленные решения в готовые цифровые сценарии. Теперь предприниматель может использовать опыт многих компаний, не проходя весь путь самостоятельно. ИИ помогает описать задачу и подготовить сценарий, владелец утверждает правила, а повторяющуюся работу выполняет скрипт.",
    industries: ["Транспорт", "Ритейл", "Производство", "Логистика", "Услуги"],
    channelEyebrow: "Дневник команды",
    channelTitle: "Покупай мою шаверму",
    channelText: "Пишем о реальном предпринимательстве: выгорании, операционке, учёте, автоматизации и идеях, из которых растёт LocalOS. Показываем рабочие заметки, ошибки и выводы.",
    channelButton: "Читать в Telegram",
    popular: "Популярный",
  },
  en: {
    metaTitle: "About the LocalOS team — 15 years of business automation",
    metaDescription: "The LocalOS team story: 15 years in business and automation across transport, retail, manufacturing, logistics, and services.",
    eyebrow: "The LocalOS team",
    title: "We started businesses to gain more freedom",
    intro: "Growth brought the opposite. Mornings were for numbers and staff, days for customers and urgent issues, evenings for everything left unfinished. Switching off the phone or leaving for a week felt risky.",
    workdayValue: "14 hours",
    workdayText: "is how long an owner's day can last when every important task comes back to them",
    workdayNote: "We know this routine from the inside.",
    storyEyebrow: "Why we built LocalOS",
    storyTitle: "15 years in business and automation",
    storyIntro: "We worked across transport, retail, manufacturing, logistics, and services.",
    chapterOneTitle: "We know this problem from the inside",
    chapterOneText: "For 15 years, we built and automated businesses in transport, retail, manufacturing, logistics, and services. We worked with both small companies and large enterprises. One transport project grew from zero to operating in 40 countries. For a large company, we implemented a model that saved several million dollars a year.\n\nBut as our own projects grew, each of us ran into the same problem: more work kept coming back to the owner. Customers, staff, numbers, urgent issues. Doing it ourselves felt easier than explaining, delegating, and checking.",
    chapterTwoTitle: "First, we solved the problem for ourselves",
    chapterTwoText: "We learned how to build remote teams, document processes, and automate recurring work. Over 15 years, we encountered the same tasks across companies in different industries and found ways to solve them. That experience became the foundation for LocalOS.",
    chapterThreeTitle: "That is how LocalOS began",
    chapterThreeText: "We turned the solutions we had accumulated into ready-to-use digital procedures. An owner can now benefit from the experience of many companies without having to repeat the entire journey. AI helps define the task and prepare the procedure, the owner approves the rules, and a script performs the recurring work.",
    industries: ["Transport", "Retail", "Manufacturing", "Logistics", "Services"],
    channelEyebrow: "Team journal",
    channelTitle: "Покупай мою шаверму",
    channelText: "We write about entrepreneurship as it is: burnout, operations, accounting, automation, and the ideas behind LocalOS. Expect working notes, mistakes, and conclusions.",
    channelButton: "Read on Telegram",
    popular: "Popular",
  },
  fr: {
    metaTitle: "L’équipe LocalOS — 15 ans d’automatisation d’entreprise",
    metaDescription: "L’histoire de l’équipe LocalOS : 15 ans d’expérience dans le transport, le commerce, la production, la logistique et les services.",
    eyebrow: "L’équipe LocalOS",
    title: "Nous avons créé nos entreprises pour gagner en liberté",
    intro: "Mais avec la croissance, cette liberté diminuait. Le matin, les chiffres et l’équipe. La journée, les clients et les urgences. Le soir, tout ce qui restait à faire. Éteindre le téléphone ou partir une semaine semblait risqué.",
    workdayValue: "14 heures",
    workdayText: "peut durer la journée d’un dirigeant lorsque chaque sujet important revient jusqu’à lui",
    workdayNote: "Nous avons vécu ce rythme de l’intérieur.",
    storyEyebrow: "Pourquoi nous avons créé LocalOS",
    storyTitle: "15 ans dans l’entreprise et l’automatisation",
    storyIntro: "Nous avons travaillé dans le transport, le commerce, la production, la logistique et les services.",
    chapterOneTitle: "Nous connaissons ce problème de l’intérieur",
    chapterOneText: "Pendant 15 ans, nous avons créé et automatisé des entreprises dans le transport, le commerce, la production, la logistique et les services. Nous avons travaillé avec de petites structures comme avec de grands groupes. L’un de nos projets de transport est passé de zéro à une activité dans 40 pays. Pour une grande entreprise, nous avons mis en place un modèle qui économisait plusieurs millions de dollars par an.\n\nMais à mesure que nos projets grandissaient, le même problème revenait : de plus en plus de travail remontait jusqu’au dirigeant. Clients, équipe, chiffres, urgences. Il paraissait plus simple de faire soi-même que d’expliquer, déléguer puis contrôler.",
    chapterTwoTitle: "Nous avons d’abord résolu le problème pour nous-mêmes",
    chapterTwoText: "Nous avons appris à construire des équipes à distance, à décrire les processus et à automatiser le travail récurrent. En 15 ans, nous avons retrouvé les mêmes tâches dans des entreprises de secteurs différents et développé des méthodes pour les traiter. Cette expérience est devenue la base de LocalOS.",
    chapterThreeTitle: "C’est ainsi qu’est né LocalOS",
    chapterThreeText: "Nous avons transformé les solutions accumulées en procédures numériques prêtes à l’emploi. Un dirigeant peut profiter de l’expérience de nombreuses entreprises sans refaire tout le chemin. L’IA aide à décrire la tâche et prépare le scénario, le dirigeant valide les règles, puis un script exécute le travail récurrent.",
    industries: ["Transport", "Commerce", "Production", "Logistique", "Services"],
    channelEyebrow: "Journal de l’équipe",
    channelTitle: "Покупай мою шаверму",
    channelText: "Nous parlons de l’entrepreneuriat réel : épuisement, opérations, gestion, automatisation et idées à l’origine de LocalOS. Nous partageons nos notes de travail, nos erreurs et nos conclusions.",
    channelButton: "Lire sur Telegram",
    popular: "Populaire",
  },
  es: {
    metaTitle: "El equipo de LocalOS — 15 años automatizando empresas",
    metaDescription: "La historia del equipo de LocalOS: 15 años en transporte, comercio, producción, logística y servicios.",
    eyebrow: "El equipo de LocalOS",
    title: "Empezamos nuestros negocios para tener más libertad",
    intro: "Pero, a medida que crecían, teníamos menos. Por la mañana, números y equipo. Durante el día, clientes y urgencias. Por la noche, lo que había quedado pendiente. Apagar el teléfono o irse una semana parecía arriesgado.",
    workdayValue: "14 horas",
    workdayText: "puede durar el día de un propietario cuando todos los asuntos importantes terminan en su mesa",
    workdayNote: "Conocemos esta rutina desde dentro.",
    storyEyebrow: "Por qué creamos LocalOS",
    storyTitle: "15 años de empresa y automatización",
    storyIntro: "Trabajamos en transporte, comercio, producción, logística y servicios.",
    chapterOneTitle: "Conocemos este problema desde dentro",
    chapterOneText: "Durante 15 años creamos y automatizamos empresas de transporte, comercio, producción, logística y servicios. Trabajamos tanto con pequeñas compañías como con grandes empresas. Uno de nuestros proyectos de transporte pasó de cero a operar en 40 países. Para una gran empresa implantamos un modelo que ahorraba varios millones de dólares al año.\n\nPero, a medida que crecían nuestros proyectos, todos nos encontramos con el mismo problema: cada vez más trabajo volvía al propietario. Clientes, empleados, números y asuntos urgentes. Parecía más fácil hacerlo uno mismo que explicarlo, delegarlo y revisarlo después.",
    chapterTwoTitle: "Primero resolvimos el problema para nosotros",
    chapterTwoText: "Aprendimos a crear equipos remotos, documentar procesos y automatizar el trabajo recurrente. Durante 15 años vimos las mismas tareas en empresas de sectores distintos y encontramos formas de resolverlas. Esa experiencia se convirtió en la base de LocalOS.",
    chapterThreeTitle: "Así nació LocalOS",
    chapterThreeText: "Convertimos las soluciones acumuladas en procedimientos digitales listos para usar. Ahora un propietario puede aprovechar la experiencia de muchas empresas sin recorrer todo el camino por su cuenta. La IA ayuda a describir la tarea y preparar el procedimiento, el propietario aprueba las reglas y un script ejecuta el trabajo recurrente.",
    industries: ["Transporte", "Comercio", "Producción", "Logística", "Servicios"],
    channelEyebrow: "Diario del equipo",
    channelTitle: "Покупай мою шаверму",
    channelText: "Escribimos sobre el emprendimiento real: agotamiento, operaciones, gestión, automatización y las ideas de las que nace LocalOS. Compartimos notas de trabajo, errores y conclusiones.",
    channelButton: "Leer en Telegram",
    popular: "Popular",
  },
  el: {
    metaTitle: "Η ομάδα του LocalOS — 15 χρόνια αυτοματοποίησης επιχειρήσεων",
    metaDescription: "Η ιστορία της ομάδας του LocalOS: 15 χρόνια σε μεταφορές, λιανική, παραγωγή, εφοδιαστική και υπηρεσίες.",
    eyebrow: "Η ομάδα του LocalOS",
    title: "Ξεκινήσαμε τις επιχειρήσεις μας για να έχουμε περισσότερη ελευθερία",
    intro: "Όσο όμως μεγάλωναν, η ελευθερία μας λιγόστευε. Το πρωί ασχολούμασταν με τους αριθμούς και την ομάδα. Μέσα στην ημέρα με πελάτες και επείγοντα θέματα. Το βράδυ με όσα δεν είχαμε προλάβει. Το να κλείσουμε το τηλέφωνο ή να λείψουμε για μία εβδομάδα έμοιαζε ριψοκίνδυνο.",
    workdayValue: "14 ώρες",
    workdayText: "μπορεί να διαρκεί η ημέρα ενός ιδιοκτήτη όταν κάθε σημαντικό θέμα καταλήγει σε αυτόν",
    workdayNote: "Έχουμε ζήσει αυτή την καθημερινότητα από πρώτο χέρι.",
    storyEyebrow: "Γιατί δημιουργήσαμε το LocalOS",
    storyTitle: "15 χρόνια εμπειρίας στις επιχειρήσεις και την αυτοματοποίηση",
    storyIntro: "Εργαστήκαμε σε μεταφορές, λιανική, παραγωγή, εφοδιαστική και υπηρεσίες.",
    chapterOneTitle: "Γνωρίζουμε το πρόβλημα από πρώτο χέρι",
    chapterOneText: "Εδώ και 15 χρόνια δημιουργούμε και αυτοματοποιούμε επιχειρήσεις στους κλάδους των μεταφορών, του λιανεμπορίου, της παραγωγής, της εφοδιαστικής και των υπηρεσιών. Έχουμε συνεργαστεί τόσο με μικρές εταιρείες όσο και με μεγάλους οργανισμούς. Ένα από τα έργα μας στις μεταφορές ξεκίνησε από το μηδέν και έφτασε να δραστηριοποιείται σε 40 χώρες. Για μια μεγάλη εταιρεία εφαρμόσαμε ένα μοντέλο που εξοικονομούσε αρκετά εκατομμύρια δολάρια τον χρόνο.\n\nΚαθώς όμως μεγάλωναν τα δικά μας έργα, αντιμετωπίσαμε όλοι το ίδιο πρόβλημα: όλο και περισσότερη δουλειά επέστρεφε σε εμάς. Πελάτες, εργαζόμενοι, αριθμοί, επείγοντα θέματα. Έμοιαζε πιο εύκολο να κάνουμε κάτι μόνοι μας παρά να το εξηγήσουμε, να το αναθέσουμε και ύστερα να ελέγξουμε το αποτέλεσμα.",
    chapterTwoTitle: "Πρώτα λύσαμε το πρόβλημα για εμάς",
    chapterTwoText: "Μάθαμε να οργανώνουμε ομάδες που εργάζονται εξ αποστάσεως, να καταγράφουμε τις διαδικασίες και να αυτοματοποιούμε τις επαναλαμβανόμενες εργασίες. Μέσα σε 15 χρόνια συναντήσαμε τα ίδια προβλήματα σε επιχειρήσεις διαφορετικών κλάδων και αναπτύξαμε τρόπους για να τα λύνουμε. Αυτή η εμπειρία έγινε η βάση του LocalOS.",
    chapterThreeTitle: "Έτσι δημιουργήθηκε το LocalOS",
    chapterThreeText: "Μετατρέψαμε τις λύσεις που συγκεντρώσαμε σε έτοιμες ψηφιακές διαδικασίες. Έτσι, ένας ιδιοκτήτης μπορεί να αξιοποιήσει την εμπειρία πολλών επιχειρήσεων χωρίς να χρειαστεί να περάσει ξανά από όλα τα στάδια. Η τεχνητή νοημοσύνη βοηθά να περιγραφεί η εργασία και να προετοιμαστεί το σενάριο. Ο ιδιοκτήτης εγκρίνει τους κανόνες και στη συνέχεια ένα πρόγραμμα εκτελεί την επαναλαμβανόμενη εργασία.",
    industries: ["Μεταφορές", "Λιανική", "Παραγωγή", "Εφοδιαστική", "Υπηρεσίες"],
    channelEyebrow: "Το ημερολόγιο της ομάδας",
    channelTitle: "Покупай мою шаверму",
    channelText: "Γράφουμε για την επιχειρηματικότητα όπως είναι στην πραγματικότητα: την εξουθένωση, την καθημερινή λειτουργία, τη διοίκηση, την αυτοματοποίηση και τις ιδέες πάνω στις οποίες χτίστηκε το LocalOS. Μοιραζόμαστε σημειώσεις από τη δουλειά μας, λάθη και συμπεράσματα.",
    channelButton: "Διαβάστε στο Telegram",
    popular: "Δημοφιλές",
  },
  de: {
    metaTitle: "Das LocalOS-Team — 15 Jahre Unternehmensautomatisierung",
    metaDescription: "Die Geschichte des LocalOS-Teams: 15 Jahre Erfahrung in Transport, Handel, Produktion, Logistik und Dienstleistungen.",
    eyebrow: "Das LocalOS-Team",
    title: "Wir gründeten Unternehmen, um freier zu werden",
    intro: "Doch mit dem Wachstum wurde die Freiheit kleiner. Morgens Zahlen und Mitarbeitende, tagsüber Kunden und dringende Fragen, abends alles, was liegen blieb. Das Telefon auszuschalten oder eine Woche wegzufahren, fühlte sich riskant an.",
    workdayValue: "14 Stunden",
    workdayText: "kann der Arbeitstag eines Inhabers dauern, wenn jedes wichtige Thema bei ihm landet",
    workdayNote: "Wir kennen diesen Alltag aus eigener Erfahrung.",
    storyEyebrow: "Warum wir LocalOS entwickelt haben",
    storyTitle: "15 Jahre Unternehmen und Automatisierung",
    storyIntro: "Wir arbeiteten in Transport, Handel, Produktion, Logistik und Dienstleistungen.",
    chapterOneTitle: "Wir kennen das Problem von innen",
    chapterOneText: "Seit 15 Jahren bauen und automatisieren wir Unternehmen in Transport, Handel, Produktion, Logistik und Dienstleistungen. Wir arbeiteten mit kleinen Betrieben ebenso wie mit Großunternehmen. Eines unserer Transportprojekte wuchs von null auf eine Tätigkeit in 40 Ländern. Für ein Großunternehmen führten wir ein Modell ein, das jährlich mehrere Millionen Dollar einsparte.\n\nMit dem Wachstum unserer eigenen Projekte begegneten wir jedoch alle demselben Problem: Immer mehr Arbeit kam zum Inhaber zurück. Kunden, Mitarbeitende, Zahlen und dringende Fragen. Es schien leichter, alles selbst zu erledigen, als es zu erklären, zu übergeben und anschließend zu prüfen.",
    chapterTwoTitle: "Zuerst lösten wir das Problem für uns selbst",
    chapterTwoText: "Wir lernten, verteilte Teams aufzubauen, Prozesse zu dokumentieren und wiederkehrende Arbeit zu automatisieren. In 15 Jahren begegneten uns dieselben Aufgaben in Unternehmen verschiedener Branchen. Wir entwickelten Lösungen dafür. Diese Erfahrung bildet die Grundlage von LocalOS.",
    chapterThreeTitle: "So entstand LocalOS",
    chapterThreeText: "Wir verwandelten die gesammelten Lösungen in fertige digitale Abläufe. Inhaber können von der Erfahrung vieler Unternehmen profitieren, ohne den gesamten Weg selbst zu wiederholen. KI hilft, die Aufgabe zu beschreiben und den Ablauf vorzubereiten. Der Inhaber bestätigt die Regeln, danach erledigt ein Skript die wiederkehrende Arbeit.",
    industries: ["Transport", "Handel", "Produktion", "Logistik", "Dienstleistungen"],
    channelEyebrow: "Team-Tagebuch",
    channelTitle: "Покупай мою шаверму",
    channelText: "Wir schreiben über Unternehmertum, wie es wirklich ist: Erschöpfung, tägliche Abläufe, Steuerung, Automatisierung und die Ideen hinter LocalOS. Wir teilen Arbeitsnotizen, Fehler und Schlussfolgerungen.",
    channelButton: "Auf Telegram lesen",
    popular: "Beliebt",
  },
  th: {
    metaTitle: "ทีม LocalOS — 15 ปีแห่งการทำธุรกิจให้เป็นระบบอัตโนมัติ",
    metaDescription: "เรื่องราวของทีม LocalOS จากประสบการณ์ 15 ปีในธุรกิจขนส่ง ค้าปลีก การผลิต โลจิสติกส์ และบริการ",
    eyebrow: "ทีม LocalOS",
    title: "เราเริ่มทำธุรกิจเพื่อให้ตัวเองมีอิสระมากขึ้น",
    intro: "แต่เมื่อธุรกิจโตขึ้น อิสระกลับน้อยลง ตอนเช้าดูตัวเลขและพนักงาน ตอนกลางวันรับมือลูกค้าและเรื่องด่วน ตอนเย็นทำสิ่งที่ค้างไว้ การปิดโทรศัพท์หรือหยุดงานหนึ่งสัปดาห์ดูเป็นเรื่องเสี่ยง",
    workdayValue: "14 ชั่วโมง",
    workdayText: "คือเวลาที่เจ้าของอาจต้องทำงานในแต่ละวัน เมื่อเรื่องสำคัญทุกอย่างย้อนกลับมาหาตนเอง",
    workdayNote: "เราเคยอยู่ในสภาพนี้ด้วยตัวเอง",
    storyEyebrow: "เหตุผลที่เราสร้าง LocalOS",
    storyTitle: "15 ปีในธุรกิจและระบบอัตโนมัติ",
    storyIntro: "เราทำงานในธุรกิจขนส่ง ค้าปลีก การผลิต โลจิสติกส์ และบริการ",
    chapterOneTitle: "เราเข้าใจปัญหานี้จากประสบการณ์ตรง",
    chapterOneText: "ตลอด 15 ปี เราสร้างและทำให้ธุรกิจขนส่ง ค้าปลีก การผลิต โลจิสติกส์ และบริการทำงานเป็นระบบอัตโนมัติ เราทำงานกับทั้งบริษัทขนาดเล็กและองค์กรขนาดใหญ่ โครงการขนส่งหนึ่งของเราเติบโตจากศูนย์จนดำเนินงานใน 40 ประเทศ และเราเคยวางระบบให้บริษัทขนาดใหญ่ซึ่งช่วยประหยัดเงินหลายล้านดอลลาร์ต่อปี\n\nแต่เมื่อโครงการของเราเติบโตขึ้น ทุกคนพบปัญหาเดียวกัน งานจำนวนมากย้อนกลับมาหาเจ้าของ ทั้งลูกค้า พนักงาน ตัวเลข และเรื่องด่วน การทำเองดูง่ายกว่าการอธิบาย มอบหมาย แล้วกลับมาตรวจสอบ",
    chapterTwoTitle: "ก่อนอื่นเราแก้ปัญหานี้ให้ตัวเอง",
    chapterTwoText: "เราเรียนรู้การสร้างทีมทางไกล การเขียนขั้นตอนการทำงาน และการทำงานซ้ำให้เป็นระบบอัตโนมัติ ตลอด 15 ปี เราพบงานแบบเดียวกันในบริษัทหลายอุตสาหกรรมและหาวิธีแก้ปัญหาเหล่านั้น ประสบการณ์นี้กลายเป็นรากฐานของ LocalOS",
    chapterThreeTitle: "LocalOS จึงเกิดขึ้น",
    chapterThreeText: "เราเปลี่ยนวิธีแก้ปัญหาที่สะสมไว้ให้เป็นขั้นตอนดิจิทัลพร้อมใช้ เจ้าของธุรกิจจึงใช้ประสบการณ์ของหลายบริษัทได้โดยไม่ต้องเริ่มใหม่ทั้งหมด AI ช่วยอธิบายงานและเตรียมขั้นตอน เจ้าของอนุมัติกฎ แล้วสคริปต์จึงทำงานที่เกิดซ้ำ",
    industries: ["ขนส่ง", "ค้าปลีก", "การผลิต", "โลจิสติกส์", "บริการ"],
    channelEyebrow: "บันทึกของทีม",
    channelTitle: "Покупай мою шаверму",
    channelText: "เราเขียนถึงชีวิตจริงของผู้ประกอบการ ทั้งภาวะหมดไฟ งานประจำวัน การบริหาร ระบบอัตโนมัติ และแนวคิดเบื้องหลัง LocalOS พร้อมแบ่งปันบันทึกการทำงาน ข้อผิดพลาด และบทเรียน",
    channelButton: "อ่านใน Telegram",
    popular: "ยอดนิยม",
  },
  ar: {
    metaTitle: "فريق LocalOS — 15 عامًا في أتمتة الأعمال",
    metaDescription: "قصة فريق LocalOS: خبرة 15 عامًا في النقل والتجزئة والإنتاج والخدمات اللوجستية والخدمات.",
    eyebrow: "فريق LocalOS",
    title: "بدأنا أعمالنا لنحصل على مزيد من الحرية",
    intro: "لكن كلما نمت الأعمال، تقلصت الحرية. في الصباح الأرقام والموظفون، وفي النهار العملاء والمسائل العاجلة، وفي المساء ما لم يُنجز. كان إغلاق الهاتف أو السفر لأسبوع يبدو مخاطرة.",
    workdayValue: "14 ساعة",
    workdayText: "قد يمتد إليها يوم صاحب العمل عندما تعود إليه كل المسائل المهمة",
    workdayNote: "نحن نعرف هذا النمط من الداخل.",
    storyEyebrow: "لماذا أنشأنا LocalOS",
    storyTitle: "15 عامًا في الأعمال والأتمتة",
    storyIntro: "عملنا في النقل والتجزئة والإنتاج والخدمات اللوجستية والخدمات.",
    chapterOneTitle: "نعرف هذه المشكلة من الداخل",
    chapterOneText: "على مدى 15 عامًا، أنشأنا أعمالًا وأتمتناها في النقل والتجزئة والإنتاج والخدمات اللوجستية والخدمات. عملنا مع شركات صغيرة ومؤسسات كبيرة. نما أحد مشاريع النقل لدينا من الصفر إلى العمل في 40 دولة. وطبّقنا لشركة كبيرة نموذجًا وفر عدة ملايين من الدولارات سنويًا.\n\nلكن مع نمو مشاريعنا، واجه كل منا المشكلة نفسها: كان المزيد من العمل يعود إلى صاحب العمل. العملاء والموظفون والأرقام والمسائل العاجلة. بدا تنفيذ كل شيء بأنفسنا أسهل من شرحه وتفويضه ثم مراجعته.",
    chapterTwoTitle: "حللنا المشكلة لأنفسنا أولًا",
    chapterTwoText: "تعلمنا بناء فرق تعمل عن بُعد، وتوثيق العمليات، وأتمتة العمل المتكرر. خلال 15 عامًا رأينا المهام نفسها في شركات من قطاعات مختلفة ووجدنا طرقًا لحلها. أصبحت هذه الخبرة أساس LocalOS.",
    chapterThreeTitle: "هكذا ظهر LocalOS",
    chapterThreeText: "حوّلنا الحلول المتراكمة إلى إجراءات رقمية جاهزة. يستطيع صاحب العمل الاستفادة من خبرة شركات كثيرة من دون أن يكرر الرحلة كلها بنفسه. يساعد الذكاء الاصطناعي في وصف المهمة وإعداد الإجراء، ويعتمد صاحب العمل القواعد، ثم ينفذ البرنامج النصي العمل المتكرر.",
    industries: ["النقل", "التجزئة", "الإنتاج", "الخدمات اللوجستية", "الخدمات"],
    channelEyebrow: "يوميات الفريق",
    channelTitle: "Покупай мою шаверму",
    channelText: "نكتب عن ريادة الأعمال كما هي: الإرهاق والتشغيل والإدارة والأتمتة والأفكار التي تقف خلف LocalOS. نشارك ملاحظات العمل والأخطاء والاستنتاجات.",
    channelButton: "اقرأ على Telegram",
    popular: "الأكثر طلبًا",
  },
  ha: {
    metaTitle: "Ƙungiyar LocalOS — shekaru 15 na sarrafa kasuwanci ta atomatik",
    metaDescription: "Labarin ƙungiyar LocalOS: shekaru 15 a sufuri, dillanci, samarwa, jigilar kayayyaki da ayyuka.",
    eyebrow: "Ƙungiyar LocalOS",
    title: "Mun fara kasuwanci ne domin mu sami ƙarin ’yanci",
    intro: "Amma yayin da kasuwancin ya girma, ’yancin ya ragu. Da safe lambobi da ma’aikata, da rana kwastomomi da gaggawa, da yamma abubuwan da ba a kammala ba. Kashe waya ko tafiya na mako guda ya zama kamar haɗari.",
    workdayValue: "Awanni 14",
    workdayText: "ranar mai kasuwanci kan kai idan kowane muhimmin al’amari yana dawowa gare shi",
    workdayNote: "Mun san wannan yanayin daga ciki.",
    storyEyebrow: "Dalilin da ya sa muka gina LocalOS",
    storyTitle: "Shekaru 15 a kasuwanci da aiki ta atomatik",
    storyIntro: "Mun yi aiki a sufuri, dillanci, samarwa, jigilar kayayyaki da ayyuka.",
    chapterOneTitle: "Mun san wannan matsala daga ciki",
    chapterOneText: "Tsawon shekaru 15 mun gina tare da sarrafa kasuwanci ta atomatik a sufuri, dillanci, samarwa, jigilar kayayyaki da ayyuka. Mun yi aiki da ƙananan kamfanoni da manyan masana’antu. Ɗaya daga cikin ayyukanmu na sufuri ya tashi daga tushe har ya kai aiki a ƙasashe 40. Ga wani babban kamfani mun aiwatar da tsarin da ya tanadi dala miliyan da dama a shekara.\n\nAmma yayin da ayyukanmu suka girma, kowannenmu ya fuskanci matsala ɗaya: ƙarin aiki yana komawa ga mai kasuwanci. Kwastomomi, ma’aikata, lambobi da gaggawa. Yin komai da kanmu ya fi sauƙi fiye da bayyanawa, miƙawa sannan a sake dubawa.",
    chapterTwoTitle: "Da farko mun warware matsalar ga kanmu",
    chapterTwoText: "Mun koyi gina ƙungiyoyin aiki daga nesa, rubuta matakan aiki da sarrafa aikin da ake maimaitawa ta atomatik. A cikin shekaru 15 mun ga ayyuka iri ɗaya a kamfanoni na fannoni daban-daban kuma mun samo hanyoyin magance su. Wannan ƙwarewar ce ta zama tushen LocalOS.",
    chapterThreeTitle: "Haka LocalOS ya fara",
    chapterThreeText: "Mun mayar da hanyoyin da muka tara zuwa shirye-shiryen dijital masu shirin amfani. Mai kasuwanci yanzu zai iya amfani da ƙwarewar kamfanoni da yawa ba tare da ya sake bin duk hanyar da kansa ba. AI yana taimakawa wajen bayyana aikin da shirya matakai, mai kasuwanci ya amince da dokoki, sannan rubutaccen shiri ya aiwatar da aikin da ake maimaitawa.",
    industries: ["Sufuri", "Dillanci", "Samarwa", "Jigilar kayayyaki", "Ayyuka"],
    channelEyebrow: "Littafin ƙungiya",
    channelTitle: "Покупай мою шаверму",
    channelText: "Muna rubutu game da kasuwanci na ainihi: gajiyawa, gudanar da yau da kullum, lissafi, aiki ta atomatik da ra’ayoyin da suka haifar da LocalOS. Muna raba bayanan aiki, kuskure da abin da muka koya.",
    channelButton: "Karanta a Telegram",
    popular: "Mafi shahara",
  },
  tr: {
    metaTitle: "LocalOS ekibi — iş otomasyonunda 15 yıl",
    metaDescription: "LocalOS ekibinin hikâyesi: ulaşım, perakende, üretim, lojistik ve hizmetlerde 15 yıllık deneyim.",
    eyebrow: "LocalOS ekibi",
    title: "İş kurarken daha özgür olmayı amaçladık",
    intro: "Ancak işler büyüdükçe özgürlük azaldı. Sabahları rakamlar ve çalışanlar, gündüz müşteriler ve acil konular, akşam ise gün içinde yetişmeyen işler vardı. Telefonu kapatmak veya bir haftalığına uzaklaşmak riskli geliyordu.",
    workdayValue: "14 saat",
    workdayText: "önemli her konu kendisine döndüğünde bir işletme sahibinin çalışma günü bu kadar sürebilir",
    workdayNote: "Bu düzeni içeriden biliyoruz.",
    storyEyebrow: "LocalOS'u neden geliştirdik",
    storyTitle: "İş ve otomasyonda 15 yıl",
    storyIntro: "Ulaşım, perakende, üretim, lojistik ve hizmet sektörlerinde çalıştık.",
    chapterOneTitle: "Bu sorunu içeriden biliyoruz",
    chapterOneText: "15 yıl boyunca ulaşım, perakende, üretim, lojistik ve hizmet sektörlerinde işletmeler kurduk ve otomatikleştirdik. Hem küçük şirketlerle hem büyük işletmelerle çalıştık. Ulaşım projelerimizden biri sıfırdan başlayıp 40 ülkede faaliyet gösterir hâle geldi. Büyük bir şirkette yılda birkaç milyon dolar tasarruf sağlayan bir model uyguladık.\n\nAncak kendi projelerimiz büyüdükçe hepimiz aynı sorunla karşılaştık: giderek daha fazla iş işletme sahibine dönüyordu. Müşteriler, çalışanlar, rakamlar ve acil konular. Kendimiz yapmak; açıklamaktan, devretmekten ve sonra kontrol etmekten daha kolay görünüyordu.",
    chapterTwoTitle: "Önce bu sorunu kendimiz için çözdük",
    chapterTwoText: "Uzaktan çalışan ekipler kurmayı, süreçleri belgelemeyi ve tekrarlanan işleri otomatikleştirmeyi öğrendik. 15 yıl boyunca farklı sektörlerdeki şirketlerde aynı görevlerle karşılaştık ve bunları çözmenin yollarını bulduk. Bu deneyim LocalOS'un temelini oluşturdu.",
    chapterThreeTitle: "LocalOS böyle ortaya çıktı",
    chapterThreeText: "Biriktirdiğimiz çözümleri kullanıma hazır dijital prosedürlere dönüştürdük. İşletme sahibi artık tüm yolu yeniden yürümek zorunda kalmadan birçok şirketin deneyiminden yararlanabiliyor. Yapay zekâ görevi tanımlamaya ve prosedürü hazırlamaya yardımcı oluyor, işletme sahibi kuralları onaylıyor, tekrarlanan işi ise bir komut dosyası yürütüyor.",
    industries: ["Ulaşım", "Perakende", "Üretim", "Lojistik", "Hizmetler"],
    channelEyebrow: "Ekip günlüğü",
    channelTitle: "Покупай мою шаверму",
    channelText: "Girişimciliğin gerçek hâlini yazıyoruz: tükenmişlik, operasyon, yönetim, otomasyon ve LocalOS'un arkasındaki fikirler. Çalışma notlarını, hataları ve çıkardığımız dersleri paylaşıyoruz.",
    channelButton: "Telegram'da oku",
    popular: "Popüler",
  },
};
