import type { Language } from '@/i18n/LanguageContext';
import type { AgentExecutionMode, EmployeeWorkspaceState } from './types';

type DeepCopy = {
  state: Record<EmployeeWorkspaceState, string>;
  mode: Record<AgentExecutionMode, string>;
  modeDescription: Record<AgentExecutionMode, string>;
  described: string; tested: string; enabled: string; working: string;
  otherActions: string; clone: string; openSettings: string; goal: string; readiness: string;
  lastWork: string; nextWork: string; lastResult: string; attention: string; openResult: string;
  resultFallback: string; missingResult: string; paramsTitle: string; paramsHint: string;
  select: string; yes: string; no: string; startType: string; confirmType: string;
  startTypeHint: string; time: string; timezone: string; save: string; confirm: string;
  schedule: string; scheduleTitle: string; scheduleHint: string; saveSchedule: string;
  history: string; runs: string; total: string; workRun: string; testRun: string;
  dateMissing: string; historyEmpty: string; originalTask: string; workGoal: string;
  startsWhen: string; sources: string; process: string; inputs: string; outputs: string;
  manualControl: string; localData: string; updateScenario: string; updateFromGoal: string;
  configureProcess: string; cancelChange: string; step: string; asksDecision: string;
  supportTools: string;
};

const states = (
  draft: string, needsMode: string, needsConnection: string, ready: string, running: string,
  review: string, blocked: string, working: string, completed: string, attention: string, error: string,
): Record<EmployeeWorkspaceState, string> => ({
  draft, needs_mode: needsMode, needs_connection: needsConnection, ready_for_test: ready,
  running_test: running, waiting_for_review: review, blocked_result: blocked, working,
  completed, needs_attention: attention, error,
});

const modes = (oneOff: string, manual: string, scheduled: string): Record<AgentExecutionMode, string> => ({ one_off: oneOff, manual, scheduled });

const copy: Record<Language, DeepCopy> = {
  ru: {
    state: states('Черновик','Выберите тип запуска','Не хватает подключения','Готов к проверке','Проверка идёт','Ждёт вашего решения','Нужен следующий шаг','Работает','Выполнено','Нужно включить','Ошибка'),
    mode: modes('Один раз','По кнопке','По расписанию'), modeDescription: modes('После выполнения задача завершится.','Вы запускаете работу, когда она нужна.','Агент запускается в указанное время.'),
    described:'Описан',tested:'Проверен',enabled:'Включён',working:'Работает',otherActions:'Другие действия',clone:'Создать копию агента',openSettings:'Открыть настройки',goal:'Цель агента',readiness:'Готовность процесса',lastWork:'Последняя работа',nextWork:'Следующая работа',lastResult:'Последний результат',attention:'Требует вашего внимания',openResult:'Открыть результат',resultFallback:'Результат сохранён и доступен в истории запуска.',missingResult:'Сотрудник завершил тест, но не сохранил текст результата. Уточните формат результата и запустите тест ещё раз.',paramsTitle:'Параметры этой работы',paramsHint:'Проверьте значения перед тестом или рабочим запуском.',select:'Выберите',yes:'Да',no:'Нет',startType:'Тип запуска',confirmType:'Подтвердите тип агента',startTypeHint:'Выбор меняет только способ запуска. Он не включает агента и не запускает работу.',time:'Время',timezone:'Часовой пояс',save:'Сохранить',confirm:'Подтвердить тип запуска',schedule:'Расписание',scheduleTitle:'Когда агент должен начинать работу',scheduleHint:'Время хранится вместе с часовым поясом.',saveSchedule:'Сохранить расписание',history:'История',runs:'Запуски агента',total:'всего',workRun:'Рабочий запуск',testRun:'Проверка',dateMissing:'Дата не сохранена',historyEmpty:'История появится после первого запуска.',originalTask:'Исходное поручение',workGoal:'Рабочая цель',startsWhen:'Когда запускается',sources:'Источники и доступы',process:'Как выполняется',inputs:'Что получает на вход',outputs:'Что сохраняет',manualControl:'Ручной контроль',localData:'Агент использует данные LocalOS и введённые параметры.',updateScenario:'Обновить сценарий по цели',updateFromGoal:'Обновить по цели',configureProcess:'Настроить процесс',cancelChange:'Отменить изменение',step:'Шаг',asksDecision:'Попросит решение',supportTools:'Служебные инструменты миграции и поддержки',
  },
  en: {
    state: states('Draft','Choose a run type','Connection required','Ready to test','Test running','Waiting for your decision','Next step required','Working','Completed','Enable required','Error'),
    mode: modes('Once','On demand','On schedule'), modeDescription: modes('The task finishes after one run.','You start the work when needed.','The agent starts at the scheduled time.'),
    described:'Defined',tested:'Tested',enabled:'Enabled',working:'Working',otherActions:'Other actions',clone:'Create a copy',openSettings:'Open settings',goal:'Agent goal',readiness:'Process readiness',lastWork:'Last run',nextWork:'Next run',lastResult:'Latest result',attention:'Needs your attention',openResult:'Open result',resultFallback:'The result is saved in run history.',missingResult:'The test finished without a saved result. Check the result format and run the test again.',paramsTitle:'Run parameters',paramsHint:'Check the values before a test or live run.',select:'Select',yes:'Yes',no:'No',startType:'Run type',confirmType:'Confirm agent type',startTypeHint:'This changes only how the agent starts. It does not enable or run it.',time:'Time',timezone:'Time zone',save:'Save',confirm:'Confirm run type',schedule:'Schedule',scheduleTitle:'When should the agent start?',scheduleHint:'Time is stored with its time zone.',saveSchedule:'Save schedule',history:'History',runs:'Agent runs',total:'total',workRun:'Live run',testRun:'Test',dateMissing:'Date unavailable',historyEmpty:'History appears after the first run.',originalTask:'Original task',workGoal:'Working goal',startsWhen:'Start condition',sources:'Sources and access',process:'How it works',inputs:'Inputs',outputs:'Saved output',manualControl:'Manual control',localData:'The agent uses LocalOS data and entered parameters.',updateScenario:'Update scenario from goal',updateFromGoal:'Update from goal',configureProcess:'Configure process',cancelChange:'Cancel changes',step:'Step',asksDecision:'Requests approval',supportTools:'Migration and support tools',
  },
  fr: {
    state: states('Brouillon','Choisir le mode de lancement','Connexion requise','Prêt à tester','Test en cours','Attend votre décision','Étape suivante requise','Actif','Terminé','Activation requise','Erreur'),
    mode:modes('Une fois','À la demande','Planifié'),modeDescription:modes('La tâche se termine après une exécution.','Vous lancez le travail quand nécessaire.','L’agent démarre à l’heure prévue.'),
    described:'Défini',tested:'Testé',enabled:'Activé',working:'Actif',otherActions:'Autres actions',clone:'Créer une copie',openSettings:'Ouvrir les réglages',goal:'Objectif de l’agent',readiness:'État du processus',lastWork:'Dernière exécution',nextWork:'Prochaine exécution',lastResult:'Dernier résultat',attention:'Votre attention est requise',openResult:'Ouvrir le résultat',resultFallback:'Le résultat est enregistré dans l’historique.',missingResult:'Le test est terminé sans résultat enregistré. Vérifiez le format et relancez le test.',paramsTitle:'Paramètres de cette exécution',paramsHint:'Vérifiez les valeurs avant un test ou une exécution réelle.',select:'Sélectionner',yes:'Oui',no:'Non',startType:'Mode de lancement',confirmType:'Confirmer le type d’agent',startTypeHint:'Ce choix modifie uniquement le lancement. Il n’active ni n’exécute l’agent.',time:'Heure',timezone:'Fuseau horaire',save:'Enregistrer',confirm:'Confirmer le lancement',schedule:'Calendrier',scheduleTitle:'Quand l’agent doit-il démarrer ?',scheduleHint:'L’heure est enregistrée avec son fuseau horaire.',saveSchedule:'Enregistrer le calendrier',history:'Historique',runs:'Exécutions de l’agent',total:'au total',workRun:'Exécution réelle',testRun:'Test',dateMissing:'Date indisponible',historyEmpty:'L’historique apparaîtra après la première exécution.',originalTask:'Mission initiale',workGoal:'Objectif actif',startsWhen:'Déclenchement',sources:'Sources et accès',process:'Fonctionnement',inputs:'Données d’entrée',outputs:'Résultat enregistré',manualControl:'Contrôle manuel',localData:'L’agent utilise les données LocalOS et les paramètres saisis.',updateScenario:'Mettre à jour selon l’objectif',updateFromGoal:'Mettre à jour',configureProcess:'Configurer le processus',cancelChange:'Annuler',step:'Étape',asksDecision:'Demande une validation',supportTools:'Outils de migration et de support',
  },
  es: {
    state: states('Borrador','Elige el tipo de ejecución','Falta una conexión','Listo para probar','Prueba en curso','Espera tu decisión','Se requiere el siguiente paso','Activo','Completado','Hay que activarlo','Error'),
    mode:modes('Una vez','Bajo demanda','Programado'),modeDescription:modes('La tarea termina después de una ejecución.','Inicias el trabajo cuando lo necesitas.','El agente comienza a la hora programada.'),
    described:'Definido',tested:'Probado',enabled:'Activado',working:'Activo',otherActions:'Otras acciones',clone:'Crear una copia',openSettings:'Abrir ajustes',goal:'Objetivo del agente',readiness:'Preparación del proceso',lastWork:'Última ejecución',nextWork:'Próxima ejecución',lastResult:'Último resultado',attention:'Requiere tu atención',openResult:'Abrir resultado',resultFallback:'El resultado está guardado en el historial.',missingResult:'La prueba terminó sin guardar el resultado. Revisa el formato y vuelve a ejecutarla.',paramsTitle:'Parámetros de esta ejecución',paramsHint:'Revisa los valores antes de una prueba o ejecución real.',select:'Seleccionar',yes:'Sí',no:'No',startType:'Tipo de ejecución',confirmType:'Confirma el tipo de agente',startTypeHint:'Solo cambia cómo se inicia. No activa ni ejecuta el agente.',time:'Hora',timezone:'Zona horaria',save:'Guardar',confirm:'Confirmar tipo de ejecución',schedule:'Horario',scheduleTitle:'¿Cuándo debe empezar el agente?',scheduleHint:'La hora se guarda junto con su zona horaria.',saveSchedule:'Guardar horario',history:'Historial',runs:'Ejecuciones del agente',total:'en total',workRun:'Ejecución real',testRun:'Prueba',dateMissing:'Fecha no disponible',historyEmpty:'El historial aparecerá después de la primera ejecución.',originalTask:'Encargo original',workGoal:'Objetivo activo',startsWhen:'Cuándo se inicia',sources:'Fuentes y accesos',process:'Cómo funciona',inputs:'Datos de entrada',outputs:'Resultado guardado',manualControl:'Control manual',localData:'El agente usa datos de LocalOS y los parámetros introducidos.',updateScenario:'Actualizar según el objetivo',updateFromGoal:'Actualizar desde el objetivo',configureProcess:'Configurar proceso',cancelChange:'Cancelar cambios',step:'Paso',asksDecision:'Solicita aprobación',supportTools:'Herramientas de migración y soporte',
  },
  de: {
    state: states('Entwurf','Startart wählen','Verbindung fehlt','Bereit zum Test','Test läuft','Wartet auf Ihre Entscheidung','Nächster Schritt erforderlich','Aktiv','Abgeschlossen','Aktivierung erforderlich','Fehler'),
    mode:modes('Einmal','Auf Abruf','Nach Zeitplan'),modeDescription:modes('Die Aufgabe endet nach einem Lauf.','Sie starten die Arbeit bei Bedarf.','Der Agent startet zur geplanten Zeit.'),
    described:'Definiert',tested:'Getestet',enabled:'Aktiviert',working:'Aktiv',otherActions:'Weitere Aktionen',clone:'Kopie erstellen',openSettings:'Einstellungen öffnen',goal:'Ziel des Agenten',readiness:'Prozessbereitschaft',lastWork:'Letzter Lauf',nextWork:'Nächster Lauf',lastResult:'Letztes Ergebnis',attention:'Benötigt Ihre Aufmerksamkeit',openResult:'Ergebnis öffnen',resultFallback:'Das Ergebnis ist im Verlauf gespeichert.',missingResult:'Der Test endete ohne gespeichertes Ergebnis. Prüfen Sie das Format und starten Sie erneut.',paramsTitle:'Parameter dieses Laufs',paramsHint:'Prüfen Sie die Werte vor Test oder Produktivlauf.',select:'Auswählen',yes:'Ja',no:'Nein',startType:'Startart',confirmType:'Agententyp bestätigen',startTypeHint:'Dies ändert nur den Start. Der Agent wird weder aktiviert noch ausgeführt.',time:'Uhrzeit',timezone:'Zeitzone',save:'Speichern',confirm:'Startart bestätigen',schedule:'Zeitplan',scheduleTitle:'Wann soll der Agent starten?',scheduleHint:'Die Uhrzeit wird mit der Zeitzone gespeichert.',saveSchedule:'Zeitplan speichern',history:'Verlauf',runs:'Agentenläufe',total:'gesamt',workRun:'Produktivlauf',testRun:'Test',dateMissing:'Datum fehlt',historyEmpty:'Der Verlauf erscheint nach dem ersten Lauf.',originalTask:'Ursprünglicher Auftrag',workGoal:'Aktives Ziel',startsWhen:'Startbedingung',sources:'Quellen und Zugriffe',process:'Ablauf',inputs:'Eingaben',outputs:'Gespeichertes Ergebnis',manualControl:'Manuelle Kontrolle',localData:'Der Agent nutzt LocalOS-Daten und eingegebene Parameter.',updateScenario:'Ablauf aus Ziel aktualisieren',updateFromGoal:'Aus Ziel aktualisieren',configureProcess:'Prozess konfigurieren',cancelChange:'Änderung abbrechen',step:'Schritt',asksDecision:'Fordert Freigabe an',supportTools:'Migrations- und Supportwerkzeuge',
  },
  el: {
    state: states('Προσχέδιο','Επιλέξτε τρόπο εκκίνησης','Απαιτείται σύνδεση','Έτοιμο για δοκιμή','Η δοκιμή εκτελείται','Αναμένει την απόφασή σας','Απαιτείται επόμενο βήμα','Ενεργό','Ολοκληρώθηκε','Απαιτείται ενεργοποίηση','Σφάλμα'),
    mode:modes('Μία φορά','Κατ’ απαίτηση','Με πρόγραμμα'),modeDescription:modes('Η εργασία ολοκληρώνεται μετά από μία εκτέλεση.','Ξεκινάτε την εργασία όταν χρειάζεται.','Ο πράκτορας ξεκινά στην προγραμματισμένη ώρα.'),
    described:'Ορίστηκε',tested:'Δοκιμάστηκε',enabled:'Ενεργοποιήθηκε',working:'Ενεργό',otherActions:'Άλλες ενέργειες',clone:'Δημιουργία αντιγράφου',openSettings:'Άνοιγμα ρυθμίσεων',goal:'Στόχος πράκτορα',readiness:'Ετοιμότητα διαδικασίας',lastWork:'Τελευταία εκτέλεση',nextWork:'Επόμενη εκτέλεση',lastResult:'Τελευταίο αποτέλεσμα',attention:'Χρειάζεται την προσοχή σας',openResult:'Άνοιγμα αποτελέσματος',resultFallback:'Το αποτέλεσμα αποθηκεύτηκε στο ιστορικό.',missingResult:'Η δοκιμή ολοκληρώθηκε χωρίς αποθηκευμένο αποτέλεσμα. Ελέγξτε τη μορφή και επαναλάβετε.',paramsTitle:'Παράμετροι εκτέλεσης',paramsHint:'Ελέγξτε τις τιμές πριν από δοκιμή ή κανονική εκτέλεση.',select:'Επιλογή',yes:'Ναι',no:'Όχι',startType:'Τρόπος εκκίνησης',confirmType:'Επιβεβαίωση τύπου πράκτορα',startTypeHint:'Αλλάζει μόνο τον τρόπο εκκίνησης. Δεν ενεργοποιεί ούτε εκτελεί τον πράκτορα.',time:'Ώρα',timezone:'Ζώνη ώρας',save:'Αποθήκευση',confirm:'Επιβεβαίωση εκκίνησης',schedule:'Πρόγραμμα',scheduleTitle:'Πότε να ξεκινά ο πράκτορας;',scheduleHint:'Η ώρα αποθηκεύεται μαζί με τη ζώνη ώρας.',saveSchedule:'Αποθήκευση προγράμματος',history:'Ιστορικό',runs:'Εκτελέσεις πράκτορα',total:'σύνολο',workRun:'Κανονική εκτέλεση',testRun:'Δοκιμή',dateMissing:'Δεν υπάρχει ημερομηνία',historyEmpty:'Το ιστορικό εμφανίζεται μετά την πρώτη εκτέλεση.',originalTask:'Αρχική ανάθεση',workGoal:'Ενεργός στόχος',startsWhen:'Πότε ξεκινά',sources:'Πηγές και πρόσβαση',process:'Τρόπος λειτουργίας',inputs:'Είσοδοι',outputs:'Αποθηκευμένο αποτέλεσμα',manualControl:'Χειροκίνητος έλεγχος',localData:'Ο πράκτορας χρησιμοποιεί δεδομένα LocalOS και τις παραμέτρους εισόδου.',updateScenario:'Ενημέρωση από τον στόχο',updateFromGoal:'Ενημέρωση στόχου',configureProcess:'Ρύθμιση διαδικασίας',cancelChange:'Ακύρωση αλλαγών',step:'Βήμα',asksDecision:'Ζητά έγκριση',supportTools:'Εργαλεία μετεγκατάστασης και υποστήριξης',
  },
  th: {
    state: states('ฉบับร่าง','เลือกวิธีเริ่มงาน','ต้องเชื่อมต่อ','พร้อมทดสอบ','กำลังทดสอบ','รอการตัดสินใจของคุณ','ต้องมีขั้นตอนถัดไป','กำลังทำงาน','เสร็จแล้ว','ต้องเปิดใช้งาน','ข้อผิดพลาด'),
    mode:modes('ครั้งเดียว','เมื่อต้องการ','ตามกำหนดเวลา'),modeDescription:modes('งานจะจบหลังทำหนึ่งครั้ง','คุณเริ่มงานเมื่อจำเป็น','เอเจนต์เริ่มตามเวลาที่กำหนด'),
    described:'กำหนดแล้ว',tested:'ทดสอบแล้ว',enabled:'เปิดแล้ว',working:'กำลังทำงาน',otherActions:'การดำเนินการอื่น',clone:'สร้างสำเนา',openSettings:'เปิดการตั้งค่า',goal:'เป้าหมายเอเจนต์',readiness:'ความพร้อมของกระบวนการ',lastWork:'การทำงานล่าสุด',nextWork:'การทำงานถัดไป',lastResult:'ผลลัพธ์ล่าสุด',attention:'ต้องการให้คุณตรวจสอบ',openResult:'เปิดผลลัพธ์',resultFallback:'บันทึกผลลัพธ์ไว้ในประวัติแล้ว',missingResult:'การทดสอบจบโดยไม่บันทึกผลลัพธ์ โปรดตรวจรูปแบบแล้วลองอีกครั้ง',paramsTitle:'พารามิเตอร์ของงานนี้',paramsHint:'ตรวจสอบค่าก่อนทดสอบหรือทำงานจริง',select:'เลือก',yes:'ใช่',no:'ไม่',startType:'วิธีเริ่มงาน',confirmType:'ยืนยันประเภทเอเจนต์',startTypeHint:'เปลี่ยนเฉพาะวิธีเริ่ม ไม่ได้เปิดหรือสั่งงานเอเจนต์',time:'เวลา',timezone:'เขตเวลา',save:'บันทึก',confirm:'ยืนยันวิธีเริ่ม',schedule:'กำหนดเวลา',scheduleTitle:'เอเจนต์ควรเริ่มเมื่อใด',scheduleHint:'เวลาจะบันทึกพร้อมเขตเวลา',saveSchedule:'บันทึกกำหนดเวลา',history:'ประวัติ',runs:'การทำงานของเอเจนต์',total:'ทั้งหมด',workRun:'การทำงานจริง',testRun:'ทดสอบ',dateMissing:'ไม่มีวันที่',historyEmpty:'ประวัติจะแสดงหลังการทำงานครั้งแรก',originalTask:'งานที่มอบหมายเดิม',workGoal:'เป้าหมายที่ใช้งาน',startsWhen:'เงื่อนไขเริ่ม',sources:'แหล่งข้อมูลและสิทธิ์',process:'วิธีทำงาน',inputs:'ข้อมูลเข้า',outputs:'ผลลัพธ์ที่บันทึก',manualControl:'การควบคุมด้วยคน',localData:'เอเจนต์ใช้ข้อมูล LocalOS และพารามิเตอร์ที่กรอก',updateScenario:'อัปเดตจากเป้าหมาย',updateFromGoal:'อัปเดตตามเป้าหมาย',configureProcess:'ตั้งค่ากระบวนการ',cancelChange:'ยกเลิกการเปลี่ยนแปลง',step:'ขั้นตอน',asksDecision:'ขอการอนุมัติ',supportTools:'เครื่องมือย้ายข้อมูลและช่วยเหลือ',
  },
  ar: {
    state: states('مسودة','اختر طريقة التشغيل','يلزم اتصال','جاهز للاختبار','الاختبار جارٍ','بانتظار قرارك','الخطوة التالية مطلوبة','يعمل','مكتمل','يلزم التفعيل','خطأ'),
    mode:modes('مرة واحدة','عند الطلب','وفق جدول'),modeDescription:modes('تنتهي المهمة بعد تشغيل واحد.','تبدأ العمل عند الحاجة.','يبدأ الوكيل في الوقت المجدول.'),
    described:'محدد',tested:'تم اختباره',enabled:'مفعّل',working:'يعمل',otherActions:'إجراءات أخرى',clone:'إنشاء نسخة',openSettings:'فتح الإعدادات',goal:'هدف الوكيل',readiness:'جاهزية العملية',lastWork:'آخر تشغيل',nextWork:'التشغيل التالي',lastResult:'آخر نتيجة',attention:'يحتاج إلى انتباهك',openResult:'فتح النتيجة',resultFallback:'حُفظت النتيجة في سجل التشغيل.',missingResult:'انتهى الاختبار دون حفظ نتيجة. تحقق من التنسيق وأعد الاختبار.',paramsTitle:'معلمات هذا التشغيل',paramsHint:'تحقق من القيم قبل الاختبار أو التشغيل الفعلي.',select:'اختر',yes:'نعم',no:'لا',startType:'طريقة التشغيل',confirmType:'تأكيد نوع الوكيل',startTypeHint:'يغير هذا طريقة البدء فقط ولا يفعّل الوكيل أو يشغله.',time:'الوقت',timezone:'المنطقة الزمنية',save:'حفظ',confirm:'تأكيد طريقة التشغيل',schedule:'الجدول',scheduleTitle:'متى يجب أن يبدأ الوكيل؟',scheduleHint:'يُحفظ الوقت مع المنطقة الزمنية.',saveSchedule:'حفظ الجدول',history:'السجل',runs:'تشغيلات الوكيل',total:'الإجمالي',workRun:'تشغيل فعلي',testRun:'اختبار',dateMissing:'التاريخ غير متاح',historyEmpty:'يظهر السجل بعد أول تشغيل.',originalTask:'المهمة الأصلية',workGoal:'الهدف الفعلي',startsWhen:'شرط البدء',sources:'المصادر والوصول',process:'طريقة العمل',inputs:'المدخلات',outputs:'المخرجات المحفوظة',manualControl:'تحكم يدوي',localData:'يستخدم الوكيل بيانات LocalOS والمعلمات المدخلة.',updateScenario:'تحديث من الهدف',updateFromGoal:'تحديث حسب الهدف',configureProcess:'إعداد العملية',cancelChange:'إلغاء التغييرات',step:'خطوة',asksDecision:'يطلب موافقة',supportTools:'أدوات الترحيل والدعم',
  },
  ha: {
    state: states('Daftari','Zaɓi hanyar farawa','Ana bukatar haɗi','A shirye don gwaji','Ana gwaji','Yana jiran shawarar ku','Ana bukatar mataki na gaba','Yana aiki','An kammala','Ana bukatar kunnawa','Kuskure'),
    mode:modes('Sau ɗaya','Bisa buƙata','Bisa jadawali'),modeDescription:modes('Aikin zai ƙare bayan gudu ɗaya.','Kuna fara aikin idan an buƙata.','Wakilin zai fara a lokacin da aka tsara.'),
    described:'An bayyana',tested:'An gwada',enabled:'An kunna',working:'Yana aiki',otherActions:'Wasu ayyuka',clone:'Ƙirƙiri kwafi',openSettings:'Buɗe saituna',goal:'Manufar wakili',readiness:'Shirin tsari',lastWork:'Gudun ƙarshe',nextWork:'Gudu na gaba',lastResult:'Sakamako na ƙarshe',attention:'Yana bukatar kulawarku',openResult:'Buɗe sakamako',resultFallback:'An adana sakamakon a tarihi.',missingResult:'Gwajin ya ƙare ba tare da adana sakamako ba. Duba tsari sannan a sake gwaji.',paramsTitle:'Siffofin wannan gudu',paramsHint:'Duba ƙimomin kafin gwaji ko gudu na aiki.',select:'Zaɓi',yes:'Eh',no:'A’a',startType:'Hanyar farawa',confirmType:'Tabbatar da nau’in wakili',startTypeHint:'Wannan yana canza hanyar farawa kawai; ba ya kunnawa ko gudanar da wakili.',time:'Lokaci',timezone:'Yankin lokaci',save:'Ajiye',confirm:'Tabbatar da farawa',schedule:'Jadawali',scheduleTitle:'Yaushe wakili zai fara?',scheduleHint:'Ana adana lokaci tare da yankin lokacinsa.',saveSchedule:'Ajiye jadawali',history:'Tarihi',runs:'Gudanarwar wakili',total:'duka',workRun:'Gudun aiki',testRun:'Gwaji',dateMissing:'Babu kwanan wata',historyEmpty:'Tarihi zai bayyana bayan gudu na farko.',originalTask:'Aikin asali',workGoal:'Manufar aiki',startsWhen:'Lokacin farawa',sources:'Tushe da izini',process:'Yadda yake aiki',inputs:'Abubuwan shiga',outputs:'Sakamakon da aka adana',manualControl:'Kulawar mutum',localData:'Wakili yana amfani da bayanan LocalOS da siffofin da aka shigar.',updateScenario:'Sabunta daga manufa',updateFromGoal:'Sabunta bisa manufa',configureProcess:'Saita tsari',cancelChange:'Soke canje-canje',step:'Mataki',asksDecision:'Yana neman amincewa',supportTools:'Kayan ƙaura da tallafi',
  },
  tr: {
    state: states('Taslak','Çalıştırma türünü seçin','Bağlantı gerekli','Teste hazır','Test çalışıyor','Kararınızı bekliyor','Sonraki adım gerekli','Çalışıyor','Tamamlandı','Etkinleştirme gerekli','Hata'),
    mode:modes('Bir kez','İstek üzerine','Zamanlamayla'),modeDescription:modes('Görev bir çalıştırmadan sonra tamamlanır.','İhtiyaç olduğunda siz başlatırsınız.','Ajan planlanan saatte başlar.'),
    described:'Tanımlandı',tested:'Test edildi',enabled:'Etkin',working:'Çalışıyor',otherActions:'Diğer işlemler',clone:'Kopya oluştur',openSettings:'Ayarları aç',goal:'Ajan hedefi',readiness:'Süreç hazırlığı',lastWork:'Son çalışma',nextWork:'Sonraki çalışma',lastResult:'Son sonuç',attention:'İlginiz gerekiyor',openResult:'Sonucu aç',resultFallback:'Sonuç çalışma geçmişine kaydedildi.',missingResult:'Test sonuç kaydedilmeden tamamlandı. Biçimi kontrol edip tekrar deneyin.',paramsTitle:'Bu çalışmanın parametreleri',paramsHint:'Test veya gerçek çalıştırmadan önce değerleri kontrol edin.',select:'Seçin',yes:'Evet',no:'Hayır',startType:'Çalıştırma türü',confirmType:'Ajan türünü doğrulayın',startTypeHint:'Bu yalnızca başlatma biçimini değiştirir; ajanı etkinleştirmez veya çalıştırmaz.',time:'Saat',timezone:'Saat dilimi',save:'Kaydet',confirm:'Çalıştırma türünü doğrula',schedule:'Zamanlama',scheduleTitle:'Ajan ne zaman başlamalı?',scheduleHint:'Saat, saat dilimiyle birlikte saklanır.',saveSchedule:'Zamanlamayı kaydet',history:'Geçmiş',runs:'Ajan çalıştırmaları',total:'toplam',workRun:'Gerçek çalışma',testRun:'Test',dateMissing:'Tarih yok',historyEmpty:'Geçmiş ilk çalıştırmadan sonra görünür.',originalTask:'İlk görev',workGoal:'Etkin hedef',startsWhen:'Başlatma koşulu',sources:'Kaynaklar ve erişim',process:'Nasıl çalışır',inputs:'Girdiler',outputs:'Kaydedilen sonuç',manualControl:'Manuel kontrol',localData:'Ajan LocalOS verilerini ve girilen parametreleri kullanır.',updateScenario:'Hedeften güncelle',updateFromGoal:'Hedefe göre güncelle',configureProcess:'Süreci yapılandır',cancelChange:'Değişiklikleri iptal et',step:'Adım',asksDecision:'Onay ister',supportTools:'Geçiş ve destek araçları',
  },
};

export const getAgentDeepCopy = (language: Language) => copy[language];
