import type { Language } from './LanguageContext';

type AgentsWorkspaceCopy = {
  title: string; description: string; refresh: string; create: string; signalTitle: string; signalDescription: string;
  maps: string; mapsHint: string; social: string; socialHint: string; news: string; newsHint: string; automate: string; automateHint: string;
  today: string; completed: string; results: string; decisions: string; errors: string; search: string;
  filters: [string, string, string, string]; selectBusiness: string; selectBusinessHint: string; emptyTitle: string; emptyHint: string;
};

type AgentsWorkspaceSupplementalCopy = {
  errorTitle: string;
  loadError: string;
  employees: string;
  employeeDescription: string;
  loadingEmployees: string;
  emptyEmployees: string;
};

const copy: Record<Language, AgentsWorkspaceCopy> = {
  ru: { title: 'Агенты', description: 'Задачи, которые LocalOS выполняет один раз, по кнопке или по расписанию.', refresh: 'Обновить', create: 'Создать агента', signalTitle: 'Сигналы превращаются в выполненную работу', signalDescription: 'Владелец видит, что происходит в картах, соцсетях и новостях. Агенты берут повторяющиеся действия на себя, а важные внешние шаги ждут подтверждения.', maps: 'Карты и отзывы', mapsHint: 'Изменения карточки, рейтинг и вопросы клиентов', social: 'Соцсети', socialHint: 'Упоминания, вопросы и темы аудитории', news: 'Новости и контент', newsHint: 'Поводы, черновики и очередь публикаций', automate: 'Агенты', automateHint: 'Выполнение, результат и ручное подтверждение', today: 'Сегодня', completed: 'выполнено', results: 'результатов', decisions: 'ждут решения', errors: 'ошибок', search: 'Найти агента', filters: ['Все', 'Работают', 'Нужны действия', 'Выполненные'], selectBusiness: 'Сначала выберите бизнес', selectBusinessHint: 'Агенты всегда привязаны к конкретному бизнесу и его правам доступа.', emptyTitle: 'Создайте первого агента', emptyHint: 'После создания LocalOS откроет карточку и покажет один следующий шаг.' },
  en: { title: 'Agents', description: 'Tasks LocalOS runs once, on demand, or on schedule.', refresh: 'Refresh', create: 'Create agent', signalTitle: 'Signals become completed work', signalDescription: 'The owner sees what is happening across maps, social channels, and news. Agents handle repeatable actions, while important external steps wait for approval.', maps: 'Maps and reviews', mapsHint: 'Listing changes, ratings, and customer questions', social: 'Social channels', socialHint: 'Mentions, questions, and audience topics', news: 'News and content', newsHint: 'Opportunities, drafts, and the publishing queue', automate: 'Agents', automateHint: 'Execution, result, and manual approval', today: 'Today', completed: 'completed', results: 'results', decisions: 'awaiting decisions', errors: 'errors', search: 'Find an agent', filters: ['All', 'Working', 'Needs action', 'Completed'], selectBusiness: 'Select a business first', selectBusinessHint: 'Agents are always tied to a business and its access rights.', emptyTitle: 'Create your first agent', emptyHint: 'LocalOS will open its card and show one clear next step.' },
  fr: { title: 'Agents', description: 'Tâches exécutées une fois, à la demande ou selon un calendrier.', refresh: 'Actualiser', create: 'Créer un agent', signalTitle: 'Les signaux deviennent du travail accompli', signalDescription: 'Le propriétaire suit les cartes, réseaux sociaux et actualités. Les agents gèrent les actions répétitives ; les étapes externes importantes attendent une validation.', maps: 'Cartes et avis', mapsHint: 'Modifications, note et questions clients', social: 'Réseaux sociaux', socialHint: 'Mentions, questions et sujets du public', news: 'Actualités et contenu', newsHint: 'Opportunités, brouillons et file de publication', automate: 'Agents', automateHint: 'Exécution, résultat et validation manuelle', today: 'Aujourd’hui', completed: 'terminés', results: 'résultats', decisions: 'à valider', errors: 'erreurs', search: 'Rechercher un agent', filters: ['Tous', 'Actifs', 'Action requise', 'Terminés'], selectBusiness: 'Sélectionnez d’abord une entreprise', selectBusinessHint: 'Chaque agent dépend d’une entreprise et de ses droits.', emptyTitle: 'Créez votre premier agent', emptyHint: 'LocalOS ouvrira sa fiche et affichera la prochaine étape.' },
  es: { title: 'Agentes', description: 'Tareas que LocalOS ejecuta una vez, bajo demanda o por horario.', refresh: 'Actualizar', create: 'Crear agente', signalTitle: 'Las señales se convierten en trabajo terminado', signalDescription: 'El propietario ve mapas, redes sociales y noticias. Los agentes resuelven acciones repetitivas y los pasos externos importantes esperan aprobación.', maps: 'Mapas y reseñas', mapsHint: 'Cambios, valoración y preguntas de clientes', social: 'Redes sociales', socialHint: 'Menciones, preguntas y temas del público', news: 'Noticias y contenido', newsHint: 'Oportunidades, borradores y cola de publicación', automate: 'Agentes', automateHint: 'Ejecución, resultado y aprobación manual', today: 'Hoy', completed: 'completados', results: 'resultados', decisions: 'esperan decisión', errors: 'errores', search: 'Buscar agente', filters: ['Todos', 'Activos', 'Requieren acción', 'Completados'], selectBusiness: 'Selecciona primero un negocio', selectBusinessHint: 'Los agentes están ligados a un negocio y sus permisos.', emptyTitle: 'Crea tu primer agente', emptyHint: 'LocalOS abrirá su ficha y mostrará el siguiente paso.' },
  el: { title: 'Πράκτορες', description: 'Εργασίες που εκτελεί το LocalOS μία φορά, κατά απαίτηση ή με πρόγραμμα.', refresh: 'Ανανέωση', create: 'Δημιουργία πράκτορα', signalTitle: 'Τα σήματα γίνονται ολοκληρωμένη εργασία', signalDescription: 'Ο ιδιοκτήτης βλέπει τι συμβαίνει σε χάρτες, κοινωνικά δίκτυα και ειδήσεις. Οι πράκτορες αναλαμβάνουν τις επαναλαμβανόμενες ενέργειες, ενώ τα σημαντικά εξωτερικά βήματα περιμένουν έγκριση.', maps: 'Χάρτες και κριτικές', mapsHint: 'Αλλαγές καταχώρισης, βαθμολογία και ερωτήσεις πελατών', social: 'Κοινωνικά δίκτυα', socialHint: 'Αναφορές, ερωτήσεις και θέματα κοινού', news: 'Ειδήσεις και περιεχόμενο', newsHint: 'Αφορμές, προσχέδια και ουρά δημοσιεύσεων', automate: 'Πράκτορες', automateHint: 'Εκτέλεση, αποτέλεσμα και χειροκίνητη έγκριση', today: 'Σήμερα', completed: 'ολοκληρώθηκαν', results: 'αποτελέσματα', decisions: 'περιμένουν απόφαση', errors: 'σφάλματα', search: 'Εύρεση πράκτορα', filters: ['Όλοι', 'Ενεργοί', 'Χρειάζονται ενέργεια', 'Ολοκληρωμένοι'], selectBusiness: 'Επιλέξτε πρώτα επιχείρηση', selectBusinessHint: 'Οι πράκτορες συνδέονται πάντα με συγκεκριμένη επιχείρηση και δικαιώματα.', emptyTitle: 'Δημιουργήστε τον πρώτο πράκτορα', emptyHint: 'Το LocalOS θα ανοίξει την κάρτα του και θα δείξει ένα σαφές επόμενο βήμα.' },
  de: { title: 'Agenten', description: 'Aufgaben, die LocalOS einmalig, auf Abruf oder nach Zeitplan ausführt.', refresh: 'Aktualisieren', create: 'Agent erstellen', signalTitle: 'Signale werden zu erledigter Arbeit', signalDescription: 'Der Inhaber sieht Karten, soziale Netzwerke und Nachrichten. Agenten erledigen wiederkehrende Aktionen; wichtige externe Schritte warten auf Freigabe.', maps: 'Karten und Bewertungen', mapsHint: 'Änderungen, Bewertung und Kundenfragen', social: 'Soziale Netzwerke', socialHint: 'Erwähnungen, Fragen und Zielgruppenthemen', news: 'Nachrichten und Inhalte', newsHint: 'Anlässe, Entwürfe und Veröffentlichungsqueue', automate: 'Agenten', automateHint: 'Ausführung, Ergebnis und manuelle Freigabe', today: 'Heute', completed: 'erledigt', results: 'Ergebnisse', decisions: 'warten auf Entscheidung', errors: 'Fehler', search: 'Agent suchen', filters: ['Alle', 'Aktiv', 'Aktion nötig', 'Abgeschlossen'], selectBusiness: 'Wählen Sie zuerst ein Unternehmen', selectBusinessHint: 'Agenten sind an ein Unternehmen und dessen Rechte gebunden.', emptyTitle: 'Ersten Agenten erstellen', emptyHint: 'LocalOS öffnet seine Karte und zeigt den nächsten Schritt.' },
  th: { title: 'เอเจนต์', description: 'งานที่ LocalOS ทำครั้งเดียว ตามคำสั่ง หรือตามเวลา', refresh: 'รีเฟรช', create: 'สร้างเอเจนต์', signalTitle: 'สัญญาณกลายเป็นงานที่เสร็จ', signalDescription: 'เจ้าของเห็นสิ่งที่เกิดขึ้นบนแผนที่ โซเชียล และข่าว เอเจนต์รับช่วงงานซ้ำ ส่วนขั้นตอนภายนอกที่สำคัญรอการอนุมัติ', maps: 'แผนที่และรีวิว', mapsHint: 'การเปลี่ยนแปลง คะแนน และคำถามลูกค้า', social: 'โซเชียล', socialHint: 'การกล่าวถึง คำถาม และหัวข้อผู้ชม', news: 'ข่าวและคอนเทนต์', newsHint: 'โอกาส ร่าง และคิวเผยแพร่', automate: 'เอเจนต์', automateHint: 'การทำงาน ผลลัพธ์ และการอนุมัติด้วยคน', today: 'วันนี้', completed: 'เสร็จ', results: 'ผลลัพธ์', decisions: 'รอการตัดสินใจ', errors: 'ข้อผิดพลาด', search: 'ค้นหาเอเจนต์', filters: ['ทั้งหมด', 'กำลังทำงาน', 'ต้องดำเนินการ', 'เสร็จแล้ว'], selectBusiness: 'เลือกธุรกิจก่อน', selectBusinessHint: 'เอเจนต์เชื่อมกับธุรกิจและสิทธิ์ของธุรกิจนั้น', emptyTitle: 'สร้างเอเจนต์ตัวแรก', emptyHint: 'LocalOS จะเปิดการ์ดและแสดงขั้นตอนถัดไป' },
  ar: { title: 'الوكلاء', description: 'مهام ينفذها LocalOS مرة واحدة أو عند الطلب أو وفق جدول.', refresh: 'تحديث', create: 'إنشاء وكيل', signalTitle: 'تتحول الإشارات إلى عمل منجز', signalDescription: 'يرى المالك ما يحدث في الخرائط والشبكات الاجتماعية والأخبار. يتولى الوكلاء الإجراءات المتكررة، وتنتظر الخطوات الخارجية المهمة الموافقة.', maps: 'الخرائط والمراجعات', mapsHint: 'التغييرات والتقييم وأسئلة العملاء', social: 'الشبكات الاجتماعية', socialHint: 'الإشارات والأسئلة وموضوعات الجمهور', news: 'الأخبار والمحتوى', newsHint: 'الفرص والمسودات وطابور النشر', automate: 'الوكلاء', automateHint: 'التنفيذ والنتيجة والموافقة اليدوية', today: 'اليوم', completed: 'مكتمل', results: 'نتائج', decisions: 'بانتظار القرار', errors: 'أخطاء', search: 'البحث عن وكيل', filters: ['الكل', 'يعمل', 'يحتاج إجراء', 'مكتمل'], selectBusiness: 'اختر نشاطًا أولًا', selectBusinessHint: 'يرتبط الوكلاء بنشاط محدد وصلاحياته.', emptyTitle: 'أنشئ أول وكيل', emptyHint: 'سيفتح LocalOS بطاقته ويعرض خطوة تالية واضحة.' },
  ha: { title: 'Wakilai', description: 'Ayyukan da LocalOS ke yi sau ɗaya, bisa buƙata ko jadawali.', refresh: 'Sabunta', create: 'Ƙirƙiri wakili', signalTitle: 'Alamomi suna zama aikin da aka kammala', signalDescription: 'Mai kasuwanci yana ganin taswira, social media da labarai. Wakilai suna ɗaukar ayyukan maimaituwa; matakan waje masu muhimmanci suna jiran amincewa.', maps: 'Taswira da reviews', mapsHint: 'Canje-canje, rating da tambayoyin kwastomomi', social: 'Social media', socialHint: 'Ambato, tambayoyi da batutuwan masu sauraro', news: 'Labarai da abun ciki', newsHint: 'Damar aiki, drafts da jerin wallafawa', automate: 'Wakilai', automateHint: 'Aiki, sakamako da amincewar mutum', today: 'Yau', completed: 'an kammala', results: 'sakamako', decisions: 'suna jiran shawara', errors: 'kurakurai', search: 'Nemo wakili', filters: ['Duka', 'Suna aiki', 'Ana bukatar aiki', 'An kammala'], selectBusiness: 'Zaɓi kasuwanci da farko', selectBusinessHint: 'Wakilai suna haɗe da takamaiman kasuwanci da izininsa.', emptyTitle: 'Ƙirƙiri wakili na farko', emptyHint: 'LocalOS zai buɗe kat ɗinsa ya nuna mataki na gaba.' },
  tr: { title: 'Ajanlar', description: 'LocalOS’un bir kez, talep üzerine veya zamanlamayla yürüttüğü görevler.', refresh: 'Yenile', create: 'Ajan oluştur', signalTitle: 'Sinyaller tamamlanan işe dönüşür', signalDescription: 'İşletme sahibi haritalar, sosyal medya ve haberlerde olanları görür. Ajanlar tekrarlanan eylemleri üstlenir; önemli dış adımlar onay bekler.', maps: 'Haritalar ve yorumlar', mapsHint: 'Kayıt değişiklikleri, puan ve müşteri soruları', social: 'Sosyal medya', socialHint: 'Bahsetmeler, sorular ve kitle konuları', news: 'Haberler ve içerik', newsHint: 'Fırsatlar, taslaklar ve yayın sırası', automate: 'Ajanlar', automateHint: 'Çalışma, sonuç ve manuel onay', today: 'Bugün', completed: 'tamamlandı', results: 'sonuç', decisions: 'karar bekliyor', errors: 'hata', search: 'Ajan bul', filters: ['Tümü', 'Çalışıyor', 'Eylem gerekli', 'Tamamlanan'], selectBusiness: 'Önce bir işletme seçin', selectBusinessHint: 'Ajanlar belirli bir işletmeye ve izinlerine bağlıdır.', emptyTitle: 'İlk ajanınızı oluşturun', emptyHint: 'LocalOS kartını açar ve net bir sonraki adım gösterir.' },
};

const clarityCopy: Record<Language, Partial<AgentsWorkspaceCopy>> = {
  ru: { title: 'Автоматизация задач', description: 'Передайте LocalOS регулярные проверки и подготовку материалов. Вы увидите готовый результат и подтвердите действия, которые затрагивают клиентов.', create: 'Настроить задачу', signalTitle: 'Что LocalOS может сделать за вас', signalDescription: 'LocalOS следит за картами, отзывами, соцсетями и новостями. Когда появляется задача, он готовит ответ, публикацию или список изменений. Перед отправкой и публикацией вы всё проверяете.', automate: 'Готовый результат', automateHint: 'Что подготовлено и что ждёт вашего подтверждения', search: 'Найти задачу', selectBusinessHint: 'Каждая автоматизированная задача относится к выбранному бизнесу и использует только разрешённые данные.', emptyTitle: 'Настройте первую задачу', emptyHint: 'Выберите, что LocalOS должен проверять и какой результат готовить.' },
  en: { title: 'Task automation', description: 'Let LocalOS handle regular checks and prepare materials. You see the finished result and approve anything that affects customers.', create: 'Set up a task', signalTitle: 'What LocalOS can do for you', signalDescription: 'LocalOS watches maps, reviews, social channels, and news. When work is needed, it prepares a reply, publication, or list of changes. You review everything before it is sent or published.', automate: 'Prepared result', automateHint: 'What is ready and what needs your approval', search: 'Find a task', selectBusinessHint: 'Each automated task belongs to the selected business and uses only permitted data.', emptyTitle: 'Set up your first task', emptyHint: 'Choose what LocalOS should check and what result it should prepare.' },
  fr: { title: 'Automatisation des tâches', description: 'Confiez à LocalOS les contrôles réguliers et la préparation des contenus. Vous voyez le résultat final et validez toute action qui concerne vos clients.', create: 'Configurer une tâche', signalTitle: 'Ce que LocalOS peut faire pour vous', signalDescription: 'LocalOS surveille les cartes, les avis, les réseaux sociaux et les actualités. Lorsqu’une action est nécessaire, il prépare une réponse, une publication ou une liste de modifications. Vous vérifiez tout avant l’envoi ou la publication.', automate: 'Résultat préparé', automateHint: 'Ce qui est prêt et ce qui attend votre validation', search: 'Rechercher une tâche', selectBusinessHint: 'Chaque tâche automatisée appartient à l’entreprise sélectionnée et utilise uniquement les données autorisées.', emptyTitle: 'Configurez votre première tâche', emptyHint: 'Choisissez ce que LocalOS doit contrôler et quel résultat il doit préparer.' },
  es: { title: 'Automatización de tareas', description: 'Deja que LocalOS haga las revisiones periódicas y prepare los materiales. Verás el resultado terminado y aprobarás cualquier acción que afecte a tus clientes.', create: 'Configurar una tarea', signalTitle: 'Qué puede hacer LocalOS por ti', signalDescription: 'LocalOS revisa mapas, reseñas, redes sociales y noticias. Cuando hace falta actuar, prepara una respuesta, una publicación o una lista de cambios. Tú lo revisas antes de enviar o publicar.', automate: 'Resultado preparado', automateHint: 'Qué está listo y qué necesita tu aprobación', search: 'Buscar una tarea', selectBusinessHint: 'Cada tarea automática pertenece al negocio elegido y solo usa los datos permitidos.', emptyTitle: 'Configura tu primera tarea', emptyHint: 'Elige qué debe revisar LocalOS y qué resultado debe preparar.' },
  el: { title: 'Αυτοματοποίηση εργασιών', description: 'Αναθέστε στο LocalOS τους τακτικούς ελέγχους και την προετοιμασία υλικού. Βλέπετε το έτοιμο αποτέλεσμα και εγκρίνετε κάθε ενέργεια που επηρεάζει πελάτες.', create: 'Ρύθμιση εργασίας', signalTitle: 'Τι μπορεί να κάνει το LocalOS για εσάς', signalDescription: 'Το LocalOS παρακολουθεί χάρτες, κριτικές, κοινωνικά δίκτυα και ειδήσεις. Όταν χρειάζεται ενέργεια, ετοιμάζει απάντηση, δημοσίευση ή λίστα αλλαγών. Εσείς ελέγχετε τα πάντα πριν από αποστολή ή δημοσίευση.', automate: 'Έτοιμο αποτέλεσμα', automateHint: 'Τι είναι έτοιμο και τι περιμένει την έγκρισή σας', search: 'Εύρεση εργασίας', selectBusinessHint: 'Κάθε αυτοματοποιημένη εργασία ανήκει στην επιλεγμένη επιχείρηση και χρησιμοποιεί μόνο επιτρεπόμενα δεδομένα.', emptyTitle: 'Ρυθμίστε την πρώτη εργασία', emptyHint: 'Επιλέξτε τι θα ελέγχει το LocalOS και ποιο αποτέλεσμα θα ετοιμάζει.' },
  de: { title: 'Aufgaben automatisieren', description: 'Überlassen Sie LocalOS regelmäßige Prüfungen und die Vorbereitung von Inhalten. Sie sehen das fertige Ergebnis und geben alles frei, was Kunden betrifft.', create: 'Aufgabe einrichten', signalTitle: 'Was LocalOS für Sie erledigen kann', signalDescription: 'LocalOS beobachtet Karten, Bewertungen, soziale Kanäle und Nachrichten. Wenn etwas zu tun ist, bereitet es eine Antwort, einen Beitrag oder eine Änderungsliste vor. Vor Versand oder Veröffentlichung prüfen Sie alles.', automate: 'Vorbereitetes Ergebnis', automateHint: 'Was fertig ist und was Ihre Freigabe braucht', search: 'Aufgabe suchen', selectBusinessHint: 'Jede automatisierte Aufgabe gehört zum ausgewählten Unternehmen und nutzt nur erlaubte Daten.', emptyTitle: 'Erste Aufgabe einrichten', emptyHint: 'Wählen Sie, was LocalOS prüfen und welches Ergebnis es vorbereiten soll.' },
  th: { title: 'งานอัตโนมัติ', description: 'ให้ LocalOS ตรวจข้อมูลตามรอบและเตรียมเนื้อหา คุณจะเห็นผลลัพธ์ที่พร้อมใช้และอนุมัติทุกการกระทำที่เกี่ยวข้องกับลูกค้า', create: 'ตั้งค่างาน', signalTitle: 'LocalOS ช่วยทำอะไรให้คุณได้บ้าง', signalDescription: 'LocalOS ติดตามแผนที่ รีวิว โซเชียล และข่าว เมื่อมีงานที่ต้องทำ ระบบจะเตรียมคำตอบ โพสต์ หรือรายการแก้ไขให้ คุณตรวจสอบก่อนส่งหรือเผยแพร่ทุกครั้ง', automate: 'ผลลัพธ์ที่เตรียมแล้ว', automateHint: 'สิ่งที่พร้อมและสิ่งที่รอการอนุมัติจากคุณ', search: 'ค้นหางาน', selectBusinessHint: 'งานอัตโนมัติแต่ละงานผูกกับธุรกิจที่เลือกและใช้เฉพาะข้อมูลที่ได้รับอนุญาต', emptyTitle: 'ตั้งค่างานแรก', emptyHint: 'เลือกสิ่งที่ LocalOS ต้องตรวจและผลลัพธ์ที่ต้องเตรียม' },
  ar: { title: 'أتمتة المهام', description: 'دع LocalOS يتولى الفحوص الدورية وإعداد المواد. سترى النتيجة الجاهزة وتوافق على أي إجراء يؤثر في العملاء.', create: 'إعداد مهمة', signalTitle: 'ما الذي يمكن أن ينجزه LocalOS لك', signalDescription: 'يتابع LocalOS الخرائط والمراجعات والشبكات الاجتماعية والأخبار. وعندما يلزم إجراء، يجهز ردًا أو منشورًا أو قائمة تغييرات. تراجع كل شيء قبل الإرسال أو النشر.', automate: 'النتيجة الجاهزة', automateHint: 'ما أصبح جاهزًا وما ينتظر موافقتك', search: 'البحث عن مهمة', selectBusinessHint: 'ترتبط كل مهمة آلية بالنشاط المحدد ولا تستخدم إلا البيانات المسموح بها.', emptyTitle: 'أعد مهمتك الأولى', emptyHint: 'اختر ما الذي يفحصه LocalOS وما النتيجة التي يجهزها.' },
  ha: { title: 'Sarrafa ayyuka ta atomatik', description: 'Bari LocalOS ya riƙa duba bayanai da shirya kayan aiki. Za ka ga sakamakon da aka gama kuma ka amince da duk abin da zai shafi kwastomomi.', create: 'Saita aiki', signalTitle: 'Abin da LocalOS zai iya yi maka', signalDescription: 'LocalOS yana lura da taswira, sharhi, kafofin sada zumunta da labarai. Idan akwai aiki, yana shirya amsa, wallafa ko jerin gyare-gyare. Kai ne ke dubawa kafin aikawa ko wallafawa.', automate: 'Sakamakon da aka shirya', automateHint: 'Abin da ya shirya da abin da ke jiran amincewarka', search: 'Nemo aiki', selectBusinessHint: 'Kowane aiki na atomatik yana da alaƙa da kasuwancin da aka zaɓa kuma yana amfani da bayanan da aka yarda kawai.', emptyTitle: 'Saita aiki na farko', emptyHint: 'Zaɓi abin da LocalOS zai duba da sakamakon da zai shirya.' },
  tr: { title: 'Görev otomasyonu', description: 'Düzenli kontrolleri ve içerik hazırlığını LocalOS’a bırakın. Hazır sonucu görün; müşterileri etkileyen her işlemi siz onaylayın.', create: 'Görev ayarla', signalTitle: 'LocalOS sizin için ne yapabilir?', signalDescription: 'LocalOS haritaları, yorumları, sosyal kanalları ve haberleri izler. Bir iş gerektiğinde yanıt, yayın veya değişiklik listesi hazırlar. Gönderim ya da yayın öncesinde her şeyi siz kontrol edersiniz.', automate: 'Hazırlanan sonuç', automateHint: 'Hazır olanlar ve onayınızı bekleyenler', search: 'Görev bul', selectBusinessHint: 'Her otomatik görev seçilen işletmeye bağlıdır ve yalnızca izin verilen verileri kullanır.', emptyTitle: 'İlk görevinizi ayarlayın', emptyHint: 'LocalOS’un neyi kontrol edeceğini ve hangi sonucu hazırlayacağını seçin.' },
};

const supplementalCopy: Record<Language, AgentsWorkspaceSupplementalCopy> = {
  ru: { errorTitle: 'Ошибка', loadError: 'Не удалось загрузить агентов.', employees: 'Сотрудники', employeeDescription: 'Тип, состояние и следующий шаг', loadingEmployees: 'Загружаем сотрудников...', emptyEmployees: 'Создайте первого сотрудника.' },
  en: { errorTitle: 'Error', loadError: 'Could not load agents.', employees: 'Team members', employeeDescription: 'Type, status, and next step', loadingEmployees: 'Loading team members...', emptyEmployees: 'Create your first team member.' },
  fr: { errorTitle: 'Erreur', loadError: 'Impossible de charger les agents.', employees: 'Collaborateurs', employeeDescription: 'État et prochaine étape', loadingEmployees: 'Chargement des collaborateurs...', emptyEmployees: 'Créez votre premier collaborateur.' },
  es: { errorTitle: 'Error', loadError: 'No se pudieron cargar los agentes.', employees: 'Colaboradores', employeeDescription: 'Tipo, estado y siguiente paso', loadingEmployees: 'Cargando colaboradores...', emptyEmployees: 'Crea tu primer colaborador.' },
  el: { errorTitle: 'Σφάλμα', loadError: 'Δεν ήταν δυνατή η φόρτωση των πρακτόρων.', employees: 'Συνεργάτες', employeeDescription: 'Τύπος, κατάσταση και επόμενο βήμα', loadingEmployees: 'Φόρτωση συνεργατών...', emptyEmployees: 'Δημιουργήστε τον πρώτο συνεργάτη.' },
  de: { errorTitle: 'Fehler', loadError: 'Agenten konnten nicht geladen werden.', employees: 'Mitarbeitende', employeeDescription: 'Typ, Status und nächster Schritt', loadingEmployees: 'Mitarbeitende werden geladen...', emptyEmployees: 'Erstellen Sie den ersten Mitarbeitenden.' },
  th: { errorTitle: 'ข้อผิดพลาด', loadError: 'โหลดเอเจนต์ไม่สำเร็จ', employees: 'ผู้ช่วย', employeeDescription: 'ประเภท สถานะ และขั้นตอนถัดไป', loadingEmployees: 'กำลังโหลดผู้ช่วย...', emptyEmployees: 'สร้างผู้ช่วยคนแรก' },
  ar: { errorTitle: 'خطأ', loadError: 'تعذر تحميل الوكلاء.', employees: 'المساعدون', employeeDescription: 'النوع والحالة والخطوة التالية', loadingEmployees: 'جاري تحميل المساعدين...', emptyEmployees: 'أنشئ أول مساعد.' },
  ha: { errorTitle: 'Kuskure', loadError: 'Ba a iya loda wakilai ba.', employees: 'Ma’aikata', employeeDescription: 'Nau’i, matsayi da mataki na gaba', loadingEmployees: 'Ana loda ma’aikata...', emptyEmployees: 'Ƙirƙiri ma’aikaci na farko.' },
  tr: { errorTitle: 'Hata', loadError: 'Ajanlar yüklenemedi.', employees: 'Çalışanlar', employeeDescription: 'Tür, durum ve sonraki adım', loadingEmployees: 'Çalışanlar yükleniyor...', emptyEmployees: 'İlk çalışanınızı oluşturun.' },
};

const supplementalClarityCopy: Record<Language, AgentsWorkspaceSupplementalCopy> = {
  ru: { errorTitle: 'Ошибка', loadError: 'Не удалось загрузить настройки автоматизации.', employees: 'Автоматизированные задачи', employeeDescription: 'Что выполняется, состояние и следующий шаг', loadingEmployees: 'Загружаем задачи...', emptyEmployees: 'Настройте первую задачу.' },
  en: { errorTitle: 'Error', loadError: 'Could not load automation settings.', employees: 'Automated tasks', employeeDescription: 'What runs, its status, and the next step', loadingEmployees: 'Loading tasks...', emptyEmployees: 'Set up your first task.' },
  fr: { errorTitle: 'Erreur', loadError: 'Impossible de charger les réglages d’automatisation.', employees: 'Tâches automatisées', employeeDescription: 'Travail effectué, état et prochaine étape', loadingEmployees: 'Chargement des tâches...', emptyEmployees: 'Configurez votre première tâche.' },
  es: { errorTitle: 'Error', loadError: 'No se pudo cargar la automatización.', employees: 'Tareas automáticas', employeeDescription: 'Qué se hace, estado y siguiente paso', loadingEmployees: 'Cargando tareas...', emptyEmployees: 'Configura tu primera tarea.' },
  el: { errorTitle: 'Σφάλμα', loadError: 'Δεν ήταν δυνατή η φόρτωση των ρυθμίσεων αυτοματοποίησης.', employees: 'Αυτοματοποιημένες εργασίες', employeeDescription: 'Τι εκτελείται, κατάσταση και επόμενο βήμα', loadingEmployees: 'Φόρτωση εργασιών...', emptyEmployees: 'Ρυθμίστε την πρώτη εργασία.' },
  de: { errorTitle: 'Fehler', loadError: 'Automatisierungseinstellungen konnten nicht geladen werden.', employees: 'Automatisierte Aufgaben', employeeDescription: 'Aufgabe, Status und nächster Schritt', loadingEmployees: 'Aufgaben werden geladen...', emptyEmployees: 'Richten Sie Ihre erste Aufgabe ein.' },
  th: { errorTitle: 'ข้อผิดพลาด', loadError: 'โหลดการตั้งค่างานอัตโนมัติไม่สำเร็จ', employees: 'งานอัตโนมัติ', employeeDescription: 'งานที่ทำ สถานะ และขั้นตอนถัดไป', loadingEmployees: 'กำลังโหลดงาน...', emptyEmployees: 'ตั้งค่างานแรก' },
  ar: { errorTitle: 'خطأ', loadError: 'تعذر تحميل إعدادات الأتمتة.', employees: 'المهام الآلية', employeeDescription: 'ما يتم تنفيذه والحالة والخطوة التالية', loadingEmployees: 'جاري تحميل المهام...', emptyEmployees: 'أعد مهمتك الأولى.' },
  ha: { errorTitle: 'Kuskure', loadError: 'Ba a iya loda saitunan aiki ta atomatik ba.', employees: 'Ayyuka na atomatik', employeeDescription: 'Abin da ake yi, matsayi da mataki na gaba', loadingEmployees: 'Ana loda ayyuka...', emptyEmployees: 'Saita aiki na farko.' },
  tr: { errorTitle: 'Hata', loadError: 'Otomasyon ayarları yüklenemedi.', employees: 'Otomatik görevler', employeeDescription: 'Yapılan iş, durum ve sonraki adım', loadingEmployees: 'Görevler yükleniyor...', emptyEmployees: 'İlk görevinizi ayarlayın.' },
};

export const getAgentsWorkspaceCopy = (language: Language): AgentsWorkspaceCopy & AgentsWorkspaceSupplementalCopy => ({
  ...copy[language],
  ...clarityCopy[language],
  ...supplementalCopy[language],
  ...supplementalClarityCopy[language],
});
