import type { Language } from '@/i18n/LanguageContext';

export type AIChatPromotionCopy = {
  title: string;
  subtitle: string;
  whyTitle: string;
  whyDescription: string;
  step: string;
  completed: string;
  todo: string;
  links: string;
  code: string;
  copy: string;
  copied: string;
  progressTitle: string;
  progressCompleted: string;
  progressFrom: string;
  success: string;
};

const copy: Record<Language, AIChatPromotionCopy> = {
  ru: { title: 'GEO-продвижение', subtitle: 'Пошаговая подготовка бизнеса к показу в ChatGPT и других ИИ-помощниках', whyTitle: 'Почему это важно?', whyDescription: 'Люди всё чаще ищут компании через ИИ-помощников. Последовательные и понятные данные о бизнесе повышают шанс попасть в их ответы.', step: 'Шаг', completed: 'Готово', todo: 'Что сделать:', links: 'Полезные ссылки:', code: 'Пример кода:', copy: 'Копировать', copied: 'Скопировано', progressTitle: 'Прогресс', progressCompleted: 'Выполнено шагов:', progressFrom: 'из', success: 'Все шаги выполнены. Данные бизнеса подготовлены для поиска через ИИ.' },
  en: { title: 'AI Chat Promotion', subtitle: 'A step-by-step guide to making your business visible in ChatGPT and other AI assistants', whyTitle: 'Why is this important?', whyDescription: 'People increasingly discover businesses through AI assistants. Consistent, clear business data improves your chances of appearing in their answers.', step: 'Step', completed: 'Completed', todo: 'What to do:', links: 'Useful links:', code: 'Code example:', copy: 'Copy', copied: 'Copied', progressTitle: 'Progress', progressCompleted: 'Steps completed:', progressFrom: 'of', success: 'All steps are complete. Your business data is ready for AI search.' },
  fr: { title: 'Promotion dans les chats IA', subtitle: 'Un guide étape par étape pour rendre votre entreprise visible dans ChatGPT et les autres assistants IA', whyTitle: 'Pourquoi est-ce important ?', whyDescription: 'Les clients découvrent de plus en plus les entreprises via les assistants IA. Des données cohérentes et claires augmentent vos chances d’apparaître dans leurs réponses.', step: 'Étape', completed: 'Terminé', todo: 'À faire :', links: 'Liens utiles :', code: 'Exemple de code :', copy: 'Copier', copied: 'Copié', progressTitle: 'Progression', progressCompleted: 'Étapes terminées :', progressFrom: 'sur', success: 'Toutes les étapes sont terminées. Les données de votre entreprise sont prêtes pour la recherche IA.' },
  es: { title: 'Promoción en chats de IA', subtitle: 'Guía paso a paso para que tu negocio aparezca en ChatGPT y otros asistentes de IA', whyTitle: '¿Por qué es importante?', whyDescription: 'Cada vez más clientes descubren negocios mediante asistentes de IA. Los datos claros y coherentes aumentan la posibilidad de aparecer en sus respuestas.', step: 'Paso', completed: 'Completado', todo: 'Qué hacer:', links: 'Enlaces útiles:', code: 'Ejemplo de código:', copy: 'Copiar', copied: 'Copiado', progressTitle: 'Progreso', progressCompleted: 'Pasos completados:', progressFrom: 'de', success: 'Todos los pasos están completados. Los datos del negocio están listos para la búsqueda con IA.' },
  el: { title: 'Προώθηση σε συνομιλίες AI', subtitle: 'Οδηγός βήμα προς βήμα για να εμφανίζεται η επιχείρησή σας στο ChatGPT και σε άλλους βοηθούς AI', whyTitle: 'Γιατί είναι σημαντικό;', whyDescription: 'Οι πελάτες βρίσκουν όλο και συχνότερα επιχειρήσεις μέσω βοηθών AI. Τα σαφή και συνεπή δεδομένα αυξάνουν την πιθανότητα εμφάνισης στις απαντήσεις τους.', step: 'Βήμα', completed: 'Ολοκληρώθηκε', todo: 'Τι να κάνετε:', links: 'Χρήσιμοι σύνδεσμοι:', code: 'Παράδειγμα κώδικα:', copy: 'Αντιγραφή', copied: 'Αντιγράφηκε', progressTitle: 'Πρόοδος', progressCompleted: 'Ολοκληρωμένα βήματα:', progressFrom: 'από', success: 'Όλα τα βήματα ολοκληρώθηκαν. Τα δεδομένα της επιχείρησης είναι έτοιμα για αναζήτηση μέσω AI.' },
  de: { title: 'KI-Chat-Promotion', subtitle: 'Schritt-für-Schritt-Anleitung für mehr Sichtbarkeit in ChatGPT und anderen KI-Assistenten', whyTitle: 'Warum ist das wichtig?', whyDescription: 'Kunden entdecken Unternehmen zunehmend über KI-Assistenten. Klare und einheitliche Unternehmensdaten erhöhen die Chance, in Antworten zu erscheinen.', step: 'Schritt', completed: 'Erledigt', todo: 'Was ist zu tun:', links: 'Nützliche Links:', code: 'Codebeispiel:', copy: 'Kopieren', copied: 'Kopiert', progressTitle: 'Fortschritt', progressCompleted: 'Erledigte Schritte:', progressFrom: 'von', success: 'Alle Schritte sind abgeschlossen. Ihre Unternehmensdaten sind für die KI-Suche vorbereitet.' },
  th: { title: 'การโปรโมตผ่านแชต AI', subtitle: 'คำแนะนำทีละขั้นเพื่อให้ธุรกิจปรากฏใน ChatGPT และผู้ช่วย AI อื่น ๆ', whyTitle: 'ทำไมจึงสำคัญ?', whyDescription: 'ลูกค้าค้นพบธุรกิจผ่านผู้ช่วย AI มากขึ้น ข้อมูลธุรกิจที่ชัดเจนและสอดคล้องช่วยเพิ่มโอกาสให้ปรากฏในคำตอบ', step: 'ขั้นตอน', completed: 'เสร็จแล้ว', todo: 'สิ่งที่ต้องทำ:', links: 'ลิงก์ที่เป็นประโยชน์:', code: 'ตัวอย่างโค้ด:', copy: 'คัดลอก', copied: 'คัดลอกแล้ว', progressTitle: 'ความคืบหน้า', progressCompleted: 'ขั้นตอนที่เสร็จแล้ว:', progressFrom: 'จาก', success: 'ทำครบทุกขั้นตอนแล้ว ข้อมูลธุรกิจพร้อมสำหรับการค้นหาด้วย AI' },
  ar: { title: 'الترويج عبر محادثات الذكاء الاصطناعي', subtitle: 'دليل خطوة بخطوة لإظهار نشاطك في ChatGPT ومساعدات الذكاء الاصطناعي الأخرى', whyTitle: 'لماذا هذا مهم؟', whyDescription: 'يكتشف العملاء الأنشطة التجارية عبر مساعدات الذكاء الاصطناعي بشكل متزايد. ترفع البيانات الواضحة والمتسقة فرصة ظهور نشاطك في الإجابات.', step: 'الخطوة', completed: 'مكتملة', todo: 'ما يجب فعله:', links: 'روابط مفيدة:', code: 'مثال للكود:', copy: 'نسخ', copied: 'تم النسخ', progressTitle: 'التقدم', progressCompleted: 'الخطوات المكتملة:', progressFrom: 'من', success: 'اكتملت جميع الخطوات. بيانات النشاط جاهزة للبحث عبر الذكاء الاصطناعي.' },
  ha: { title: 'Tallatawa a hirar AI', subtitle: 'Jagora mataki-mataki don bayyana kasuwancinka a ChatGPT da sauran mataimakan AI', whyTitle: 'Me ya sa wannan yake da muhimmanci?', whyDescription: 'Abokan ciniki suna ƙara gano kasuwanci ta mataimakan AI. Bayani mai kyau da daidaito yana ƙara damar bayyana a amsoshinsu.', step: 'Mataki', completed: 'An kammala', todo: 'Abin da za a yi:', links: 'Hanyoyin haɗi masu amfani:', code: 'Misalin lamba:', copy: 'Kwafa', copied: 'An kwafa', progressTitle: 'Ci gaba', progressCompleted: 'Matakan da aka kammala:', progressFrom: 'cikin', success: 'An kammala duk matakai. Bayanan kasuwanci sun shirya don binciken AI.' },
  tr: { title: 'AI Sohbet Tanıtımı', subtitle: 'İşletmenizi ChatGPT ve diğer AI asistanlarında görünür kılmak için adım adım rehber', whyTitle: 'Bu neden önemli?', whyDescription: 'Müşteriler işletmeleri giderek daha fazla AI asistanlarıyla keşfediyor. Açık ve tutarlı işletme bilgileri yanıtlarda görünme şansını artırır.', step: 'Adım', completed: 'Tamamlandı', todo: 'Yapılacaklar:', links: 'Yararlı bağlantılar:', code: 'Kod örneği:', copy: 'Kopyala', copied: 'Kopyalandı', progressTitle: 'İlerleme', progressCompleted: 'Tamamlanan adımlar:', progressFrom: '/', success: 'Tüm adımlar tamamlandı. İşletme bilgileriniz AI araması için hazır.' },
};

export const getAIChatPromotionCopy = (language: Language) => copy[language];
