import type { Language } from './LanguageContext';

export interface ChatsWorkspaceCopy {
  tabsLabel: string;
  dialogs: string;
  agentSandbox: string;
  outreachSandbox: string;
  agents: string;
  marketingAgent: string;
  bookingAgent: string;
  chats: string;
  noChats: string;
  selectWorkspace: string;
  sandboxTitle: string;
  sandboxSubtitle: string;
  noAgent: string;
  sandboxEmpty: string;
  sandboxPlaceholder: string;
  user: string;
  agent: string;
  agentTyping: string;
  dryRunTitle: string;
  dryRunDescription: string;
}

const copy: Record<Language, ChatsWorkspaceCopy> = {
  ru: { tabsLabel: 'Разделы чатов', dialogs: 'Диалоги', agentSandbox: 'Проверить агента', outreachSandbox: 'Проверить рассылку', agents: 'Агенты', marketingAgent: 'Контент и продвижение', bookingAgent: 'Запись клиентов', chats: 'Диалоги', noChats: 'Нет активных диалогов', selectWorkspace: 'Выберите диалог или режим проверки', sandboxTitle: 'Проверка агента', sandboxSubtitle: 'Выбранный агент', noAgent: 'Сначала выберите агента', sandboxEmpty: 'Напишите сообщение, чтобы проверить ответ агента до запуска.', sandboxPlaceholder: 'Введите сообщение клиента…', user: 'Клиент', agent: 'Агент', agentTyping: 'Агент готовит ответ…', dryRunTitle: 'Без отправки клиенту', dryRunDescription: 'Здесь можно проверить ответ. LocalOS ничего не отправит в Telegram, WhatsApp или по электронной почте.' },
  en: { tabsLabel: 'Chat sections', dialogs: 'Conversations', agentSandbox: 'Test an agent', outreachSandbox: 'Test outreach', agents: 'Agents', marketingAgent: 'Content and promotion', bookingAgent: 'Customer booking', chats: 'Conversations', noChats: 'No active conversations', selectWorkspace: 'Select a conversation or test mode', sandboxTitle: 'Agent test', sandboxSubtitle: 'Selected agent', noAgent: 'Select an agent first', sandboxEmpty: 'Write a message to check the agent’s reply before launch.', sandboxPlaceholder: 'Enter a customer message…', user: 'Customer', agent: 'Agent', agentTyping: 'The agent is preparing a reply…', dryRunTitle: 'Nothing is sent to the customer', dryRunDescription: 'Check the reply here. LocalOS will not send anything to Telegram, WhatsApp or email.' },
  de: { tabsLabel: 'Chatbereiche', dialogs: 'Gespräche', agentSandbox: 'Agent testen', outreachSandbox: 'Nachrichten testen', agents: 'Agenten', marketingAgent: 'Inhalte und Werbung', bookingAgent: 'Kundentermine', chats: 'Gespräche', noChats: 'Keine aktiven Chats', selectWorkspace: 'Wählen Sie einen Chat oder Testbereich aus', sandboxTitle: 'Agent testen', sandboxSubtitle: 'Ausgewählter Agent', noAgent: 'Wählen Sie zuerst einen Agenten aus', sandboxEmpty: 'Schreiben Sie eine Nachricht, um die Antwort vor dem Start zu prüfen.', sandboxPlaceholder: 'Kundennachricht eingeben…', user: 'Kunde', agent: 'Agent', agentTyping: 'Der Agent bereitet eine Antwort vor…', dryRunTitle: 'Keine Nachricht wird versendet', dryRunDescription: 'Prüfen Sie die Antwort hier. LocalOS sendet nichts an Telegram, WhatsApp oder per E-Mail.' },
  fr: { tabsLabel: 'Sections des conversations', dialogs: 'Conversations', agentSandbox: 'Tester un agent', outreachSandbox: 'Tester les messages', agents: 'Agents', marketingAgent: 'Contenu et promotion', bookingAgent: 'Prise de rendez-vous', chats: 'Conversations', noChats: 'Aucune conversation active', selectWorkspace: 'Sélectionnez une conversation ou un mode de test', sandboxTitle: 'Test de l’agent', sandboxSubtitle: 'Agent sélectionné', noAgent: 'Sélectionnez d’abord un agent', sandboxEmpty: 'Écrivez un message pour vérifier la réponse avant le lancement.', sandboxPlaceholder: 'Saisissez le message d’un client…', user: 'Client', agent: 'Agent', agentTyping: 'L’agent prépare une réponse…', dryRunTitle: 'Aucun message n’est envoyé', dryRunDescription: 'Vérifiez la réponse ici. LocalOS n’enverra rien sur Telegram, WhatsApp ou par e-mail.' },
  es: { tabsLabel: 'Secciones de conversaciones', dialogs: 'Conversaciones', agentSandbox: 'Probar un agente', outreachSandbox: 'Probar mensajes', agents: 'Agentes', marketingAgent: 'Contenido y promoción', bookingAgent: 'Reservas de clientes', chats: 'Conversaciones', noChats: 'No hay conversaciones activas', selectWorkspace: 'Selecciona una conversación o un modo de prueba', sandboxTitle: 'Prueba del agente', sandboxSubtitle: 'Agente seleccionado', noAgent: 'Primero selecciona un agente', sandboxEmpty: 'Escribe un mensaje para revisar la respuesta antes de activar el agente.', sandboxPlaceholder: 'Escribe el mensaje de un cliente…', user: 'Cliente', agent: 'Agente', agentTyping: 'El agente está preparando una respuesta…', dryRunTitle: 'No se envía nada al cliente', dryRunDescription: 'Revisa aquí la respuesta. LocalOS no enviará nada a Telegram, WhatsApp ni por correo electrónico.' },
  el: { tabsLabel: 'Ενότητες συνομιλιών', dialogs: 'Συνομιλίες', agentSandbox: 'Δοκιμή πράκτορα', outreachSandbox: 'Δοκιμή μηνυμάτων', agents: 'Πράκτορες', marketingAgent: 'Περιεχόμενο και προώθηση', bookingAgent: 'Κρατήσεις πελατών', chats: 'Συνομιλίες', noChats: 'Δεν υπάρχουν ενεργές συνομιλίες', selectWorkspace: 'Επιλέξτε συνομιλία ή λειτουργία δοκιμής', sandboxTitle: 'Δοκιμή πράκτορα', sandboxSubtitle: 'Επιλεγμένος πράκτορας', noAgent: 'Επιλέξτε πρώτα έναν πράκτορα', sandboxEmpty: 'Γράψτε ένα μήνυμα για να ελέγξετε την απάντηση πριν από την ενεργοποίηση.', sandboxPlaceholder: 'Γράψτε μήνυμα πελάτη…', user: 'Πελάτης', agent: 'Πράκτορας', agentTyping: 'Ο πράκτορας ετοιμάζει απάντηση…', dryRunTitle: 'Δεν αποστέλλεται μήνυμα', dryRunDescription: 'Ελέγξτε την απάντηση εδώ. Το LocalOS δεν θα στείλει τίποτα σε Telegram, WhatsApp ή email.' },
  tr: { tabsLabel: 'Sohbet bölümleri', dialogs: 'Sohbetler', agentSandbox: 'Temsilciyi dene', outreachSandbox: 'Mesajları dene', agents: 'Temsilciler', marketingAgent: 'İçerik ve tanıtım', bookingAgent: 'Müşteri randevuları', chats: 'Sohbetler', noChats: 'Aktif sohbet yok', selectWorkspace: 'Bir sohbet veya test alanı seçin', sandboxTitle: 'Temsilci testi', sandboxSubtitle: 'Seçilen temsilci', noAgent: 'Önce bir temsilci seçin', sandboxEmpty: 'Yayına almadan önce yanıtı kontrol etmek için bir mesaj yazın.', sandboxPlaceholder: 'Müşteri mesajını yazın…', user: 'Müşteri', agent: 'Temsilci', agentTyping: 'Temsilci yanıt hazırlıyor…', dryRunTitle: 'Müşteriye hiçbir şey gönderilmez', dryRunDescription: 'Yanıtı burada kontrol edin. LocalOS Telegram, WhatsApp veya e-posta üzerinden hiçbir şey göndermez.' },
  th: { tabsLabel: 'ส่วนการสนทนา', dialogs: 'การสนทนา', agentSandbox: 'ทดสอบเอเจนต์', outreachSandbox: 'ทดสอบข้อความ', agents: 'เอเจนต์', marketingAgent: 'เนื้อหาและการโปรโมต', bookingAgent: 'การจองของลูกค้า', chats: 'การสนทนา', noChats: 'ไม่มีการสนทนาที่ใช้งานอยู่', selectWorkspace: 'เลือกการสนทนาหรือโหมดทดสอบ', sandboxTitle: 'ทดสอบเอเจนต์', sandboxSubtitle: 'เอเจนต์ที่เลือก', noAgent: 'เลือกเอเจนต์ก่อน', sandboxEmpty: 'เขียนข้อความเพื่อตรวจสอบคำตอบก่อนเปิดใช้งาน', sandboxPlaceholder: 'พิมพ์ข้อความของลูกค้า…', user: 'ลูกค้า', agent: 'เอเจนต์', agentTyping: 'เอเจนต์กำลังเตรียมคำตอบ…', dryRunTitle: 'จะไม่มีการส่งข้อความถึงลูกค้า', dryRunDescription: 'ตรวจสอบคำตอบได้ที่นี่ LocalOS จะไม่ส่งข้อความไปยัง Telegram, WhatsApp หรืออีเมล' },
  ar: { tabsLabel: 'أقسام المحادثات', dialogs: 'المحادثات', agentSandbox: 'اختبار الموظف الرقمي', outreachSandbox: 'اختبار الرسائل', agents: 'الموظفون الرقميون', marketingAgent: 'المحتوى والترويج', bookingAgent: 'حجوزات العملاء', chats: 'المحادثات', noChats: 'لا توجد محادثات نشطة', selectWorkspace: 'اختر محادثة أو وضع اختبار', sandboxTitle: 'اختبار الموظف الرقمي', sandboxSubtitle: 'الموظف المحدد', noAgent: 'اختر موظفًا رقميًا أولًا', sandboxEmpty: 'اكتب رسالة للتحقق من الرد قبل التشغيل.', sandboxPlaceholder: 'اكتب رسالة العميل…', user: 'العميل', agent: 'الموظف الرقمي', agentTyping: 'يجري إعداد الرد…', dryRunTitle: 'لن تُرسل رسالة إلى العميل', dryRunDescription: 'راجع الرد هنا. لن يرسل LocalOS أي شيء عبر Telegram أو WhatsApp أو البريد الإلكتروني.' },
  ha: { tabsLabel: 'Sassan tattaunawa', dialogs: 'Tattaunawa', agentSandbox: 'Gwada wakili', outreachSandbox: 'Gwada saƙonni', agents: 'Wakilai', marketingAgent: 'Abun ciki da talla', bookingAgent: 'Ajiyar kwastomomi', chats: 'Tattaunawa', noChats: 'Babu tattaunawa mai gudana', selectWorkspace: 'Zaɓi tattaunawa ko yanayin gwaji', sandboxTitle: 'Gwajin wakili', sandboxSubtitle: 'Wakilin da aka zaɓa', noAgent: 'Da farko zaɓi wakili', sandboxEmpty: 'Rubuta saƙo don duba amsar kafin kunnawa.', sandboxPlaceholder: 'Rubuta saƙon kwastoma…', user: 'Kwastoma', agent: 'Wakili', agentTyping: 'Wakili yana shirya amsa…', dryRunTitle: 'Ba za a aika wa kwastoma komai ba', dryRunDescription: 'Duba amsar a nan. LocalOS ba zai aika komai ta Telegram, WhatsApp ko imel ba.' },
};

export const getChatsWorkspaceCopy = (language: Language) => copy[language];

export const chatDateLocale: Record<Language, string> = {
  ru: 'ru-RU', en: 'en-US', fr: 'fr-FR', es: 'es-ES', el: 'el-GR', de: 'de-DE', th: 'th-TH', ar: 'ar', ha: 'ha-NG', tr: 'tr-TR',
};
