import type { Language } from './LanguageContext';

export type ContentCalendarCopy = {
  aiResult: string;
  contentReady: string;
  preparingCalendar: string;
  filledDays: string;
  nextPublication: string;
  noDate: string;
  whatNow: string;
  whatNowHint: string;
  reviewNearest: string;
  approving: string;
  approveReady: string;
  scheduling: string;
  schedule: string;
  deletePlan: string;
  month: string;
  week: string;
  list: string;
  needsReview: string;
  underControl: string;
  today: string;
  createdPosts: string;
  requiresReview: string;
  eventSuggestion: string;
  eventReason: string;
  competitorSuggestion: string;
  competitorReason: string;
  photoSuggestion: string;
  photoReason: string;
  nextAction: string;
  reviewPosts: string;
  nearestReady: string;
  createPlan: string;
  reviewHint: string;
  nextHint: string;
  prepareHint: string;
  publication: string;
  content: string;
  channels: string;
  more: string;
  weekdays: string[];
  status: Record<string, string>;
};

const statusRu = {
  failed: 'Не удалось', place: 'Нужно разместить', review: 'Нужно проверить', scheduled: 'Запланировано', published: 'Опубликовано', draft: 'Черновик',
  textApproved: 'Текст утверждён', fix: 'Исправить', waitDate: 'Ждёт даты', done: 'Готово', chooseChannels: 'Выберите каналы', textReady: 'Текст готов',
  approveText: 'Утвердить текст', prepareChannels: 'Подготовить каналы', writeText: 'Написать текст',
};

const copy: Record<Language, ContentCalendarCopy> = {
  ru: {
    aiResult: 'Результат работы ИИ', contentReady: 'Контент готов', preparingCalendar: 'Готовим календарь', filledDays: '{filled} из {total} дней заполнены', nextPublication: 'Следующая публикация', noDate: 'нет даты', whatNow: 'Что сделать сейчас', whatNowHint: 'Быстро проверьте ближайшее, подтвердите готовое и закройте раздел.', reviewNearest: 'Проверить ближайшие', approving: 'Утверждаем...', approveReady: 'Утвердить готовое', scheduling: 'Планируем...', schedule: 'Запланировать', deletePlan: 'Удалить план', month: 'Месяц', week: 'Неделя', list: 'Список', needsReview: 'Нужно проверить', underControl: 'Ближайшие публикации под контролем', today: 'Сегодня', createdPosts: 'Создано публикаций', requiresReview: 'Требует проверки', eventSuggestion: 'Предлагаю публикацию к ближайшему событию', eventReason: 'Потому что сезонные темы обычно дают больше поводов написать.', competitorSuggestion: 'Проверьте акции конкурентов', competitorReason: 'Если рядом появилась акция, стоит ответить своим предложением.', photoSuggestion: 'Стоит обновить фотографии', photoReason: 'Визуальные посты лучше работают в картах.', nextAction: 'Следующее действие', reviewPosts: 'Проверить публикации', nearestReady: 'Ближайшая публикация готова', createPlan: 'Создать план', reviewHint: 'Осталось быстро посмотреть тексты и подтвердить готовые публикации.', nextHint: '{date} выйдет следующая публикация.', prepareHint: 'LocalOS подготовит календарь за вас.', publication: 'Публикация', content: 'Контент', channels: 'каналов', more: 'ещё', weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'], status: statusRu,
  },
  en: {
    aiResult: 'AI output', contentReady: 'Content is ready', preparingCalendar: 'Preparing the calendar', filledDays: '{filled} of {total} days filled', nextPublication: 'Next publication', noDate: 'no date', whatNow: 'What to do now', whatNowHint: 'Review the nearest items, approve what is ready, and close the section.', reviewNearest: 'Review upcoming', approving: 'Approving...', approveReady: 'Approve ready', scheduling: 'Scheduling...', schedule: 'Schedule', deletePlan: 'Delete plan', month: 'Month', week: 'Week', list: 'List', needsReview: 'Needs review', underControl: 'Upcoming publications are under control', today: 'Today', createdPosts: 'Publications created', requiresReview: 'Needs review', eventSuggestion: 'Prepare a post for the nearest event', eventReason: 'Seasonal topics usually provide a timely reason to publish.', competitorSuggestion: 'Check competitor offers', competitorReason: 'If a nearby competitor launched an offer, consider responding with your own.', photoSuggestion: 'Update the photos', photoReason: 'Visual posts perform better in map listings.', nextAction: 'Next action', reviewPosts: 'Review publications', nearestReady: 'The next publication is ready', createPlan: 'Create a plan', reviewHint: 'Quickly review the texts and approve the ready publications.', nextHint: 'The next publication is scheduled for {date}.', prepareHint: 'LocalOS will prepare the calendar for you.', publication: 'Publication', content: 'Content', channels: 'channels', more: 'more', weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], status: { failed: 'Failed', place: 'Needs publishing', review: 'Needs review', scheduled: 'Scheduled', published: 'Published', draft: 'Draft', textApproved: 'Text approved', fix: 'Fix', waitDate: 'Waiting for date', done: 'Done', chooseChannels: 'Choose channels', textReady: 'Text ready', approveText: 'Approve text', prepareChannels: 'Prepare channels', writeText: 'Write text' },
  },
  fr: {
    aiResult: 'Résultat de l’IA', contentReady: 'Le contenu est prêt', preparingCalendar: 'Préparation du calendrier', filledDays: '{filled} jours remplis sur {total}', nextPublication: 'Prochaine publication', noDate: 'aucune date', whatNow: 'Que faire maintenant', whatNowHint: 'Vérifiez les contenus proches, validez ceux qui sont prêts puis terminez cette section.', reviewNearest: 'Vérifier les prochaines', approving: 'Validation...', approveReady: 'Valider les contenus prêts', scheduling: 'Planification...', schedule: 'Planifier', deletePlan: 'Supprimer le plan', month: 'Mois', week: 'Semaine', list: 'Liste', needsReview: 'À vérifier', underControl: 'Les prochaines publications sont sous contrôle', today: 'Aujourd’hui', createdPosts: 'Publications créées', requiresReview: 'À vérifier', eventSuggestion: 'Préparer une publication pour le prochain événement', eventReason: 'Les sujets saisonniers donnent généralement une bonne raison de publier.', competitorSuggestion: 'Vérifiez les offres concurrentes', competitorReason: 'Si un concurrent proche lance une offre, envisagez une réponse adaptée.', photoSuggestion: 'Actualisez les photos', photoReason: 'Les publications visuelles fonctionnent mieux sur les fiches.', nextAction: 'Prochaine action', reviewPosts: 'Vérifier les publications', nearestReady: 'La prochaine publication est prête', createPlan: 'Créer un plan', reviewHint: 'Vérifiez rapidement les textes et validez les publications prêtes.', nextHint: 'La prochaine publication est prévue le {date}.', prepareHint: 'LocalOS préparera le calendrier pour vous.', publication: 'Publication', content: 'Contenu', channels: 'canaux', more: 'de plus', weekdays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'], status: { failed: 'Échec', place: 'À publier', review: 'À vérifier', scheduled: 'Planifié', published: 'Publié', draft: 'Brouillon', textApproved: 'Texte validé', fix: 'Corriger', waitDate: 'En attente d’une date', done: 'Terminé', chooseChannels: 'Choisir les canaux', textReady: 'Texte prêt', approveText: 'Valider le texte', prepareChannels: 'Préparer les canaux', writeText: 'Rédiger le texte' },
  },
  es: {
    aiResult: 'Resultado de la IA', contentReady: 'El contenido está listo', preparingCalendar: 'Preparando el calendario', filledDays: '{filled} de {total} días completados', nextPublication: 'Próxima publicación', noDate: 'sin fecha', whatNow: 'Qué hacer ahora', whatNowHint: 'Revisa lo más próximo, aprueba lo que esté listo y cierra la sección.', reviewNearest: 'Revisar próximas', approving: 'Aprobando...', approveReady: 'Aprobar listas', scheduling: 'Programando...', schedule: 'Programar', deletePlan: 'Eliminar plan', month: 'Mes', week: 'Semana', list: 'Lista', needsReview: 'Necesita revisión', underControl: 'Las próximas publicaciones están bajo control', today: 'Hoy', createdPosts: 'Publicaciones creadas', requiresReview: 'Necesitan revisión', eventSuggestion: 'Prepara una publicación para el próximo evento', eventReason: 'Los temas de temporada suelen dar un buen motivo para publicar.', competitorSuggestion: 'Revisa las ofertas de la competencia', competitorReason: 'Si un competidor cercano lanzó una oferta, valora responder con la tuya.', photoSuggestion: 'Actualiza las fotos', photoReason: 'Las publicaciones visuales funcionan mejor en las fichas.', nextAction: 'Siguiente acción', reviewPosts: 'Revisar publicaciones', nearestReady: 'La próxima publicación está lista', createPlan: 'Crear un plan', reviewHint: 'Revisa rápidamente los textos y aprueba las publicaciones listas.', nextHint: 'La próxima publicación está prevista para el {date}.', prepareHint: 'LocalOS preparará el calendario por ti.', publication: 'Publicación', content: 'Contenido', channels: 'canales', more: 'más', weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'], status: { failed: 'Error', place: 'Hay que publicar', review: 'Necesita revisión', scheduled: 'Programado', published: 'Publicado', draft: 'Borrador', textApproved: 'Texto aprobado', fix: 'Corregir', waitDate: 'Esperando fecha', done: 'Listo', chooseChannels: 'Elige canales', textReady: 'Texto listo', approveText: 'Aprobar texto', prepareChannels: 'Preparar canales', writeText: 'Escribir texto' },
  },
  el: {
    aiResult: 'Αποτέλεσμα ΤΝ', contentReady: 'Το περιεχόμενο είναι έτοιμο', preparingCalendar: 'Προετοιμασία ημερολογίου', filledDays: '{filled} από {total} ημέρες συμπληρώθηκαν', nextPublication: 'Επόμενη δημοσίευση', noDate: 'χωρίς ημερομηνία', whatNow: 'Τι να κάνετε τώρα', whatNowHint: 'Ελέγξτε τα επόμενα θέματα, εγκρίνετε όσα είναι έτοιμα και ολοκληρώστε την ενότητα.', reviewNearest: 'Έλεγχος επόμενων', approving: 'Έγκριση...', approveReady: 'Έγκριση έτοιμων', scheduling: 'Προγραμματισμός...', schedule: 'Προγραμματισμός', deletePlan: 'Διαγραφή πλάνου', month: 'Μήνας', week: 'Εβδομάδα', list: 'Λίστα', needsReview: 'Χρειάζεται έλεγχο', underControl: 'Οι επόμενες δημοσιεύσεις είναι υπό έλεγχο', today: 'Σήμερα', createdPosts: 'Δημοσιεύσεις που δημιουργήθηκαν', requiresReview: 'Χρειάζονται έλεγχο', eventSuggestion: 'Ετοιμάστε δημοσίευση για το επόμενο γεγονός', eventReason: 'Τα εποχικά θέματα συνήθως δίνουν επίκαιρη αφορμή για δημοσίευση.', competitorSuggestion: 'Ελέγξτε τις προσφορές ανταγωνιστών', competitorReason: 'Αν ένας κοντινός ανταγωνιστής έχει προσφορά, εξετάστε μια δική σας απάντηση.', photoSuggestion: 'Ανανεώστε τις φωτογραφίες', photoReason: 'Οι οπτικές δημοσιεύσεις αποδίδουν καλύτερα στις καταχωρίσεις.', nextAction: 'Επόμενη ενέργεια', reviewPosts: 'Έλεγχος δημοσιεύσεων', nearestReady: 'Η επόμενη δημοσίευση είναι έτοιμη', createPlan: 'Δημιουργία πλάνου', reviewHint: 'Ελέγξτε γρήγορα τα κείμενα και εγκρίνετε τις έτοιμες δημοσιεύσεις.', nextHint: 'Η επόμενη δημοσίευση έχει προγραμματιστεί για {date}.', prepareHint: 'Το LocalOS θα ετοιμάσει το ημερολόγιο για εσάς.', publication: 'Δημοσίευση', content: 'Περιεχόμενο', channels: 'κανάλια', more: 'ακόμη', weekdays: ['Δευ', 'Τρι', 'Τετ', 'Πεμ', 'Παρ', 'Σαβ', 'Κυρ'], status: { failed: 'Αποτυχία', place: 'Χρειάζεται δημοσίευση', review: 'Χρειάζεται έλεγχο', scheduled: 'Προγραμματισμένο', published: 'Δημοσιευμένο', draft: 'Πρόχειρο', textApproved: 'Κείμενο εγκεκριμένο', fix: 'Διόρθωση', waitDate: 'Αναμονή ημερομηνίας', done: 'Έτοιμο', chooseChannels: 'Επιλέξτε κανάλια', textReady: 'Κείμενο έτοιμο', approveText: 'Έγκριση κειμένου', prepareChannels: 'Προετοιμασία καναλιών', writeText: 'Σύνταξη κειμένου' },
  },
  de: {
    aiResult: 'KI-Ergebnis', contentReady: 'Inhalte sind bereit', preparingCalendar: 'Kalender wird vorbereitet', filledDays: '{filled} von {total} Tagen gefüllt', nextPublication: 'Nächste Veröffentlichung', noDate: 'kein Datum', whatNow: 'Was jetzt zu tun ist', whatNowHint: 'Prüfen Sie die nächsten Inhalte, bestätigen Sie fertige Beiträge und schließen Sie den Bereich ab.', reviewNearest: 'Nächste prüfen', approving: 'Wird bestätigt...', approveReady: 'Fertige bestätigen', scheduling: 'Wird geplant...', schedule: 'Planen', deletePlan: 'Plan löschen', month: 'Monat', week: 'Woche', list: 'Liste', needsReview: 'Prüfung nötig', underControl: 'Die nächsten Veröffentlichungen sind unter Kontrolle', today: 'Heute', createdPosts: 'Erstellte Beiträge', requiresReview: 'Prüfung nötig', eventSuggestion: 'Beitrag zum nächsten Ereignis vorbereiten', eventReason: 'Saisonale Themen bieten meist einen aktuellen Anlass für einen Beitrag.', competitorSuggestion: 'Angebote der Konkurrenz prüfen', competitorReason: 'Wenn ein naher Mitbewerber ein Angebot startet, erwägen Sie eine passende Antwort.', photoSuggestion: 'Fotos aktualisieren', photoReason: 'Visuelle Beiträge funktionieren in Karteneinträgen besser.', nextAction: 'Nächste Aktion', reviewPosts: 'Beiträge prüfen', nearestReady: 'Der nächste Beitrag ist bereit', createPlan: 'Plan erstellen', reviewHint: 'Prüfen Sie kurz die Texte und bestätigen Sie fertige Beiträge.', nextHint: 'Der nächste Beitrag ist für den {date} geplant.', prepareHint: 'LocalOS bereitet den Kalender für Sie vor.', publication: 'Beitrag', content: 'Inhalt', channels: 'Kanäle', more: 'weitere', weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'], status: { failed: 'Fehlgeschlagen', place: 'Veröffentlichung nötig', review: 'Prüfung nötig', scheduled: 'Geplant', published: 'Veröffentlicht', draft: 'Entwurf', textApproved: 'Text bestätigt', fix: 'Korrigieren', waitDate: 'Wartet auf Datum', done: 'Fertig', chooseChannels: 'Kanäle wählen', textReady: 'Text bereit', approveText: 'Text bestätigen', prepareChannels: 'Kanäle vorbereiten', writeText: 'Text schreiben' },
  },
  th: {
    aiResult: 'ผลลัพธ์จาก AI', contentReady: 'เนื้อหาพร้อมแล้ว', preparingCalendar: 'กำลังเตรียมปฏิทิน', filledDays: 'กรอกแล้ว {filled} จาก {total} วัน', nextPublication: 'โพสต์ถัดไป', noDate: 'ยังไม่มีวันที่', whatNow: 'สิ่งที่ต้องทำตอนนี้', whatNowHint: 'ตรวจรายการที่ใกล้ที่สุด อนุมัติสิ่งที่พร้อม แล้วปิดส่วนนี้', reviewNearest: 'ตรวจรายการถัดไป', approving: 'กำลังอนุมัติ...', approveReady: 'อนุมัติรายการพร้อม', scheduling: 'กำลังตั้งเวลา...', schedule: 'ตั้งเวลา', deletePlan: 'ลบแผน', month: 'เดือน', week: 'สัปดาห์', list: 'รายการ', needsReview: 'ต้องตรวจสอบ', underControl: 'โพสต์ถัดไปอยู่ภายใต้การควบคุม', today: 'วันนี้', createdPosts: 'โพสต์ที่สร้างแล้ว', requiresReview: 'ต้องตรวจสอบ', eventSuggestion: 'เตรียมโพสต์สำหรับกิจกรรมถัดไป', eventReason: 'หัวข้อตามฤดูกาลมักเป็นเหตุผลที่เหมาะสมในการโพสต์', competitorSuggestion: 'ตรวจข้อเสนอของคู่แข่ง', competitorReason: 'หากคู่แข่งใกล้เคียงมีข้อเสนอใหม่ ให้พิจารณาตอบด้วยข้อเสนอของคุณ', photoSuggestion: 'อัปเดตรูปภาพ', photoReason: 'โพสต์ที่มีภาพทำงานได้ดีกว่าในรายการแผนที่', nextAction: 'ขั้นตอนถัดไป', reviewPosts: 'ตรวจโพสต์', nearestReady: 'โพสต์ถัดไปพร้อมแล้ว', createPlan: 'สร้างแผน', reviewHint: 'ตรวจข้อความอย่างรวดเร็วและอนุมัติโพสต์ที่พร้อม', nextHint: 'โพสต์ถัดไปกำหนดไว้วันที่ {date}', prepareHint: 'LocalOS จะเตรียมปฏิทินให้คุณ', publication: 'โพสต์', content: 'เนื้อหา', channels: 'ช่องทาง', more: 'เพิ่มเติม', weekdays: ['จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.', 'อา.'], status: { failed: 'ล้มเหลว', place: 'ต้องเผยแพร่', review: 'ต้องตรวจสอบ', scheduled: 'ตั้งเวลาแล้ว', published: 'เผยแพร่แล้ว', draft: 'ฉบับร่าง', textApproved: 'อนุมัติข้อความแล้ว', fix: 'แก้ไข', waitDate: 'รอวันที่', done: 'พร้อม', chooseChannels: 'เลือกช่องทาง', textReady: 'ข้อความพร้อม', approveText: 'อนุมัติข้อความ', prepareChannels: 'เตรียมช่องทาง', writeText: 'เขียนข้อความ' },
  },
  ar: {
    aiResult: 'نتيجة الذكاء الاصطناعي', contentReady: 'المحتوى جاهز', preparingCalendar: 'جارٍ إعداد التقويم', filledDays: 'تم ملء {filled} من {total} يومًا', nextPublication: 'المنشور التالي', noDate: 'بلا تاريخ', whatNow: 'ما الذي يجب فعله الآن', whatNowHint: 'راجع العناصر الأقرب، واعتمد الجاهز، ثم أغلق هذا القسم.', reviewNearest: 'مراجعة الأقرب', approving: 'جارٍ الاعتماد...', approveReady: 'اعتماد الجاهز', scheduling: 'جارٍ الجدولة...', schedule: 'جدولة', deletePlan: 'حذف الخطة', month: 'شهر', week: 'أسبوع', list: 'قائمة', needsReview: 'يحتاج إلى مراجعة', underControl: 'المنشورات القادمة تحت السيطرة', today: 'اليوم', createdPosts: 'المنشورات المنشأة', requiresReview: 'تحتاج إلى مراجعة', eventSuggestion: 'حضّر منشورًا للحدث القادم', eventReason: 'توفر الموضوعات الموسمية عادةً سببًا مناسبًا للنشر.', competitorSuggestion: 'راجع عروض المنافسين', competitorReason: 'إذا أطلق منافس قريب عرضًا، ففكر في الرد بعرض مناسب.', photoSuggestion: 'حدّث الصور', photoReason: 'تؤدي المنشورات المرئية أفضل في قوائم الخرائط.', nextAction: 'الإجراء التالي', reviewPosts: 'مراجعة المنشورات', nearestReady: 'المنشور التالي جاهز', createPlan: 'إنشاء خطة', reviewHint: 'راجع النصوص سريعًا واعتمد المنشورات الجاهزة.', nextHint: 'المنشور التالي مجدول في {date}.', prepareHint: 'سيُعد LocalOS التقويم نيابةً عنك.', publication: 'منشور', content: 'محتوى', channels: 'قنوات', more: 'أخرى', weekdays: ['اثن', 'ثلا', 'أرب', 'خمي', 'جمع', 'سبت', 'أحد'], status: { failed: 'فشل', place: 'يحتاج إلى نشر', review: 'يحتاج إلى مراجعة', scheduled: 'مجدول', published: 'منشور', draft: 'مسودة', textApproved: 'النص معتمد', fix: 'إصلاح', waitDate: 'بانتظار التاريخ', done: 'جاهز', chooseChannels: 'اختر القنوات', textReady: 'النص جاهز', approveText: 'اعتماد النص', prepareChannels: 'إعداد القنوات', writeText: 'كتابة النص' },
  },
  ha: {
    aiResult: 'Sakamakon AI', contentReady: 'Abun ciki ya shirya', preparingCalendar: 'Ana shirya kalanda', filledDays: 'An cika kwanaki {filled} cikin {total}', nextPublication: 'Wallafa ta gaba', noDate: 'babu kwanan wata', whatNow: 'Abin da za a yi yanzu', whatNowHint: 'Duba abubuwan da ke gaba, amince da waɗanda suka shirya, sannan ka rufe sashen.', reviewNearest: 'Duba na gaba', approving: 'Ana amincewa...', approveReady: 'Amince da shirye', scheduling: 'Ana tsarawa...', schedule: 'Tsara lokaci', deletePlan: 'Goge tsari', month: 'Wata', week: 'Mako', list: 'Jeri', needsReview: 'Yana buƙatar dubawa', underControl: 'Wallafe-wallafe masu zuwa suna ƙarƙashin kulawa', today: 'Yau', createdPosts: 'Wallafe-wallafen da aka ƙirƙira', requiresReview: 'Suna buƙatar dubawa', eventSuggestion: 'Shirya wallafa don taron da ke gaba', eventReason: 'Batutuwan yanayi sukan ba da dalili mai kyau na wallafawa.', competitorSuggestion: 'Duba tayin masu gasa', competitorReason: 'Idan mai gasa na kusa ya kawo tayi, yi la’akari da amsawa da naka.', photoSuggestion: 'Sabunta hotuna', photoReason: 'Wallafe-wallafen gani suna aiki mafi kyau a taswirori.', nextAction: 'Mataki na gaba', reviewPosts: 'Duba wallafe-wallafe', nearestReady: 'Wallafa ta gaba ta shirya', createPlan: 'Ƙirƙiri tsari', reviewHint: 'Duba rubutun da sauri kuma amince da wallafe-wallafen da suka shirya.', nextHint: 'An tsara wallafa ta gaba a {date}.', prepareHint: 'LocalOS zai shirya kalanda a madadinka.', publication: 'Wallafa', content: 'Abun ciki', channels: 'tashoshi', more: 'ƙari', weekdays: ['Lit', 'Tal', 'Lar', 'Alh', 'Jum', 'Asb', 'Lah'], status: { failed: 'Bai yi nasara ba', place: 'Ana buƙatar wallafawa', review: 'Yana buƙatar dubawa', scheduled: 'An tsara', published: 'An wallafa', draft: 'Daftari', textApproved: 'An amince da rubutu', fix: 'Gyara', waitDate: 'Yana jiran kwanan wata', done: 'Shirye', chooseChannels: 'Zaɓi tashoshi', textReady: 'Rubutu ya shirya', approveText: 'Amince da rubutu', prepareChannels: 'Shirya tashoshi', writeText: 'Rubuta rubutu' },
  },
  tr: {
    aiResult: 'Yapay zekâ sonucu', contentReady: 'İçerik hazır', preparingCalendar: 'Takvim hazırlanıyor', filledDays: '{total} günün {filled} günü dolduruldu', nextPublication: 'Sonraki yayın', noDate: 'tarih yok', whatNow: 'Şimdi ne yapmalı', whatNowHint: 'Yakındaki içerikleri hızla inceleyin, hazır olanları onaylayın ve bölümü kapatın.', reviewNearest: 'Yakındakileri incele', approving: 'Onaylanıyor...', approveReady: 'Hazırları onayla', scheduling: 'Planlanıyor...', schedule: 'Planla', deletePlan: 'Planı sil', month: 'Ay', week: 'Hafta', list: 'Liste', needsReview: 'İnceleme gerekiyor', underControl: 'Yaklaşan yayınlar kontrol altında', today: 'Bugün', createdPosts: 'Oluşturulan yayınlar', requiresReview: 'İnceleme gerekiyor', eventSuggestion: 'Yaklaşan etkinlik için bir yayın hazırlayın', eventReason: 'Mevsimsel konular genellikle paylaşım için güncel bir neden sağlar.', competitorSuggestion: 'Rakip kampanyalarını kontrol edin', competitorReason: 'Yakındaki bir rakip kampanya başlattıysa kendi teklifinizle yanıt vermeyi değerlendirin.', photoSuggestion: 'Fotoğrafları güncelleyin', photoReason: 'Görsel yayınlar harita kayıtlarında daha iyi sonuç verir.', nextAction: 'Sonraki adım', reviewPosts: 'Yayınları incele', nearestReady: 'Sonraki yayın hazır', createPlan: 'Plan oluştur', reviewHint: 'Metinleri hızla inceleyin ve hazır yayınları onaylayın.', nextHint: 'Sonraki yayın {date} tarihinde planlandı.', prepareHint: 'LocalOS takvimi sizin için hazırlayacak.', publication: 'Yayın', content: 'İçerik', channels: 'kanal', more: 'daha', weekdays: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'], status: { failed: 'Başarısız', place: 'Yayınlanmalı', review: 'İnceleme gerekiyor', scheduled: 'Planlandı', published: 'Yayınlandı', draft: 'Taslak', textApproved: 'Metin onaylandı', fix: 'Düzelt', waitDate: 'Tarih bekliyor', done: 'Hazır', chooseChannels: 'Kanalları seçin', textReady: 'Metin hazır', approveText: 'Metni onayla', prepareChannels: 'Kanalları hazırla', writeText: 'Metni yaz' },
  },
};

const statusKeyByRussian: Record<string, string> = {
  'Не удалось': 'failed', 'Нужно разместить': 'place', 'Нужно проверить': 'review', 'Запланировано': 'scheduled', 'Опубликовано': 'published', 'Черновик': 'draft',
  'Текст утверждён': 'textApproved', 'Исправить': 'fix', 'Ждёт даты': 'waitDate', 'Готово': 'done', 'Выберите каналы': 'chooseChannels', 'Текст готов': 'textReady',
  'Утвердить текст': 'approveText', 'Подготовить каналы': 'prepareChannels', 'Написать текст': 'writeText',
};

export const getContentCalendarCopy = (language: Language) => copy[language];

export const localizeContentCalendarStatus = (label: string, localized: ContentCalendarCopy) => {
  const key = statusKeyByRussian[label];
  return key ? localized.status[key] || label : label;
};

export const fillContentCalendarTemplate = (value: string, replacements: Record<string, string | number>) => (
  Object.entries(replacements).reduce((result, [key, replacement]) => result.replace(`{${key}}`, String(replacement)), value)
);
