import type { Language } from './LanguageContext';

export type ContentWorkspaceCopy = {
  eyebrow: string; title: string; fallbackSubtitle: string; createPlan: string; calendar: string; media: string; audience: string;
  marketKnowledge: string; audienceTitle: string; audienceDescription: string; refresh: string; loading: string;
  emptyTitle: string; emptyDescription: string; loadError: string; saveError: string;
  insightTypes: Record<string, string>; audienceTopic: string; importance: string; repeated: string; whyImportant: string;
  addedToPlan: string; useInPlan: string; saveRule: string; unsuitable: string;
  decisionPlan: string; decisionRule: string; decisionIgnored: string;
};

type ContentWorkspaceControlsCopy = {
  configureContent: string;
  configureSources: string;
  sourcesTitle: string;
  sourcesDescription: string;
  addSource: string;
};

const controlsCopy: Record<Language, ContentWorkspaceControlsCopy> = {
  ru: { configureContent: 'Настроить контент', configureSources: 'Настроить источники', sourcesTitle: 'Добавить канал конкурента', sourcesDescription: 'Выберите публичные Telegram-каналы и чаты, за темами которых хотите следить. LocalOS ищет повторяющиеся вопросы, а не копирует чужие посты.', addSource: 'Добавить канал конкурента' },
  en: { configureContent: 'Configure content', configureSources: 'Configure sources', sourcesTitle: 'Add a competitor channel', sourcesDescription: 'Choose public Telegram channels and chats whose topics you want to follow. LocalOS finds recurring questions instead of copying other people’s posts.', addSource: 'Add a competitor channel' },
  fr: { configureContent: 'Configurer le contenu', configureSources: 'Configurer les sources', sourcesTitle: 'Ajouter un canal concurrent', sourcesDescription: 'Choisissez les canaux et groupes Telegram publics dont vous souhaitez suivre les sujets. LocalOS repère les questions récurrentes sans copier les publications.', addSource: 'Ajouter un canal concurrent' },
  es: { configureContent: 'Configurar contenido', configureSources: 'Configurar fuentes', sourcesTitle: 'Añadir un canal de la competencia', sourcesDescription: 'Elige canales y chats públicos de Telegram cuyos temas quieras seguir. LocalOS encuentra preguntas recurrentes sin copiar publicaciones ajenas.', addSource: 'Añadir un canal de la competencia' },
  el: { configureContent: 'Ρύθμιση περιεχομένου', configureSources: 'Ρύθμιση πηγών', sourcesTitle: 'Προσθήκη καναλιού ανταγωνιστή', sourcesDescription: 'Επιλέξτε δημόσια κανάλια και συνομιλίες Telegram των οποίων τα θέματα θέλετε να παρακολουθείτε. Το LocalOS εντοπίζει επαναλαμβανόμενες ερωτήσεις χωρίς να αντιγράφει αναρτήσεις.', addSource: 'Προσθήκη καναλιού ανταγωνιστή' },
  de: { configureContent: 'Inhalte konfigurieren', configureSources: 'Quellen konfigurieren', sourcesTitle: 'Kanal eines Mitbewerbers hinzufügen', sourcesDescription: 'Wählen Sie öffentliche Telegram-Kanäle und Chats aus, deren Themen Sie verfolgen möchten. LocalOS erkennt wiederkehrende Fragen, ohne fremde Beiträge zu kopieren.', addSource: 'Mitbewerberkanal hinzufügen' },
  th: { configureContent: 'ตั้งค่าเนื้อหา', configureSources: 'ตั้งค่าแหล่งข้อมูล', sourcesTitle: 'เพิ่มช่องของคู่แข่ง', sourcesDescription: 'เลือกช่องและแชต Telegram สาธารณะที่ต้องการติดตามหัวข้อ LocalOS จะค้นหาคำถามที่เกิดซ้ำโดยไม่คัดลอกโพสต์ของผู้อื่น', addSource: 'เพิ่มช่องของคู่แข่ง' },
  ar: { configureContent: 'إعداد المحتوى', configureSources: 'إعداد المصادر', sourcesTitle: 'إضافة قناة منافس', sourcesDescription: 'اختر قنوات ومحادثات Telegram العامة التي تريد متابعة موضوعاتها. يعثر LocalOS على الأسئلة المتكررة دون نسخ منشورات الآخرين.', addSource: 'إضافة قناة منافس' },
  ha: { configureContent: 'Saita abun ciki', configureSources: 'Saita tushe', sourcesTitle: 'Ƙara tashar abokin gasa', sourcesDescription: 'Zaɓi tashoshi da hirarrakin Telegram na jama’a da kuke son bibiyar batutuwansu. LocalOS yana gano tambayoyin da ke maimaituwa ba tare da kwafin saƙonnin wasu ba.', addSource: 'Ƙara tashar abokin gasa' },
  tr: { configureContent: 'İçeriği yapılandır', configureSources: 'Kaynakları yapılandır', sourcesTitle: 'Rakip kanalı ekle', sourcesDescription: 'Konularını takip etmek istediğiniz herkese açık Telegram kanallarını ve sohbetlerini seçin. LocalOS başkalarının gönderilerini kopyalamadan tekrarlanan soruları bulur.', addSource: 'Rakip kanalı ekle' },
};

export const getContentWorkspaceControlsCopy = (language: Language) => controlsCopy[language];

const copy: Record<Language, ContentWorkspaceCopy> = {
  ru: { eyebrow: 'LocalOS Контент', title: 'Контент', fallbackSubtitle: 'Единый календарь публикаций', createPlan: 'Создать новый план', calendar: 'Календарь', media: 'Медиатека', audience: 'Что волнует аудиторию', marketKnowledge: 'Знания рынка', audienceTitle: 'Что волнует аудиторию', audienceDescription: 'Повторяющиеся вопросы и проблемы из выбранных источников. Закрытые сообщения не цитируются и не показываются другим бизнесам.', refresh: 'Обновить', loading: 'Собираем темы', emptyTitle: 'Повторяющихся тем пока нет', emptyDescription: 'Подключите Telegram-источники в настройках. LocalOS загрузит последние 90 дней и будет обновлять их раз в день.', loadError: 'Не удалось загрузить темы аудитории', saveError: 'Не удалось сохранить решение', insightTypes: { pain: 'Проблема аудитории', question: 'Частый вопрос', objection: 'Сомнение', practice: 'Рабочая практика', market_signal: 'Тема рынка' }, audienceTopic: 'Тема аудитории', importance: 'важность', repeated: 'Повторилось в {messages} сообщениях из {sources} источников.', whyImportant: 'Почему это важно: полезность темы {relevance}%, интерес обсуждения {engagement}%.', addedToPlan: 'Добавлено в план', useInPlan: 'Использовать в плане', saveRule: 'Сохранить как правило', unsuitable: 'Не подходит', decisionPlan: 'Тема добавлена в текущий контент-план.', decisionRule: 'Правило отправлено на проверку.', decisionIgnored: 'Сигнал больше не будет предлагаться.' },
  en: { eyebrow: 'LocalOS Content', title: 'Content', fallbackSubtitle: 'Unified publication calendar', createPlan: 'Create a new plan', calendar: 'Calendar', media: 'Media library', audience: 'Audience concerns', marketKnowledge: 'Market insights', audienceTitle: 'What concerns your audience', audienceDescription: 'Recurring questions and problems from selected sources. Private messages are never quoted or shown to other businesses.', refresh: 'Refresh', loading: 'Collecting topics', emptyTitle: 'No recurring topics yet', emptyDescription: 'Connect Telegram sources in Settings. LocalOS will load the last 90 days and refresh them daily.', loadError: 'Could not load audience topics', saveError: 'Could not save the decision', insightTypes: { pain: 'Audience problem', question: 'Frequent question', objection: 'Objection', practice: 'Working practice', market_signal: 'Market signal' }, audienceTopic: 'Audience topic', importance: 'importance', repeated: 'Repeated in {messages} messages from {sources} sources.', whyImportant: 'Why it matters: relevance {relevance}%, discussion interest {engagement}%.', addedToPlan: 'Added to plan', useInPlan: 'Use in plan', saveRule: 'Save as a rule', unsuitable: 'Not relevant', decisionPlan: 'Topic added to the current content plan.', decisionRule: 'Rule sent for review.', decisionIgnored: 'This signal will no longer be suggested.' },
  fr: { eyebrow: 'Contenu LocalOS', title: 'Contenu', fallbackSubtitle: 'Calendrier éditorial unifié', createPlan: 'Créer un plan', calendar: 'Calendrier', media: 'Médiathèque', audience: 'Préoccupations du public', marketKnowledge: 'Connaissance du marché', audienceTitle: 'Ce qui préoccupe votre public', audienceDescription: 'Questions et problèmes récurrents des sources sélectionnées. Les messages privés ne sont jamais cités ni montrés à d’autres entreprises.', refresh: 'Actualiser', loading: 'Collecte des sujets', emptyTitle: 'Aucun sujet récurrent pour le moment', emptyDescription: 'Connectez des sources Telegram dans les paramètres. LocalOS chargera les 90 derniers jours et les actualisera chaque jour.', loadError: 'Impossible de charger les sujets', saveError: 'Impossible d’enregistrer la décision', insightTypes: { pain: 'Problème du public', question: 'Question fréquente', objection: 'Objection', practice: 'Bonne pratique', market_signal: 'Signal du marché' }, audienceTopic: 'Sujet du public', importance: 'importance', repeated: 'Répété dans {messages} messages provenant de {sources} sources.', whyImportant: 'Pourquoi : pertinence {relevance} %, intérêt {engagement} %.', addedToPlan: 'Ajouté au plan', useInPlan: 'Utiliser dans le plan', saveRule: 'Enregistrer comme règle', unsuitable: 'Non pertinent', decisionPlan: 'Sujet ajouté au plan.', decisionRule: 'Règle envoyée en validation.', decisionIgnored: 'Ce signal ne sera plus proposé.' },
  es: { eyebrow: 'Contenido LocalOS', title: 'Contenido', fallbackSubtitle: 'Calendario editorial unificado', createPlan: 'Crear un plan', calendar: 'Calendario', media: 'Biblioteca multimedia', audience: 'Qué preocupa al público', marketKnowledge: 'Conocimiento del mercado', audienceTitle: 'Qué preocupa a tu público', audienceDescription: 'Preguntas y problemas recurrentes de las fuentes elegidas. Los mensajes privados no se citan ni se muestran a otros negocios.', refresh: 'Actualizar', loading: 'Recopilando temas', emptyTitle: 'Aún no hay temas recurrentes', emptyDescription: 'Conecta fuentes de Telegram en Ajustes. LocalOS cargará los últimos 90 días y los actualizará a diario.', loadError: 'No se pudieron cargar los temas', saveError: 'No se pudo guardar la decisión', insightTypes: { pain: 'Problema del público', question: 'Pregunta frecuente', objection: 'Objeción', practice: 'Práctica útil', market_signal: 'Señal de mercado' }, audienceTopic: 'Tema del público', importance: 'importancia', repeated: 'Se repitió en {messages} mensajes de {sources} fuentes.', whyImportant: 'Por qué importa: relevancia {relevance} %, interés {engagement} %.', addedToPlan: 'Añadido al plan', useInPlan: 'Usar en el plan', saveRule: 'Guardar como regla', unsuitable: 'No relevante', decisionPlan: 'Tema añadido al plan.', decisionRule: 'Regla enviada a revisión.', decisionIgnored: 'Esta señal ya no se sugerirá.' },
  el: { eyebrow: 'Περιεχόμενο LocalOS', title: 'Περιεχόμενο', fallbackSubtitle: 'Ενιαίο ημερολόγιο δημοσιεύσεων', createPlan: 'Δημιουργία νέου πλάνου', calendar: 'Ημερολόγιο', media: 'Βιβλιοθήκη πολυμέσων', audience: 'Τι απασχολεί το κοινό', marketKnowledge: 'Γνώση αγοράς', audienceTitle: 'Τι απασχολεί το κοινό', audienceDescription: 'Επαναλαμβανόμενες ερωτήσεις και προβλήματα από επιλεγμένες πηγές. Τα ιδιωτικά μηνύματα δεν παρατίθενται ούτε εμφανίζονται σε άλλες επιχειρήσεις.', refresh: 'Ανανέωση', loading: 'Συλλογή θεμάτων', emptyTitle: 'Δεν υπάρχουν ακόμη επαναλαμβανόμενα θέματα', emptyDescription: 'Συνδέστε πηγές Telegram στις Ρυθμίσεις. Το LocalOS θα φορτώσει τις τελευταίες 90 ημέρες και θα τις ανανεώνει καθημερινά.', loadError: 'Δεν ήταν δυνατή η φόρτωση των θεμάτων', saveError: 'Δεν ήταν δυνατή η αποθήκευση της απόφασης', insightTypes: { pain: 'Πρόβλημα κοινού', question: 'Συχνή ερώτηση', objection: 'Ένσταση', practice: 'Χρήσιμη πρακτική', market_signal: 'Σήμα αγοράς' }, audienceTopic: 'Θέμα κοινού', importance: 'σημασία', repeated: 'Εμφανίστηκε σε {messages} μηνύματα από {sources} πηγές.', whyImportant: 'Γιατί έχει σημασία: συνάφεια {relevance}%, ενδιαφέρον {engagement}%.', addedToPlan: 'Προστέθηκε στο πλάνο', useInPlan: 'Χρήση στο πλάνο', saveRule: 'Αποθήκευση ως κανόνας', unsuitable: 'Δεν ταιριάζει', decisionPlan: 'Το θέμα προστέθηκε στο πλάνο.', decisionRule: 'Ο κανόνας στάλθηκε για έλεγχο.', decisionIgnored: 'Αυτό το σήμα δεν θα προτείνεται πλέον.' },
  de: { eyebrow: 'LocalOS Inhalte', title: 'Inhalte', fallbackSubtitle: 'Gemeinsamer Redaktionskalender', createPlan: 'Neuen Plan erstellen', calendar: 'Kalender', media: 'Mediathek', audience: 'Themen der Zielgruppe', marketKnowledge: 'Marktwissen', audienceTitle: 'Was Ihre Zielgruppe beschäftigt', audienceDescription: 'Wiederkehrende Fragen und Probleme aus ausgewählten Quellen. Private Nachrichten werden nie zitiert oder anderen Unternehmen gezeigt.', refresh: 'Aktualisieren', loading: 'Themen werden gesammelt', emptyTitle: 'Noch keine wiederkehrenden Themen', emptyDescription: 'Verbinden Sie Telegram-Quellen in den Einstellungen. LocalOS lädt die letzten 90 Tage und aktualisiert sie täglich.', loadError: 'Themen konnten nicht geladen werden', saveError: 'Entscheidung konnte nicht gespeichert werden', insightTypes: { pain: 'Problem der Zielgruppe', question: 'Häufige Frage', objection: 'Einwand', practice: 'Bewährte Praxis', market_signal: 'Marktsignal' }, audienceTopic: 'Zielgruppenthema', importance: 'Bedeutung', repeated: 'In {messages} Nachrichten aus {sources} Quellen wiederholt.', whyImportant: 'Warum wichtig: Relevanz {relevance} %, Interesse {engagement} %.', addedToPlan: 'Zum Plan hinzugefügt', useInPlan: 'Im Plan verwenden', saveRule: 'Als Regel speichern', unsuitable: 'Nicht passend', decisionPlan: 'Thema zum Plan hinzugefügt.', decisionRule: 'Regel zur Prüfung gesendet.', decisionIgnored: 'Dieses Signal wird nicht mehr vorgeschlagen.' },
  th: { eyebrow: 'คอนเทนต์ LocalOS', title: 'คอนเทนต์', fallbackSubtitle: 'ปฏิทินเผยแพร่รวม', createPlan: 'สร้างแผนใหม่', calendar: 'ปฏิทิน', media: 'คลังสื่อ', audience: 'สิ่งที่ผู้ชมกังวล', marketKnowledge: 'ข้อมูลเชิงลึกตลาด', audienceTitle: 'สิ่งที่ผู้ชมกังวล', audienceDescription: 'คำถามและปัญหาที่เกิดซ้ำจากแหล่งที่เลือก ข้อความส่วนตัวจะไม่ถูกอ้างหรือแสดงแก่ธุรกิจอื่น', refresh: 'รีเฟรช', loading: 'กำลังรวบรวมหัวข้อ', emptyTitle: 'ยังไม่มีหัวข้อที่เกิดซ้ำ', emptyDescription: 'เชื่อมต่อแหล่ง Telegram ในการตั้งค่า LocalOS จะโหลดข้อมูล 90 วันล่าสุดและรีเฟรชทุกวัน', loadError: 'โหลดหัวข้อไม่ได้', saveError: 'บันทึกการตัดสินใจไม่ได้', insightTypes: { pain: 'ปัญหาของผู้ชม', question: 'คำถามที่พบบ่อย', objection: 'ข้อโต้แย้ง', practice: 'แนวทางที่ได้ผล', market_signal: 'สัญญาณตลาด' }, audienceTopic: 'หัวข้อผู้ชม', importance: 'ความสำคัญ', repeated: 'พบซ้ำใน {messages} ข้อความจาก {sources} แหล่ง', whyImportant: 'เหตุผลที่สำคัญ: ความเกี่ยวข้อง {relevance}% ความสนใจ {engagement}%', addedToPlan: 'เพิ่มในแผนแล้ว', useInPlan: 'ใช้ในแผน', saveRule: 'บันทึกเป็นกฎ', unsuitable: 'ไม่เกี่ยวข้อง', decisionPlan: 'เพิ่มหัวข้อในแผนแล้ว', decisionRule: 'ส่งกฎให้ตรวจสอบแล้ว', decisionIgnored: 'จะไม่แนะนำสัญญาณนี้อีก' },
  ar: { eyebrow: 'محتوى LocalOS', title: 'المحتوى', fallbackSubtitle: 'تقويم نشر موحّد', createPlan: 'إنشاء خطة جديدة', calendar: 'التقويم', media: 'مكتبة الوسائط', audience: 'اهتمامات الجمهور', marketKnowledge: 'معرفة السوق', audienceTitle: 'ما الذي يشغل جمهورك', audienceDescription: 'أسئلة ومشكلات متكررة من المصادر المحددة. لا تُقتبس الرسائل الخاصة ولا تظهر لأعمال أخرى.', refresh: 'تحديث', loading: 'جمع الموضوعات', emptyTitle: 'لا توجد موضوعات متكررة بعد', emptyDescription: 'اربط مصادر Telegram من الإعدادات. سيحمّل LocalOS آخر 90 يومًا ويحدّثها يوميًا.', loadError: 'تعذر تحميل الموضوعات', saveError: 'تعذر حفظ القرار', insightTypes: { pain: 'مشكلة الجمهور', question: 'سؤال متكرر', objection: 'اعتراض', practice: 'ممارسة ناجحة', market_signal: 'إشارة سوق' }, audienceTopic: 'موضوع الجمهور', importance: 'الأهمية', repeated: 'تكرر في {messages} رسالة من {sources} مصدر.', whyImportant: 'سبب الأهمية: الصلة {relevance}%، الاهتمام {engagement}%.', addedToPlan: 'أضيف إلى الخطة', useInPlan: 'استخدام في الخطة', saveRule: 'حفظ كقاعدة', unsuitable: 'غير مناسب', decisionPlan: 'أضيف الموضوع إلى الخطة.', decisionRule: 'أُرسلت القاعدة للمراجعة.', decisionIgnored: 'لن يُقترح هذا التنبيه مجددًا.' },
  ha: { eyebrow: 'Abun cikin LocalOS', title: 'Abun ciki', fallbackSubtitle: 'Kalanda na wallafawa guda', createPlan: 'Ƙirƙiri sabon tsari', calendar: 'Kalanda', media: 'Ma’ajin kafofi', audience: 'Abin da ke damun masu sauraro', marketKnowledge: 'Bayanan kasuwa', audienceTitle: 'Abin da ke damun masu sauraro', audienceDescription: 'Tambayoyi da matsalolin da ke maimaituwa daga zaɓaɓɓun tushe. Ba a ambaton saƙonnin sirri ko nuna su ga wasu kasuwanci.', refresh: 'Sabunta', loading: 'Ana tattara batutuwa', emptyTitle: 'Babu batutuwa masu maimaituwa tukuna', emptyDescription: 'Haɗa tushen Telegram a Saituna. LocalOS zai loda kwanaki 90 na ƙarshe kuma ya sabunta kullum.', loadError: 'Ba a iya loda batutuwa ba', saveError: 'Ba a iya ajiye shawara ba', insightTypes: { pain: 'Matsalar masu sauraro', question: 'Tambaya mai yawa', objection: 'Ƙin yarda', practice: 'Hanyar aiki', market_signal: 'Alamar kasuwa' }, audienceTopic: 'Batun masu sauraro', importance: 'muhimmanci', repeated: 'Ya maimaitu a saƙonni {messages} daga tushe {sources}.', whyImportant: 'Dalili: dacewa {relevance}%, sha’awa {engagement}%.', addedToPlan: 'An ƙara zuwa tsari', useInPlan: 'Yi amfani a tsari', saveRule: 'Ajiye a matsayin ka’ida', unsuitable: 'Bai dace ba', decisionPlan: 'An ƙara batun zuwa tsari.', decisionRule: 'An aika ka’idar don dubawa.', decisionIgnored: 'Ba za a sake ba da wannan alama ba.' },
  tr: { eyebrow: 'LocalOS İçerik', title: 'İçerik', fallbackSubtitle: 'Birleşik yayın takvimi', createPlan: 'Yeni plan oluştur', calendar: 'Takvim', media: 'Medya arşivi', audience: 'Kitlenin gündemi', marketKnowledge: 'Pazar bilgisi', audienceTitle: 'Kitlenizi ne düşündürüyor', audienceDescription: 'Seçili kaynaklardan tekrarlanan sorular ve sorunlar. Özel mesajlar alıntılanmaz veya başka işletmelere gösterilmez.', refresh: 'Yenile', loading: 'Konular toplanıyor', emptyTitle: 'Henüz tekrarlanan konu yok', emptyDescription: 'Ayarlar’dan Telegram kaynaklarını bağlayın. LocalOS son 90 günü yükler ve her gün yeniler.', loadError: 'Kitle konuları yüklenemedi', saveError: 'Karar kaydedilemedi', insightTypes: { pain: 'Kitle sorunu', question: 'Sık soru', objection: 'İtiraz', practice: 'İşe yarayan uygulama', market_signal: 'Pazar sinyali' }, audienceTopic: 'Kitle konusu', importance: 'önem', repeated: '{sources} kaynaktaki {messages} mesajda tekrarlandı.', whyImportant: 'Neden önemli: alaka %{relevance}, ilgi %{engagement}.', addedToPlan: 'Plana eklendi', useInPlan: 'Planda kullan', saveRule: 'Kural olarak kaydet', unsuitable: 'Uygun değil', decisionPlan: 'Konu mevcut plana eklendi.', decisionRule: 'Kural incelemeye gönderildi.', decisionIgnored: 'Bu sinyal artık önerilmeyecek.' },
};

export const getContentWorkspaceCopy = (language: Language) => copy[language];

export const fillContentTemplate = (template: string, values: Record<string, string | number>) => (
  Object.entries(values).reduce((result, [key, value]) => result.replace(`{${key}}`, String(value)), template)
);
