import type { Language } from './LanguageContext';

type DashboardNavigationCopy = {
  operator: string;
  operatorHint: string;
  content: string;
  contentHint: string;
  agents: string;
  agentsHint: string;
  partnerships: string;
  partnershipsHint: string;
  promotion: string;
  promotionHint: string;
  webAnalytics: string;
  webAnalyticsHint: string;
  expand: string;
  collapse: string;
};

const copy: Record<Language, DashboardNavigationCopy> = {
  ru: { operator: 'Оператор', operatorHint: 'Управляйте LocalOS через единый чат: сводки, действия и безопасные следующие шаги.', content: 'Контент', contentHint: 'Календарь публикаций: что готово, что проверить и что выйдет дальше.', agents: 'Автоматизация', agentsHint: 'LocalOS регулярно проверяет данные, готовит материалы и показывает результат. Публикации и отправки подтверждаете вы.', partnerships: 'Партнёрские акции', partnershipsHint: 'Найдите бизнесы с похожими клиентами и подготовьте совместную акцию или взаимное продвижение.', promotion: 'Продвижение', promotionHint: 'Привлекайте клиентов через партнёрские акции и локальных авторов.', webAnalytics: 'Аналитика сайта', webAnalyticsHint: 'Посетители, источники, страницы и целевые действия на сайте.', expand: 'Развернуть меню', collapse: 'Свернуть меню' },
  en: { operator: 'Operator', operatorHint: 'Control LocalOS through one chat: briefs, actions, and safe next steps.', content: 'Content', contentHint: 'Publication calendar: what is ready, what needs review, and what comes next.', agents: 'Automation', agentsHint: 'LocalOS checks data on schedule, prepares materials, and shows the result. You approve publishing and sending.', partnerships: 'Joint promotions', partnershipsHint: 'Find businesses with a similar audience and prepare a joint offer or cross-promotion.', promotion: 'Promotion', promotionHint: 'Reach new customers through business partnerships and local creators.', webAnalytics: 'Website analytics', webAnalyticsHint: 'Visitors, sources, pages, and target actions on your website.', expand: 'Expand menu', collapse: 'Collapse menu' },
  fr: { operator: 'Opérateur', operatorHint: 'Pilotez LocalOS depuis un chat : synthèses, actions et prochaines étapes sûres.', content: 'Contenu', contentHint: 'Calendrier éditorial : contenus prêts, à vérifier et à venir.', agents: 'Automatisation', agentsHint: 'LocalOS contrôle régulièrement les données, prépare les contenus et affiche le résultat. Vous validez toute publication ou tout envoi.', partnerships: 'Actions partenaires', partnershipsHint: 'Trouvez des entreprises qui partagent votre clientèle et préparez une action ou une promotion commune.', promotion: 'Promotion', promotionHint: 'Trouvez de nouveaux clients via des partenaires et des créateurs locaux.', webAnalytics: 'Analyse du site', webAnalyticsHint: 'Visiteurs, sources, pages et actions cibles sur votre site.', expand: 'Développer le menu', collapse: 'Réduire le menu' },
  es: { operator: 'Operador', operatorHint: 'Controla LocalOS desde un chat: resúmenes, acciones y próximos pasos seguros.', content: 'Contenido', contentHint: 'Calendario editorial: qué está listo, qué revisar y qué viene después.', agents: 'Automatización', agentsHint: 'LocalOS revisa los datos de forma periódica, prepara materiales y muestra el resultado. Tú apruebas publicaciones y envíos.', partnerships: 'Acciones conjuntas', partnershipsHint: 'Encuentra negocios con un público similar y prepara una acción o promoción conjunta.', promotion: 'Promoción', promotionHint: 'Atrae clientes mediante alianzas y creadores locales.', webAnalytics: 'Analítica del sitio', webAnalyticsHint: 'Visitantes, fuentes, páginas y acciones objetivo de tu sitio.', expand: 'Expandir menú', collapse: 'Contraer menú' },
  el: { operator: 'Χειριστής', operatorHint: 'Διαχειριστείτε το LocalOS από μία συνομιλία: σύνοψη, ενέργειες και ασφαλή επόμενα βήματα.', content: 'Περιεχόμενο', contentHint: 'Ημερολόγιο δημοσιεύσεων: τι είναι έτοιμο, τι χρειάζεται έλεγχο και τι ακολουθεί.', agents: 'Αυτοματοποίηση', agentsHint: 'Το LocalOS ελέγχει τα δεδομένα τακτικά, ετοιμάζει υλικό και δείχνει το αποτέλεσμα. Εσείς εγκρίνετε δημοσιεύσεις και αποστολές.', partnerships: 'Κοινές ενέργειες', partnershipsHint: 'Βρείτε επιχειρήσεις με παρόμοιο κοινό και ετοιμάστε κοινή προσφορά ή αμοιβαία προώθηση.', promotion: 'Προώθηση', promotionHint: 'Προσεγγίστε πελάτες μέσω συνεργασιών και τοπικών δημιουργών.', webAnalytics: 'Αναλυτικά ιστοτόπου', webAnalyticsHint: 'Επισκέπτες, πηγές, σελίδες και ενέργειες στόχου στον ιστότοπό σας.', expand: 'Ανάπτυξη μενού', collapse: 'Σύμπτυξη μενού' },
  de: { operator: 'Operator', operatorHint: 'Steuern Sie LocalOS über einen Chat: Übersichten, Aktionen und sichere nächste Schritte.', content: 'Inhalte', contentHint: 'Redaktionskalender: bereit, zu prüfen und als Nächstes geplant.', agents: 'Automatisierung', agentsHint: 'LocalOS prüft Daten regelmäßig, bereitet Inhalte vor und zeigt das Ergebnis. Veröffentlichungen und Sendungen geben Sie frei.', partnerships: 'Gemeinsame Aktionen', partnershipsHint: 'Finden Sie Unternehmen mit ähnlicher Kundschaft und planen Sie eine gemeinsame Aktion oder gegenseitige Werbung.', promotion: 'Promotion', promotionHint: 'Gewinnen Sie Kunden über Partnerschaften und lokale Creator.', webAnalytics: 'Website-Analyse', webAnalyticsHint: 'Besucher, Quellen, Seiten und Zielaktionen auf Ihrer Website.', expand: 'Menü erweitern', collapse: 'Menü einklappen' },
  th: { operator: 'ผู้ดำเนินการ', operatorHint: 'ควบคุม LocalOS ผ่านแชตเดียว: สรุป การดำเนินการ และขั้นตอนถัดไปที่ปลอดภัย', content: 'คอนเทนต์', contentHint: 'ปฏิทินเผยแพร่: สิ่งที่พร้อม สิ่งที่ต้องตรวจ และสิ่งที่จะตามมา', agents: 'งานอัตโนมัติ', agentsHint: 'LocalOS ตรวจข้อมูลตามเวลา เตรียมเนื้อหาและแสดงผลลัพธ์ คุณเป็นผู้อนุมัติการเผยแพร่และการส่ง', partnerships: 'โปรโมชันร่วมกัน', partnershipsHint: 'ค้นหาธุรกิจที่มีกลุ่มลูกค้าใกล้เคียงและเตรียมกิจกรรมหรือโปรโมชันร่วมกัน', promotion: 'การโปรโมต', promotionHint: 'เข้าถึงลูกค้าผ่านพันธมิตรและครีเอเตอร์ท้องถิ่น', webAnalytics: 'การวิเคราะห์เว็บไซต์', webAnalyticsHint: 'ผู้เข้าชม แหล่งที่มา หน้า และการดำเนินการเป้าหมายบนเว็บไซต์', expand: 'ขยายเมนู', collapse: 'ย่อเมนู' },
  ar: { operator: 'المشغّل', operatorHint: 'أدر LocalOS عبر محادثة واحدة: ملخصات وإجراءات وخطوات تالية آمنة.', content: 'المحتوى', contentHint: 'تقويم النشر: ما هو جاهز وما يحتاج مراجعة وما يأتي لاحقًا.', agents: 'الأتمتة', agentsHint: 'يفحص LocalOS البيانات دوريًا ويجهز المواد ويعرض النتيجة. أنت توافق على النشر والإرسال.', partnerships: 'عروض مشتركة', partnershipsHint: 'اعثر على أنشطة تجارية ذات جمهور مشابه وأعد عرضًا أو ترويجًا مشتركًا.', promotion: 'الترويج', promotionHint: 'اجذب العملاء عبر الشراكات وصناع المحتوى المحليين.', webAnalytics: 'تحليلات الموقع', webAnalyticsHint: 'الزوار والمصادر والصفحات والإجراءات المستهدفة على موقعك.', expand: 'توسيع القائمة', collapse: 'طي القائمة' },
  ha: { operator: 'Mai gudanarwa', operatorHint: 'Sarrafa LocalOS ta hira guda: taƙaitawa, ayyuka da matakai masu aminci.', content: 'Abun ciki', contentHint: 'Kalanda na wallafawa: abin da ya shirya, abin dubawa da abin da zai biyo baya.', agents: 'Aiki ta atomatik', agentsHint: 'LocalOS yana duba bayanai akai-akai, yana shirya kayan aiki kuma yana nuna sakamako. Kai ne ke amincewa da wallafawa da aikawa.', partnerships: 'Haɗin talla', partnershipsHint: 'Nemo kasuwanci masu irin kwastomominka kuma ku shirya tayin ko talla tare.', promotion: 'Talla', promotionHint: 'Samu kwastomomi ta haɗin gwiwa da masu ƙirƙira na yankinku.', webAnalytics: 'Binciken shafin yanar gizo', webAnalyticsHint: 'Baƙi, tushe, shafuka da ayyukan manufa a shafinka.', expand: 'Faɗaɗa menu', collapse: 'Rufe menu' },
  tr: { operator: 'Operatör', operatorHint: 'LocalOS’u tek sohbetten yönetin: özetler, eylemler ve güvenli sonraki adımlar.', content: 'İçerik', contentHint: 'Yayın takvimi: hazır olanlar, kontrol edilecekler ve sıradakiler.', agents: 'Otomasyon', agentsHint: 'LocalOS verileri düzenli olarak kontrol eder, içerikleri hazırlar ve sonucu gösterir. Yayın ve gönderimleri siz onaylarsınız.', partnerships: 'Ortak kampanyalar', partnershipsHint: 'Benzer müşterilere ulaşan işletmeleri bulun ve ortak kampanya veya çapraz tanıtım hazırlayın.', promotion: 'Tanıtım', promotionHint: 'İş ortaklıkları ve yerel içerik üreticileriyle yeni müşterilere ulaşın.', webAnalytics: 'Web sitesi analitiği', webAnalyticsHint: 'Web sitenizdeki ziyaretçiler, kaynaklar, sayfalar ve hedef eylemler.', expand: 'Menüyü genişlet', collapse: 'Menüyü daralt' },
};

export const getDashboardNavigationCopy = (language: Language) => copy[language];
