import type { Language } from './LanguageContext';

type DashboardShellCopy = {
  today: string; todayHint: string; profileHint: string; cardHint: string; progressHint: string; financeHint: string; chatsHint: string; settingsHint: string;
  growthPaths: string; growthPathsHint: string; feed: string; feedHint: string; results: string; resultsHint: string; more: string; moreHint: string;
  currentLocation: string; wholeNetwork: string; network: string; business: string; currency: string;
};

const copy: Record<Language, DashboardShellCopy> = {
  ru: { today: 'Сегодня', todayHint: 'Что изменилось, какие материалы готовы и что проверить в первую очередь.', growthPaths: 'Пути роста', growthPathsHint: 'Карты, контент, инфлюенсеры, партнёрства и автоматизация — по понятным сценариям.', feed: 'Лента', feedHint: 'Входящие сообщения и новости вашей индустрии.', results: 'Результаты', resultsHint: 'Завершённые действия, изменения и динамика показателей.', more: 'Ещё', moreHint: 'Профиль, финансы, агенты, чаты, интеграции и настройки.', profileHint: 'Заполните данные бизнеса, добавьте ссылку на карты и запустите первый аудит.', cardHint: 'Проверьте услуги, отзывы, новости и свежесть данных карточки.', progressHint: 'Что уже сделано, что требует внимания и куда перейти дальше.', financeHint: 'Выручка, расходы, маржа, средний чек и загрузка.', chatsHint: 'Сообщения клиентов, подготовленные ответы и канал отправки.', settingsHint: 'Подключённые источники, доступы и правила ручного подтверждения.', currentLocation: 'Текущая точка', wholeNetwork: 'Вся сеть', network: 'Сеть', business: 'Бизнес', currency: 'Валюта' },
  en: { today: 'Today', todayHint: 'Confirmed changes, current LocalOS work, and one next step.', growthPaths: 'Growth paths', growthPathsHint: 'Maps, content, creators, partnerships, and automation in guided scenarios.', feed: 'Feed', feedHint: 'Incoming messages and news from your industry.', results: 'Results', resultsHint: 'Completed actions, changes, and metric trends.', more: 'More', moreHint: 'Profile, finance, agents, chats, integrations, and settings.', profileHint: 'Complete business details, connect a map listing, and start the first audit.', cardHint: 'Manage listing data, services, reviews, and refreshes.', progressHint: 'See completed work, attention points, and the most important next step.', financeHint: 'Business metrics and operating economics.', chatsHint: 'Customer conversations and replies across channels.', settingsHint: 'Account, integration, and workflow settings.', currentLocation: 'Current location', wholeNetwork: 'Whole network', network: 'Network', business: 'Business', currency: 'Currency' },
  fr: { today: 'Aujourd’hui', todayHint: 'Changements confirmés, travail en cours et prochaine étape.', growthPaths: 'Pistes de croissance', growthPathsHint: 'Cartes, contenu, créateurs, partenariats et automatisation par scénarios guidés.', feed: 'Fil', feedHint: 'Messages entrants et actualités de votre secteur.', results: 'Résultats', resultsHint: 'Actions terminées, changements et évolution des indicateurs.', more: 'Plus', moreHint: 'Profil, finances, agents, discussions, intégrations et paramètres.', profileHint: 'Complétez l’entreprise, connectez une fiche et lancez le premier audit.', cardHint: 'Gérez la fiche, les services, les avis et les actualisations.', progressHint: 'Voyez le travail terminé, les points d’attention et la prochaine priorité.', financeHint: 'Indicateurs financiers et économie opérationnelle.', chatsHint: 'Conversations clients et réponses par canal.', settingsHint: 'Paramètres du compte, des intégrations et du travail.', currentLocation: 'Point actuel', wholeNetwork: 'Tout le réseau', network: 'Réseau', business: 'Entreprise', currency: 'Devise' },
  es: { today: 'Hoy', todayHint: 'Cambios confirmados, trabajo actual y siguiente paso.', growthPaths: 'Rutas de crecimiento', growthPathsHint: 'Mapas, contenido, creadores, alianzas y automatización en escenarios guiados.', feed: 'Actividad', feedHint: 'Mensajes entrantes y noticias de tu sector.', results: 'Resultados', resultsHint: 'Acciones terminadas, cambios y evolución de métricas.', more: 'Más', moreHint: 'Perfil, finanzas, agentes, chats, integraciones y ajustes.', profileHint: 'Completa el negocio, conecta una ficha e inicia la primera auditoría.', cardHint: 'Gestiona la ficha, servicios, reseñas y actualizaciones.', progressHint: 'Consulta el trabajo terminado, los puntos de atención y la siguiente prioridad.', financeHint: 'Métricas financieras y economía operativa.', chatsHint: 'Conversaciones y respuestas de clientes por canal.', settingsHint: 'Ajustes de cuenta, integraciones y trabajo.', currentLocation: 'Ubicación actual', wholeNetwork: 'Toda la red', network: 'Red', business: 'Negocio', currency: 'Moneda' },
  el: { today: 'Σήμερα', todayHint: 'Επιβεβαιωμένες αλλαγές, τρέχουσα εργασία και επόμενο βήμα.', growthPaths: 'Διαδρομές ανάπτυξης', growthPathsHint: 'Χάρτες, περιεχόμενο, δημιουργοί, συνεργασίες και αυτοματοποίηση σε καθοδηγούμενα σενάρια.', feed: 'Ροή', feedHint: 'Εισερχόμενα μηνύματα και νέα του κλάδου σας.', results: 'Αποτελέσματα', resultsHint: 'Ολοκληρωμένες ενέργειες, αλλαγές και εξέλιξη δεικτών.', more: 'Περισσότερα', moreHint: 'Προφίλ, οικονομικά, πράκτορες, συνομιλίες, συνδέσεις και ρυθμίσεις.', profileHint: 'Συμπληρώστε την επιχείρηση, συνδέστε καταχώριση και ξεκινήστε έλεγχο.', cardHint: 'Διαχειριστείτε καταχώριση, υπηρεσίες, κριτικές και ενημερώσεις.', progressHint: 'Δείτε ολοκληρωμένη εργασία, σημεία προσοχής και επόμενη προτεραιότητα.', financeHint: 'Οικονομικοί δείκτες και λειτουργική οικονομία.', chatsHint: 'Συνομιλίες πελατών και απαντήσεις ανά κανάλι.', settingsHint: 'Ρυθμίσεις λογαριασμού, συνδέσεων και εργασίας.', currentLocation: 'Τρέχον σημείο', wholeNetwork: 'Όλο το δίκτυο', network: 'Δίκτυο', business: 'Επιχείρηση', currency: 'Νόμισμα' },
  de: { today: 'Heute', todayHint: 'Bestätigte Änderungen, aktuelle Arbeit und nächster Schritt.', growthPaths: 'Wachstumspfade', growthPathsHint: 'Karten, Inhalte, Creator, Partnerschaften und Automatisierung in geführten Szenarien.', feed: 'Feed', feedHint: 'Eingehende Nachrichten und Neuigkeiten aus Ihrer Branche.', results: 'Ergebnisse', resultsHint: 'Abgeschlossene Aktionen, Änderungen und Kennzahlentrends.', more: 'Mehr', moreHint: 'Profil, Finanzen, Agenten, Chats, Integrationen und Einstellungen.', profileHint: 'Geschäft ergänzen, Eintrag verbinden und erstes Audit starten.', cardHint: 'Eintrag, Dienste, Bewertungen und Aktualisierungen verwalten.', progressHint: 'Erledigte Arbeit, Handlungsbedarf und nächste Priorität sehen.', financeHint: 'Finanzkennzahlen und Betriebswirtschaft.', chatsHint: 'Kundengespräche und Antworten nach Kanal.', settingsHint: 'Konto-, Integrations- und Arbeitseinstellungen.', currentLocation: 'Aktueller Standort', wholeNetwork: 'Gesamtes Netzwerk', network: 'Netzwerk', business: 'Unternehmen', currency: 'Währung' },
  th: { today: 'วันนี้', todayHint: 'การเปลี่ยนแปลงที่ยืนยัน งานปัจจุบัน และขั้นต่อไป', growthPaths: 'เส้นทางการเติบโต', growthPathsHint: 'แผนที่ เนื้อหา ครีเอเตอร์ พันธมิตร และระบบอัตโนมัติในขั้นตอนที่ชัดเจน', feed: 'ฟีด', feedHint: 'ข้อความเข้าและข่าวสารในอุตสาหกรรมของคุณ', results: 'ผลลัพธ์', resultsHint: 'งานที่เสร็จ การเปลี่ยนแปลง และแนวโน้มตัวชี้วัด', more: 'เพิ่มเติม', moreHint: 'โปรไฟล์ การเงิน เอเจนต์ แชต การเชื่อมต่อ และการตั้งค่า', profileHint: 'กรอกข้อมูลธุรกิจ เชื่อมต่อรายการ และเริ่มตรวจครั้งแรก', cardHint: 'จัดการรายการ บริการ รีวิว และการอัปเดต', progressHint: 'ดูงานที่เสร็จ จุดที่ต้องดูแล และขั้นสำคัญถัดไป', financeHint: 'ตัวชี้วัดการเงินและเศรษฐกิจการดำเนินงาน', chatsHint: 'บทสนทนาลูกค้าและคำตอบในแต่ละช่องทาง', settingsHint: 'การตั้งค่าบัญชี การเชื่อมต่อ และงาน', currentLocation: 'สาขาปัจจุบัน', wholeNetwork: 'ทั้งเครือข่าย', network: 'เครือข่าย', business: 'ธุรกิจ', currency: 'สกุลเงิน' },
  ar: { today: 'اليوم', todayHint: 'التغييرات المؤكدة والعمل الحالي والخطوة التالية.', growthPaths: 'مسارات النمو', growthPathsHint: 'الخرائط والمحتوى والمنشئون والشراكات والأتمتة ضمن سيناريوهات موجهة.', feed: 'الخلاصة', feedHint: 'الرسائل الواردة وأخبار قطاعك.', results: 'النتائج', resultsHint: 'الإجراءات المكتملة والتغييرات واتجاهات المؤشرات.', more: 'المزيد', moreHint: 'الملف والمالية والوكلاء والمحادثات والتكاملات والإعدادات.', profileHint: 'أكمل بيانات النشاط واربط البطاقة وابدأ أول تدقيق.', cardHint: 'أدر البطاقة والخدمات والمراجعات والتحديثات.', progressHint: 'شاهد العمل المكتمل ونقاط الاهتمام والأولوية التالية.', financeHint: 'المؤشرات المالية واقتصاد التشغيل.', chatsHint: 'محادثات العملاء والردود حسب القناة.', settingsHint: 'إعدادات الحساب والتكاملات والعمل.', currentLocation: 'الموقع الحالي', wholeNetwork: 'الشبكة كاملة', network: 'الشبكة', business: 'النشاط', currency: 'العملة' },
  ha: { today: 'Yau', todayHint: 'Canje-canjen da aka tabbatar, aikin yanzu da mataki na gaba.', growthPaths: 'Hanyoyin bunƙasa', growthPathsHint: 'Taswira, abun ciki, masu ƙirƙira, haɗin gwiwa da sarrafa kai a matakai masu jagora.', feed: 'Sabbin bayanai', feedHint: 'Saƙonnin shiga da labaran masana’antarku.', results: 'Sakamako', resultsHint: 'Ayyukan da aka kammala, canje-canje da yanayin ma’auni.', more: 'Ƙari', moreHint: 'Bayanan martaba, kuɗi, wakilai, tattaunawa, haɗe-haɗe da saituna.', profileHint: 'Cika bayanan kasuwanci, haɗa kati sannan a fara bincike.', cardHint: 'Sarrafa kati, ayyuka, bita da sabuntawa.', progressHint: 'Duba aikin da aka gama, abin kulawa da mataki na gaba.', financeHint: 'Ma’aunin kuɗi da tattalin arzikin aiki.', chatsHint: 'Tattaunawar abokan ciniki da amsoshi.', settingsHint: 'Saitunan asusu, haɗe-haɗe da aiki.', currentLocation: 'Wurin yanzu', wholeNetwork: 'Dukkan cibiyar', network: 'Cibiya', business: 'Kasuwanci', currency: 'Kuɗi' },
  tr: { today: 'Bugün', todayHint: 'Doğrulanan değişiklikler, mevcut çalışma ve sonraki adım.', growthPaths: 'Büyüme yolları', growthPathsHint: 'Haritalar, içerik, üreticiler, ortaklıklar ve otomasyon için rehberli senaryolar.', feed: 'Akış', feedHint: 'Gelen mesajlar ve sektörünüzden haberler.', results: 'Sonuçlar', resultsHint: 'Tamamlanan işlemler, değişiklikler ve metrik eğilimleri.', more: 'Daha fazla', moreHint: 'Profil, finans, ajanlar, sohbetler, entegrasyonlar ve ayarlar.', profileHint: 'İşletmeyi tamamlayın, kaydı bağlayın ve ilk denetimi başlatın.', cardHint: 'Kayıt, hizmet, yorum ve güncellemeleri yönetin.', progressHint: 'Tamamlanan işi, dikkat noktalarını ve sonraki önceliği görün.', financeHint: 'Finansal göstergeler ve işletme ekonomisi.', chatsHint: 'Müşteri görüşmeleri ve kanal yanıtları.', settingsHint: 'Hesap, entegrasyon ve çalışma ayarları.', currentLocation: 'Geçerli konum', wholeNetwork: 'Tüm ağ', network: 'Ağ', business: 'İşletme', currency: 'Para birimi' },
};

export const getDashboardShellCopy = (language: Language) => copy[language];
