import type { Language } from './LanguageContext';

type DashboardShellCopy = {
  today: string; todayHint: string; profileHint: string; cardHint: string; progressHint: string; financeHint: string; chatsHint: string; settingsHint: string;
  currentLocation: string; wholeNetwork: string; network: string; business: string;
};

const copy: Record<Language, DashboardShellCopy> = {
  ru: { today: 'Сегодня', todayHint: 'Подтверждённые изменения, текущая работа LocalOS и один следующий шаг.', profileHint: 'Заполните данные бизнеса, добавьте ссылку на карты и запустите первый аудит.', cardHint: 'Управляйте карточкой, услугами, отзывами и обновлением данных.', progressHint: 'Что уже сделано, что требует внимания и какой шаг важнее всего.', financeHint: 'Финансовые показатели бизнеса и рабочая экономика.', chatsHint: 'Клиентские диалоги и ответы по каналам связи.', settingsHint: 'Настройки аккаунта, интеграций и рабочих режимов.', currentLocation: 'Текущая точка', wholeNetwork: 'Вся сеть', network: 'Сеть', business: 'Бизнес' },
  en: { today: 'Today', todayHint: 'Confirmed changes, current LocalOS work, and one next step.', profileHint: 'Complete business details, connect a map listing, and start the first audit.', cardHint: 'Manage listing data, services, reviews, and refreshes.', progressHint: 'See completed work, attention points, and the most important next step.', financeHint: 'Business metrics and operating economics.', chatsHint: 'Customer conversations and replies across channels.', settingsHint: 'Account, integration, and workflow settings.', currentLocation: 'Current location', wholeNetwork: 'Whole network', network: 'Network', business: 'Business' },
  fr: { today: 'Aujourd’hui', todayHint: 'Changements confirmés, travail en cours et prochaine étape.', profileHint: 'Complétez l’entreprise, connectez une fiche et lancez le premier audit.', cardHint: 'Gérez la fiche, les services, les avis et les actualisations.', progressHint: 'Voyez le travail terminé, les points d’attention et la prochaine priorité.', financeHint: 'Indicateurs financiers et économie opérationnelle.', chatsHint: 'Conversations clients et réponses par canal.', settingsHint: 'Paramètres du compte, des intégrations et du travail.', currentLocation: 'Point actuel', wholeNetwork: 'Tout le réseau', network: 'Réseau', business: 'Entreprise' },
  es: { today: 'Hoy', todayHint: 'Cambios confirmados, trabajo actual y siguiente paso.', profileHint: 'Completa el negocio, conecta una ficha e inicia la primera auditoría.', cardHint: 'Gestiona la ficha, servicios, reseñas y actualizaciones.', progressHint: 'Consulta el trabajo terminado, los puntos de atención y la siguiente prioridad.', financeHint: 'Métricas financieras y economía operativa.', chatsHint: 'Conversaciones y respuestas de clientes por canal.', settingsHint: 'Ajustes de cuenta, integraciones y trabajo.', currentLocation: 'Ubicación actual', wholeNetwork: 'Toda la red', network: 'Red', business: 'Negocio' },
  el: { today: 'Σήμερα', todayHint: 'Επιβεβαιωμένες αλλαγές, τρέχουσα εργασία και επόμενο βήμα.', profileHint: 'Συμπληρώστε την επιχείρηση, συνδέστε καταχώριση και ξεκινήστε έλεγχο.', cardHint: 'Διαχειριστείτε καταχώριση, υπηρεσίες, κριτικές και ενημερώσεις.', progressHint: 'Δείτε ολοκληρωμένη εργασία, σημεία προσοχής και επόμενη προτεραιότητα.', financeHint: 'Οικονομικοί δείκτες και λειτουργική οικονομία.', chatsHint: 'Συνομιλίες πελατών και απαντήσεις ανά κανάλι.', settingsHint: 'Ρυθμίσεις λογαριασμού, συνδέσεων και εργασίας.', currentLocation: 'Τρέχον σημείο', wholeNetwork: 'Όλο το δίκτυο', network: 'Δίκτυο', business: 'Επιχείρηση' },
  de: { today: 'Heute', todayHint: 'Bestätigte Änderungen, aktuelle Arbeit und nächster Schritt.', profileHint: 'Geschäft ergänzen, Eintrag verbinden und erstes Audit starten.', cardHint: 'Eintrag, Dienste, Bewertungen und Aktualisierungen verwalten.', progressHint: 'Erledigte Arbeit, Handlungsbedarf und nächste Priorität sehen.', financeHint: 'Finanzkennzahlen und Betriebswirtschaft.', chatsHint: 'Kundengespräche und Antworten nach Kanal.', settingsHint: 'Konto-, Integrations- und Arbeitseinstellungen.', currentLocation: 'Aktueller Standort', wholeNetwork: 'Gesamtes Netzwerk', network: 'Netzwerk', business: 'Unternehmen' },
  th: { today: 'วันนี้', todayHint: 'การเปลี่ยนแปลงที่ยืนยัน งานปัจจุบัน และขั้นต่อไป', profileHint: 'กรอกข้อมูลธุรกิจ เชื่อมต่อรายการ และเริ่มตรวจครั้งแรก', cardHint: 'จัดการรายการ บริการ รีวิว และการอัปเดต', progressHint: 'ดูงานที่เสร็จ จุดที่ต้องดูแล และขั้นสำคัญถัดไป', financeHint: 'ตัวชี้วัดการเงินและเศรษฐกิจการดำเนินงาน', chatsHint: 'บทสนทนาลูกค้าและคำตอบในแต่ละช่องทาง', settingsHint: 'การตั้งค่าบัญชี การเชื่อมต่อ และงาน', currentLocation: 'สาขาปัจจุบัน', wholeNetwork: 'ทั้งเครือข่าย', network: 'เครือข่าย', business: 'ธุรกิจ' },
  ar: { today: 'اليوم', todayHint: 'التغييرات المؤكدة والعمل الحالي والخطوة التالية.', profileHint: 'أكمل بيانات النشاط واربط البطاقة وابدأ أول تدقيق.', cardHint: 'أدر البطاقة والخدمات والمراجعات والتحديثات.', progressHint: 'شاهد العمل المكتمل ونقاط الاهتمام والأولوية التالية.', financeHint: 'المؤشرات المالية واقتصاد التشغيل.', chatsHint: 'محادثات العملاء والردود حسب القناة.', settingsHint: 'إعدادات الحساب والتكاملات والعمل.', currentLocation: 'الموقع الحالي', wholeNetwork: 'الشبكة كاملة', network: 'الشبكة', business: 'النشاط' },
  ha: { today: 'Yau', todayHint: 'Canje-canjen da aka tabbatar, aikin yanzu da mataki na gaba.', profileHint: 'Cika bayanan kasuwanci, haɗa kati sannan a fara bincike.', cardHint: 'Sarrafa kati, ayyuka, bita da sabuntawa.', progressHint: 'Duba aikin da aka gama, abin kulawa da mataki na gaba.', financeHint: 'Ma’aunin kuɗi da tattalin arzikin aiki.', chatsHint: 'Tattaunawar abokan ciniki da amsoshi.', settingsHint: 'Saitunan asusu, haɗe-haɗe da aiki.', currentLocation: 'Wurin yanzu', wholeNetwork: 'Dukkan cibiyar', network: 'Cibiya', business: 'Kasuwanci' },
  tr: { today: 'Bugün', todayHint: 'Doğrulanan değişiklikler, mevcut çalışma ve sonraki adım.', profileHint: 'İşletmeyi tamamlayın, kaydı bağlayın ve ilk denetimi başlatın.', cardHint: 'Kayıt, hizmet, yorum ve güncellemeleri yönetin.', progressHint: 'Tamamlanan işi, dikkat noktalarını ve sonraki önceliği görün.', financeHint: 'Finansal göstergeler ve işletme ekonomisi.', chatsHint: 'Müşteri görüşmeleri ve kanal yanıtları.', settingsHint: 'Hesap, entegrasyon ve çalışma ayarları.', currentLocation: 'Geçerli konum', wholeNetwork: 'Tüm ağ', network: 'Ağ', business: 'İşletme' },
};

export const getDashboardShellCopy = (language: Language) => copy[language];
