import type { Language } from './LanguageContext';

type TelegramRadarCopy = {
  pageTitle: string; pageDescription: string; connect: string; manualTitle: string; manualDescription: string;
  workTitle: string; settingsTitle: string; workDescription: string; settingsDescription: string; newItems: string;
  chooseBusiness: string; peerLabel: string; peerPlaceholder: string; titleLabel: string; titlePlaceholder: string; add: string;
  keywordsLabel: string; keywordsDescription: string; keywordsPlaceholder: string; words: string; saving: string; saveWords: string;
  savedFor: string; loadError: string; addError: string; saveError: string; refresh: string; workHint: string; settingsHint: string;
  sources: string; emptySources: string; emptyMessages: string; answered: string; idea: string; useful: string; hide: string;
  statuses: Record<string, string>;
};

type AverageTicketCopy = {
  title: string; description: string; link: string; finance: string; refresh: string; generate: string;
  averageTicket: string; averageTicketHint: string; addOnRate: string; addOnRateHint: string; upsellRevenue: string;
  upsellRevenueHint: string; packages: string; conversion: string; potential: string; potentialHint: string; unavailable: string;
  chooseBusiness: string; chooseBusinessDescription: string; emptyTitle: string; emptyDescription: string; generateDraft: string;
  loadError: string; retry: string;
};

type CompetitorsCopy = {
  title: string; description: string; addHint: string; urlPlaceholder: string; namePlaceholder: string; adding: string; add: string;
  manualTitle: string; competitor: string; audit: string; requested: string; ready: string; notRequested: string; openReport: string;
  sending: string; delete: string; deleting: string; unnamed: string; viewOnMap: string; empty: string;
};

type SidebarCopy = {
  telegramRadar: string; telegramRadarHint: string; upsells: string; upsellsHint: string; geoPromotionHint: string;
};

type GeoFallbackStep = { id: number; title: string; description: string; details: string[]; links: never[] };

export type DemoWorkspaceCopy = {
  telegram: TelegramRadarCopy;
  averageTicket: AverageTicketCopy;
  competitors: CompetitorsCopy;
  sidebar: SidebarCopy;
  geoFallbackSteps: GeoFallbackStep[];
};

const copy: Record<Language, DemoWorkspaceCopy> = {
  ru: {
    telegram: { pageTitle: 'Telegram-радар', pageDescription: 'Список сообщений из выбранных чатов: где ответить, что сохранить как идею и что скрыть.', connect: 'Подключить Telegram', manualTitle: 'Отвечайте только вручную', manualDescription: 'LocalOS читает выбранные чаты, но не пишет в них автоматически. Вы сами решаете, где ответить и что сохранить для контента.', workTitle: 'Найденные сообщения', settingsTitle: 'Telegram-радар', workDescription: 'Просматривайте сообщения: что требует ответа, что сохранить как идею и что скрыть.', settingsDescription: 'LocalOS отслеживает выбранные чаты и показывает сообщения для ручной проверки.', newItems: 'новых', chooseBusiness: 'Выберите бизнес, чтобы настроить наблюдение.', peerLabel: 'Чат или канал', peerPlaceholder: '@channel или идентификатор', titleLabel: 'Название для списка', titlePlaceholder: 'Владельцы бизнеса', add: 'Добавить', keywordsLabel: 'Слова для поиска', keywordsDescription: 'LocalOS показывает сообщения с этими словами и фразами. Разделяйте их запятыми или переносами строк.', keywordsPlaceholder: 'заказ, рекомендация, клиенты, продвижение', words: 'слов', saving: 'Сохраняем...', saveWords: 'Сохранить слова', savedFor: 'Сохранено для', loadError: 'Не удалось загрузить радар', addError: 'Не удалось добавить чат', saveError: 'Не удалось сохранить слова поиска', refresh: 'Обновить', workHint: 'Источники и слова для поиска настраиваются здесь.', settingsHint: 'LocalOS только читает выбранные источники; ответы остаются ручными.', sources: 'Источники', emptySources: 'Добавьте первый чат или канал.', emptyMessages: 'Подходящие сообщения появятся здесь.', answered: 'Ответил', idea: 'Идея', useful: 'Полезно', hide: 'Скрыть', statuses: { new: 'Новые', useful: 'Полезно', answered: 'Ответил', saved_as_content_idea: 'Идея', ignored: 'Неинтересно' } },
    averageTicket: { title: 'Допродажи', description: 'Пакеты, дополнительные услуги и готовые фразы для сотрудников по реальным записям.', link: 'Связать услуги', finance: 'Финансы', refresh: 'Обновить', generate: 'Подготовить план', averageTicket: 'Средний чек', averageTicketHint: 'За 30 дней', addOnRate: 'Визиты с допродажей', addOnRateHint: 'Доля визитов, где купили дополнительную услугу', upsellRevenue: 'Выручка от допродаж', upsellRevenueHint: 'По подтверждённым покупкам', packages: 'Готовые пакеты', conversion: 'Доля покупок', potential: 'Возможная выручка', potentialHint: 'Оценка по выбранным наборам услуг', unavailable: 'н/д', chooseBusiness: 'Выберите бизнес', chooseBusinessDescription: 'LocalOS использует услуги и записи выбранного бизнеса.', emptyTitle: 'План допродаж ещё не создан', emptyDescription: 'LocalOS предложит, какие услуги продавать вместе, как назвать пакет и что сказать клиенту.', generateDraft: 'Подготовить план', loadError: 'Не удалось загрузить допродажи', retry: 'Проверьте соединение и попробуйте снова.' },
    competitors: { title: 'Конкуренты', description: 'Добавьте карточки рядом, чтобы сравнить рейтинг, отзывы, услуги и новости.', addHint: 'Вставьте ссылку на карточку конкурента. После проверки появятся рейтинг, отзывы и изменения.', urlPlaceholder: 'Ссылка на карточку конкурента', namePlaceholder: 'Название (необязательно)', adding: 'Добавляем...', add: 'Добавить конкурента', manualTitle: 'Добавленные конкуренты', competitor: 'Конкурент', audit: 'Проверить карточку', requested: 'проверка запрошена', ready: 'отчёт готов', notRequested: 'ещё не проверен', openReport: 'Открыть отчёт', sending: 'Запускаем проверку...', delete: 'Удалить', deleting: 'Удаляем...', unnamed: 'Без названия', viewOnMap: 'Открыть на карте', empty: 'Конкуренты не добавлены.' },
    sidebar: { telegramRadar: 'Telegram-радар', telegramRadarHint: 'Сообщения из выбранных Telegram-чатов: ответить, сохранить идею или скрыть.', upsells: 'Допродажи', upsellsHint: 'Дополнительные услуги и пакеты по данным клиентов.', geoPromotionHint: 'Видимость бизнеса в ответах сервисов с искусственным интеллектом.' },
    geoFallbackSteps: [{ id: 1, title: 'Проверьте присутствие бизнеса', description: 'Сверьте сайт, карты и публичные данные бизнеса.', details: ['Проверьте название, адрес, телефон и услуги.'], links: [] }],
  },
  en: {
    telegram: { pageTitle: 'Telegram Radar', pageDescription: 'A working list of messages from selected chats: decide what to answer, save as an idea, or dismiss.', connect: 'Connect Telegram', manualTitle: 'Reply manually only', manualDescription: 'LocalOS reads selected chats but never posts to them automatically.', workTitle: 'Found messages', settingsTitle: 'Telegram Radar', workDescription: 'Review messages and decide what needs a reply, an idea, or dismissal.', settingsDescription: 'LocalOS monitors selected chats for manual review.', newItems: 'new', chooseBusiness: 'Select a business to configure monitoring.', peerLabel: 'Chat or channel', peerPlaceholder: '@channel or ID', titleLabel: 'List name', titlePlaceholder: 'Business owners', add: 'Add', keywordsLabel: 'Search words', keywordsDescription: 'LocalOS highlights messages containing these words and phrases. Separate them with commas or line breaks.', keywordsPlaceholder: 'order, recommendation, clients, promotion', words: 'words', saving: 'Saving...', saveWords: 'Save words', savedFor: 'Saved for', loadError: 'Could not load the radar', addError: 'Could not add the chat', saveError: 'Could not save search words', refresh: 'Refresh', workHint: 'Sources and search words are configured here.', settingsHint: 'LocalOS only reads selected sources; replies remain manual.', sources: 'Sources', emptySources: 'Add the first chat or channel to monitor.', emptyMessages: 'Matching messages will appear here.', answered: 'Answered', idea: 'Idea', useful: 'Useful', hide: 'Hide', statuses: { new: 'New', useful: 'Useful', answered: 'Answered', saved_as_content_idea: 'Idea', ignored: 'Dismissed' } },
    averageTicket: { title: 'Upsells', description: 'Upsells, cross-sells, scripts, packages, and an offer plan based on real appointments.', link: 'Link', finance: 'Finance', refresh: 'Refresh', generate: 'Generate', averageTicket: 'Average ticket', averageTicketHint: '30 days', addOnRate: 'Add-on rate', addOnRateHint: 'Share of visits with an upsell', upsellRevenue: 'Upsell revenue', upsellRevenueHint: 'Based on purchase events', packages: 'Packages', conversion: 'Conversion', potential: 'Potential', potentialHint: 'Estimate from active links', unavailable: 'N/A', chooseBusiness: 'Select a business', chooseBusinessDescription: 'The average-ticket matrix is built from one business’s services.', emptyTitle: 'The matrix has not been created yet', emptyDescription: 'LocalOS will use services from Maps Management to prepare an upsell, script, and package draft.', generateDraft: 'Generate draft', loadError: 'Could not load Upsells', retry: 'Check the connection and try again.' },
    competitors: { title: 'Competitors', description: 'Add important nearby listings to track their activity and run focused audits.', addHint: 'Add a competitor to track its activity.', urlPlaceholder: 'Competitor link (https://...)', namePlaceholder: 'Name (optional)', adding: 'Adding...', add: 'Add competitor', manualTitle: 'Manually added competitors', competitor: 'Competitor', audit: 'Audit', requested: 'requested', ready: 'ready', notRequested: 'not requested', openReport: 'Open report', sending: 'Sending...', delete: 'Delete', deleting: 'Deleting...', unnamed: 'Unnamed', viewOnMap: 'View on map', empty: 'No competitors found. Try refreshing the parsed data.' },
    sidebar: { telegramRadar: 'Telegram Radar', telegramRadarHint: 'Messages from selected Telegram chats: reply, save an idea, or dismiss.', upsells: 'Upsells', upsellsHint: 'Extra services and packages based on customer data.', geoPromotionHint: 'Business visibility in AI-powered answers.' },
    geoFallbackSteps: [{ id: 1, title: 'Check your business presence', description: 'Compare the website, maps, and public business data.', details: ['Verify the name, address, phone, and services.'], links: [] }],
  },
  fr: {
    telegram: { pageTitle: 'Radar Telegram', pageDescription: 'Boîte de réception des messages et mentions des chats sélectionnés : répondre, enregistrer une idée ou ignorer.', connect: 'Connecter Telegram', manualTitle: 'Répondez uniquement manuellement', manualDescription: 'LocalOS lit les chats sélectionnés et signale les messages, sans jamais écrire automatiquement dans des chats tiers.', workTitle: 'Messages trouvés', settingsTitle: 'Radar Telegram', workDescription: 'Examinez les messages et décidez lesquels nécessitent une réponse, une idée ou un classement.', settingsDescription: 'LocalOS surveille les chats sélectionnés pour une analyse manuelle.', newItems: 'nouveaux', chooseBusiness: 'Sélectionnez une entreprise pour configurer la surveillance.', peerLabel: 'Chat ou canal', peerPlaceholder: '@canal ou identifiant', titleLabel: 'Nom dans la liste', titlePlaceholder: 'Propriétaires d’entreprise', add: 'Ajouter', keywordsLabel: 'Mots recherchés', keywordsDescription: 'LocalOS met en évidence les messages contenant ces mots. Séparez-les par des virgules ou des retours à la ligne.', keywordsPlaceholder: 'commande, conseil, clients, promotion', words: 'mots', saving: 'Enregistrement...', saveWords: 'Enregistrer les mots', savedFor: 'Enregistré pour', loadError: 'Impossible de charger le radar', addError: 'Impossible d’ajouter le chat', saveError: 'Impossible d’enregistrer les mots', refresh: 'Actualiser', workHint: 'Configurez ici les sources et les mots recherchés.', settingsHint: 'LocalOS lit uniquement les sources ; les réponses restent manuelles.', sources: 'Sources', emptySources: 'Ajoutez un premier chat ou canal.', emptyMessages: 'Les messages correspondants apparaîtront ici.', answered: 'Répondu', idea: 'Idée', useful: 'Utile', hide: 'Masquer', statuses: { new: 'Nouveau', useful: 'Utile', answered: 'Répondu', saved_as_content_idea: 'Idée', ignored: 'Ignoré' } },
    averageTicket: { title: 'Ventes additionnelles', description: 'Ventes additionnelles et croisées, scripts, forfaits et plan d’offres selon les rendez-vous réels.', link: 'Association', finance: 'Finances', refresh: 'Actualiser', generate: 'Générer', averageTicket: 'Panier moyen', averageTicketHint: '30 jours', addOnRate: 'Taux additionnel', addOnRateHint: 'Part des visites avec vente additionnelle', upsellRevenue: 'Revenu additionnel', upsellRevenueHint: 'Selon les événements d’achat', packages: 'Forfaits', conversion: 'Conversion', potential: 'Potentiel', potentialHint: 'Estimation des associations actives', unavailable: 'N/D', chooseBusiness: 'Sélectionnez une entreprise', chooseBusinessDescription: 'La matrice est construite à partir des services d’une entreprise.', emptyTitle: 'La matrice n’est pas encore créée', emptyDescription: 'LocalOS utilisera les services des cartes pour préparer un brouillon de ventes, scripts et forfaits.', generateDraft: 'Générer le brouillon', loadError: 'Impossible de charger les ventes additionnelles', retry: 'Vérifiez la connexion et réessayez.' },
    competitors: { title: 'Concurrents', description: 'Ajoutez les fiches proches importantes pour suivre leurs actions et lancer des audits ciblés.', addHint: 'Ajoutez un concurrent pour suivre ses actions.', urlPlaceholder: 'Lien du concurrent (https://...)', namePlaceholder: 'Nom (facultatif)', adding: 'Ajout...', add: 'Ajouter un concurrent', manualTitle: 'Concurrents ajoutés manuellement', competitor: 'Concurrent', audit: 'Audit', requested: 'demandé', ready: 'prêt', notRequested: 'non demandé', openReport: 'Ouvrir le rapport', sending: 'Envoi...', delete: 'Supprimer', deleting: 'Suppression...', unnamed: 'Sans nom', viewOnMap: 'Voir sur la carte', empty: 'Aucun concurrent trouvé. Actualisez les données.' },
    sidebar: { telegramRadar: 'Radar Telegram', telegramRadarHint: 'Messages des chats Telegram : répondre, enregistrer une idée ou ignorer.', upsells: 'Ventes additionnelles', upsellsHint: 'Services et forfaits supplémentaires selon les données clients.', geoPromotionHint: 'Visibilité de l’entreprise dans les réponses assistées par IA.' },
    geoFallbackSteps: [{ id: 1, title: 'Vérifiez la présence de l’entreprise', description: 'Comparez le site, les cartes et les données publiques.', details: ['Vérifiez le nom, l’adresse, le téléphone et les services.'], links: [] }],
  },
  es: {
    telegram: { pageTitle: 'Radar de Telegram', pageDescription: 'Bandeja de mensajes y menciones de chats seleccionados: responder, guardar una idea o descartar.', connect: 'Conectar Telegram', manualTitle: 'Responde solo manualmente', manualDescription: 'LocalOS lee los chats seleccionados y destaca señales, pero nunca escribe automáticamente en chats ajenos.', workTitle: 'Mensajes encontrados', settingsTitle: 'Radar de Telegram', workDescription: 'Revisa mensajes y decide cuáles requieren respuesta, una idea o descarte.', settingsDescription: 'LocalOS supervisa chats seleccionados para revisión manual.', newItems: 'nuevos', chooseBusiness: 'Selecciona un negocio para configurar la supervisión.', peerLabel: 'Chat o canal', peerPlaceholder: '@canal o identificador', titleLabel: 'Nombre en la lista', titlePlaceholder: 'Propietarios de negocios', add: 'Añadir', keywordsLabel: 'Palabras de búsqueda', keywordsDescription: 'LocalOS destaca mensajes con estas palabras. Sepáralas con comas o saltos de línea.', keywordsPlaceholder: 'pedido, recomendación, clientes, promoción', words: 'palabras', saving: 'Guardando...', saveWords: 'Guardar palabras', savedFor: 'Guardado para', loadError: 'No se pudo cargar el radar', addError: 'No se pudo añadir el chat', saveError: 'No se pudieron guardar las palabras', refresh: 'Actualizar', workHint: 'Configura aquí las fuentes y palabras.', settingsHint: 'LocalOS solo lee las fuentes; las respuestas son manuales.', sources: 'Fuentes', emptySources: 'Añade el primer chat o canal.', emptyMessages: 'Los mensajes coincidentes aparecerán aquí.', answered: 'Respondido', idea: 'Idea', useful: 'Útil', hide: 'Ocultar', statuses: { new: 'Nuevo', useful: 'Útil', answered: 'Respondido', saved_as_content_idea: 'Idea', ignored: 'Ignorado' } },
    averageTicket: { title: 'Ventas adicionales', description: 'Ventas adicionales y cruzadas, guiones, paquetes y plan de ofertas según citas reales.', link: 'Vínculo', finance: 'Finanzas', refresh: 'Actualizar', generate: 'Generar', averageTicket: 'Ticket medio', averageTicketHint: '30 días', addOnRate: 'Tasa adicional', addOnRateHint: 'Visitas con venta adicional', upsellRevenue: 'Ingresos adicionales', upsellRevenueHint: 'Según eventos de compra', packages: 'Paquetes', conversion: 'Conversión', potential: 'Potencial', potentialHint: 'Estimación de vínculos activos', unavailable: 'N/D', chooseBusiness: 'Selecciona un negocio', chooseBusinessDescription: 'La matriz se construye con los servicios de un negocio.', emptyTitle: 'La matriz aún no está creada', emptyDescription: 'LocalOS usará los servicios de Mapas para preparar un borrador de ventas, guiones y paquetes.', generateDraft: 'Generar borrador', loadError: 'No se pudieron cargar las ventas adicionales', retry: 'Comprueba la conexión e inténtalo de nuevo.' },
    competitors: { title: 'Competidores', description: 'Añade fichas cercanas importantes para seguir sus acciones y ejecutar auditorías específicas.', addHint: 'Añade un competidor para seguir sus acciones.', urlPlaceholder: 'Enlace del competidor (https://...)', namePlaceholder: 'Nombre (opcional)', adding: 'Añadiendo...', add: 'Añadir competidor', manualTitle: 'Competidores añadidos manualmente', competitor: 'Competidor', audit: 'Auditoría', requested: 'solicitada', ready: 'lista', notRequested: 'no solicitada', openReport: 'Abrir informe', sending: 'Enviando...', delete: 'Eliminar', deleting: 'Eliminando...', unnamed: 'Sin nombre', viewOnMap: 'Ver en el mapa', empty: 'No se encontraron competidores. Actualiza los datos.' },
    sidebar: { telegramRadar: 'Radar de Telegram', telegramRadarHint: 'Mensajes de chats Telegram: responder, guardar una idea o descartar.', upsells: 'Ventas adicionales', upsellsHint: 'Servicios y paquetes adicionales según datos de clientes.', geoPromotionHint: 'Visibilidad del negocio en respuestas asistidas por IA.' },
    geoFallbackSteps: [{ id: 1, title: 'Comprueba la presencia del negocio', description: 'Compara el sitio, los mapas y los datos públicos.', details: ['Verifica nombre, dirección, teléfono y servicios.'], links: [] }],
  },
  el: {
    telegram: { pageTitle: 'Ραντάρ Telegram', pageDescription: 'Λίστα μηνυμάτων από επιλεγμένες συνομιλίες: απάντηση, αποθήκευση ιδέας ή απόκρυψη.', connect: 'Σύνδεση Telegram', manualTitle: 'Απαντήστε μόνο χειροκίνητα', manualDescription: 'Το LocalOS διαβάζει επιλεγμένες συνομιλίες, αλλά δεν γράφει αυτόματα σε αυτές.', workTitle: 'Μηνύματα που βρέθηκαν', settingsTitle: 'Ραντάρ Telegram', workDescription: 'Ελέγξτε μηνύματα και αποφασίστε ποια χρειάζονται απάντηση, ιδέα ή απόκρυψη.', settingsDescription: 'Το LocalOS παρακολουθεί επιλεγμένες συνομιλίες για χειροκίνητο έλεγχο.', newItems: 'νέα', chooseBusiness: 'Επιλέξτε επιχείρηση για τη ρύθμιση παρακολούθησης.', peerLabel: 'Συνομιλία ή κανάλι', peerPlaceholder: '@κανάλι ή αναγνωριστικό', titleLabel: 'Όνομα λίστας', titlePlaceholder: 'Ιδιοκτήτες επιχειρήσεων', add: 'Προσθήκη', keywordsLabel: 'Λέξεις αναζήτησης', keywordsDescription: 'Το LocalOS επισημαίνει μηνύματα με αυτές τις λέξεις. Χωρίστε τις με κόμματα ή αλλαγές γραμμής.', keywordsPlaceholder: 'παραγγελία, σύσταση, πελάτες, προώθηση', words: 'λέξεις', saving: 'Αποθήκευση...', saveWords: 'Αποθήκευση λέξεων', savedFor: 'Αποθηκεύτηκε για', loadError: 'Δεν ήταν δυνατή η φόρτωση του ραντάρ', addError: 'Δεν ήταν δυνατή η προσθήκη συνομιλίας', saveError: 'Δεν ήταν δυνατή η αποθήκευση λέξεων', refresh: 'Ανανέωση', workHint: 'Οι πηγές και οι λέξεις ρυθμίζονται εδώ.', settingsHint: 'Το LocalOS μόνο διαβάζει πηγές· οι απαντήσεις παραμένουν χειροκίνητες.', sources: 'Πηγές', emptySources: 'Προσθέστε την πρώτη συνομιλία ή κανάλι.', emptyMessages: 'Τα κατάλληλα μηνύματα θα εμφανιστούν εδώ.', answered: 'Απαντήθηκε', idea: 'Ιδέα', useful: 'Χρήσιμο', hide: 'Απόκρυψη', statuses: { new: 'Νέο', useful: 'Χρήσιμο', answered: 'Απαντήθηκε', saved_as_content_idea: 'Ιδέα', ignored: 'Αγνοήθηκε' } },
    averageTicket: { title: 'Πρόσθετες πωλήσεις', description: 'Συμπληρωματικές υπηρεσίες, έτοιμες φράσεις για την ομάδα, πακέτα και σχέδιο προσφορών με βάση πραγματικά ραντεβού.', link: 'Σύνδεση υπηρεσιών', finance: 'Οικονομικά', refresh: 'Ανανέωση', generate: 'Προετοιμασία σχεδίου', averageTicket: 'Μέση αξία συναλλαγής', averageTicketHint: '30 ημέρες', addOnRate: 'Επισκέψεις με πρόσθετη αγορά', addOnRateHint: 'Ποσοστό επισκέψεων με πρόσθετη υπηρεσία', upsellRevenue: 'Έσοδα από πρόσθετες πωλήσεις', upsellRevenueHint: 'Με βάση επιβεβαιωμένες αγορές', packages: 'Πακέτα υπηρεσιών', conversion: 'Ποσοστό αγοράς', potential: 'Πιθανά έσοδα', potentialHint: 'Εκτίμηση με βάση τους ενεργούς συνδυασμούς', unavailable: 'Μ/Δ', chooseBusiness: 'Επιλέξτε επιχείρηση', chooseBusinessDescription: 'Το LocalOS χρησιμοποιεί τις υπηρεσίες και τα ραντεβού της επιλεγμένης επιχείρησης.', emptyTitle: 'Δεν έχει δημιουργηθεί ακόμη σχέδιο πρόσθετων πωλήσεων', emptyDescription: 'Το LocalOS θα προτείνει ποιες υπηρεσίες μπορούν να συνδυαστούν, πώς να ονομαστεί το πακέτο και τι μπορεί να πει η ομάδα στον πελάτη.', generateDraft: 'Προετοιμασία σχεδίου', loadError: 'Δεν ήταν δυνατή η φόρτωση των πρόσθετων πωλήσεων', retry: 'Ελέγξτε τη σύνδεση και δοκιμάστε ξανά.' },
    competitors: { title: 'Ανταγωνιστές', description: 'Προσθέστε σημαντικές κοντινές καταχωρίσεις για παρακολούθηση ενεργειών και στοχευμένους ελέγχους.', addHint: 'Προσθέστε ανταγωνιστή για παρακολούθηση.', urlPlaceholder: 'Σύνδεσμος ανταγωνιστή (https://...)', namePlaceholder: 'Όνομα (προαιρετικό)', adding: 'Προσθήκη...', add: 'Προσθήκη ανταγωνιστή', manualTitle: 'Χειροκίνητα προστιθέμενοι ανταγωνιστές', competitor: 'Ανταγωνιστής', audit: 'Έλεγχος', requested: 'ζητήθηκε', ready: 'έτοιμος', notRequested: 'δεν ζητήθηκε', openReport: 'Άνοιγμα αναφοράς', sending: 'Αποστολή...', delete: 'Διαγραφή', deleting: 'Διαγραφή...', unnamed: 'Χωρίς όνομα', viewOnMap: 'Προβολή στον χάρτη', empty: 'Δεν βρέθηκαν ανταγωνιστές. Ανανεώστε τα δεδομένα.' },
    sidebar: { telegramRadar: 'Ραντάρ Telegram', telegramRadarHint: 'Μηνύματα από συνομιλίες Telegram: απάντηση, ιδέα ή απόκρυψη.', upsells: 'Πρόσθετες πωλήσεις', upsellsHint: 'Πρόσθετες υπηρεσίες και πακέτα από δεδομένα πελατών.', geoPromotionHint: 'Ορατότητα της επιχείρησης σε απαντήσεις τεχνητής νοημοσύνης.' },
    geoFallbackSteps: [{ id: 1, title: 'Ελέγξτε την παρουσία της επιχείρησης', description: 'Συγκρίνετε ιστότοπο, χάρτες και δημόσια δεδομένα.', details: ['Ελέγξτε όνομα, διεύθυνση, τηλέφωνο και υπηρεσίες.'], links: [] }],
  },
  de: {
    telegram: { pageTitle: 'Telegram-Radar', pageDescription: 'Arbeits-Posteingang für Nachrichten und Erwähnungen: antworten, als Idee speichern oder ausblenden.', connect: 'Telegram verbinden', manualTitle: 'Nur manuell antworten', manualDescription: 'LocalOS liest ausgewählte Chats und markiert Signale, schreibt aber nie automatisch in fremde Chats.', workTitle: 'Gefundene Nachrichten', settingsTitle: 'Telegram-Radar', workDescription: 'Prüfen Sie Nachrichten und entscheiden Sie über Antwort, Idee oder Ausblenden.', settingsDescription: 'LocalOS überwacht ausgewählte Chats zur manuellen Prüfung.', newItems: 'neu', chooseBusiness: 'Wählen Sie ein Unternehmen für die Überwachung.', peerLabel: 'Chat oder Kanal', peerPlaceholder: '@kanal oder Kennung', titleLabel: 'Listenname', titlePlaceholder: 'Unternehmensinhaber', add: 'Hinzufügen', keywordsLabel: 'Suchwörter', keywordsDescription: 'LocalOS markiert Nachrichten mit diesen Wörtern. Trennen Sie sie durch Kommas oder Zeilenumbrüche.', keywordsPlaceholder: 'Bestellung, Empfehlung, Kunden, Werbung', words: 'Wörter', saving: 'Speichern...', saveWords: 'Wörter speichern', savedFor: 'Gespeichert für', loadError: 'Radar konnte nicht geladen werden', addError: 'Chat konnte nicht hinzugefügt werden', saveError: 'Suchwörter konnten nicht gespeichert werden', refresh: 'Aktualisieren', workHint: 'Quellen und Suchwörter werden hier eingerichtet.', settingsHint: 'LocalOS liest Quellen nur; Antworten bleiben manuell.', sources: 'Quellen', emptySources: 'Fügen Sie den ersten Chat oder Kanal hinzu.', emptyMessages: 'Passende Nachrichten erscheinen hier.', answered: 'Beantwortet', idea: 'Idee', useful: 'Nützlich', hide: 'Ausblenden', statuses: { new: 'Neu', useful: 'Nützlich', answered: 'Beantwortet', saved_as_content_idea: 'Idee', ignored: 'Ignoriert' } },
    averageTicket: { title: 'Zusatzverkäufe', description: 'Zusatz- und Querverkäufe, Skripte, Pakete und Angebotsplan aus echten Terminen.', link: 'Verknüpfung', finance: 'Finanzen', refresh: 'Aktualisieren', generate: 'Erstellen', averageTicket: 'Durchschnittsbon', averageTicketHint: '30 Tage', addOnRate: 'Zusatzrate', addOnRateHint: 'Besuche mit Zusatzverkauf', upsellRevenue: 'Zusatzumsatz', upsellRevenueHint: 'Aus Kaufereignissen', packages: 'Pakete', conversion: 'Konversion', potential: 'Potenzial', potentialHint: 'Schätzung aktiver Verknüpfungen', unavailable: 'k. A.', chooseBusiness: 'Unternehmen auswählen', chooseBusinessDescription: 'Die Matrix basiert auf den Leistungen eines Unternehmens.', emptyTitle: 'Die Matrix wurde noch nicht erstellt', emptyDescription: 'LocalOS verwendet Leistungen aus der Kartenverwaltung für einen Entwurf mit Verkäufen, Skripten und Paketen.', generateDraft: 'Entwurf erstellen', loadError: 'Zusatzverkäufe konnten nicht geladen werden', retry: 'Verbindung prüfen und erneut versuchen.' },
    competitors: { title: 'Wettbewerber', description: 'Fügen Sie wichtige Einträge in der Nähe hinzu, um Aktivitäten zu verfolgen und gezielte Audits durchzuführen.', addHint: 'Fügen Sie einen Wettbewerber zur Beobachtung hinzu.', urlPlaceholder: 'Wettbewerber-Link (https://...)', namePlaceholder: 'Name (optional)', adding: 'Wird hinzugefügt...', add: 'Wettbewerber hinzufügen', manualTitle: 'Manuell hinzugefügte Wettbewerber', competitor: 'Wettbewerber', audit: 'Audit', requested: 'angefordert', ready: 'bereit', notRequested: 'nicht angefordert', openReport: 'Bericht öffnen', sending: 'Senden...', delete: 'Löschen', deleting: 'Löschen...', unnamed: 'Ohne Namen', viewOnMap: 'Auf Karte ansehen', empty: 'Keine Wettbewerber gefunden. Daten aktualisieren.' },
    sidebar: { telegramRadar: 'Telegram-Radar', telegramRadarHint: 'Nachrichten aus Telegram-Chats: antworten, Idee speichern oder ausblenden.', upsells: 'Zusatzverkäufe', upsellsHint: 'Zusatzleistungen und Pakete aus Kundendaten.', geoPromotionHint: 'Sichtbarkeit des Unternehmens in KI-gestützten Antworten.' },
    geoFallbackSteps: [{ id: 1, title: 'Unternehmenspräsenz prüfen', description: 'Website, Karten und öffentliche Daten vergleichen.', details: ['Name, Adresse, Telefon und Leistungen prüfen.'], links: [] }],
  },
  th: {
    telegram: { pageTitle: 'เรดาร์ Telegram', pageDescription: 'รายการข้อความจากแชตที่เลือก: ตอบ บันทึกเป็นไอเดีย หรือซ่อน', connect: 'เชื่อมต่อ Telegram', manualTitle: 'ตอบด้วยตนเองเท่านั้น', manualDescription: 'LocalOS อ่านแชตที่เลือก แต่จะไม่เขียนข้อความโดยอัตโนมัติ', workTitle: 'ข้อความที่พบ', settingsTitle: 'เรดาร์ Telegram', workDescription: 'ตรวจสอบข้อความและเลือกว่าจะตอบ บันทึกเป็นไอเดีย หรือซ่อน', settingsDescription: 'LocalOS ติดตามแชตที่เลือกเพื่อให้ตรวจสอบด้วยตนเอง', newItems: 'ใหม่', chooseBusiness: 'เลือกธุรกิจเพื่อตั้งค่าการติดตาม', peerLabel: 'แชตหรือช่อง', peerPlaceholder: '@channel หรือรหัส', titleLabel: 'ชื่อในรายการ', titlePlaceholder: 'เจ้าของธุรกิจ', add: 'เพิ่ม', keywordsLabel: 'คำค้นหา', keywordsDescription: 'LocalOS เน้นข้อความที่มีคำเหล่านี้ คั่นด้วยจุลภาคหรือขึ้นบรรทัดใหม่', keywordsPlaceholder: 'คำสั่งซื้อ, คำแนะนำ, ลูกค้า, โปรโมชัน', words: 'คำ', saving: 'กำลังบันทึก...', saveWords: 'บันทึกคำ', savedFor: 'บันทึกสำหรับ', loadError: 'โหลดเรดาร์ไม่ได้', addError: 'เพิ่มแชตไม่ได้', saveError: 'บันทึกคำค้นหาไม่ได้', refresh: 'รีเฟรช', workHint: 'ตั้งค่าแหล่งข้อมูลและคำค้นหาที่นี่', settingsHint: 'LocalOS อ่านแหล่งข้อมูลเท่านั้น การตอบทำด้วยตนเอง', sources: 'แหล่งข้อมูล', emptySources: 'เพิ่มแชตหรือช่องแรก', emptyMessages: 'ข้อความที่ตรงกันจะแสดงที่นี่', answered: 'ตอบแล้ว', idea: 'ไอเดีย', useful: 'มีประโยชน์', hide: 'ซ่อน', statuses: { new: 'ใหม่', useful: 'มีประโยชน์', answered: 'ตอบแล้ว', saved_as_content_idea: 'ไอเดีย', ignored: 'ละเว้น' } },
    averageTicket: { title: 'การขายเพิ่ม', description: 'การขายเพิ่มและขายพ่วง สคริปต์ แพ็กเกจ และแผนข้อเสนอจากนัดหมายจริง', link: 'ความเชื่อมโยง', finance: 'การเงิน', refresh: 'รีเฟรช', generate: 'สร้าง', averageTicket: 'ยอดเฉลี่ย', averageTicketHint: '30 วัน', addOnRate: 'อัตราขายเพิ่ม', addOnRateHint: 'สัดส่วนการเข้ารับบริการที่มีการขายเพิ่ม', upsellRevenue: 'รายได้จากการขายเพิ่ม', upsellRevenueHint: 'ตามเหตุการณ์ซื้อ', packages: 'แพ็กเกจ', conversion: 'คอนเวอร์ชัน', potential: 'ศักยภาพ', potentialHint: 'ประเมินจากความเชื่อมโยงที่ใช้งาน', unavailable: 'ไม่มีข้อมูล', chooseBusiness: 'เลือกธุรกิจ', chooseBusinessDescription: 'เมทริกซ์สร้างจากบริการของธุรกิจหนึ่งแห่ง', emptyTitle: 'ยังไม่ได้สร้างเมทริกซ์', emptyDescription: 'LocalOS จะใช้บริการจากการจัดการแผนที่เพื่อเตรียมร่างการขาย สคริปต์ และแพ็กเกจ', generateDraft: 'สร้างฉบับร่าง', loadError: 'โหลดการขายเพิ่มไม่ได้', retry: 'ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง' },
    competitors: { title: 'คู่แข่ง', description: 'เพิ่มรายการใกล้เคียงที่สำคัญเพื่อติดตามการทำงานและตรวจสอบแบบเจาะจง', addHint: 'เพิ่มคู่แข่งเพื่อติดตามการทำงาน', urlPlaceholder: 'ลิงก์คู่แข่ง (https://...)', namePlaceholder: 'ชื่อ (ไม่บังคับ)', adding: 'กำลังเพิ่ม...', add: 'เพิ่มคู่แข่ง', manualTitle: 'คู่แข่งที่เพิ่มด้วยตนเอง', competitor: 'คู่แข่ง', audit: 'ตรวจสอบ', requested: 'ร้องขอแล้ว', ready: 'พร้อม', notRequested: 'ยังไม่ร้องขอ', openReport: 'เปิดรายงาน', sending: 'กำลังส่ง...', delete: 'ลบ', deleting: 'กำลังลบ...', unnamed: 'ไม่มีชื่อ', viewOnMap: 'ดูบนแผนที่', empty: 'ไม่พบคู่แข่ง ลองรีเฟรชข้อมูล' },
    sidebar: { telegramRadar: 'เรดาร์ Telegram', telegramRadarHint: 'ข้อความจากแชต Telegram: ตอบ บันทึกไอเดีย หรือซ่อน', upsells: 'การขายเพิ่ม', upsellsHint: 'บริการเสริมและแพ็กเกจจากข้อมูลลูกค้า', geoPromotionHint: 'การมองเห็นธุรกิจในคำตอบจากปัญญาประดิษฐ์' },
    geoFallbackSteps: [{ id: 1, title: 'ตรวจสอบตัวตนของธุรกิจ', description: 'เปรียบเทียบเว็บไซต์ แผนที่ และข้อมูลสาธารณะ', details: ['ตรวจสอบชื่อ ที่อยู่ โทรศัพท์ และบริการ'], links: [] }],
  },
  ar: {
    telegram: { pageTitle: 'رادار Telegram', pageDescription: 'صندوق عمل للرسائل والإشارات من المحادثات المختارة: الرد أو حفظ فكرة أو الإخفاء.', connect: 'ربط Telegram', manualTitle: 'الرد يدويًا فقط', manualDescription: 'يقرأ LocalOS المحادثات المختارة ويبرز الإشارات، لكنه لا يكتب تلقائيًا في محادثات الآخرين.', workTitle: 'الرسائل المكتشفة', settingsTitle: 'رادار Telegram', workDescription: 'راجع الرسائل وحدد ما يحتاج إلى رد أو فكرة أو إخفاء.', settingsDescription: 'يراقب LocalOS المحادثات المختارة للمراجعة اليدوية.', newItems: 'جديدة', chooseBusiness: 'اختر نشاطًا لإعداد المراقبة.', peerLabel: 'محادثة أو قناة', peerPlaceholder: '@channel أو المعرّف', titleLabel: 'اسم القائمة', titlePlaceholder: 'أصحاب الأعمال', add: 'إضافة', keywordsLabel: 'كلمات البحث', keywordsDescription: 'يبرز LocalOS الرسائل التي تحتوي هذه الكلمات. افصل بينها بفواصل أو أسطر جديدة.', keywordsPlaceholder: 'طلب، توصية، عملاء، ترويج', words: 'كلمات', saving: 'جارٍ الحفظ...', saveWords: 'حفظ الكلمات', savedFor: 'تم الحفظ لـ', loadError: 'تعذر تحميل الرادار', addError: 'تعذرت إضافة المحادثة', saveError: 'تعذر حفظ كلمات البحث', refresh: 'تحديث', workHint: 'تُضبط المصادر وكلمات البحث هنا.', settingsHint: 'يقرأ LocalOS المصادر فقط؛ تبقى الردود يدوية.', sources: 'المصادر', emptySources: 'أضف أول محادثة أو قناة.', emptyMessages: 'ستظهر الرسائل المطابقة هنا.', answered: 'تم الرد', idea: 'فكرة', useful: 'مفيد', hide: 'إخفاء', statuses: { new: 'جديد', useful: 'مفيد', answered: 'تم الرد', saved_as_content_idea: 'فكرة', ignored: 'متجاهل' } },
    averageTicket: { title: 'المبيعات الإضافية', description: 'مبيعات إضافية ومتقاطعة ونصوص وباقات وخطة عروض مبنية على مواعيد حقيقية.', link: 'ربط', finance: 'المالية', refresh: 'تحديث', generate: 'إنشاء', averageTicket: 'متوسط الفاتورة', averageTicketHint: '30 يومًا', addOnRate: 'معدل الإضافة', addOnRateHint: 'زيارات تتضمن بيعًا إضافيًا', upsellRevenue: 'إيراد المبيعات الإضافية', upsellRevenueHint: 'وفق أحداث الشراء', packages: 'الباقات', conversion: 'التحويل', potential: 'الإمكانات', potentialHint: 'تقدير الروابط النشطة', unavailable: 'غير متاح', chooseBusiness: 'اختر نشاطًا', chooseBusinessDescription: 'تُبنى المصفوفة من خدمات نشاط واحد.', emptyTitle: 'لم تُنشأ المصفوفة بعد', emptyDescription: 'سيستخدم LocalOS خدمات إدارة الخرائط لإعداد مسودة مبيعات ونصوص وباقات.', generateDraft: 'إنشاء مسودة', loadError: 'تعذر تحميل المبيعات الإضافية', retry: 'تحقق من الاتصال وحاول مجددًا.' },
    competitors: { title: 'المنافسون', description: 'أضف القوائم القريبة المهمة لمتابعة نشاطها وإجراء تدقيقات مركزة.', addHint: 'أضف منافسًا لمتابعة نشاطه.', urlPlaceholder: 'رابط المنافس (https://...)', namePlaceholder: 'الاسم (اختياري)', adding: 'جارٍ الإضافة...', add: 'إضافة منافس', manualTitle: 'المنافسون المضافون يدويًا', competitor: 'منافس', audit: 'تدقيق', requested: 'مطلوب', ready: 'جاهز', notRequested: 'غير مطلوب', openReport: 'فتح التقرير', sending: 'جارٍ الإرسال...', delete: 'حذف', deleting: 'جارٍ الحذف...', unnamed: 'بلا اسم', viewOnMap: 'عرض على الخريطة', empty: 'لم يتم العثور على منافسين. حدّث البيانات.' },
    sidebar: { telegramRadar: 'رادار Telegram', telegramRadarHint: 'رسائل محادثات Telegram: الرد أو حفظ فكرة أو الإخفاء.', upsells: 'المبيعات الإضافية', upsellsHint: 'خدمات وباقات إضافية وفق بيانات العملاء.', geoPromotionHint: 'ظهور النشاط في إجابات الذكاء الاصطناعي.' },
    geoFallbackSteps: [{ id: 1, title: 'تحقق من حضور النشاط', description: 'قارن الموقع والخرائط والبيانات العامة.', details: ['تحقق من الاسم والعنوان والهاتف والخدمات.'], links: [] }],
  },
  ha: {
    telegram: { pageTitle: 'Radar na Telegram', pageDescription: 'Akwatin saƙonni daga tattaunawar da aka zaɓa: amsa, ajiye ra’ayi ko ɓoye.', connect: 'Haɗa Telegram', manualTitle: 'Amsa da hannu kawai', manualDescription: 'LocalOS yana karanta tattaunawar da aka zaɓa, amma ba ya rubutawa a tattaunawar wasu kai tsaye.', workTitle: 'Saƙonnin da aka samu', settingsTitle: 'Radar na Telegram', workDescription: 'Duba saƙonni ka zaɓi wanda za a amsa, ajiye a matsayin ra’ayi ko ɓoye.', settingsDescription: 'LocalOS yana sa ido kan tattaunawa domin a duba da hannu.', newItems: 'sababbi', chooseBusiness: 'Zaɓi kasuwanci domin saita sa ido.', peerLabel: 'Tattaunawa ko tashar', peerPlaceholder: '@channel ko lambar ganewa', titleLabel: 'Sunan jeri', titlePlaceholder: 'Masu kasuwanci', add: 'Ƙara', keywordsLabel: 'Kalmomin nema', keywordsDescription: 'LocalOS yana nuna saƙonnin da ke ɗauke da waɗannan kalmomi. Raba su da waƙafi ko sabon layi.', keywordsPlaceholder: 'oda, shawara, abokan ciniki, talla', words: 'kalmomi', saving: 'Ana ajiyewa...', saveWords: 'Ajiye kalmomi', savedFor: 'An ajiye wa', loadError: 'Ba a iya loda radar ba', addError: 'Ba a iya ƙara tattaunawa ba', saveError: 'Ba a iya ajiye kalmomin nema ba', refresh: 'Sabunta', workHint: 'Ana saita tushe da kalmomi a nan.', settingsHint: 'LocalOS yana karanta tushe kawai; amsoshi na hannu ne.', sources: 'Tushe', emptySources: 'Ƙara tattaunawa ko tasha ta farko.', emptyMessages: 'Saƙonnin da suka dace za su bayyana a nan.', answered: 'An amsa', idea: 'Ra’ayi', useful: 'Mai amfani', hide: 'Ɓoye', statuses: { new: 'Sabo', useful: 'Mai amfani', answered: 'An amsa', saved_as_content_idea: 'Ra’ayi', ignored: 'An yi watsi' } },
    averageTicket: { title: 'Ƙarin tallace-tallace', description: 'Ƙarin tallace-tallace, rubutun magana, fakitoci da shirin tayin bisa alƙawura na gaske.', link: 'Haɗi', finance: 'Kuɗi', refresh: 'Sabunta', generate: 'Ƙirƙira', averageTicket: 'Matsakaicin biya', averageTicketHint: 'Kwana 30', addOnRate: 'Adadin ƙari', addOnRateHint: 'Ziyarar da ta samu ƙarin saye', upsellRevenue: 'Kuɗin ƙarin saye', upsellRevenueHint: 'Daga bayanan saye', packages: 'Fakitoci', conversion: 'Juyawa', potential: 'Dama', potentialHint: 'Kimanta haɗin da ke aiki', unavailable: 'Babu', chooseBusiness: 'Zaɓi kasuwanci', chooseBusinessDescription: 'Ana gina matrix daga ayyukan kasuwanci ɗaya.', emptyTitle: 'Ba a ƙirƙiri matrix ba tukuna', emptyDescription: 'LocalOS zai yi amfani da ayyukan sarrafa taswira don shirya daftarin saye, rubutu da fakitoci.', generateDraft: 'Ƙirƙiri daftari', loadError: 'Ba a iya loda ƙarin tallace-tallace ba', retry: 'Duba haɗin ka sake gwadawa.' },
    competitors: { title: 'Masu gasa', description: 'Ƙara muhimman jerin kusa domin bibiyar ayyukansu da yin takamaiman bincike.', addHint: 'Ƙara mai gasa domin bibiyarsa.', urlPlaceholder: 'Haɗin mai gasa (https://...)', namePlaceholder: 'Suna (ba dole ba)', adding: 'Ana ƙarawa...', add: 'Ƙara mai gasa', manualTitle: 'Masu gasa da aka ƙara da hannu', competitor: 'Mai gasa', audit: 'Bincike', requested: 'an nema', ready: 'a shirye', notRequested: 'ba a nema ba', openReport: 'Buɗe rahoto', sending: 'Ana aikawa...', delete: 'Share', deleting: 'Ana sharewa...', unnamed: 'Ba suna', viewOnMap: 'Duba a taswira', empty: 'Ba a sami masu gasa ba. Sabunta bayanai.' },
    sidebar: { telegramRadar: 'Radar na Telegram', telegramRadarHint: 'Saƙonnin Telegram: amsa, ajiye ra’ayi ko ɓoye.', upsells: 'Ƙarin tallace-tallace', upsellsHint: 'Ƙarin ayyuka da fakitoci daga bayanan kwastomomi.', geoPromotionHint: 'Bayyanar kasuwanci a amsoshin basirar wucin gadi.' },
    geoFallbackSteps: [{ id: 1, title: 'Duba bayyanar kasuwanci', description: 'Kwatanta shafin yanar gizo, taswira da bayanan jama’a.', details: ['Duba suna, adireshi, waya da ayyuka.'], links: [] }],
  },
  tr: {
    telegram: { pageTitle: 'Telegram Radarı', pageDescription: 'Seçili sohbetlerden gelen mesaj ve bahsetmeler için çalışma kutusu: yanıtla, fikir olarak kaydet veya gizle.', connect: 'Telegram’ı bağla', manualTitle: 'Yalnızca elle yanıtlayın', manualDescription: 'LocalOS seçili sohbetleri okur ve sinyalleri vurgular, ancak başka sohbetlere otomatik yazmaz.', workTitle: 'Bulunan mesajlar', settingsTitle: 'Telegram Radarı', workDescription: 'Mesajları inceleyin; yanıt, fikir veya gizleme gerektirenleri seçin.', settingsDescription: 'LocalOS seçili sohbetleri elle inceleme için takip eder.', newItems: 'yeni', chooseBusiness: 'İzlemeyi ayarlamak için işletme seçin.', peerLabel: 'Sohbet veya kanal', peerPlaceholder: '@kanal veya kimlik', titleLabel: 'Liste adı', titlePlaceholder: 'İşletme sahipleri', add: 'Ekle', keywordsLabel: 'Arama kelimeleri', keywordsDescription: 'LocalOS bu kelimeleri içeren mesajları vurgular. Virgül veya satır sonuyla ayırın.', keywordsPlaceholder: 'sipariş, öneri, müşteriler, tanıtım', words: 'kelime', saving: 'Kaydediliyor...', saveWords: 'Kelimeleri kaydet', savedFor: 'Kaydedilen kaynak', loadError: 'Radar yüklenemedi', addError: 'Sohbet eklenemedi', saveError: 'Arama kelimeleri kaydedilemedi', refresh: 'Yenile', workHint: 'Kaynaklar ve arama kelimeleri burada ayarlanır.', settingsHint: 'LocalOS yalnızca kaynakları okur; yanıtlar elle verilir.', sources: 'Kaynaklar', emptySources: 'İlk sohbeti veya kanalı ekleyin.', emptyMessages: 'Eşleşen mesajlar burada görünür.', answered: 'Yanıtlandı', idea: 'Fikir', useful: 'Yararlı', hide: 'Gizle', statuses: { new: 'Yeni', useful: 'Yararlı', answered: 'Yanıtlandı', saved_as_content_idea: 'Fikir', ignored: 'Yoksayıldı' } },
    averageTicket: { title: 'Ek satışlar', description: 'Gerçek randevulara göre ek ve çapraz satışlar, metinler, paketler ve teklif planı.', link: 'Bağlantı', finance: 'Finans', refresh: 'Yenile', generate: 'Oluştur', averageTicket: 'Ortalama sepet', averageTicketHint: '30 gün', addOnRate: 'Ek satış oranı', addOnRateHint: 'Ek satış yapılan ziyaret oranı', upsellRevenue: 'Ek satış geliri', upsellRevenueHint: 'Satın alma olaylarına göre', packages: 'Paketler', conversion: 'Dönüşüm', potential: 'Potansiyel', potentialHint: 'Etkin bağlantılara göre tahmin', unavailable: 'Yok', chooseBusiness: 'İşletme seçin', chooseBusinessDescription: 'Matris bir işletmenin hizmetlerinden oluşturulur.', emptyTitle: 'Matris henüz oluşturulmadı', emptyDescription: 'LocalOS, Harita Yönetimi hizmetlerini kullanarak ek satış, metin ve paket taslağı hazırlayacak.', generateDraft: 'Taslak oluştur', loadError: 'Ek satışlar yüklenemedi', retry: 'Bağlantıyı kontrol edip yeniden deneyin.' },
    competitors: { title: 'Rakipler', description: 'Faaliyetlerini izlemek ve hedefli denetimler yapmak için önemli yakın kayıtları ekleyin.', addHint: 'Faaliyetlerini izlemek için rakip ekleyin.', urlPlaceholder: 'Rakip bağlantısı (https://...)', namePlaceholder: 'Ad (isteğe bağlı)', adding: 'Ekleniyor...', add: 'Rakip ekle', manualTitle: 'Elle eklenen rakipler', competitor: 'Rakip', audit: 'Denetim', requested: 'istendi', ready: 'hazır', notRequested: 'istenmedi', openReport: 'Raporu aç', sending: 'Gönderiliyor...', delete: 'Sil', deleting: 'Siliniyor...', unnamed: 'Adsız', viewOnMap: 'Haritada görüntüle', empty: 'Rakip bulunamadı. Verileri yenileyin.' },
    sidebar: { telegramRadar: 'Telegram Radarı', telegramRadarHint: 'Telegram mesajları: yanıtla, fikir kaydet veya gizle.', upsells: 'Ek satışlar', upsellsHint: 'Müşteri verilerine göre ek hizmetler ve paketler.', geoPromotionHint: 'Yapay zekâ yanıtlarında işletme görünürlüğü.' },
    geoFallbackSteps: [{ id: 1, title: 'İşletme varlığını kontrol edin', description: 'Web sitesi, haritalar ve herkese açık verileri karşılaştırın.', details: ['Adı, adresi, telefonu ve hizmetleri doğrulayın.'], links: [] }],
  },
};

export const getDemoWorkspaceCopy = (language: Language): DemoWorkspaceCopy => copy[language];

export const normalizeGeoPromotionSteps = (language: Language, value: unknown) => (
  Array.isArray(value) ? value : copy[language].geoFallbackSteps
);
