import type { Language } from './LanguageContext';

export interface FinanceWorkspaceCopy {
  period: string; presets: [string, string, string, string, string, string, string]; quality: string; ready: string; refresh: string;
  revenue: string; averageTicket: string; profit: string; occupancy: string; rebooking: string; margin: string; noData: string; unavailable: string;
  missingExpenses: string; noWorkplaceHours: string; idle: string; hours: string; recordsNeeded: string; nextVisit: string;
  chartTitle: string; chartDescription: string; months: string; chartEmpty: string;
  tabs: [string, string, string, string, string, string];
  attentionTitle: string; attentionDescription: string; actions: string; open: string;
  noShows: string; noShowsProblem: string; noShowsImpact: string; rebookingProblem: string; rebookingImpact: string; occupancyProblem: string; occupancyImpact: string;
  nextTitle: string; nextDescription: string; priority: string; priorityTitle: string; priorityText: string; goToActions: string; noUrgent: string;
  impactTitle: string; impactWithData: string; impactEmpty: string; show: string; hide: string; noComparison: string;
}

const ru: FinanceWorkspaceCopy = { period: 'Период', presets: ['30 дней', '3 месяца', 'Текущий месяц', 'Прошлый месяц', 'Год', 'Всё время', 'Свой период'], quality: 'Качество', ready: 'готово к анализу', refresh: 'Обновить', revenue: 'Выручка', averageTicket: 'Средний чек', profit: 'Прибыль', occupancy: 'Загрузка', rebooking: 'Повторная запись', margin: 'Маржа', noData: 'Нет данных', unavailable: 'Не хватает данных', missingExpenses: 'Не хватает расходов', noWorkplaceHours: 'Нет часов рабочих мест', idle: 'Простой', hours: 'ч', recordsNeeded: 'Нужны записи клиентов', nextVisit: 'Следующий визит', chartTitle: 'Динамика выручки', chartDescription: 'Помесячная динамика по выбранным данным.', months: 'мес.', chartEmpty: 'График появится после ввода или импорта выручки.', tabs: ['Обзор', 'Ввести', 'Услуги', 'Команда', 'Рабочие места', 'Импорт'], attentionTitle: 'На что смотреть в первую очередь', attentionDescription: 'Три показателя, которые быстрее всего влияют на деньги.', actions: 'Действия', open: 'Открыть', noShows: 'Неявки', noShowsProblem: 'Потери из-за несостоявшихся визитов', noShowsImpact: 'Окна заняты в расписании, но не приносят деньги.', rebookingProblem: 'Клиенты уходят без следующего визита', rebookingImpact: 'Будущая выручка не закрепляется заранее.', occupancyProblem: 'Часть рабочих часов может простаивать', occupancyImpact: 'Кресла и кабинеты есть, но часть времени не приносит выручку.', nextTitle: 'Ближайший шаг', nextDescription: 'Здесь показано одно главное действие. Полный план находится в разделе «Прогресс».', priority: 'Сейчас важнее всего', priorityTitle: 'Проверьте показатели, которые требуют внимания', priorityText: 'Откройте план действий и выберите первую задачу для команды.', goToActions: 'Перейти к действиям', noUrgent: 'Срочных финансовых действий нет. Следующие шаги доступны в разделе «Прогресс».', impactTitle: 'Что изменилось после действий', impactWithData: 'Выполнено действий: {count}. Сравниваем с предыдущим таким же периодом.', impactEmpty: 'Сравнение появится после данных за два периода и выполненных действий.', show: 'Показать', hide: 'Скрыть', noComparison: 'нет сравнения' };
const en: FinanceWorkspaceCopy = { period: 'Period', presets: ['30 days', '3 months', 'Current month', 'Previous month', 'Year', 'All time', 'Custom period'], quality: 'Data quality', ready: 'ready for analysis', refresh: 'Refresh', revenue: 'Revenue', averageTicket: 'Average ticket', profit: 'Profit', occupancy: 'Capacity use', rebooking: 'Rebooking', margin: 'Margin', noData: 'No data', unavailable: 'Not enough data', missingExpenses: 'Expenses are missing', noWorkplaceHours: 'Workplace hours are missing', idle: 'Idle time', hours: 'h', recordsNeeded: 'Customer bookings are needed', nextVisit: 'Next visit', chartTitle: 'Revenue trend', chartDescription: 'Monthly trend for the selected data.', months: 'mo.', chartEmpty: 'The chart will appear after revenue is entered or imported.', tabs: ['Overview', 'Enter data', 'Services', 'Team', 'Workplaces', 'Import'], attentionTitle: 'What to check first', attentionDescription: 'Three figures that have the fastest impact on revenue.', actions: 'Actions', open: 'Open', noShows: 'No-shows', noShowsProblem: 'Revenue lost to missed visits', noShowsImpact: 'Time is reserved but brings in no revenue.', rebookingProblem: 'Customers leave without booking the next visit', rebookingImpact: 'Future revenue is not secured in advance.', occupancyProblem: 'Some working hours may be idle', occupancyImpact: 'Chairs and rooms are available but not earning revenue.', nextTitle: 'Next step', nextDescription: 'This is the single most useful action now. The full plan is in Progress.', priority: 'Most important now', priorityTitle: 'Review the figures that need attention', priorityText: 'Open the action plan and choose the first task for the team.', goToActions: 'Open actions', noUrgent: 'There are no urgent financial actions. The next steps are available in Progress.', impactTitle: 'What changed after the actions', impactWithData: '{count} actions completed. Comparing with the previous matching period.', impactEmpty: 'A comparison will appear after two periods of data and completed actions.', show: 'Show', hide: 'Hide', noComparison: 'no comparison' };
const de: FinanceWorkspaceCopy = { period: 'Zeitraum', presets: ['30 Tage', '3 Monate', 'Aktueller Monat', 'Vorheriger Monat', 'Jahr', 'Gesamter Zeitraum', 'Eigener Zeitraum'], quality: 'Datenqualität', ready: 'bereit zur Analyse', refresh: 'Aktualisieren', revenue: 'Umsatz', averageTicket: 'Durchschnittsbon', profit: 'Gewinn', occupancy: 'Auslastung', rebooking: 'Folgetermine', margin: 'Marge', noData: 'Keine Daten', unavailable: 'Nicht genügend Daten', missingExpenses: 'Ausgaben fehlen', noWorkplaceHours: 'Arbeitsplatzstunden fehlen', idle: 'Leerlauf', hours: 'Std.', recordsNeeded: 'Kundentermine werden benötigt', nextVisit: 'Nächster Besuch', chartTitle: 'Umsatzentwicklung', chartDescription: 'Monatliche Entwicklung der ausgewählten Daten.', months: 'Mon.', chartEmpty: 'Das Diagramm erscheint nach der Eingabe oder dem Import von Umsätzen.', tabs: ['Übersicht', 'Daten eingeben', 'Leistungen', 'Team', 'Arbeitsplätze', 'Import'], attentionTitle: 'Was Sie zuerst prüfen sollten', attentionDescription: 'Drei Kennzahlen mit dem schnellsten Einfluss auf den Umsatz.', actions: 'Maßnahmen', open: 'Öffnen', noShows: 'Nicht erschienene Kunden', noShowsProblem: 'Umsatzverlust durch ausgefallene Termine', noShowsImpact: 'Die Zeit ist reserviert, bringt aber keinen Umsatz.', rebookingProblem: 'Kunden gehen ohne Folgetermin', rebookingImpact: 'Künftiger Umsatz wird nicht im Voraus gesichert.', occupancyProblem: 'Ein Teil der Arbeitszeit bleibt möglicherweise ungenutzt', occupancyImpact: 'Plätze und Räume sind verfügbar, erzielen aber keinen Umsatz.', nextTitle: 'Nächster Schritt', nextDescription: 'Hier sehen Sie die jetzt wichtigste Maßnahme. Der vollständige Plan steht unter „Fortschritt“.', priority: 'Jetzt am wichtigsten', priorityTitle: 'Prüfen Sie die auffälligen Kennzahlen', priorityText: 'Öffnen Sie den Maßnahmenplan und wählen Sie die erste Aufgabe für das Team.', goToActions: 'Maßnahmen öffnen', noUrgent: 'Es gibt keine dringenden Finanzaufgaben. Die nächsten Schritte stehen unter „Fortschritt“.', impactTitle: 'Was sich nach den Maßnahmen geändert hat', impactWithData: '{count} Maßnahmen erledigt. Vergleich mit dem vorherigen gleich langen Zeitraum.', impactEmpty: 'Der Vergleich erscheint nach Daten für zwei Zeiträume und erledigten Maßnahmen.', show: 'Anzeigen', hide: 'Ausblenden', noComparison: 'kein Vergleich' };

const copy: Record<Language, FinanceWorkspaceCopy> = {
  ru, en, de,
  fr: { ...en, period: 'Période', refresh: 'Actualiser', revenue: 'Chiffre d’affaires', averageTicket: 'Panier moyen', profit: 'Bénéfice', occupancy: 'Occupation', rebooking: 'Prochain rendez-vous', margin: 'Marge', noData: 'Aucune donnée', unavailable: 'Données insuffisantes', chartTitle: 'Évolution du chiffre d’affaires', chartDescription: 'Évolution mensuelle des données sélectionnées.', chartEmpty: 'Le graphique apparaîtra après la saisie ou l’import du chiffre d’affaires.', tabs: ['Vue d’ensemble', 'Saisir', 'Services', 'Équipe', 'Postes de travail', 'Importer'], attentionTitle: 'À vérifier en premier', attentionDescription: 'Trois indicateurs qui agissent le plus vite sur le chiffre d’affaires.', actions: 'Actions', open: 'Ouvrir', nextTitle: 'Prochaine étape', goToActions: 'Voir les actions' },
  es: { ...en, period: 'Periodo', refresh: 'Actualizar', revenue: 'Ingresos', averageTicket: 'Ticket medio', profit: 'Beneficio', occupancy: 'Ocupación', rebooking: 'Próxima reserva', margin: 'Margen', noData: 'Sin datos', unavailable: 'Faltan datos', chartTitle: 'Evolución de ingresos', chartDescription: 'Evolución mensual de los datos seleccionados.', chartEmpty: 'El gráfico aparecerá después de introducir o importar ingresos.', tabs: ['Resumen', 'Introducir', 'Servicios', 'Equipo', 'Puestos', 'Importar'], attentionTitle: 'Qué revisar primero', attentionDescription: 'Tres métricas con mayor impacto inmediato en los ingresos.', actions: 'Acciones', open: 'Abrir', nextTitle: 'Siguiente paso', goToActions: 'Ver acciones' },
  el: { ...en, period: 'Περίοδος', presets: ['30 ημέρες', '3 μήνες', 'Τρέχων μήνας', 'Προηγούμενος μήνας', 'Έτος', 'Όλη η περίοδος', 'Προσαρμοσμένη περίοδος'], quality: 'Ποιότητα δεδομένων', ready: 'έτοιμα για ανάλυση', refresh: 'Ανανέωση', revenue: 'Έσοδα', averageTicket: 'Μέση αξία συναλλαγής', profit: 'Κέρδος', occupancy: 'Πληρότητα', rebooking: 'Επόμενο ραντεβού', margin: 'Περιθώριο', noData: 'Δεν υπάρχουν δεδομένα', unavailable: 'Δεν υπάρχουν αρκετά δεδομένα', missingExpenses: 'Λείπουν τα έξοδα', noWorkplaceHours: 'Λείπουν οι ώρες λειτουργίας', idle: 'Χρόνος αδράνειας', hours: 'ώρες', recordsNeeded: 'Χρειάζονται κρατήσεις πελατών', nextVisit: 'Επόμενη επίσκεψη', chartTitle: 'Εξέλιξη εσόδων', chartDescription: 'Μηνιαία εξέλιξη για τα επιλεγμένα δεδομένα.', months: 'μήνες', chartEmpty: 'Το γράφημα θα εμφανιστεί μετά την εισαγωγή εσόδων.', tabs: ['Επισκόπηση', 'Εισαγωγή', 'Υπηρεσίες', 'Ομάδα', 'Θέσεις εργασίας', 'Εισαγωγή αρχείου'], attentionTitle: 'Τι να ελέγξετε πρώτα', attentionDescription: 'Τρεις δείκτες που επηρεάζουν πιο γρήγορα τα έσοδα.', actions: 'Ενέργειες', open: 'Άνοιγμα', noShows: 'Απουσίες', noShowsProblem: 'Απώλεια εσόδων από χαμένα ραντεβού', noShowsImpact: 'Ο χρόνος δεσμεύεται, αλλά δεν φέρνει έσοδα.', rebookingProblem: 'Οι πελάτες φεύγουν χωρίς να κλείσουν το επόμενο ραντεβού', rebookingImpact: 'Τα μελλοντικά έσοδα δεν εξασφαλίζονται εκ των προτέρων.', occupancyProblem: 'Μέρος των ωρών λειτουργίας μπορεί να μένει αξιοποίητο', occupancyImpact: 'Θέσεις και χώροι υπάρχουν, αλλά μέρος του χρόνου δεν φέρνει έσοδα.', nextTitle: 'Επόμενο βήμα', nextDescription: 'Εδώ εμφανίζεται η πιο χρήσιμη ενέργεια αυτή τη στιγμή. Το πλήρες πλάνο βρίσκεται στην Πρόοδο.', priority: 'Μεγαλύτερη προτεραιότη τώρα', priorityTitle: 'Ελέγξτε τους δείκτες που χρειάζονται προσοχή', priorityText: 'Ανοίξτε το πλάνο ενεργειών και επιλέξτε την πρώτη εργασία για την ομάδα.', goToActions: 'Άνοιγμα ενεργειών', noUrgent: 'Δεν υπάρχουν επείγουσες οικονομικές ενέργειες. Τα επόμενα βήματα βρίσκονται στην Πρόοδο.', impactTitle: 'Τι άλλαξε μετά τις ενέργειες', impactWithData: 'Ολοκληρώθηκαν {count} ενέργειες. Σύγκριση με την προηγούμενη αντίστοιχη περίοδο.', impactEmpty: 'Η σύγκριση θα εμφανιστεί μετά την καταχώριση δεδομένων για δύο περιόδους και την ολοκλήρωση ενεργειών.', show: 'Εμφάνιση', hide: 'Απόκρυψη', noComparison: 'δεν υπάρχει σύγκριση' },
  tr: { ...en, period: 'Dönem', refresh: 'Yenile', revenue: 'Gelir', averageTicket: 'Ortalama sepet', profit: 'Kâr', occupancy: 'Doluluk', rebooking: 'Tekrar randevu', margin: 'Marj', noData: 'Veri yok', unavailable: 'Yeterli veri yok', chartTitle: 'Gelir değişimi', chartDescription: 'Seçilen verilerin aylık değişimi.', chartEmpty: 'Gelir girildiğinde veya aktarıldığında grafik burada görünür.', tabs: ['Genel bakış', 'Veri gir', 'Hizmetler', 'Ekip', 'Çalışma alanları', 'İçe aktar'], attentionTitle: 'Önce neyi kontrol etmeli?', attentionDescription: 'Geliri en hızlı etkileyen üç gösterge.', actions: 'Adımlar', open: 'Aç', nextTitle: 'Sonraki adım', goToActions: 'Adımları aç' },
  th: { ...en, period: 'ช่วงเวลา', refresh: 'อัปเดต', revenue: 'รายได้', averageTicket: 'ยอดเฉลี่ย', profit: 'กำไร', occupancy: 'อัตราการใช้บริการ', rebooking: 'การจองครั้งถัดไป', margin: 'อัตรากำไร', noData: 'ไม่มีข้อมูล', unavailable: 'ข้อมูลไม่เพียงพอ', chartTitle: 'แนวโน้มรายได้', chartDescription: 'แนวโน้มรายเดือนจากข้อมูลที่เลือก', chartEmpty: 'กราฟจะแสดงหลังกรอกหรือนำเข้ารายได้', tabs: ['ภาพรวม', 'กรอกข้อมูล', 'บริการ', 'ทีม', 'พื้นที่บริการ', 'นำเข้า'], attentionTitle: 'สิ่งที่ควรตรวจสอบก่อน', attentionDescription: 'ตัวเลขสามรายการที่ส่งผลต่อรายได้เร็วที่สุด', actions: 'สิ่งที่ต้องทำ', open: 'เปิด', nextTitle: 'ขั้นตอนถัดไป', goToActions: 'เปิดรายการงาน' },
  ar: { ...en, period: 'الفترة', refresh: 'تحديث', revenue: 'الإيرادات', averageTicket: 'متوسط الفاتورة', profit: 'الربح', occupancy: 'الإشغال', rebooking: 'الحجز التالي', margin: 'الهامش', noData: 'لا توجد بيانات', unavailable: 'البيانات غير كافية', chartTitle: 'تطور الإيرادات', chartDescription: 'التغير الشهري للبيانات المحددة.', chartEmpty: 'سيظهر الرسم بعد إدخال الإيرادات أو استيرادها.', tabs: ['نظرة عامة', 'إدخال البيانات', 'الخدمات', 'الفريق', 'أماكن العمل', 'استيراد'], attentionTitle: 'ما الذي ينبغي مراجعته أولًا', attentionDescription: 'ثلاثة مؤشرات تؤثر في الإيرادات بأسرع وقت.', actions: 'الإجراءات', open: 'فتح', nextTitle: 'الخطوة التالية', goToActions: 'فتح الإجراءات' },
  ha: { ...en, period: 'Lokaci', refresh: 'Sabunta', revenue: 'Kuɗin shiga', averageTicket: 'Matsakaicin saye', profit: 'Riba', occupancy: 'Cikar lokaci', rebooking: 'Sake yin alƙawari', margin: 'Ratayen riba', noData: 'Babu bayanai', unavailable: 'Bayanai ba su isa ba', chartTitle: 'Canjin kuɗin shiga', chartDescription: 'Canjin wata-wata na bayanan da aka zaɓa.', chartEmpty: 'Jadawalin zai bayyana bayan an shigar ko an ɗora kuɗin shiga.', tabs: ['Taƙaitawa', 'Shigar da bayanai', 'Ayyuka', 'Ƙungiya', 'Wuraren aiki', 'Shigo da bayanai'], attentionTitle: 'Abin da za a fara dubawa', attentionDescription: 'Alkaluma uku da suka fi saurin shafar kuɗin shiga.', actions: 'Matakai', open: 'Buɗe', nextTitle: 'Mataki na gaba', goToActions: 'Buɗe matakai' },
};

export const getFinanceWorkspaceCopy = (language: Language) => copy[language];
