import type { Language } from './LanguageContext';

type NewsWorkspaceCopy = {
  planTab: string;
  planTitle: string;
  planSubtitle: string;
  sourceMaterial: string;
  generateFromSeo: string;
  loadingSeo: string;
  noSeo: string;
  selectSeo: string;
  seoHint: string;
  abMode: string;
  generated: string;
  generating: string;
  discard: string;
  addedAutomatically: string;
  external: string;
  noText: string;
  viewOriginal: string;
};

const copy: Record<Language, NewsWorkspaceCopy> = {
  ru: { planTab: 'Контент-план', planTitle: 'Контент-план и посты', planSubtitle: 'Готовьте посты для карт и соцсетей, проверяйте тексты и ставьте публикации в расписание.', sourceMaterial: 'Исходный материал', generateFromSeo: 'Генерировать на основе популярных SEO-ключей', loadingSeo: 'Загружаем SEO-ключи...', noSeo: 'SEO-ключи не найдены', selectSeo: 'Выберите SEO-ключ', seoHint: 'Будут использованы популярные запросы и ваши услуги.', abMode: 'A/B-режим (тест)', generated: 'Создано', generating: 'Создаём...', discard: 'Удалить', addedAutomatically: 'Пост автоматически добавлен в список ниже', external: 'Внешний', noText: 'Нет текста', viewOriginal: 'Открыть оригинал' },
  en: { planTab: 'Content plan', planTitle: 'Content plan and posts', planSubtitle: 'Prepare map and social posts, review copy, and schedule publication.', sourceMaterial: 'Source material', generateFromSeo: 'Generate from popular SEO keywords', loadingSeo: 'Loading SEO keywords...', noSeo: 'No SEO keywords found', selectSeo: 'Select an SEO keyword', seoHint: 'Popular searches and your services will be used.', abMode: 'A/B mode (test)', generated: 'Generated', generating: 'Generating...', discard: 'Discard', addedAutomatically: 'The post was added to the list below automatically', external: 'External', noText: 'No text content', viewOriginal: 'View original' },
  fr: { planTab: 'Plan de contenu', planTitle: 'Plan de contenu et publications', planSubtitle: 'Préparez les publications, relisez les textes et planifiez leur diffusion.', sourceMaterial: 'Matériel source', generateFromSeo: 'Générer à partir de mots-clés SEO populaires', loadingSeo: 'Chargement des mots-clés SEO...', noSeo: 'Aucun mot-clé SEO trouvé', selectSeo: 'Choisir un mot-clé SEO', seoHint: 'Les recherches populaires et vos services seront utilisés.', abMode: 'Mode A/B (test)', generated: 'Généré', generating: 'Génération...', discard: 'Supprimer', addedAutomatically: 'La publication a été ajoutée automatiquement ci-dessous', external: 'Externe', noText: 'Aucun texte', viewOriginal: "Voir l'original" },
  es: { planTab: 'Plan de contenido', planTitle: 'Plan de contenido y publicaciones', planSubtitle: 'Prepara publicaciones, revisa los textos y programa su publicación.', sourceMaterial: 'Material de origen', generateFromSeo: 'Generar con palabras clave SEO populares', loadingSeo: 'Cargando palabras clave SEO...', noSeo: 'No se encontraron palabras clave SEO', selectSeo: 'Selecciona una palabra clave SEO', seoHint: 'Se usarán búsquedas populares y tus servicios.', abMode: 'Modo A/B (prueba)', generated: 'Generado', generating: 'Generando...', discard: 'Descartar', addedAutomatically: 'La publicación se añadió automáticamente a la lista', external: 'Externo', noText: 'Sin texto', viewOriginal: 'Ver original' },
  el: { planTab: 'Πλάνο περιεχομένου', planTitle: 'Πλάνο περιεχομένου και αναρτήσεις', planSubtitle: 'Ετοιμάστε αναρτήσεις, ελέγξτε τα κείμενα και προγραμματίστε τη δημοσίευση.', sourceMaterial: 'Υλικό πηγής', generateFromSeo: 'Δημιουργία από δημοφιλείς λέξεις-κλειδιά SEO', loadingSeo: 'Φόρτωση λέξεων-κλειδιών SEO...', noSeo: 'Δεν βρέθηκαν λέξεις-κλειδιά SEO', selectSeo: 'Επιλέξτε λέξη-κλειδί SEO', seoHint: 'Θα χρησιμοποιηθούν δημοφιλείς αναζητήσεις και οι υπηρεσίες σας.', abMode: 'Λειτουργία A/B (δοκιμή)', generated: 'Δημιουργήθηκε', generating: 'Δημιουργία...', discard: 'Διαγραφή', addedAutomatically: 'Η ανάρτηση προστέθηκε αυτόματα στη λίστα', external: 'Εξωτερικό', noText: 'Χωρίς κείμενο', viewOriginal: 'Προβολή πρωτοτύπου' },
  de: { planTab: 'Inhaltsplan', planTitle: 'Inhaltsplan und Beiträge', planSubtitle: 'Bereiten Sie Beiträge vor, prüfen Sie Texte und planen Sie die Veröffentlichung.', sourceMaterial: 'Ausgangsmaterial', generateFromSeo: 'Aus beliebten SEO-Keywords erstellen', loadingSeo: 'SEO-Keywords werden geladen...', noSeo: 'Keine SEO-Keywords gefunden', selectSeo: 'SEO-Keyword auswählen', seoHint: 'Beliebte Suchanfragen und Ihre Leistungen werden verwendet.', abMode: 'A/B-Modus (Test)', generated: 'Erstellt', generating: 'Wird erstellt...', discard: 'Verwerfen', addedAutomatically: 'Der Beitrag wurde automatisch zur Liste hinzugefügt', external: 'Extern', noText: 'Kein Text', viewOriginal: 'Original ansehen' },
  th: { planTab: 'แผนคอนเทนต์', planTitle: 'แผนคอนเทนต์และโพสต์', planSubtitle: 'เตรียมโพสต์ ตรวจทานข้อความ และกำหนดเวลาเผยแพร่', sourceMaterial: 'ข้อมูลต้นทาง', generateFromSeo: 'สร้างจากคีย์เวิร์ด SEO ยอดนิยม', loadingSeo: 'กำลังโหลดคีย์เวิร์ด SEO...', noSeo: 'ไม่พบคีย์เวิร์ด SEO', selectSeo: 'เลือกคีย์เวิร์ด SEO', seoHint: 'จะใช้คำค้นยอดนิยมและบริการของคุณ', abMode: 'โหมด A/B (ทดสอบ)', generated: 'สร้างแล้ว', generating: 'กำลังสร้าง...', discard: 'ลบ', addedAutomatically: 'เพิ่มโพสต์ในรายการด้านล่างอัตโนมัติแล้ว', external: 'ภายนอก', noText: 'ไม่มีข้อความ', viewOriginal: 'ดูต้นฉบับ' },
  ar: { planTab: 'خطة المحتوى', planTitle: 'خطة المحتوى والمنشورات', planSubtitle: 'أعد المنشورات وراجع النصوص وجدول النشر.', sourceMaterial: 'المادة المصدرية', generateFromSeo: 'إنشاء من كلمات SEO الشائعة', loadingSeo: 'جاري تحميل كلمات SEO...', noSeo: 'لم يتم العثور على كلمات SEO', selectSeo: 'اختر كلمة SEO', seoHint: 'ستُستخدم عبارات البحث الشائعة وخدماتك.', abMode: 'وضع A/B (اختبار)', generated: 'تم الإنشاء', generating: 'جاري الإنشاء...', discard: 'حذف', addedAutomatically: 'تمت إضافة المنشور تلقائيًا إلى القائمة', external: 'خارجي', noText: 'لا يوجد نص', viewOriginal: 'عرض الأصل' },
  ha: { planTab: 'Tsarin abun ciki', planTitle: 'Tsarin abun ciki da sakonni', planSubtitle: 'Shirya sakonni, duba rubutu, sannan tsara lokacin wallafawa.', sourceMaterial: 'Bayanan tushe', generateFromSeo: 'Kirkira daga shahararrun kalmomin SEO', loadingSeo: 'Ana loda kalmomin SEO...', noSeo: 'Ba a sami kalmomin SEO ba', selectSeo: 'Zaɓi kalmar SEO', seoHint: 'Za a yi amfani da shahararrun bincike da ayyukanku.', abMode: 'Yanayin A/B (gwaji)', generated: 'An kirkira', generating: 'Ana kirkira...', discard: 'Share', addedAutomatically: 'An ƙara sakon kai tsaye zuwa jerin da ke ƙasa', external: 'Na waje', noText: 'Babu rubutu', viewOriginal: 'Duba na asali' },
  tr: { planTab: 'İçerik planı', planTitle: 'İçerik planı ve gönderiler', planSubtitle: 'Gönderileri hazırlayın, metinleri kontrol edin ve yayını planlayın.', sourceMaterial: 'Kaynak materyal', generateFromSeo: 'Popüler SEO anahtar kelimelerinden oluştur', loadingSeo: 'SEO anahtar kelimeleri yükleniyor...', noSeo: 'SEO anahtar kelimesi bulunamadı', selectSeo: 'SEO anahtar kelimesi seçin', seoHint: 'Popüler aramalar ve hizmetleriniz kullanılacak.', abMode: 'A/B modu (test)', generated: 'Oluşturuldu', generating: 'Oluşturuluyor...', discard: 'Sil', addedAutomatically: 'Gönderi aşağıdaki listeye otomatik olarak eklendi', external: 'Harici', noText: 'Metin yok', viewOriginal: 'Orijinali görüntüle' },
};

export const getNewsWorkspaceCopy = (language: Language): NewsWorkspaceCopy => copy[language];
