import type { Language } from './LanguageContext';

export type PartnershipWorkspaceCopy = {
  title: string;
  description: string;
  candidates: string;
  candidatesHint: string;
  pipeline: string;
  pipelineHint: string;
  drafts: string;
  draftsHint: string;
  queue: string;
  queueHint: string;
  replies: string;
  repliesHint: string;
  nextStep: string;
  nextStepDescription: string;
  selectBusiness: string;
  currentLayer: string;
  workspace: string;
  overview: string;
  sending: string;
  report: string;
};

type PartnershipDemoCopy = {
  demoPartnerName: string;
  demoPartnerBadge: string;
  demoApproved: string;
  demoOfferTitle: string;
  demoOfferBody: string;
  demoOpenRoom: string;
  demoExplanationTitle: string;
  demoExplanation: string;
};

const copy: Record<Language, PartnershipWorkspaceCopy> = {
  ru: { title: 'Поиск партнёров', description: 'Здесь партнёр проходит путь от найденной компании до ответа: отбор, подготовка письма, ручная отправка и фиксация результата.', candidates: 'Кандидаты', candidatesHint: 'Компании, которые нашли, но ещё не проверили.', pipeline: 'В отборе', pipelineHint: 'Компании, выбранные для подготовки предложения.', drafts: 'Письма', draftsHint: 'Письма и предложения, которые нужно проверить.', queue: 'К отправке', queueHint: 'Проверенные письма для ручной отправки.', replies: 'Ответы', repliesHint: 'Ответы партнёров и договорённости о следующем шаге.', nextStep: 'Что делать дальше', nextStepDescription: 'Проверьте кандидата → подготовьте предложение → проверьте письмо → отправьте вручную → сохраните ответ.', selectBusiness: 'Сначала выберите бизнес в переключателе сверху.', currentLayer: 'Открыт этап', workspace: 'работы с партнёрами', overview: 'Обзор', sending: 'Отправка', report: 'Отчёт' },
  en: { title: 'Partner Search', description: 'One workspace for finding partners: candidates, selection, messages, manual sending, replies, and reporting are separated into tabs.', candidates: 'Candidates', candidatesHint: 'Companies found but not yet taken into work.', pipeline: 'Selected', pipelineHint: 'Partners already being worked with.', drafts: 'Messages', draftsHint: 'First messages and proposals awaiting review.', queue: 'Queue', queueHint: 'Messages prepared for manual sending.', replies: 'Replies', repliesHint: 'Recorded partner responses.', nextStep: 'Next step', nextStepDescription: 'Move from left to right: search → selection → messages → manual sending → result. Each screen shows only the actions for the current stage.', selectBusiness: 'Select a business using the switcher above first.', currentLayer: 'Current stage', workspace: 'workspace', overview: 'Overview', sending: 'Sending', report: 'Report' },
  fr: { title: 'Recherche de partenaires', description: 'Un espace unique pour trouver des partenaires : candidats, sélection, messages, envoi manuel, réponses et rapports sont séparés par onglets.', candidates: 'Candidats', candidatesHint: 'Entreprises trouvées, pas encore prises en charge.', pipeline: 'Sélection', pipelineHint: 'Partenaires avec lesquels le travail a commencé.', drafts: 'Messages', draftsHint: 'Premiers messages et propositions en attente de validation.', queue: 'File d’envoi', queueHint: 'Messages préparés pour un envoi manuel.', replies: 'Réponses', repliesHint: 'Réactions des partenaires enregistrées.', nextStep: 'Étape suivante', nextStepDescription: 'Avancez de gauche à droite : recherche → sélection → messages → envoi manuel → résultat. Chaque écran ne montre que les actions de l’étape actuelle.', selectBusiness: 'Sélectionnez d’abord une entreprise en haut.', currentLayer: 'Étape actuelle', workspace: 'espace de travail', overview: 'Aperçu', sending: 'Envoi', report: 'Rapport' },
  es: { title: 'Buscar socios', description: 'Un espacio para encontrar socios: candidatos, selección, mensajes, envío manual, respuestas e informes están separados en pestañas.', candidates: 'Candidatos', candidatesHint: 'Empresas encontradas que aún no están en proceso.', pipeline: 'En selección', pipelineHint: 'Socios con los que ya se está trabajando.', drafts: 'Mensajes', draftsHint: 'Primeros mensajes y propuestas pendientes de revisión.', queue: 'Cola', queueHint: 'Mensajes preparados para envío manual.', replies: 'Respuestas', repliesHint: 'Reacciones registradas de los socios.', nextStep: 'Siguiente paso', nextStepDescription: 'Avanza de izquierda a derecha: búsqueda → selección → mensajes → envío manual → resultado. Cada pantalla muestra solo las acciones de la etapa actual.', selectBusiness: 'Primero selecciona un negocio en el selector superior.', currentLayer: 'Etapa actual', workspace: 'espacio de trabajo', overview: 'Resumen', sending: 'Envío', report: 'Informe' },
  el: { title: 'Αναζήτηση συνεργατών', description: 'Ένας χώρος για αναζήτηση συνεργατών: υποψήφιοι, επιλογή, μηνύματα, χειροκίνητη αποστολή, απαντήσεις και αναφορές σε ξεχωριστές καρτέλες.', candidates: 'Υποψήφιοι', candidatesHint: 'Επιχειρήσεις που βρέθηκαν αλλά δεν έχουν ακόμη αναληφθεί.', pipeline: 'Σε επιλογή', pipelineHint: 'Συνεργάτες με τους οποίους έχει ξεκινήσει η εργασία.', drafts: 'Μηνύματα', draftsHint: 'Πρώτα μηνύματα και προτάσεις που περιμένουν έλεγχο.', queue: 'Ουρά', queueHint: 'Μηνύματα έτοιμα για χειροκίνητη αποστολή.', replies: 'Απαντήσεις', repliesHint: 'Καταγεγραμμένες αντιδράσεις συνεργατών.', nextStep: 'Επόμενο βήμα', nextStepDescription: 'Προχωρήστε από αριστερά προς τα δεξιά: αναζήτηση → επιλογή → μηνύματα → χειροκίνητη αποστολή → αποτέλεσμα. Κάθε οθόνη δείχνει μόνο τις ενέργειες του τρέχοντος σταδίου.', selectBusiness: 'Επιλέξτε πρώτα επιχείρηση από τον επάνω επιλογέα.', currentLayer: 'Τρέχον στάδιο', workspace: 'χώρος εργασίας', overview: 'Επισκόπηση', sending: 'Αποστολή', report: 'Αναφορά' },
  de: { title: 'Partnersuche', description: 'Ein Arbeitsbereich für die Partnersuche: Kandidaten, Auswahl, Nachrichten, manueller Versand, Antworten und Berichte sind in Tabs getrennt.', candidates: 'Kandidaten', candidatesHint: 'Gefundene Unternehmen, die noch nicht bearbeitet werden.', pipeline: 'In Auswahl', pipelineHint: 'Partner, mit denen bereits gearbeitet wird.', drafts: 'Nachrichten', draftsHint: 'Erste Nachrichten und Angebote, die auf Prüfung warten.', queue: 'Warteschlange', queueHint: 'Nachrichten, die für den manuellen Versand vorbereitet sind.', replies: 'Antworten', repliesHint: 'Erfasste Reaktionen von Partnern.', nextStep: 'Nächster Schritt', nextStepDescription: 'Gehen Sie von links nach rechts: Suche → Auswahl → Nachrichten → manueller Versand → Ergebnis. Jeder Bildschirm zeigt nur die Aktionen der aktuellen Phase.', selectBusiness: 'Wählen Sie zuerst oben ein Unternehmen aus.', currentLayer: 'Aktuelle Phase', workspace: 'Arbeitsbereich', overview: 'Übersicht', sending: 'Versand', report: 'Bericht' },
  th: { title: 'ค้นหาพาร์ทเนอร์', description: 'พื้นที่เดียวสำหรับค้นหาพาร์ทเนอร์ โดยแยกผู้สมัคร การคัดเลือก ข้อความ การส่งด้วยตนเอง การตอบกลับ และรายงานเป็นแท็บ', candidates: 'ผู้สมัคร', candidatesHint: 'ธุรกิจที่พบแต่ยังไม่ได้เริ่มดำเนินงาน', pipeline: 'กำลังคัดเลือก', pipelineHint: 'พาร์ทเนอร์ที่เริ่มทำงานด้วยแล้ว', drafts: 'ข้อความ', draftsHint: 'ข้อความแรกและข้อเสนอที่รอตรวจสอบ', queue: 'คิว', queueHint: 'ข้อความที่เตรียมไว้สำหรับส่งด้วยตนเอง', replies: 'การตอบกลับ', repliesHint: 'ปฏิกิริยาจากพาร์ทเนอร์ที่บันทึกไว้', nextStep: 'ขั้นตอนถัดไป', nextStepDescription: 'ดำเนินการจากซ้ายไปขวา: ค้นหา → คัดเลือก → ข้อความ → ส่งด้วยตนเอง → ผลลัพธ์ แต่ละหน้าจอจะแสดงเฉพาะงานของขั้นตอนปัจจุบัน', selectBusiness: 'เลือกธุรกิจจากตัวเลือกด้านบนก่อน', currentLayer: 'ขั้นตอนปัจจุบัน', workspace: 'พื้นที่ทำงาน', overview: 'ภาพรวม', sending: 'การส่ง', report: 'รายงาน' },
  ar: { title: 'البحث عن شركاء', description: 'مساحة واحدة للعثور على الشركاء، مع فصل المرشحين والاختيار والرسائل والإرسال اليدوي والردود والتقارير في علامات تبويب.', candidates: 'المرشحون', candidatesHint: 'شركات تم العثور عليها ولم يبدأ العمل عليها بعد.', pipeline: 'قيد الاختيار', pipelineHint: 'شركاء بدأ العمل معهم.', drafts: 'الرسائل', draftsHint: 'الرسائل الأولى والعروض التي تنتظر المراجعة.', queue: 'قائمة الانتظار', queueHint: 'رسائل جاهزة للإرسال اليدوي.', replies: 'الردود', repliesHint: 'ردود الشركاء المسجلة.', nextStep: 'الخطوة التالية', nextStepDescription: 'انتقل من اليمين إلى اليسار عبر المراحل: البحث ← الاختيار ← الرسائل ← الإرسال اليدوي ← النتيجة. تعرض كل شاشة إجراءات المرحلة الحالية فقط.', selectBusiness: 'اختر نشاطًا من المحدد العلوي أولًا.', currentLayer: 'المرحلة الحالية', workspace: 'مساحة العمل', overview: 'نظرة عامة', sending: 'الإرسال', report: 'التقرير' },
  ha: { title: 'Neman abokan hulɗa', description: 'Wuri guda don neman abokan hulɗa: candidates, zaɓe, saƙonni, turawa da hannu, amsoshi da rahoto suna cikin shafuka dabam.', candidates: 'Candidates', candidatesHint: 'Kamfanonin da aka samo amma ba a fara aiki da su ba.', pipeline: 'Ana zaɓe', pipelineHint: 'Abokan hulɗar da aka fara aiki da su.', drafts: 'Saƙonni', draftsHint: 'Saƙonnin farko da tayin da ke jiran dubawa.', queue: 'Jeri', queueHint: 'Saƙonnin da aka shirya don turawa da hannu.', replies: 'Amsoshi', repliesHint: 'Martanin abokan hulɗa da aka rubuta.', nextStep: 'Mataki na gaba', nextStepDescription: 'Bi daga hagu zuwa dama: nema → zaɓe → saƙonni → turawa da hannu → sakamako. Kowane allo yana nuna ayyukan matakin yanzu kawai.', selectBusiness: 'Da farko zaɓi kasuwanci daga maɓallin sama.', currentLayer: 'Matakin yanzu', workspace: 'wurin aiki', overview: 'Taƙaitawa', sending: 'Turawa', report: 'Rahoto' },
  tr: { title: 'İş ortağı arama', description: 'İş ortakları bulmak için tek çalışma alanı: adaylar, seçim, mesajlar, manuel gönderim, yanıtlar ve raporlama ayrı sekmelerdedir.', candidates: 'Adaylar', candidatesHint: 'Bulunan ancak henüz çalışmaya alınmayan işletmeler.', pipeline: 'Seçimde', pipelineHint: 'Çalışmaya başlanan iş ortakları.', drafts: 'Mesajlar', draftsHint: 'Kontrol bekleyen ilk mesajlar ve teklifler.', queue: 'Kuyruk', queueHint: 'Manuel gönderim için hazırlanmış mesajlar.', replies: 'Yanıtlar', repliesHint: 'Kaydedilen iş ortağı tepkileri.', nextStep: 'Sonraki adım', nextStepDescription: 'Soldan sağa ilerleyin: arama → seçim → mesajlar → manuel gönderim → sonuç. Her ekran yalnızca mevcut aşamanın işlemlerini gösterir.', selectBusiness: 'Önce üstteki seçiciden bir işletme seçin.', currentLayer: 'Mevcut aşama', workspace: 'çalışma alanı', overview: 'Genel bakış', sending: 'Gönderim', report: 'Rapor' },
};

const clarityCopy: Record<Language, Partial<PartnershipWorkspaceCopy>> = {
  ru: { title: 'Партнёрские акции', description: 'Найдите компании с похожими клиентами и предложите совместную акцию. Здесь можно выбрать кандидатов, подготовить предложение и сохранить полученные ответы.', nextStep: 'Как запустить совместную акцию', nextStepDescription: 'Выберите подходящую компанию, подготовьте предложение, проверьте письмо и отправьте его вручную. Когда партнёр ответит, сохраните договорённость здесь.' },
  en: { title: 'Joint promotions', description: 'Find businesses with a similar audience and propose a joint promotion. Choose suitable companies, prepare an offer, and keep their replies here.', nextStep: 'How to launch a joint promotion', nextStepDescription: 'Choose a suitable business, prepare the offer, review the message, and send it manually. When the partner replies, save the agreement here.' },
  fr: { title: 'Actions partenaires', description: 'Trouvez des entreprises qui partagent votre clientèle et proposez une action commune. Sélectionnez les entreprises, préparez l’offre et conservez leurs réponses ici.', nextStep: 'Comment lancer une action commune', nextStepDescription: 'Choisissez une entreprise, préparez l’offre, vérifiez le message et envoyez-le manuellement. Lorsque le partenaire répond, enregistrez l’accord ici.' },
  es: { title: 'Acciones conjuntas', description: 'Encuentra negocios con un público similar y propón una acción conjunta. Elige las empresas adecuadas, prepara la oferta y guarda aquí sus respuestas.', nextStep: 'Cómo lanzar una acción conjunta', nextStepDescription: 'Elige un negocio, prepara la oferta, revisa el mensaje y envíalo manualmente. Cuando responda el socio, guarda aquí el acuerdo.' },
  el: { title: 'Κοινές ενέργειες', description: 'Βρείτε επιχειρήσεις με παρόμοιο κοινό και προτείνετε μια κοινή ενέργεια. Επιλέξτε τις κατάλληλες εταιρείες, ετοιμάστε την προσφορά και κρατήστε εδώ τις απαντήσεις.', nextStep: 'Πώς ξεκινά μια κοινή ενέργεια', nextStepDescription: 'Επιλέξτε μια κατάλληλη επιχείρηση, ετοιμάστε την προσφορά, ελέγξτε το μήνυμα και στείλτε το χειροκίνητα. Όταν απαντήσει ο συνεργάτης, αποθηκεύστε εδώ τη συμφωνία.' },
  de: { title: 'Gemeinsame Aktionen', description: 'Finden Sie Unternehmen mit ähnlicher Kundschaft und schlagen Sie eine gemeinsame Aktion vor. Wählen Sie passende Firmen, bereiten Sie das Angebot vor und halten Sie Antworten hier fest.', nextStep: 'So starten Sie eine gemeinsame Aktion', nextStepDescription: 'Wählen Sie ein passendes Unternehmen, bereiten Sie das Angebot vor, prüfen Sie die Nachricht und senden Sie sie manuell. Speichern Sie die Vereinbarung hier, sobald der Partner antwortet.' },
  th: { title: 'โปรโมชันร่วมกัน', description: 'ค้นหาธุรกิจที่มีกลุ่มลูกค้าใกล้เคียงและเสนอโปรโมชันร่วมกัน เลือกธุรกิจที่เหมาะ เตรียมข้อเสนอ และเก็บคำตอบไว้ที่นี่', nextStep: 'วิธีเริ่มโปรโมชันร่วมกัน', nextStepDescription: 'เลือกธุรกิจที่เหมาะ เตรียมข้อเสนอ ตรวจข้อความ และส่งด้วยตนเอง เมื่อพาร์ทเนอร์ตอบ ให้บันทึกข้อตกลงไว้ที่นี่' },
  ar: { title: 'عروض مشتركة', description: 'اعثر على أنشطة تجارية ذات جمهور مشابه واقترح عرضًا مشتركًا. اختر الأنشطة المناسبة وجهز العرض واحتفظ بالردود هنا.', nextStep: 'كيف تبدأ عرضًا مشتركًا', nextStepDescription: 'اختر نشاطًا مناسبًا وجهز العرض وراجع الرسالة ثم أرسلها يدويًا. عندما يرد الشريك، احفظ الاتفاق هنا.' },
  ha: { title: 'Haɗin talla', description: 'Nemo kasuwanci masu irin kwastomominka ku shirya talla tare. Zaɓi waɗanda suka dace, shirya tayin kuma ka adana amsoshinsu a nan.', nextStep: 'Yadda ake fara haɗin talla', nextStepDescription: 'Zaɓi kasuwancin da ya dace, shirya tayin, duba saƙon sannan ka aika da hannu. Idan abokin hulɗa ya amsa, adana yarjejeniyar a nan.' },
  tr: { title: 'Ortak kampanyalar', description: 'Benzer müşterilere ulaşan işletmeleri bulun ve ortak bir kampanya önerin. Uygun işletmeleri seçin, teklifi hazırlayın ve yanıtları burada saklayın.', nextStep: 'Ortak kampanya nasıl başlatılır?', nextStepDescription: 'Uygun işletmeyi seçin, teklifi hazırlayın, mesajı kontrol edip manuel olarak gönderin. İş ortağı yanıt verdiğinde anlaşmayı buraya kaydedin.' },
};

const demoCopy: Record<Language, PartnershipDemoCopy> = {
  ru: { demoPartnerName: 'Ромашка', demoPartnerBadge: 'Партнёр', demoApproved: 'Можно отправлять', demoOfferTitle: 'Совместный день для клиентов двух салонов', demoOfferBody: 'Готово предложение: пригласить клиентов двух салонов на общий день и измерить число новых записей.', demoOpenRoom: 'Посмотреть предложение', demoExplanationTitle: 'Что произошло до этого шага', demoExplanation: '«Ромашку» выбрали из кандидатов, подготовили предложение и проверили текст. Следующий шаг — вручную отправить письмо и сохранить ответ.' },
  en: { demoPartnerName: 'Chamomile', demoPartnerBadge: 'Partner', demoApproved: 'Proposal approved', demoOfferTitle: 'Joint customer day', demoOfferBody: 'The joint customer-day proposal has been prepared and approved.', demoOpenRoom: 'Open digital room', demoExplanationTitle: 'Partnerships move through clear stages', demoExplanation: 'Candidates, selection, messages, manual sending, and replies stay in separate stages.' },
  fr: { demoPartnerName: 'Camomille', demoPartnerBadge: 'Partenaire', demoApproved: 'Proposition approuvée', demoOfferTitle: 'Journée clients commune', demoOfferBody: 'La proposition de journée clients commune a été préparée et approuvée.', demoOpenRoom: 'Ouvrir la salle numérique', demoExplanationTitle: 'Les partenariats avancent par étapes', demoExplanation: 'Les candidats, la sélection, les messages, les envois manuels et les réponses restent séparés.' },
  es: { demoPartnerName: 'Manzanilla', demoPartnerBadge: 'Socio', demoApproved: 'Propuesta aprobada', demoOfferTitle: 'Jornada conjunta para clientes', demoOfferBody: 'La propuesta de jornada conjunta para clientes está preparada y aprobada.', demoOpenRoom: 'Abrir sala digital', demoExplanationTitle: 'Las alianzas avanzan por etapas', demoExplanation: 'Los candidatos, la selección, los mensajes, el envío manual y las respuestas permanecen separados.' },
  el: { demoPartnerName: 'Χαμομήλι', demoPartnerBadge: 'Συνεργάτης', demoApproved: 'Η πρόταση εγκρίθηκε', demoOfferTitle: 'Κοινή ημέρα πελατών', demoOfferBody: 'Η πρόταση για κοινή ημέρα πελατών ετοιμάστηκε και εγκρίθηκε.', demoOpenRoom: 'Άνοιγμα ψηφιακού δωματίου', demoExplanationTitle: 'Οι συνεργασίες προχωρούν σε στάδια', demoExplanation: 'Οι υποψήφιοι, η επιλογή, τα μηνύματα, η χειροκίνητη αποστολή και οι απαντήσεις παραμένουν ξεχωριστά.' },
  de: { demoPartnerName: 'Kamille', demoPartnerBadge: 'Partner', demoApproved: 'Angebot freigegeben', demoOfferTitle: 'Gemeinsamer Kundentag', demoOfferBody: 'Das Angebot für einen gemeinsamen Kundentag wurde vorbereitet und freigegeben.', demoOpenRoom: 'Digitalen Raum öffnen', demoExplanationTitle: 'Partnerschaften laufen in klaren Phasen', demoExplanation: 'Kandidaten, Auswahl, Nachrichten, manueller Versand und Antworten bleiben getrennt.' },
  th: { demoPartnerName: 'คาโมมายล์', demoPartnerBadge: 'พาร์ทเนอร์', demoApproved: 'อนุมัติข้อเสนอแล้ว', demoOfferTitle: 'วันลูกค้าร่วมกัน', demoOfferBody: 'ข้อเสนอวันลูกค้าร่วมกันถูกเตรียมและอนุมัติแล้ว', demoOpenRoom: 'เปิดห้องดิจิทัล', demoExplanationTitle: 'พาร์ทเนอร์ชิปดำเนินเป็นขั้นตอน', demoExplanation: 'ผู้สมัคร การคัดเลือก ข้อความ การส่งด้วยตนเอง และการตอบกลับจะแยกกัน' },
  ar: { demoPartnerName: 'البابونج', demoPartnerBadge: 'شريك', demoApproved: 'تمت الموافقة على العرض', demoOfferTitle: 'يوم مشترك للعملاء', demoOfferBody: 'تم إعداد واعتماد عرض يوم العملاء المشترك.', demoOpenRoom: 'فتح الغرفة الرقمية', demoExplanationTitle: 'تتقدم الشراكات عبر مراحل واضحة', demoExplanation: 'يبقى المرشحون والاختيار والرسائل والإرسال اليدوي والردود في مراحل منفصلة.' },
  ha: { demoPartnerName: 'Chamomile', demoPartnerBadge: 'Abokin hulɗa', demoApproved: 'An amince da tayin', demoOfferTitle: 'Ranar kwastomomi ta haɗin gwiwa', demoOfferBody: 'An shirya kuma an amince da tayin ranar kwastomomi ta haɗin gwiwa.', demoOpenRoom: 'Buɗe ɗakin dijital', demoExplanationTitle: 'Haɗin gwiwa yana tafiya mataki-mataki', demoExplanation: 'Candidates, zaɓe, saƙonni, turawa da hannu da amsoshi suna zama a matakai dabam.' },
  tr: { demoPartnerName: 'Papatya', demoPartnerBadge: 'İş ortağı', demoApproved: 'Teklif onaylandı', demoOfferTitle: 'Ortak müşteri günü', demoOfferBody: 'Ortak müşteri günü teklifi hazırlandı ve onaylandı.', demoOpenRoom: 'Dijital odayı aç', demoExplanationTitle: 'İş ortaklıkları aşama aşama ilerler', demoExplanation: 'Adaylar, seçim, mesajlar, manuel gönderim ve yanıtlar ayrı aşamalarda tutulur.' },
};

const demoClarityCopy: Record<Language, Partial<PartnershipDemoCopy>> = {
  ru: { demoApproved: 'Можно отправлять', demoOfferTitle: 'Совместный день для клиентов двух салонов', demoOfferBody: 'Готово предложение: пригласить клиентов двух салонов на общий день и измерить число новых записей.', demoOpenRoom: 'Посмотреть предложение', demoExplanationTitle: 'Все договорённости остаются перед глазами', demoExplanation: 'Отдельно показаны компании для проверки, готовые предложения, отправленные письма и ответы. Поэтому понятно, с кем уже связались и кто ждёт следующего шага.' },
  en: { demoApproved: 'Ready to send', demoOfferTitle: 'A joint customer day for two salons', demoOfferBody: 'The offer is ready: invite customers of both salons to a joint event and measure new bookings.', demoOpenRoom: 'View the offer', demoExplanationTitle: 'Every agreement stays visible', demoExplanation: 'Businesses to review, ready offers, sent messages, and replies are shown separately. You can see who has been contacted and who needs the next step.' },
  fr: { demoApproved: 'Prêt à envoyer', demoOfferTitle: 'Une journée commune pour les clients des deux salons', demoOfferBody: 'L’offre est prête : inviter les clients des deux salons à une journée commune et mesurer les nouvelles réservations.', demoOpenRoom: 'Voir l’offre', demoExplanationTitle: 'Toutes les démarches restent visibles', demoExplanation: 'Les entreprises à vérifier, les offres prêtes, les messages envoyés et les réponses sont séparés. Vous savez qui a déjà été contacté et qui attend la suite.' },
  es: { demoApproved: 'Listo para enviar', demoOfferTitle: 'Una jornada conjunta para clientes de dos salones', demoOfferBody: 'La oferta está lista: invitar a los clientes de ambos salones y medir las nuevas reservas.', demoOpenRoom: 'Ver la oferta', demoExplanationTitle: 'Todos los acuerdos quedan a la vista', demoExplanation: 'Los negocios por revisar, las ofertas listas, los mensajes enviados y las respuestas aparecen por separado. Así sabes con quién ya hablaste y quién necesita el siguiente paso.' },
  el: { demoApproved: 'Έτοιμο για αποστολή', demoOfferTitle: 'Κοινή ημέρα για τους πελάτες δύο κομμωτηρίων', demoOfferBody: 'Η προσφορά είναι έτοιμη: πρόσκληση των πελατών και των δύο επιχειρήσεων και μέτρηση των νέων κρατήσεων.', demoOpenRoom: 'Προβολή προσφοράς', demoExplanationTitle: 'Όλες οι συμφωνίες παραμένουν ορατές', demoExplanation: 'Οι επιχειρήσεις για έλεγχο, οι έτοιμες προσφορές, τα απεσταλμένα μηνύματα και οι απαντήσεις εμφανίζονται ξεχωριστά. Έτσι ξέρετε με ποιον μιλήσατε και ποιος περιμένει το επόμενο βήμα.' },
  de: { demoApproved: 'Versandbereit', demoOfferTitle: 'Gemeinsamer Kundentag für zwei Salons', demoOfferBody: 'Das Angebot ist fertig: Kundinnen und Kunden beider Salons einladen und neue Buchungen messen.', demoOpenRoom: 'Angebot ansehen', demoExplanationTitle: 'Alle Vereinbarungen bleiben sichtbar', demoExplanation: 'Zu prüfende Unternehmen, fertige Angebote, gesendete Nachrichten und Antworten werden getrennt gezeigt. So sehen Sie, wer bereits kontaktiert wurde und wer den nächsten Schritt braucht.' },
  th: { demoApproved: 'พร้อมส่ง', demoOfferTitle: 'วันลูกค้าร่วมกันสำหรับสองร้าน', demoOfferBody: 'ข้อเสนอพร้อมแล้ว: เชิญลูกค้าของทั้งสองร้านมาร่วมกิจกรรมและวัดจำนวนการจองใหม่', demoOpenRoom: 'ดูข้อเสนอ', demoExplanationTitle: 'ติดตามข้อตกลงได้ทั้งหมด', demoExplanation: 'ธุรกิจที่ต้องตรวจ ข้อเสนอที่พร้อม ข้อความที่ส่งแล้ว และคำตอบจะแสดงแยกกัน จึงเห็นได้ว่าใครได้รับการติดต่อแล้วและใครต้องทำขั้นตอนต่อไป' },
  ar: { demoApproved: 'جاهز للإرسال', demoOfferTitle: 'يوم مشترك لعملاء صالونين', demoOfferBody: 'العرض جاهز: دعوة عملاء الصالونين إلى فعالية مشتركة وقياس الحجوزات الجديدة.', demoOpenRoom: 'عرض الاقتراح', demoExplanationTitle: 'تبقى كل الاتفاقات واضحة', demoExplanation: 'تظهر الأنشطة التي تحتاج مراجعة والعروض الجاهزة والرسائل المرسلة والردود بشكل منفصل. لذلك تعرف من تم التواصل معه ومن يحتاج إلى الخطوة التالية.' },
  ha: { demoApproved: 'Ya shirya don aikawa', demoOfferTitle: 'Ranar kwastomomi ta haɗin gwiwa ga salon biyu', demoOfferBody: 'Tayin ya shirya: gayyatar kwastomomin salon biyu zuwa rana guda da auna sabbin bookings.', demoOpenRoom: 'Duba tayin', demoExplanationTitle: 'Dukkan yarjejeniyoyi suna bayyane', demoExplanation: 'Kasuwancin da za a duba, tayin da ya shirya, saƙonnin da aka aika da amsoshi suna dabam. Za ka san wanda aka tuntuɓa da wanda yake jiran mataki na gaba.' },
  tr: { demoApproved: 'Gönderime hazır', demoOfferTitle: 'İki salonun müşterileri için ortak gün', demoOfferBody: 'Teklif hazır: iki salonun müşterilerini ortak bir güne davet edin ve yeni randevuları ölçün.', demoOpenRoom: 'Teklifi görüntüle', demoExplanationTitle: 'Tüm anlaşmalar göz önünde kalır', demoExplanation: 'Kontrol edilecek işletmeler, hazır teklifler, gönderilen mesajlar ve yanıtlar ayrı gösterilir. Kiminle iletişim kurulduğunu ve kimin sonraki adımı beklediğini görürsünüz.' },
};

export const getPartnershipWorkspaceCopy = (language: Language): PartnershipWorkspaceCopy & PartnershipDemoCopy => ({
  ...copy[language],
  ...demoCopy[language],
  ...clarityCopy[language],
  ...demoClarityCopy[language],
});
