import type { Language } from './LanguageContext';

export type PartnershipWorkspaceCopy = {
  title: string;
  description: string;
  candidates: string;
  candidatesHint: string;
  pipeline: string;
  pipelineHint: string;
  drafts: string;
  draftsHint: string;
  queue: string;
  queueHint: string;
  replies: string;
  repliesHint: string;
  nextStep: string;
  nextStepDescription: string;
  selectBusiness: string;
  currentLayer: string;
  workspace: string;
  overview: string;
  sending: string;
  report: string;
};

type PartnershipDemoCopy = {
  demoPartnerName: string;
  demoPartnerBadge: string;
  demoApproved: string;
  demoOfferTitle: string;
  demoOfferBody: string;
  demoOpenRoom: string;
  demoExplanationTitle: string;
  demoExplanation: string;
};

const copy: Record<Language, PartnershipWorkspaceCopy> = {
  ru: { title: 'Поиск партнёров', description: 'Здесь партнёр проходит путь от найденной компании до ответа: отбор, подготовка письма, ручная отправка и фиксация результата.', candidates: 'Кандидаты', candidatesHint: 'Компании, которые нашли, но ещё не проверили.', pipeline: 'В отборе', pipelineHint: 'Компании, выбранные для подготовки предложения.', drafts: 'Письма', draftsHint: 'Письма и предложения, которые нужно проверить.', queue: 'К отправке', queueHint: 'Проверенные письма для ручной отправки.', replies: 'Ответы', repliesHint: 'Ответы партнёров и договорённости о следующем шаге.', nextStep: 'Что делать дальше', nextStepDescription: 'Проверьте кандидата → подготовьте предложение → проверьте письмо → отправьте вручную → сохраните ответ.', selectBusiness: 'Сначала выберите бизнес в переключателе сверху.', currentLayer: 'Открыт этап', workspace: 'работы с партнёрами', overview: 'Обзор', sending: 'Отправка', report: 'Отчёт' },
  en: { title: 'Partner Search', description: 'One workspace for finding partners: candidates, selection, messages, manual sending, replies, and reporting are separated into tabs.', candidates: 'Candidates', candidatesHint: 'Companies found but not yet taken into work.', pipeline: 'Selected', pipelineHint: 'Partners already being worked with.', drafts: 'Messages', draftsHint: 'First messages and proposals awaiting review.', queue: 'Queue', queueHint: 'Messages prepared for manual sending.', replies: 'Replies', repliesHint: 'Recorded partner responses.', nextStep: 'Next step', nextStepDescription: 'Move from left to right: search → selection → messages → manual sending → result. Each screen shows only the actions for the current stage.', selectBusiness: 'Select a business using the switcher above first.', currentLayer: 'Current stage', workspace: 'workspace', overview: 'Overview', sending: 'Sending', report: 'Report' },
  fr: { title: 'Recherche de partenaires', description: 'Un espace unique pour trouver des partenaires : candidats, sélection, messages, envoi manuel, réponses et rapports sont séparés par onglets.', candidates: 'Candidats', candidatesHint: 'Entreprises trouvées, pas encore prises en charge.', pipeline: 'Sélection', pipelineHint: 'Partenaires avec lesquels le travail a commencé.', drafts: 'Messages', draftsHint: 'Premiers messages et propositions en attente de validation.', queue: 'File d’envoi', queueHint: 'Messages préparés pour un envoi manuel.', replies: 'Réponses', repliesHint: 'Réactions des partenaires enregistrées.', nextStep: 'Étape suivante', nextStepDescription: 'Avancez de gauche à droite : recherche → sélection → messages → envoi manuel → résultat. Chaque écran ne montre que les actions de l’étape actuelle.', selectBusiness: 'Sélectionnez d’abord une entreprise en haut.', currentLayer: 'Étape actuelle', workspace: 'espace de travail', overview: 'Aperçu', sending: 'Envoi', report: 'Rapport' },
  es: { title: 'Buscar socios', description: 'Un espacio para encontrar socios: candidatos, selección, mensajes, envío manual, respuestas e informes están separados en pestañas.', candidates: 'Candidatos', candidatesHint: 'Empresas encontradas que aún no están en proceso.', pipeline: 'En selección', pipelineHint: 'Socios con los que ya se está trabajando.', drafts: 'Mensajes', draftsHint: 'Primeros mensajes y propuestas pendientes de revisión.', queue: 'Cola', queueHint: 'Mensajes preparados para envío manual.', replies: 'Respuestas', repliesHint: 'Reacciones registradas de los socios.', nextStep: 'Siguiente paso', nextStepDescription: 'Avanza de izquierda a derecha: búsqueda → selección → mensajes → envío manual → resultado. Cada pantalla muestra solo las acciones de la etapa actual.', selectBusiness: 'Primero selecciona un negocio en el selector superior.', currentLayer: 'Etapa actual', workspace: 'espacio de trabajo', overview: 'Resumen', sending: 'Envío', report: 'Informe' },
  el: { title: 'Αναζήτηση συνεργατών', description: 'Ένας χώρος για αναζήτηση συνεργατών: υποψήφιοι, επιλογή, μηνύματα, χειροκίνητη αποστολή, απαντήσεις και αναφορές σε ξεχωριστές καρτέλες.', candidates: 'Υποψήφιοι', candidatesHint: 'Επιχειρήσεις που βρέθηκαν αλλά δεν έχουν ακόμη αναληφθεί.', pipeline: 'Σε επιλογή', pipelineHint: 'Συνεργάτες με τους οποίους έχει ξεκινήσει η εργασία.', drafts: 'Μηνύματα', draftsHint: 'Πρώτα μηνύματα και προτάσεις που περιμένουν έλεγχο.', queue: 'Ουρά', queueHint: 'Μηνύματα έτοιμα για χειροκίνητη αποστολή.', replies: 'Απαντήσεις', repliesHint: 'Καταγεγραμμένες αντιδράσεις συνεργατών.', nextStep: 'Επόμενο βήμα', nextStepDescription: 'Προχωρήστε από αριστερά προς τα δεξιά: αναζήτηση → επιλογή → μηνύματα → χειροκίνητη αποστολή → αποτέλεσμα. Κάθε οθόνη δείχνει μόνο τις ενέργειες του τρέχοντος σταδίου.', selectBusiness: 'Επιλέξτε πρώτα επιχείρηση από τον επάνω επιλογέα.', currentLayer: 'Τρέχον στάδιο', workspace: 'χώρος εργασίας', overview: 'Επισκόπηση', sending: 'Αποστολή', report: 'Αναφορά' },
  de: { title: 'Partnersuche', description: 'Ein Arbeitsbereich für die Partnersuche: Kandidaten, Auswahl, Nachrichten, manueller Versand, Antworten und Berichte sind in Tabs getrennt.', candidates: 'Kandidaten', candidatesHint: 'Gefundene Unternehmen, die noch nicht bearbeitet werden.', pipeline: 'In Auswahl', pipelineHint: 'Partner, mit denen bereits gearbeitet wird.', drafts: 'Nachrichten', draftsHint: 'Erste Nachrichten und Angebote, die auf Prüfung warten.', queue: 'Warteschlange', queueHint: 'Nachrichten, die für den manuellen Versand vorbereitet sind.', replies: 'Antworten', repliesHint: 'Erfasste Reaktionen von Partnern.', nextStep: 'Nächster Schritt', nextStepDescription: 'Gehen Sie von links nach rechts: Suche → Auswahl → Nachrichten → manueller Versand → Ergebnis. Jeder Bildschirm zeigt nur die Aktionen der aktuellen Phase.', selectBusiness: 'Wählen Sie zuerst oben ein Unternehmen aus.', currentLayer: 'Aktuelle Phase', workspace: 'Arbeitsbereich', overview: 'Übersicht', sending: 'Versand', report: 'Bericht' },
  th: { title: 'ค้นหาพาร์ทเนอร์', description: 'พื้นที่เดียวสำหรับค้นหาพาร์ทเนอร์ โดยแยกผู้สมัคร การคัดเลือก ข้อความ การส่งด้วยตนเอง การตอบกลับ และรายงานเป็นแท็บ', candidates: 'ผู้สมัคร', candidatesHint: 'ธุรกิจที่พบแต่ยังไม่ได้เริ่มดำเนินงาน', pipeline: 'กำลังคัดเลือก', pipelineHint: 'พาร์ทเนอร์ที่เริ่มทำงานด้วยแล้ว', drafts: 'ข้อความ', draftsHint: 'ข้อความแรกและข้อเสนอที่รอตรวจสอบ', queue: 'คิว', queueHint: 'ข้อความที่เตรียมไว้สำหรับส่งด้วยตนเอง', replies: 'การตอบกลับ', repliesHint: 'ปฏิกิริยาจากพาร์ทเนอร์ที่บันทึกไว้', nextStep: 'ขั้นตอนถัดไป', nextStepDescription: 'ดำเนินการจากซ้ายไปขวา: ค้นหา → คัดเลือก → ข้อความ → ส่งด้วยตนเอง → ผลลัพธ์ แต่ละหน้าจอจะแสดงเฉพาะงานของขั้นตอนปัจจุบัน', selectBusiness: 'เลือกธุรกิจจากตัวเลือกด้านบนก่อน', currentLayer: 'ขั้นตอนปัจจุบัน', workspace: 'พื้นที่ทำงาน', overview: 'ภาพรวม', sending: 'การส่ง', report: 'รายงาน' },
  ar: { title: 'البحث عن شركاء', description: 'مساحة واحدة للعثور على الشركاء، مع فصل المرشحين والاختيار والرسائل والإرسال اليدوي والردود والتقارير في علامات تبويب.', candidates: 'المرشحون', candidatesHint: 'شركات تم العثور عليها ولم يبدأ العمل عليها بعد.', pipeline: 'قيد الاختيار', pipelineHint: 'شركاء بدأ العمل معهم.', drafts: 'الرسائل', draftsHint: 'الرسائل الأولى والعروض التي تنتظر المراجعة.', queue: 'قائمة الانتظار', queueHint: 'رسائل جاهزة للإرسال اليدوي.', replies: 'الردود', repliesHint: 'ردود الشركاء المسجلة.', nextStep: 'الخطوة التالية', nextStepDescription: 'انتقل من اليمين إلى اليسار عبر المراحل: البحث ← الاختيار ← الرسائل ← الإرسال اليدوي ← النتيجة. تعرض كل شاشة إجراءات المرحلة الحالية فقط.', selectBusiness: 'اختر نشاطًا من المحدد العلوي أولًا.', currentLayer: 'المرحلة الحالية', workspace: 'مساحة العمل', overview: 'نظرة عامة', sending: 'الإرسال', report: 'التقرير' },
  ha: { title: 'Neman abokan hulɗa', description: 'Wuri guda don neman abokan hulɗa: candidates, zaɓe, saƙonni, turawa da hannu, amsoshi da rahoto suna cikin shafuka dabam.', candidates: 'Candidates', candidatesHint: 'Kamfanonin da aka samo amma ba a fara aiki da su ba.', pipeline: 'Ana zaɓe', pipelineHint: 'Abokan hulɗar da aka fara aiki da su.', drafts: 'Saƙonni', draftsHint: 'Saƙonnin farko da tayin da ke jiran dubawa.', queue: 'Jeri', queueHint: 'Saƙonnin da aka shirya don turawa da hannu.', replies: 'Amsoshi', repliesHint: 'Martanin abokan hulɗa da aka rubuta.', nextStep: 'Mataki na gaba', nextStepDescription: 'Bi daga hagu zuwa dama: nema → zaɓe → saƙonni → turawa da hannu → sakamako. Kowane allo yana nuna ayyukan matakin yanzu kawai.', selectBusiness: 'Da farko zaɓi kasuwanci daga maɓallin sama.', currentLayer: 'Matakin yanzu', workspace: 'wurin aiki', overview: 'Taƙaitawa', sending: 'Turawa', report: 'Rahoto' },
  tr: { title: 'İş ortağı arama', description: 'İş ortakları bulmak için tek çalışma alanı: adaylar, seçim, mesajlar, manuel gönderim, yanıtlar ve raporlama ayrı sekmelerdedir.', candidates: 'Adaylar', candidatesHint: 'Bulunan ancak henüz çalışmaya alınmayan işletmeler.', pipeline: 'Seçimde', pipelineHint: 'Çalışmaya başlanan iş ortakları.', drafts: 'Mesajlar', draftsHint: 'Kontrol bekleyen ilk mesajlar ve teklifler.', queue: 'Kuyruk', queueHint: 'Manuel gönderim için hazırlanmış mesajlar.', replies: 'Yanıtlar', repliesHint: 'Kaydedilen iş ortağı tepkileri.', nextStep: 'Sonraki adım', nextStepDescription: 'Soldan sağa ilerleyin: arama → seçim → mesajlar → manuel gönderim → sonuç. Her ekran yalnızca mevcut aşamanın işlemlerini gösterir.', selectBusiness: 'Önce üstteki seçiciden bir işletme seçin.', currentLayer: 'Mevcut aşama', workspace: 'çalışma alanı', overview: 'Genel bakış', sending: 'Gönderim', report: 'Rapor' },
};

const demoCopy: Record<Language, PartnershipDemoCopy> = {
  ru: { demoPartnerName: 'Ромашка', demoPartnerBadge: 'Партнёр', demoApproved: 'Можно отправлять', demoOfferTitle: 'Совместный день для клиентов двух салонов', demoOfferBody: 'Готово предложение: пригласить клиентов двух салонов на общий день и измерить число новых записей.', demoOpenRoom: 'Посмотреть предложение', demoExplanationTitle: 'Что произошло до этого шага', demoExplanation: '«Ромашку» выбрали из кандидатов, подготовили предложение и проверили текст. Следующий шаг — вручную отправить письмо и сохранить ответ.' },
  en: { demoPartnerName: 'Chamomile', demoPartnerBadge: 'Partner', demoApproved: 'Proposal approved', demoOfferTitle: 'Joint customer day', demoOfferBody: 'The joint customer-day proposal has been prepared and approved.', demoOpenRoom: 'Open digital room', demoExplanationTitle: 'Partnerships move through clear stages', demoExplanation: 'Candidates, selection, messages, manual sending, and replies stay in separate stages.' },
  fr: { demoPartnerName: 'Camomille', demoPartnerBadge: 'Partenaire', demoApproved: 'Proposition approuvée', demoOfferTitle: 'Journée clients commune', demoOfferBody: 'La proposition de journée clients commune a été préparée et approuvée.', demoOpenRoom: 'Ouvrir la salle numérique', demoExplanationTitle: 'Les partenariats avancent par étapes', demoExplanation: 'Les candidats, la sélection, les messages, les envois manuels et les réponses restent séparés.' },
  es: { demoPartnerName: 'Manzanilla', demoPartnerBadge: 'Socio', demoApproved: 'Propuesta aprobada', demoOfferTitle: 'Jornada conjunta para clientes', demoOfferBody: 'La propuesta de jornada conjunta para clientes está preparada y aprobada.', demoOpenRoom: 'Abrir sala digital', demoExplanationTitle: 'Las alianzas avanzan por etapas', demoExplanation: 'Los candidatos, la selección, los mensajes, el envío manual y las respuestas permanecen separados.' },
  el: { demoPartnerName: 'Χαμομήλι', demoPartnerBadge: 'Συνεργάτης', demoApproved: 'Η πρόταση εγκρίθηκε', demoOfferTitle: 'Κοινή ημέρα πελατών', demoOfferBody: 'Η πρόταση για κοινή ημέρα πελατών ετοιμάστηκε και εγκρίθηκε.', demoOpenRoom: 'Άνοιγμα ψηφιακού δωματίου', demoExplanationTitle: 'Οι συνεργασίες προχωρούν σε στάδια', demoExplanation: 'Οι υποψήφιοι, η επιλογή, τα μηνύματα, η χειροκίνητη αποστολή και οι απαντήσεις παραμένουν ξεχωριστά.' },
  de: { demoPartnerName: 'Kamille', demoPartnerBadge: 'Partner', demoApproved: 'Angebot freigegeben', demoOfferTitle: 'Gemeinsamer Kundentag', demoOfferBody: 'Das Angebot für einen gemeinsamen Kundentag wurde vorbereitet und freigegeben.', demoOpenRoom: 'Digitalen Raum öffnen', demoExplanationTitle: 'Partnerschaften laufen in klaren Phasen', demoExplanation: 'Kandidaten, Auswahl, Nachrichten, manueller Versand und Antworten bleiben getrennt.' },
  th: { demoPartnerName: 'คาโมมายล์', demoPartnerBadge: 'พาร์ทเนอร์', demoApproved: 'อนุมัติข้อเสนอแล้ว', demoOfferTitle: 'วันลูกค้าร่วมกัน', demoOfferBody: 'ข้อเสนอวันลูกค้าร่วมกันถูกเตรียมและอนุมัติแล้ว', demoOpenRoom: 'เปิดห้องดิจิทัล', demoExplanationTitle: 'พาร์ทเนอร์ชิปดำเนินเป็นขั้นตอน', demoExplanation: 'ผู้สมัคร การคัดเลือก ข้อความ การส่งด้วยตนเอง และการตอบกลับจะแยกกัน' },
  ar: { demoPartnerName: 'البابونج', demoPartnerBadge: 'شريك', demoApproved: 'تمت الموافقة على العرض', demoOfferTitle: 'يوم مشترك للعملاء', demoOfferBody: 'تم إعداد واعتماد عرض يوم العملاء المشترك.', demoOpenRoom: 'فتح الغرفة الرقمية', demoExplanationTitle: 'تتقدم الشراكات عبر مراحل واضحة', demoExplanation: 'يبقى المرشحون والاختيار والرسائل والإرسال اليدوي والردود في مراحل منفصلة.' },
  ha: { demoPartnerName: 'Chamomile', demoPartnerBadge: 'Abokin hulɗa', demoApproved: 'An amince da tayin', demoOfferTitle: 'Ranar kwastomomi ta haɗin gwiwa', demoOfferBody: 'An shirya kuma an amince da tayin ranar kwastomomi ta haɗin gwiwa.', demoOpenRoom: 'Buɗe ɗakin dijital', demoExplanationTitle: 'Haɗin gwiwa yana tafiya mataki-mataki', demoExplanation: 'Candidates, zaɓe, saƙonni, turawa da hannu da amsoshi suna zama a matakai dabam.' },
  tr: { demoPartnerName: 'Papatya', demoPartnerBadge: 'İş ortağı', demoApproved: 'Teklif onaylandı', demoOfferTitle: 'Ortak müşteri günü', demoOfferBody: 'Ortak müşteri günü teklifi hazırlandı ve onaylandı.', demoOpenRoom: 'Dijital odayı aç', demoExplanationTitle: 'İş ortaklıkları aşama aşama ilerler', demoExplanation: 'Adaylar, seçim, mesajlar, manuel gönderim ve yanıtlar ayrı aşamalarda tutulur.' },
};

export const getPartnershipWorkspaceCopy = (language: Language): PartnershipWorkspaceCopy & PartnershipDemoCopy => ({
  ...copy[language],
  ...demoCopy[language],
});
